### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by rvandegrift** [DisplayLink/evdi#102]
I'm considering packaging evdi for debian, and I have a question about the licensing.

README.md explains that `module/` and `library/` each have their own licenses.  Those are clear enough.  What about the rest of the repo?

**Comment by hstock** [comment]
Same problem here. 

@rvandegrift: Have you already started packaging? I have filed an ITP and am currently working on it: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918992

**Comment by displaylink-emajewsk** [comment]
We'll be addressing this. 😅  Thanks.
