### ISSUE TITLE
FIxing Ubuntu 16.04 with kernel 4.10+ 

### ISSUE THREAD

**Issue by ZEROF** [DisplayLink/evdi#106]
Hi,

After getting this error in my logs:

Failed to start DisplayLink Manager Service
dlm.service: Unit entered failed state
modprobe: FATAL: Module evdi not found in directory 

System info:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename: xenial
Kernel: 4.10.0-35-generic

I start looking for solution, but i couldn't find any post about it, only some info but people didn't share their solution. Here you can find my solution:

apt install dkms
apt install libdrm-dev

Go to https://github.com/DisplayLink/evdi/releases

    cd /tmp
    wget https://github.com/DisplayLink/evdi/archive/v1.4.0.zip
    unzip v1.4.0.zip
    sudo cp -r evdi-1.4.0 /usr/src
    cd /usr/src/evdi-1.4.0
    sudo make
    sudo make check
    sudo make install

Have fun ;)

**Comment by TomWright** [comment]
Hi @ZEROF,
I have attempted the above but I get errors when running `sudo make`.

```
2017-10-02 13:58:13 ⌚  tom-wright-antergos in /usr/src/evdi-1.4.0
○ → sudo make
CFLAGS="-Werror -Wextra -Wall" make -C module 
make[1]: Entering directory '/usr/src/evdi-1.4.0/module'
make -C /lib/modules/4.13.3-1-ARCH/build M=$PWD
make[2]: Entering directory '/usr/lib/modules/4.13.3-1-ARCH/build'
  AR      /usr/src/evdi-1.4.0/module/built-in.o
  CC [M]  /usr/src/evdi-1.4.0/module/evdi_drv.o
/usr/src/evdi-1.4.0/module/evdi_drv.c: In function ‘evdi_platform_probe’:
/usr/src/evdi-1.4.0/module/evdi_drv.c:120:9: error: implicit declaration of function ‘drm_platform_init’; did you mean ‘early_platform_init’? [-Werror=implicit-function-declaration]
  return drm_platform_init(&driver, pdev);
         ^~~~~~~~~~~~~~~~~
         early_platform_init
cc1: all warnings being treated as errors
make[3]: *** [scripts/Makefile.build:303: /usr/src/evdi-1.4.0/module/evdi_drv.o] Error 1
make[2]: *** [Makefile:1512: _module_/usr/src/evdi-1.4.0/module] Error 2
make[2]: Leaving directory '/usr/lib/modules/4.13.3-1-ARCH/build'
make[1]: *** [Makefile:57: module] Error 2
make[1]: Leaving directory '/usr/src/evdi-1.4.0/module'
make: *** [Makefile:8: all] Error 2
```

Do you have any suggestions? I am running Arch Linux with Kernel version `4.13.3-1-ARCH`.

**Comment by konserw** [comment]
@TomWright you could try with this PR patched in: https://github.com/DisplayLink/evdi/pull/104 but some people say it doesn't work for them in Arch

**Comment by TomWright** [comment]
@konserw Thanks for your feedback, I may get around to trying that in the near future.

In the meantime since I'm trying to work on this PC, I have fallen back to using the `lts` kernel in Arch and it seems to be working, although after sleep/hibernation none of the monitors come back on... this may be unrelated though.

If anyone is interested, [here are instructions on how to use the lts kernel in Arch](http://www.yourtypicalguide.com/for-tech/tips-and-tricks/arch-linux-how-to-switch-to-long-term-support-lts-kernel/).

**Comment by ZEROF** [comment]
@TomWright Like i said in previous post, this was only tested on Ubuntu 16.04 and kernel version is 4.10+. Sorry, and i'm glad you have found your way.

**Comment by displaylink-mlukaszek** [comment]
4.10+ compatibility is provided with the v1.5.0
