### ISSUE TITLE
Framerate issues after upgrading to evdi 1.5.0

### ISSUE THREAD

**Issue by laurenblackfox** [DisplayLink/evdi#109]
Running ArchLinux 4.13.6-1 - the issue began when upgrading from kernel 4.12 to 4.13, and evdi 1.4.1 to 1.5.0. Getting a very low framerate, and a flood of errors in my dmesg:

[  799.610105] evdi: [W] collapse_dirty_rects:112 Not enough space for clip rects! Rects will be collapsed

(This appears to be a similar issue to #100)

**Comment by el-psycho** [comment]
I experience the same behaviour running Fedora 26. It seems worse with Chrome and Electron based applications.

displaylink version: 1.4
evdi version: 1.5.0
Kernel version: 4.13.5

**Comment by laurenblackfox** [comment]
I'll also add that Java apps (PHPStorm) cause the framerate to go dog-slow while they load. Takes a good while for it to settle out.

**Comment by Phaestion** [comment]
I can confirm with Java apps, IntelliJ and Android Studio, I have noticeable lag.

**Comment by displaylink-mlukaszek** [comment]
This is not reproducible with Ubuntu 17.10 using Kernel 4.13 and PageFlip set to off in modesetting options.

**Comment by bmgandre** [comment]
Same behavior running Slackware 14.2:
Kernel: 4.4.88
evdi: 1.5.0
displaylink: 1.4.210

**Comment by displaylink-mlukaszek** [comment]
Please raise these on [DisplayLink's Linux forum](http://displaylink.org/forum/forumdisplay.php?f=29) and attach logs which are specific to this particular evdi client (DisplayLinkManager). So far we have not been able to reproduce this - maybe attaching a video captured when you experience this would help, too. I'll close this as it doesn't seem to be a generic evdi problem so far.

**Comment by compuguy** [comment]
I have seen the same issues with 17.04, kernel 4.10, with the intel drivers (I can't get modesetting to work even with pageflip off; black screen). It's not a consistent frame rate issue. There are short periods when the framerate is normal.
