### ISSUE TITLE
Fix for displaylink-installer.sh

### ISSUE THREAD

**Issue by benmccann** [DisplayLink/evdi#11]
Here's an improved version of `detect_distro` which makes it work not only on Ubuntu, but also on forks of Ubuntu such as Linux Mint, Elementary OS, etc. I'm sending this patch using my external monitor powered by DisplayLink on Linux Mint :-)

```bash
detect_distro()
{
  if which lsb_release >/dev/null; then
    lsb_release -u > /dev/null 2>&1
    lsb_release_exit_code=$?
    if [ "$lsb_release_exit_code" = "0" ]; then
      # if this is a fork then use -u to find upstream version
      local R=$(lsb_release -d -s -u)
    else
      local R=$(lsb_release -d -s)
    fi
    echo "Distribution discovered: $R"
    if [ -z "${R##Ubuntu 14.*}" ]; then
      SYSTEMINITDAEMON=upstart
    elif [ -z "${R##Ubuntu 15.*}" ]; then
      SYSTEMINITDAEMON=systemd
    else
      echo "none"
    fi
  else
    echo "WARNING: Unknown distribution, assuming defaults - this may fail." >&2
  fi
}
```

**Comment by ajbogh** [comment]
Based on your code, I modified it to use the system init detection methods, instead of parsing the word "Ubuntu" from the distribution. it works with Ubuntu 16.04. Would you be willing to test this version with Ubuntu 15.10 and below, as well as Mint and your other distros, if you have them available. 

The only problem I found with this method is that in Ubuntu 16.04 the  --version flag isn't available on /sbin/init and it crashes at that point. This is why I put the 14.* code below the 15.* detection code. It would be nice if this used a more universal approach to init system detection, such as "which systemd" and "which upstart".

`
detect_distro()
{
  if which lsb_release >/dev/null; then
    lsb_release -u > /dev/null 2>&1
    lsb_release_exit_code=$?
    if [ "$lsb_release_exit_code" = "0" ]; then
      # if this is a fork then use -u to find upstream version
      local R=$(lsb_release -d -s -u)
    else
      local R=$(lsb_release -d -s)
    fi
    echo "Distribution discovered: $R"

    if [[ `systemctl` =~ -\.mount ]]; then
      #elif [ -z "${R##Ubuntu 15.*}" ]; then
      SYSTEMINITDAEMON=systemd
      echo "SYSTEMINITDAEMON set to systemd"
    elif [[ `/sbin/init --version` =~ upstart ]]; then
      #if [ -z "${R##Ubuntu 14.*}" ]; then
      SYSTEMINITDAEMON=upstart
      echo "SYSTEMINITDAEMON set to upstart"
    else
      echo "System init daemon not supported. Maybe sys-v?"
    fi
  else
    echo "WARNING: Unknown distribution, assuming defaults - this may fail." >&2
  fi
}
`

**Comment by benmccann** [comment]
I could probably spin up a couple VMs to test with over the weekend

Not a bad idea to try using a more universal approach. I think the way to do that would be the following:

```bash
$ sudo ls -l /proc/1/exe
lrwxrwxrwx 1 root root 0 Mar  8 06:16 /proc/1/exe -> /sbin/init
$ /sbin/init --version
init (upstart 1.12.1)
Copyright (C) 2006-2014 Canonical Ltd., 2011 Scott James Remnant

This is free software; see the source for copying conditions.  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE.
```

**Comment by benmccann** [comment]
Here's a more universal version which detects the init system itself instead of the distro. I've tested this on Ubuntu 14.04, Ubuntu 15.10, and Linux Mint 17.3.

```bash
detect_distro()
{
  # init process is pid 1
  INIT=`ls -l /proc/1/exe`
  if [[ $INIT == *"upstart"* ]]; then
    SYSTEMINITDAEMON=upstart
  elif [[ $INIT == *"systemd"* ]]; then
    SYSTEMINITDAEMON=systemd
  elif [[ $INIT == *"/sbin/init"* ]]; then
    INIT=`/sbin/init --version`
    if [[ $INIT == *"upstart"* ]]; then
      SYSTEMINITDAEMON=upstart
    elif [[ $INIT == *"systemd"* ]]; then
      SYSTEMINITDAEMON=systemd
    fi
  fi

  if [ -z "$SYSTEMINITDAEMON" ]; then
    echo "WARNING: Unknown distribution, assuming defaults - this may fail." >&2
  else
    echo "Init system discovered: $SYSTEMINITDAEMON"
  fi
}
```

**Comment by displaylink-mlukaszek** [comment]
Thanks. We'll be looking at a possibility of using something similar in next Ubuntu driver release.

**Comment by unfulvio** [comment]
@benmccann I can't get the Displaylink driver to work on Ubuntu 15.10 -- do you mind sharing the modified script you have if it works for you? thanks!

**Comment by benmccann** [comment]
@unfulvio just replace the `detect_distro` in the original script with the one I pasted just above

**Comment by unfulvio** [comment]
hello @benmccann I can't find that `detect_distro` function in the downloaded drivers/install script found on Displaylink site -- maybe they updated it? do you have a patched older version of the driver? I'd give it a try -- many thanks!

**Comment by benmccann** [comment]
Did you extract the driver components? http://support.displaylink.com/knowledgebase/articles/679060-porting-the-displaylink-ubuntu-driver-to-other-lin

**Comment by unfulvio** [comment]
ah thanks you're very kind helping -- I was looking in the wrong place, but... it still doesn't seem to work

I tried to replace the portion you reccomended, when I run  `sudo bash displaylink-installer.sh` I only get

```
DisplayLink Linux Software 1.0.335 install script called: 
Init system discovered: systemd
WARNING: Kernel version 4.2.0-34-generic is not supported. Highest supported version is 3.19.
```

However, if I run the driver as it is, it will get past through this warning (except then it wouldn't work at the end, more details here https://github.com/DisplayLink/evdi/issues/15)

**Comment by unfulvio** [comment]
sorry forget that, I didn't call `install` parameter

**Comment by unfulvio** [comment]
I'm able to run the modified script, but it'd still get the same issues as in #15
