### ISSUE TITLE
EVDI causes nouevau X driver crash

### ISSUE THREAD

**Issue by aplund** [DisplayLink/evdi#114]
I can only get EVDI to work when hot-plugging as there is a crash when X starts if EVDI has been installed as a module.  The crash trace is:

```
                Stack trace of thread 1669:
                #0  0x00007fe7dabff810 __GI_raise (libc.so.6)
                #1  0x00007fe7dac00e89 __GI_abort (libc.so.6)
                #2  0x000055ca15a1651a OsAbort (Xorg)
                #3  0x000055ca158f2874 ddxGiveUp (Xorg)
                #4  0x000055ca15a1c082 AbortServer (Xorg)
                #5  0x000055ca15a1cede FatalError (Xorg)
                #6  0x000055ca15a135ee OsSigHandler (Xorg)
                #7  0x00007fe7daf93de0 __restore_rt (libpthread.so.0)
                #8  0x00007fe7dabff810 __GI_raise (libc.so.6)
                #9  0x00007fe7dac00e89 __GI_abort (libc.so.6)
                #10 0x00007fe7dabf80ac __assert_fail_base (libc.so.6)
                #11 0x00007fe7dabf8123 __GI___assert_fail (libc.so.6)
                #12 0x00007fe7d72da719 drmmode_crtc_init (nouveau_drv.so)
                #13 0x00007fe7d72c3e46 NVPreInit (nouveau_drv.so)
                #14 0x000055ca158f47b2 InitOutput (Xorg)
                #15 0x000055ca158b2123 dix_main (Xorg)
                #16 0x00007fe7dabebf4a __libc_start_main (libc.so.6)
                #17 0x000055ca1589bf1a _start (Xorg)
```

Using gdb the code that raises the assertion is in the xorg nouveau driver:

```
#13 0x00007fe7d72da719 in drmmode_crtc_init (num=0, drmmode=0x55ca17885160, 
    pScrn=0x55ca1787a160) at drmmode_display.c:793
793		assert(ret == 0);
(gdb) list
788		drmmode_crtc->drmmode = drmmode;
789		drmmode_crtc->hw_crtc_index = num;
790	
791		ret = nouveau_bo_new(pNv->dev, NOUVEAU_BO_GART | NOUVEAU_BO_MAP, 0,
792				     64*64*4, NULL, &drmmode_crtc->cursor);
793		assert(ret == 0);
794	
795		crtc->driver_private = drmmode_crtc;
796	
797		/* Mark num'th crtc as in use on this device. */
```

When EVDI isn't installed the nouveau driver works fine.

evdi version: git-a73092d
kernel: 4.15 (mainline)
xf86 nouveau: 1.0.15
xorg-server: 1.19.6

$ lspci | egrep '(3D|VGA)'
00:02.0 VGA compatible controller: Intel Corporation Device 591b (rev 04)
01:00.0 3D controller: NVIDIA Corporation GM107GLM [Quadro M1200 Mobile] (rev a2)

**Comment by displaylink-mlukaszek** [comment]
Do you still see the same problem if you boot with the device connected, so that `/dev/dri/*` entries are created before X start? Alternatively, you can use sysfsutils to force evdi to create 2 DRM device nodes regardless of the fact that a device is connected or not. You can alter the number, depending on how many additional monitors you're connecting.

So, after you install sysfsutils the following should change the behaviour:
`echo "devices/evdi/add = 2" >> /etc/sysfs.conf`

**Comment by displaylink-dkurek** [comment]
Will close the issue for now as there was no response or any other activity.
If you still see the problem please first check support page
(https://support.displaylink.com/), there are some things to try.
