### ISSUE TITLE
Display port issue

### ISSUE THREAD

**Issue by DaveSys911** [DisplayLink/evdi#119]
hi running the following kernel and distro - 4.14.16-300.fc27.x86_64
have a dell xps 13,dell d6000 docking
installed the following rpm 
 fedora-26-displaylink-1.5.0-1.x86_64.rpm 

for some reason the driver only works with hdmi ports on the docking but not the display ports

kindly assist

**Comment by displaylink-dkurek** [comment]
Will close the issue for now as there was no response or any other activity.
If you still see the problem please first check support page
(https://support.displaylink.com/), there are some things to try.
