### ISSUE TITLE
Evdi on debian jessie

### ISSUE THREAD

**Issue by infermita** [DisplayLink/evdi#12]
Hi guys,
i have a aoc usb display with Bus 002 Device 004: ID 17e9:ff0d DisplayLink 
I use the ubuntu driver from displaylink.com and not working
This is result of the kernel message

[drm] evdi: evdi_stats_init
Mar[drm] Initialized evdi 1.0.68 19700101 on minor 0
Mar[W] evdi_painter_disconnect (dev=0) An unknown connection to ffff8800a1e6a600 tries to close us - ignoring
Mar[W] evdi_painter_disconnect (dev=0) An unknown connection to ffff8800a1e6a600 tries to close us - ignoring
Mar[D] evdi_detect Painter is disconnected
Mar[D] evdi_detect Painter is disconnected
Mar[D] evdi_detect Painter is disconnected
Mar[D] evdi_detect Painter is disconnected
Mar[D] evdi_painter_crtc_state_notify (dev=0) Notifying crtc state: 0
Mar[D] evdi_painter_crtc_state_notify (dev=0) Notifying crtc state: 0
Mar[W] evdi_painter_disconnect (dev=0) An unknown connection to ffff8800b5e3a000 tries to close us - ignoring
Mar[D] evdi_painter_connect (dev=0) Connected with ffff8800b5e3a000
Mar[D] evdi_painter_connect (dev=0) Edid (3 bytes): 94 c4 00
Mar[D] evdi_detect (dev=0) Painter is connected
Mar[D] evdi_detect (dev=0) Painter is connected
Mar[D] evdi_painter_get_edid (dev=0) 94 c4 00
MarRaw EDID:
Mar  	94 c4 00 ef dd 7f 00 00 94 c4 00 ef 00 00 00 00
Mar   	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Mar  	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Mar  	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Mar  	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Mar  	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Mar  	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Mar  	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
evdevdi.0: DVI-I-1: EDID invalid.

Can you help me?

Best regards Alberto

**Comment by displaylink-mlukaszek** [comment]
The EDID looks indeed invalid. What cable are you using for the monitor? Can you try with other (shorter/better quality) cable?

**Comment by displaylink-mlukaszek** [comment]
No feedback so far, closing this - please use DisplayLink forum for further help.
