### ISSUE TITLE
High system load

### ISSUE THREAD

**Issue by n1-cz** [DisplayLink/evdi#126]
Hi everyone,

I use your driver packed for Ubuntu (http://www.displaylink.com/downloads/ubuntu). It works flawlessly but it utilizes my i7 to ~50%+ when I do some "fast movement" on the screen - webpage scroll, youtube video, etc. The 50% is purely allocated by the DisplayLink process not by the browser.
My external screen is 1080p via HDMI and I'm kinda worried to connect 1440p (via DP) because of the heavy load.

Is this normal or am I missing something?

![2018-04-12-233345_1920x1080_scrot](https://user-images.githubusercontent.com/198654/38705525-16e53196-3eaa-11e8-8275-b962c4ea7b0e.png)

**Comment by grafa** [comment]
I guess this might be related to this
https://displaylink.org/forum/showthread.php?s=35ed3da47fb401dcdedb472d024f57bf&t=65983

**Comment by MatthewBooth** [comment]
I've been experiencing this issue. It's much less pronoucned in 18.04 as it was in 16.04, but it's still a huge issue.

I came from a Dell XPS 15 (9550) using a Dell WD15 USB-C dock with zero issues, to a HP zBook 15 G3 with a USB3SDOCKHD and huge CPU usage. It was entirely unusable on 16.04 with two 1080p displays.

**Comment by grafa** [comment]
@MatthewBooth had u used the dell docking station on Linux too? Does it need any drivers and what was the load? Or was there any?

I was thinking about the dell station but it's ultra expensive in my country. But if it runs without drivers and it doesn't put any load on CPU (like it's not a virtual screen where everything is rendered by CPU)...... I might consider it.

**Comment by petrleocompel** [comment]
Well, if you use it as USB hub then what did you expect. No CPU load.

**Comment by dawikur** [comment]
DisplayLinkManager is userspace driver and it is better to use [DisplayLink Linux Forum](https://displaylink.org/forum/forumdisplay.php?f=29) to raise problems with it. Let keep evdi repo for actual problem with it :-)

**Comment by mauromol** [comment]
@displaylink-dkurek @dawikur 

> DisplayLinkManager is userspace driver and it is better to use [DisplayLink Linux Forum](https://displaylink.org/forum/forumdisplay.php?f=29) to raise problems with it. Let keep evdi repo for actual problem with it :-)

I understand DisplayLinkManager is a userspace driver distinct from evdi, but how can someone put this to the attention of DisplayLink developers? The forum is evidently useless, since many messages posted their about DisplayLinkManager performance issues under Linux have been clearly ignored.
Are DisplayLink developers aware of the issue? Are they working on it? Is there any hope to get future improvements on that area?

**Comment by im-n1** [comment]
Thankfully there are other manufacturers where their docking stations have a proper support.

**Comment by groovyman** [comment]
Well there is Intel with their Thunderbold but their chaps can not be found in AMD Ryzen notebooks..
