### ISSUE TITLE
evdi: [E] evdi_painter_grabpix_ioctl:708 Invalid buffer dimension

### ISSUE THREAD

**Issue by MichaelJCole** [DisplayLink/evdi#129]
Hi, I'm having trouble getting Displaylink to work with Ubuntu 18.04.  Same hardware was working with Ubuntu Gnome 16.04 (also uses x)

https://displaylink.org/forum/showthread.php?t=66106

When trying to set the mode with xrandr, I found this error in the logs:  "Invalid buffer dimension"

Any suggestions how to get past this issue?

Thanks!

```
michael@mc-desktop ~
☀  cvt 1920 1080 60                                                                                           
# 1920x1080 59.96 Hz (CVT 2.07M9) hsync: 67.16 kHz; pclk: 173.00 MHz
Modeline "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync

michael@mc-desktop ~
☀  xrandr --newmode "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync 

michael@mc-desktop ~
☀  xrandr --addmode DVI-I-1-1 1920x1080_60.00                                                  

michael@mc-desktop ~
☀  xrandr --output DVI-I-1-1 --mode 1920x1080_60.00                                                  

michael@mc-desktop ~
☀  
```
Here is the `dmesg` output:

```
[ 1150.952697] evdi: [D] evdi_painter_crtc_state_notify:482 (dev=1) Notifying crtc state: 3
[ 1150.956102] evdi: [D] evdi_painter_mode_changed_notify:506 (dev=1) Notifying mode changed: 1920x1080@60; bpp 32; 
[ 1150.956104] evdi: [D] evdi_painter_mode_changed_notify:507 pixel format 875713112
[ 1150.956118] evdi: [D] evdi_painter_crtc_state_notify:482 (dev=1) Notifying crtc state: 0
[ 1150.956121] evdi: [D] evdi_painter_dpms_notify:469 (dev=1) Notifying dpms mode: 0
[ 1150.956312] evdi: [E] evdi_painter_grabpix_ioctl:708 Invalid buffer dimension
[ 1151.151066] evdi: [D] evdi_detect:75 (dev=2) Painter is connected
[ 1151.151069] evdi: [D] evdi_painter_get_edid_copy:216 (dev=2) 00 ff ff
[ 1151.151087] evdi: [W] evdi_mode_valid:61 Mode 800x600@56 rejected
[ 1151.151088] evdi: [W] evdi_mode_valid:61 Mode 800x600@60 rejected
[ 1151.151089] evdi: [W] evdi_mode_valid:61 Mode 848x480@60 rejected
[ 1151.151090] evdi: [W] evdi_mode_valid:61 Mode 1024x768@60 rejected
[ 1151.151129] evdi: [D] evdi_detect:75 (dev=1) Painter is connected
[ 1151.151130] evdi: [D] evdi_painter_get_edid_copy:216 (dev=1) 00 ff ff
[ 1151.151141] evdi: [W] evdi_mode_valid:61 Mode 800x600@56 rejected
[ 1151.151142] evdi: [W] evdi_mode_valid:61 Mode 800x600@60 rejected
[ 1151.151143] evdi: [W] evdi_mode_valid:61 Mode 848x480@60 rejected
[ 1151.151144] evdi: [W] evdi_mode_valid:61 Mode 1024x768@60 rejected
```

**Comment by dawikur** [comment]
Are you using the latest [driver](http://www.displaylink.com/downloads/ubuntu)? Did you update only the Ubuntu (assuming also newer kernel)?

**Comment by MichaelJCole** [comment]
Hi Dawikur, yes.  I'm using the latest driver and a fresh install of Ubuntu.

Here's the output from the support tool: https://drive.google.com/file/d/1Q6RKJ_F8CB1PfSKSw0jMX5G7AjwCl1pi/view?usp=sharing

**Comment by MichaelJCole** [comment]
The hardware has DisplayPort and HDMI ports for each of the monitors.  Replacing the DisplayPort cables with HDMI cables fixed the problem.  It's astronomical to have two cables fail at the same time, so It seems like a driver or firmware bug.  

After reinstalling different versions of linux about 6 times, I'm back to Ubuntu 18.04, using [this repo's](https://github.com/AdnanHodzic/displaylink-debian/issues/132#issuecomment-393055775) script to install it.

**Comment by bowerth** [comment]
hello - I may have a related problem, posting here because dmesg output similar: `[ 2374.142424] evdi: [E] evdi_painter_grabpix_ioctl:708 Invalid buffer dimension`

I see output on the DL device (LT1421@XPS13), however there are issues with the way the image is drawn

here a photo of the screen how it displays the background image:

![](https://s3.eu-central-1.amazonaws.com/picshare11/displaylink/lt1421.jpg)

this is how the image should look like:

![](https://s3.eu-central-1.amazonaws.com/picshare11/displaylink/printscreen.png)

any suggestions would be appreciated!

**Comment by MartinHerrman** [comment]
I run into the same error message in the logs:

[14333.915889] evdi: [D] evdi_detect:85 (dev=1) Painter is connected
[14333.915894] evdi: [D] evdi_painter_get_edid_copy:217 (dev=1) 00 ff ff
[14333.966009] evdi: [D] evdi_detect:85 (dev=1) Painter is connected
[14333.966012] evdi: [D] evdi_painter_get_edid_copy:217 (dev=1) 00 ff ff
[14354.023752] evdi: [D] evdi_painter_crtc_state_notify:483 (dev=1) Notifying crtc state: 3
[14354.036762] evdi: [D] evdi_painter_mode_changed_notify:507 (dev=1) Notifying mode changed: 1920x1080@60; bpp 32; 
[14354.036765] evdi: [D] evdi_painter_mode_changed_notify:508 pixel format 875713112
[14354.036777] evdi: [D] evdi_painter_crtc_state_notify:483 (dev=1) Notifying crtc state: 0
[14354.036780] evdi: [D] evdi_painter_dpms_notify:470 (dev=1) Notifying dpms mode: 0
[14354.036937] evdi: [E] evdi_painter_grabpix_ioctl:710 Invalid buffer dimension

This happens when I switch resolution from 1920x1080 to 2560x1440. In 1920x1080 everything works fine, when I switch to 2560x1440 the monitor turns black, saying 'Input not supported', and then (of course) Fedora switches back to 1920x1080.

Fedora 28
Latest displaylink RPM
Dell XPS13 9343
Displaylink DA200 USB dongle
Monitor AOC Q2790PQU

Is there anything I can do to help and get this problem solved?

**Comment by cheese1** [comment]
@MartinHerrman : where are your rpms from?

**Comment by MartinHerrman** [comment]
@cheese1 Hm.. maybe my mistake! I downloaded the RPM here:

https://github.com/displaylink-rpm/displaylink-rpm/releases

**Comment by cheese1** [comment]
maybe you want to test from
http://www.nosuchhost.net/~cheese/fedora/packages/29/x86_64/displaylink.html
it's based on the same spec-file

**Comment by MartinHerrman** [comment]
Thanks for sharing!

Unfortunately it gives me the same result: 1080 works, but when I try 1440 the monitor states that the input is invalid.

BTW, since my first post here I upgraded fedora from version 28 to 29.

**Comment by cheese1** [comment]
i myself have troubles since adding a third display. i now get artifacts. seem to be related to my windows manager xfwm4 and *not* using compositing.

**Comment by MartinHerrman** [comment]
Nice dependency :-)

In the mean time I have a new PC (ubuntu 18.10 / nvidia graphics) connected to the monitor, and my laptop is now also running Ubuntu 18.10. So unfortunately no updates from my side on this topic anymore..

**Comment by itarozzi** [comment]
I have a similar problem using Debian buster. Second and third monitor are detected but they display a wrong image

**Comment by itarozzi** [comment]
I solved my issue now:

- downgraded to kernel 4.18.0-3-amd64 #1 SMP Debian 4.18.20-2 (2018-11-23) x86_64 GNU/Linux
- downgraded xserver-xorg-core to 2:1.19.2-1+deb9u4
- uninstalled and installed again 
- added xorg.conf (without this, only the mouse pointer is active in secondary monitor)

`/etc/X11/xorg.conf`
Section "Device"
Identifier "Intel"
        Driver "intel"
        Option "VSync" "false"
EndSection

**Comment by CharlesCage** [comment]
Having a similar problem here. Any solution that doesn't involve downgrading kernel?

**Comment by rumble-up** [comment]
My issue was solved by running a shell script that slightly lowers the resolution from 1366x768 to 1360x768.  

Following instructions from [this forum](https://www.displaylink.org/forum/showthread.php?p=88777#post88777).

The shell script is here:
```
#!/bin/bash

# Adjust these parameters to your needs.
# These worked for me (AOC E1659Fwu)
OUTPUT="DVI-I-1-1"
HORIZONTAL_RES="1360"
VERTICAL_RES="768"

MODELINE="$(cvt ${HORIZONTAL_RES} ${VERTICAL_RES} | tail -n 1 | awk '{for (i=3; i<=NF; i++) print $i}')"
MODELINE_NAME=$(echo ${MODELINE} | awk '{print $1}' | sed -e 's/^"//' -e 's/"$//')

echo "Modeline:"
echo ${MODELINE_NAME} ${MODELINE}
echo

echo "[*] xrandr --newmode"
xrandr -d :0 --newmode ${MODELINE_NAME} ${MODELINE}

echo "[*] xrandr --addmode (${OUTPUT})"
xrandr -d :0 --addmode "${OUTPUT}" ${MODELINE_NAME}

echo "[*] Set new resolution"
xrandr -d :0 --output "${OUTPUT}" --mode ${MODELINE_NAME}
```

**Comment by Lqp1** [comment]
I also have that issue; I have two external screens with high resolutions (DVI-I-2-2 connected 2560x1440+1920+0 (normal left inverted right x axis y axis) 527mm x 296mm)

Adding the first screen gives me this error when I change the layout (did not have any error while running `setprovideroutputsource`:
```
$ xrandr --output DVI-I-2-2 --right-of eDP-1
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  139 (RANDR)
  Minor opcode of failed request:  7 (RRSetScreenSize)
  Value in failed request:  0x0
  Serial number of failed request:  42
  Current serial number in output stream:  43
```
But the screen works just fine.

Adding the second screen later gives me this error in `dmesg` when I run the `setprovideroutputsource`, and then X server quits and I need to login again:
`[E] evdi_painter_grabpix_ioctl:840 Invalid buffer dimension`
Xorg log:
```
[   529.121] (EE)
[   529.121] (EE) Backtrace:
[   529.121] (EE) 0: /usr/bin/X (xorg_backtrace+0x4d) [0x556237663f9d]
[   529.121] (EE) 1: /usr/bin/X (0x5562374bc000+0x1abc58) [0x556237667c58]
[   529.121] (EE) 2: /lib64/libpthread.so.0 (0x7f6b524f2000+0x14680) [0x7f6b52506680]
[   529.121] (EE) 3: /usr/lib64/xorg/modules/drivers/modesetting_drv.so (0x7f6b52a7d000+0x8d4f) [0x7f6b52a85d4f]
[   529.121] (EE) 4: /usr/bin/X (RRCrtcSet+0x804) [0x5562375c54a4]
[   529.122] (EE) 5: /usr/bin/X (ProcRRSetCrtcConfig+0x53f) [0x5562375c689f]
[   529.122] (EE) 6: /usr/bin/X (0x5562374bc000+0x56264) [0x556237512264]
[   529.122] (EE) 7: /usr/bin/X (0x5562374bc000+0x5a244) [0x556237516244]
[   529.122] (EE) 8: /lib64/libc.so.6 (__libc_start_main+0xeb) [0x7f6b52346e9b]
[   529.122] (EE) 9: /usr/bin/X (_start+0x2a) [0x55623750008a]
[   529.122] (EE)
[   529.122] (EE) Segmentation fault at address 0x29
[   529.122] (EE)
Fatal server error:
[   529.122] (EE) Caught signal 11 (Segmentation fault). Server aborting
[   529.122] (EE)
[   529.122] (EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
[   529.122] (EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
[   529.122] (EE)
[   529.122] (II) AIGLX: Suspending AIGLX clients for VT switch
[   529.167] (EE) Server terminated with error (1). Closing log file.
```
I tries lowering the resolutions but that did not change anything.

**Comment by displaylink-emajewsk** [comment]
We'll be verifying this on our end. I'll close this for now. Please create a new issue if the problem resurfaces.
