### ISSUE TITLE
evdi upstream opportunity

### ISSUE THREAD

**Issue by RussianNeuroMancer** [DisplayLink/evdi#131]
Hello, evdi developers!

There seems like opportunity to upstream evdi: https://lists.freedesktop.org/archives/dri-devel/2018-May/177130.html

Maybe it's makes sense to cooperate with VMware to get evdi upstreamed?

**Comment by displaylink-dkurek** [comment]
Thanks for letting us know. We are keeping an eye on this. 
Will close the issue now.
