### ISSUE TITLE
XFCI

### ISSUE THREAD

**Issue by sameehj** [DisplayLink/evdi#132]
When I try to login to my desktop environment (XFCE) I get logged out immediately, I believe that the x server is crashing during the login operation. When I disconnect the usb I can login successfully.

Xserver log:
[  5307.398] randr: falling back to unsynchronized pixmap sharing
[  5307.398] (II) modeset(G0): Allocate new frame buffer 1920x1080 stride
[  5307.406] (EE) modeset(G0): failed to set mode: No such file or directory

uname -a:
Linux Terminator 4.16.13-1-ARCH #1 SMP PREEMPT Thu May 31 23:29:29 UTC 2018 x86_64 GNU/Linux

**Comment by cacarr-pdxweb** [comment]
What version of xorg-server are you running? 1.20 and up is apparently incompatible, and you may need to downgrade -- as far as I can tell.

**Comment by sameehj** [comment]
I have tried to downgrade however the issue keeps occurring...

**Comment by cacarr-pdxweb** [comment]
What xorg server version did you downgrade to?

**Comment by sameehj** [comment]
Actually the downgrade process didn't quit succeed, so please ignore my
last comment. I'll update as soon as I'll have time to do this

**Comment by sameehj** [comment]
I have just downgraded the xorg back to 1.19 and everything started working again,
Thanks!
