### ISSUE TITLE
kernel headers not found

### ISSUE THREAD

**Issue by matvrix** [DisplayLink/evdi#137]
Trying to install evdi on F28 provided by /DisplayLink USB Graphics Software for Ubuntu 4.2/displaylink-driver-4.2.29

But, evdi fails to build with this exception :
Your kernel headers for kernel 4.17.9-200.fc28.x86_64 cannot be found at /lib/modules/4.17.9-200.fc28.x86_64/build or /lib/modules/4.17.9-200.fc28.x86_64/source.

Have the following kernel modules :
[root@works displaylink-driver-4.2.29]# rpm -qa | grep '^kernel' | sort -V 
kernel-4.16.3-301.fc28.x86_64
**kernel-4.17.9-200.fc28.x86_64**
kernel-core-4.16.3-301.fc28.x86_64
**kernel-core-4.17.9-200.fc28.x86_64**
kernel-debug-devel-4.17.11-200.fc28.x86_64
kernel-devel-4.17.11-200.fc28.x86_64
**kernel-headers-4.17.9-200.fc28.x86_64**
kernel-modules-4.16.3-301.fc28.x86_64
kernel-modules-4.17.9-200.fc28.x86_64
kernel-modules-extra-4.16.3-301.fc28.x86_64
kernel-modules-extra-4.17.9-200.fc28.x86_64

Highlighted entries show that the header exists for the corresponding kernel core and all that.

**Comment by displaylink-dkurek** [comment]
Will close the issue for now as there was no response or any other activity.
Hopefully the new packages does not have this problem.
