### ISSUE TITLE
xrandr --setprovideroutputsource 1 0 failed to run

### ISSUE THREAD

**Issue by zioalex** [DisplayLink/evdi#141]
Hi guys trying to get the Dell displaylink hub on my laptop but I have some problem.
I have a Sabayon machine.
I managed to install the proper kernel and displaylink package.
Some info:
* Linux sabayon 4.18.5-pentoo
* evdi-1.5.0-r2
* x11-drivers/displaylink-driver-4.1.9
* x11-base/xorg-server-1.19.5-r2
* gnome-base/gnome-desktop-3.24.2

Noticed that when the evdi module is loaded I get the follow message:
```
17.592680] evdi: loading out-of-tree module taints kernel.
[   17.592772] evdi: no symbol version for drm_framebuffer_cleanup
[   17.593774] evdi: [I] Initialising logging on level 5
[   17.593776] evdi: [I] Atomic driver:no
```

Not sure if it means something useful.

I tried with both :
```
::::::::::::::
20-displaylink.conf1
::::::::::::::
Section "Device" 
  Identifier "Intel Graphics"
  Driver "intel"
EndSection

::::::::::::::
20-displaylink.conf2
::::::::::::::
Section "Device"
  Identifier "DisplayLink"
  Driver "modesetting"
  Option "PageFlip" "false"
EndSection 
```

As suggested here https://github.com/AdnanHodzic/displaylink-debian/issues/68

While running with the 20-displaylink.conf1 I could not see 2 providers.
Now I am running with the 20-displaylink.conf2 and I can see the 2 providers:

```
> xrandr --listproviders
Providers: number : 2
Provider 0: id: 0x66 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 4 associated providers: 0 name:modesetting
Provider 1: id: 0x3f cap: 0x0 crtcs: 0 outputs: 0 associated providers: 0 name:modesetting
```

Then I try to connect the provider and I receive the follow error.
```
> xrandr --setprovideroutputsource 1 0
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  139 (RANDR)
  Minor opcode of failed request:  35 (RRSetProviderOutputSource)
  Value in failed request:  0x3f
  Serial number of failed request:  16
  Current serial number in output stream:  17
```

After this I do not see the additional monitors...neither with xrandr, arandr or gnome display setting.
Any suggestions.

**Comment by Lqp1** [comment]
On Gentoo I needed to upgrade EVDI and DisplayLink to make my Latitude 7490 work with D6000 dock:
```
x11-drivers/evdi-1.6.4
x11-drivers/displaylink-driver-5.2.14
x11-base/xorg-server-1.20.5
```
Kernel is `4.19.86-gentoo`

I noticed the same errors using xrandr (BadValue etc...) but the screen works anyway when setting provideroutputsource then configuring the screen.

**Comment by displaylink-dkurek** [comment]
There has been a long time without any update. 
Will close this issue. If you still can see it with newest versions please raise a new one.
Thanks!
