### ISSUE TITLE
Ubuntu 18.10 support

### ISSUE THREAD

**Issue by olivertappin** [DisplayLink/evdi#143]
Is there any support for Ubuntu 18.10 (Cosmic Cuttlefish) in the near future? Kernel version `4.19`

**Comment by AdnanHodzic** [comment]
Please refer to [displaylink-debian](https://github.com/AdnanHodzic/displaylink-debian)

**Comment by displaylink-dkurek** [comment]
I think we should split this into two questions:

 1) is kernel 4.19 supported?
Yes, EVDI version 1.6.0 adds support for kernel 4.19 and 4.20.

 2) is Ubuntu 18.10 suported?
This is not a question related to this repository, rather to DisplayLinkManager.
For this it is better to check displaylink [home page](https://www.displaylink.com/) or [support](https://support.displaylink.com/) page.
