### ISSUE TITLE
Incompatible with 4.20.0

### ISSUE THREAD

**Issue by noraj** [DisplayLink/evdi#145]
> noraj a commenté le 2018-12-26 15:27
>
> evdi 1.5.1 is not building for 4.20.0 (manjaro) ...

> > mwawrzyniak a commenté le 2018-12-26 19:21
> >
> >I uploaded a new release to fix building in 4.20 kernels. The error in make.log related to something removed in 4.20 (https://github.com/torvalds/linux/commit/04cfcc7ab358e331b32cabde1e853a125f3f8735#diff-43768cc89c01c730cb119634b42dfa81).
> >
> > The functionality wasn't apparently stable enough to be worthwhile. Removing it should have no effect on kernels < 4.20 either.

See the patch here https://aur.archlinux.org/cgit/aur.git/commit/?h=evdi&id=432d29bbfafebcf62be0d5930c6f87c16ac6fa12

**Comment by displaylink-dkurek** [comment]
We are preparing new release which will address problems with compatibility with new kernels. We have fix  for 4.20 version. Will close this issue after the code reaches github.

**Comment by NathanDeckinga** [comment]
I just rolled up to 4.20 on Fedora 29 and ran into this.  Thanks for the update and I look forward to the release.  As I'm getting the issue currently, let me know if you need any info and I'll try it out as soon as it makes it to git (with feedback if needed).

Thanks again!

**Comment by tobikl1** [comment]
for Fedora 29 and kernel 4.20 i got an error when trying to run

> dkms build evdi/1.5.1

i just edited /var/lib/dkms/evdi/1.5.1/source/evdi_drv.h and added the line

> #define FBINFO_CAN_FORCE_OUTPUT 1

right after 

> #define DRIVER_PATCHLEVEL 1

then i ran

> dkms build evdi/1.5.1
> dkms install evdi/1.5.1

which fixed the problem for me.

**Comment by noraj** [comment]
It is working with evdi 1.5.1 (with [AUR](https://aur.archlinux.org/packages/evdi/) 1.5.1-2 and its patch) and kernel 4.20.3-1-MANJARO.

**Comment by lfuelling** [comment]
@displaylink-dkurek when exactly will the fix (that you apparently are still holding back) be released to GitHub?

**Comment by displaylink-dkurek** [comment]
Sorry for no response - we have a bit of a slip. We are aiming for beginning of the next week.

**Comment by NathanDeckinga** [comment]
Slips happen.  Is it still looking like this week though, @displaylink-dkurek ?

**Comment by displaylink-dkurek** [comment]
So, finally its there :)
evdi repository has been updated with quite some number of changes.
We are shifting towards 'atomic modeset', which means we are dropping 
support for kernels older than 4.2.
With this change we did bump-up the evdi/libevdi versions, so for compatibility
please install new DisplayLinkManager, which can be downloaded from here:
https://www.displaylink.com/downloads/ubuntu 
Hope you will like it ;)
