### ISSUE TITLE
High CPU ussage on Kubuntu 18.10

### ISSUE THREAD

**Issue by killmasta93** [DisplayLink/evdi#147]
Hi,
I was wondering if someone could shed some light on the issue im having. Sometimes when i connect i get high CPU usage not sure why. Here is a screen shot. Only happens when i connect the plugable

![screenshot at 2019-01-07 16-00-01](https://user-images.githubusercontent.com/13953629/50905251-63dcbc00-13f0-11e9-9211-1ed077d1a53c.png)

Thank you

**Comment by kubaceg** [comment]
Same here. Linux mint 19 Tara. I have always around 20% CPU.

**Comment by displaylink-dkurek** [comment]
@killmasta93 can you please check the new 5.1 release of DisplayLinkManager?
It can be downloaded from here:
https://www.displaylink.com/downloads/ubuntu
Can you compare it to the previous one?
If you still find CPU usage to high please take a look at our
support page (https://support.displaylink.com/)
Thanks. 

Will close the issue as this is not evdi related.

**Comment by nhondong** [comment]
I installed the 5.1 Release on ubuntu disco with 2 external monitors (wide screen 2580x1080).
CPU monitor shows 2 CPUs at 100%.
movements on the monitors are very slow.

**Comment by kubaceg** [comment]
For me 5.1 driver is much more stable, but sometimes it can eat up to 50% of CPU
