### ISSUE TITLE
Develop in the open

### ISSUE THREAD

**Issue by ericschultz** [DisplayLink/evdi#149]
In at least a few forum posts, such as (https://support.displaylink.com/forums/287786-displaylink-feature-suggestions/suggestions/16639654-linux-wayland-support), it was suggested that the community develop functionality that doesn't exist. Unfortunately, that would be pointless as pull requests are not considered for actual merging as described in comments for  #148, #146, #142. Additionally, the core driver code is provided as binary. I can't for the life of me figure out why you won't open source some code that you clearly don't not care about maintaining all that much.

**Comment by displaylink-dkurek** [comment]
Development for Wayland is in progress (as Wim wrote in the link you have
provided) mainly in other components, like GNOME or Mutter. We had also added
support for different pixel formats (e4ea8d3d8aec816411bfcf1057448a4cac36381c) to EVDI as a possible optimization
of pixel path. Any PR is welcome and is considered for merge but sometimes we
already have those changes and are testing them before a push.

We have explained why we are providing part of the solution in binary format,
please take a look at our [support page](https://support.displaylink.com/knowledgebase/articles/1104056-why-has-displaylink-not-released-source-code-for-t).

Hope I have helped explaining things a bit. 
Closing.
