### ISSUE TITLE
Must Login Twice when using driver (Linux)

### ISSUE THREAD

**Issue by ameeno** [DisplayLink/evdi#153]
hello, for some reason, my display manager forces me to enter my password a second time after the first time (and activates extra displays)

loginctl shows 2 sessions
$ loginctl
SESSION  UID USER SEAT  TTY
      2 1000 xxxx seat0    
      4 1000 xxxx seat0    

2 sessions listed.

it does not matter if i use lightdm or gdm or sddm.

the setup i am using is arch with displaylink from aur and this xorg file:

/usr/share/X11/xorg.conf.d/20-evdidevice.conf
Section "OutputClass"
	Identifier "DisplayLink"
	MatchDriver "evdi"
	Driver "modesetting"
	Option  "AccelMethod" "none"
EndSection

please advise

**Comment by displaylink-dkurek** [comment]
Hi @ameeno 
How many monitors are you using? Also, what is your GPU card?

Here is something which sounds similar:
https://support.displaylink.com/knowledgebase/articles/1859356-x-server-crashes-on-nvidia-systems-when-displaylin
Note in the `solution` there is Section `Device` and there is less options ;)

You could also try to check this out
https://support.displaylink.com/knowledgebase/articles/1883074-ubuntu-16-04-x-server-starts-in-low-graphics-mode

**Comment by ameeno** [comment]
Hello.I am using and integrated hd4600 from hasw3ll CPU, with 2 additional screens connected via displaylink (chip supports 3 screens)I think the problem is to do with systems load order and the displaylink acctioins.Basically displaylink systems file is told to start after display-manager has ended. But does not actually start u til password is entered on the login screen (sddm or lighten)And loginctl shows me 2 sessional one I just logged into and one I crashed out off,What logs can tell us what's happening?Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Dawid Kurek <notifications@github.com> Date: 19/04/2019  07:29  (GMT+00:00) To: DisplayLink/evdi <evdi@noreply.github.com> Cc: Arun Shah <fastah@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [DisplayLink/evdi] Must Login Twice when using driver (Linux) (#153) Hi @ameeno
How many monitors are you using? Also, what is your GPU card?
Here is something which sounds similar:
https://support.displaylink.com/knowledgebase/articles/1859356-x-server-crashes-on-nvidia-systems-when-displaylin
Note in the solution there is Section Device and there is less options ;)
You could also try to check this out
https://support.displaylink.com/knowledgebase/articles/1883074-ubuntu-16-04-x-server-starts-in-low-graphics-mode

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DisplayLink/evdi","title":"DisplayLink/evdi","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/DisplayLink/evdi"}},"updates":{"snippets":[{"icon":"PERSON","message":"@displaylink-dkurek in #153: Hi @ameeno \r\nHow many monitors are you using? Also, what is your GPU card?\r\n\r\nHere is something which sounds similar:\r\nhttps://support.displaylink.com/knowledgebase/articles/1859356-x-server-crashes-on-nvidia-systems-when-displaylin\r\nNote in the `solution` there is Section `Device` and there is less options ;)\r\n\r\nYou could also try to check this out\r\nhttps://support.displaylink.com/knowledgebase/articles/1883074-ubuntu-16-04-x-server-starts-in-low-graphics-mode\r\n"}],"action":{"name":"View Issue","url":"https://github.com/DisplayLink/evdi/issues/153#issuecomment-484780722"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DisplayLink/evdi/issues/153#issuecomment-484780722",
"url": "https://github.com/DisplayLink/evdi/issues/153#issuecomment-484780722",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by displaylink-dkurek** [comment]
Have you checked the suggested solutions?
I would guess the 'login twice' is actually xserver crash on the first attempt. 
You can check Xorg logs, the location of them depends on the version you use
(`${HOME}/.local/share/xorg`, or `/var/log/xorg`, somethign like that)
You can also explicitly look for xserver crashed, or look into dmesg.. :-)

**Comment by ameeno** [comment]
Hi, I will look at this when i get a chance. but i have since moved back to windows 10.

it works better and my linux needs can be fulfilled via WSL/Hyper-V.

**Comment by Galiaf47** [comment]
Hello. I've had the same issue, double log in. 
Video card: Intel Corporation UHD Graphics 620

I have tried solutions provided by @displaylink-dkurek, the following actually helped me to resolve the issue

> You could also try to check this out
> https://support.displaylink.com/knowledgebase/articles/1883074-ubuntu-16-04-x-server-starts-in-low-graphics-mode

Thanks.
