### ISSUE TITLE
https://github.com/DisplayLink/evdi/issues/154 continuation

### ISSUE THREAD

**Issue by AndreV84** [DisplayLink/evdi#156]
could you share any insight on how to implement the display output displayed somehow?

**Comment by displaylink-dkurek** [comment]
Take a look at 
https://github.com/mlukaszek/evdipp
It is as simple QT based 'display' with evdi underneath.

Is this what you are looking for?

**Comment by AndreV84** [comment]
is there any solution to use DisplayLink on nvidia Jetson nano [aarch64] ?
