### ISSUE TITLE
Entire screen considered dirty

### ISSUE THREAD

**Issue by qguv** [DisplayLink/evdi#157]
I've been working on a pixelflut client that uses evdi to present a virtual monitor onto which a user can drag whatever content they'd like. The contents of this virtual monitor are sent to a running pixelflut instance.

`evdi` seems like a perfect DRM driver quickstart for this sort of thing, but when I request a framebuffer update, the dirty rectangles array always comes back with a single element indicating that the whole screen is dirty. Updating the whole display is simply too slow for the pixelflut protocol, which is inefficient by design.

I've tried a couple different EDIDs, and both values of the module option `enable_cursor_blending`. I've disabled my compositor and redshift. I have _not_ tried different window managers.

I've even instrumented the `monitorsim` program from [evdicpp](https://github.com/mlukaszek/evdipp) to see if its behavior is the same, and it is. Both my program and `monitorsim` only ever receive entire dirty screens, never small sub-rectangles.

Could you point me in the right direction? Does the driver have support for dirty rectangles smaller than the entire screen? If so, is there anything else that might be interfering on my machine?

Thanks!

**Comment by displaylink-dkurek** [comment]
Hi @qguv,
the base idea is that evdi keeps track of dirty rectangles and sends them to the
userspace. Note that there is assumption for max 16 rects in buffer - we try to
merge two into one if the overal size is smaller or we will simply callapse all
into one if the number still exeeds the buffers limit (it is done in
[evdi_painter_mark_dirty](https://github.com/DisplayLink/evdi/blob/72386e564b04602f78f569a0ec68a9c03d50b19a/module/evdi_painter.c#L482)).

That is the idea but it heavily depens on how we get the pixels.
  * FB - it handles three callbacks:
    * [evdi_fb_fillrect](https://github.com/DisplayLink/evdi/blob/72386e564b04602f78f569a0ec68a9c03d50b19a/module/evdi_fb.c#L149)
    * [evdi_fb_copyarea](https://github.com/DisplayLink/evdi/blob/72386e564b04602f78f569a0ec68a9c03d50b19a/module/evdi_fb.c#L160)
    * [evdi_fb_imageblit](https://github.com/DisplayLink/evdi/blob/72386e564b04602f78f569a0ec68a9c03d50b19a/module/evdi_fb.c#L171)
    The dirty rect is whatever we get from the userspace there. This is old one 
    and probably not in heavy use anymore.
  * dirty_fb - one callback:
    * [evdi_user_framebuffer_dirty](https://github.com/DisplayLink/evdi/blob/72386e564b04602f78f569a0ec68a9c03d50b19a/module/evdi_fb.c#L236)
    Same as FB this one will use dirty rects which comes from userspace.
    Note: from kernel 5.0 there is upstream version of it atomic helper for this one:
    [drm_atomic_helper_dirtyfb](https://github.com/torvalds/linux/blob/851ca779d110f694b5d078bc4af06d3ad37169e8/drivers/gpu/drm/drm_damage_helper.c#L160)
  * atomic - new one, most important callback here would be probably:
    * [evdi_plane_atomic_update](https://github.com/DisplayLink/evdi/blob/72386e564b04602f78f569a0ec68a9c03d50b19a/module/evdi_modeset.c#L193)
    Here, if we get new framebuffer from kernel we mark fullscreen dirty.
    It will also be called if you get `dirty_fb` callback.
    The official `drm_atomic_helper_dirtyfb` supports damage rects which we
    could use. If you are falling into this one it might be possible to improve (still
    depends on the use userspace).

Can you check what is the source of dirts in evdi? `dirty_fb`, `atomic` or (not
likely) `FB`. Can you also say form is your environment (OS, display manager,
etc) and kernel version?

**Comment by qguv** [comment]
Thanks for the info @displaylink-dkurek, I'll instrument some of the evdi callbacks and get back to you.

I'm running Arch on kernel 5.0.13 (with [this Kconfig](https://git.archlinux.org/svntogit/packages.git/tree/trunk/config?h=packages/linux&id=db9609721c9fc71343c17c9e460cc1f613ed1795)) with evdi version 1.6.0 (commit 09e6dd50c5615d2ac08432c372134d042ae4f7a5). My window manager is dwm 6.1 (with [a couple patches](https://github.com/qguv/dwm)).

**Comment by displaylink-dkurek** [comment]
Hi @qguv 
Have you any luck with this?

I'm not familiar with the pixelflut protocol but is setting pixel by pixel the only way of 
sending image?

**Comment by qguv** [comment]
I'm currently on holiday but I will get back to you soon about the results of instrumenting those calls.

Yes, pixelflut is a pixel-by-pixel protocol used to control a display at hacker events. It's simple and inefficient to simplify client implementation and encourage people to learn more about how their TCP/IP stack works and how it can be configured. The inefficiency also means smaller images perform better.

**Comment by qguv** [comment]
I'm currently on holiday but I will get back to you soon about the results of instrumenting those calls.

Yes, pixelflut is a pixel-by-pixel protocol used to control a display at hacker events. It's simple and inefficient to simplify client implementation and encourage people to learn more about how their TCP/IP stack works and how it can be configured.
