### ISSUE TITLE
porting to other distributions - OpenSuse Leap 15.1

### ISSUE THREAD

**Issue by xmentos** [DisplayLink/evdi#168]
Hello, I'm using OpenSuse Leap 15.1 and their kernel 4.12.14 has seen several DRM patches from upstream kernels. To make your driver work, I had to modify the include macros for the evdi module. In addition I had to modify the installer script but this is outside the scope of this repo.

For information, the files are here: https://github.com/xmentos/displaylink-evdi-opensuse-leap/
Do you the best way to share this with the community?

**Comment by noraj** [comment]
It would be nice if DisplayLink would provide a generic tarball in addition to the Ubuntu package. Maybe also a rpm for rpm-based distro. But I think this will never happen, they already struggle to only maintain it for ubuntu LTS.

**Comment by angeles-ricardo-89** [comment]
Yes, it wouldbe nice, but the Leap's kernel it's quite different from the original kernel... I think xmentos could fork evdi and include the patches there and make a pull request.
I also made some modifications in evdi and DisplayLink's installer for OpenSuse tumbleweed, and it actually worked using gnome 3.32 on wayland, but it got broken with gnome 3.34 and kernel 5.4, and I can't find a solution yet.

**Comment by bnavigator** [comment]
Good way to share with OpenSUSE users is to provide RPMs through OBS. dstoecker has patches for Leap 15 and 15.1 in his [home repository](https://build.opensuse.org/package/show/home:dstoecker/displaylink) similar to what you did.

I modified on that base and included the patch from #172 in mine home repo:

Unfortunately the proprietary license of displaylink does not allow to include the rpm into official distribution repos. Maybe a separate evdi package would do that.
