### ISSUE TITLE
Ubuntu 19.04 install and detect driver but not the correct resolution

### ISSUE THREAD

**Issue by joaogerardo** [DisplayLink/evdi#169]
I've recently brought and install DisplayLink resource by the latest Software (5.2 08 Jul 2019) and my device is recognized. But the best possible resolution presented is 1024 x 768. I've a ultrawide monitor. How can I make the best resolution possible to this device on Ubuntu?

  * Linux distribution and its version
Ubuntu 19.04

  * Linux kernel version
5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

  * Xorg version (if used)
ii  xserver-xorg-core 2:1.20.4-1ubuntu3 amd64 Xorg X server - core server

  * Desktop environment in use
Desktop: ubuntu:GNOME
Session: ubuntu

DISPLAYLINK SHOWS ONLY LOW RESOLUTION:
```
DVI-I-1-1 connected 1024x768+0+0 (normal left inverted right x axis y axis) 673mm x 284mm
   1024x768      60.00* 
   800x600       60.32    56.25  
   848x480       60.00  
   640x480       59.94  
  1024x768 (0x42) 65.000MHz -HSync -VSync
        h: width  1024 start 1048 end 1184 total 1344 skew    0 clock  48.36KHz
        v: height  768 start  771 end  777 total  806           clock  60.00Hz
  800x600 (0x43) 40.000MHz +HSync +VSync
        h: width   800 start  840 end  968 total 1056 skew    0 clock  37.88KHz
        v: height  600 start  601 end  605 total  628           clock  60.32Hz
  800x600 (0x44) 36.000MHz +HSync +VSync
        h: width   800 start  824 end  896 total 1024 skew    0 clock  35.16KHz
        v: height  600 start  601 end  603 total  625           clock  56.25Hz
  640x480 (0x46) 25.175MHz -HSync -VSync
        h: width   640 start  656 end  752 total  800 skew    0 clock  31.47KHz
        v: height  480 start  490 end  492 total  525           clock  59.94Hz


```

SAME MONITOR RESOLUTION BUT BY HDMI:

```
HDMI-1 connected primary 2560x1080+0+0 (normal left inverted right x axis y axis) 673mm x 284mm
   2560x1080     60.00*+
   1920x1080     60.00    60.00    50.00    59.94  
   1920x1080i    60.00    60.00    50.00    59.94  
   1680x1050     59.88  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1280x720      60.00    60.00    50.00    59.94  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       60.00    60.00    59.94    59.94  
   640x480       75.00    60.00    59.94    59.94  
   720x400       70.08  

```

**Comment by apreczewski** [comment]
Up!
How can I make the best resolution possible to this device on Ubuntu?

**Comment by displaylink-dkurek** [comment]
There are different types of adapters/docking stations which can handle different max resolutions. It might be simply that your device is not supporting 2.5k - it should be somewhere described on the device/manual/etc. 
Will close this issue now. If you still have problem/question please provide the exact producer, product number so we can identify the device. Thanks.
