### ISSUE TITLE
Friendly wish to Update Driver for Kernel 4.6.0-rc2

### ISSUE THREAD

**Issue by DonRichie** [DisplayLink/evdi#17]
I am trying to get the Driver work on the newest Linux Kernel (4.6.0-rc2) and get the following errors on executing make.
I know the official support is limited but can some smart developer have a look into this? I have a feeling these are some minor Problems which can be solved easy. 

> 
> `make -C module 
> make[1]: Verzeichnis „/home/user/evdi/module“ wird betreten
> make -C /lib/modules/4.6.0-rc2/build M=$PWD
> make[2]: Verzeichnis „/root/linux-4.6-rc2“ wird betreten
>   LD      /home/user/evdi/module/built-in.o
>   CC [M]  /home/user/evdi/module/evdi_drv.o
>   CC [M]  /home/user/evdi/module/evdi_modeset.o
> /home/user/evdi/module/evdi_modeset.c:286:18: Fehler: Initialisierung von inkompatiblem Zeigertyp [-Werror=incompatible-pointer-types]
>   .set_property = drm_atomic_crtc_set_property,
>                   ^
> /home/user/evdi/module/evdi_modeset.c:286:18: Anmerkung: (nahe der Initialisierung für »evdi_crtc_funcs.set_property«)
> /home/user/evdi/module/evdi_modeset.c:346:15: Fehler: Initialisierung von inkompatiblem Zeigertyp [-Werror=incompatible-pointer-types]
>   .fb_create = evdi_fb_user_fb_create,
>                ^
> /home/user/evdi/module/evdi_modeset.c:346:15: Anmerkung: (nahe der Initialisierung für »evdi_mode_funcs.fb_create«)
> cc1: Einige Warnungen werden als Fehler behandelt
> scripts/Makefile.build:291: die Regel für Ziel „/home/user/evdi/module/evdi_modeset.o“ scheiterte
> make[3]: *** [/home/user/evdi/module/evdi_modeset.o] Fehler 1
> Makefile:1427: die Regel für Ziel „_module_/home/user/evdi/module“ scheiterte
> make[2]: *** [_module_/home/user/evdi/module] Fehler 2
> make[2]: Verzeichnis „/root/linux-4.6-rc2“ wird verlassen
> Makefile:56: die Regel für Ziel „module“ scheiterte
> make[1]: *** [module] Fehler 2
> make[1]: Verzeichnis „/home/user/evdi/module“ wird verlassen
> Makefile:6: die Regel für Ziel „all“ scheiterte
> make: *** [all] Fehler 2`

**Comment by daugustin** [comment]
A 4.5 Patch is linked in #13. Also it seems it just fails because of -Werror:
```
-Werror=
Make the specified warning into an error. 
```
```
Initialisierung von inkompatiblem Zeigertyp [-Werror=incompatible-pointer-types]
```
This is not in the Makefile and seems to come from your local environment.

**Comment by cajus** [comment]
I managed to compile it with 4.6.0rc2, but I can't tell you if it works: my small Dell DA200 is recognized, but the second screen stays black while the primary is optically freezed. Recovers when I disconnect the adapter. Thats on Fedora 23.

I tried Ubuntu with the original one, but there all screens go black after I've plugged it in. The Dell D3100 isn't even recognized.

**Comment by displaylink-mlukaszek** [comment]
The compilation is now fine on 4.6. As I stated on the forum, to be also useful for a DisplayLink driver we need to release new version of the whole package. Stay tuned.

**Comment by wbolster** [comment]
@cajus as far as i can see, the da200 (dell adapter) is _not_ a displaylink device.

you may be suffering from https://bugs.freedesktop.org/show_bug.cgi?id=94567

**Comment by cajus** [comment]
@wbolster thanks. Yes, maybe. I did not have time to check anything further yet. Just using the laptop without any external screens and being in the "hopefully it works some day" mode ;-)

**Comment by wbolster** [comment]
@cajus about the da200:  it does _not_ seem to use displaylink, but it's not working because of https://bugs.freedesktop.org/show_bug.cgi?id=94567

in the mean time, a usb-c to hdmi converter  (without network, without vga, without usb port, just display) _does_ work, e.g. those made by Trust and Startech.

this issue discussions is getting off-topic, since it does not have anything to do with displaylink.
