### ISSUE TITLE
crash on 5.4.1 kernel

### ISSUE THREAD

**Issue by pbartyik** [DisplayLink/evdi#173]
Laptop info:
5.4.1-arch1-1
running wayland
DE: sway version 1.2

I upgraded evdi via [AUR](https://aur.archlinux.org/packages/evdi) yesterday, from `pacman.log`:
`[2019-12-05T20:36:02+0100] [ALPM] upgraded evdi (1.6.4-1 -> 1.6.4-2)`

During install CPU hit 100% and the laptop didn't react to any inputs apart from the power key, so after power cycling I reinstalled the package to be sure.
`[2019-12-05T20:43:28+0100] [ALPM] reinstalled evdi (1.6.4-2)`

Since then when playing video (netflix via qutebrowser) the screen that the video is on randomly freezes, audio processing continues. If I move the mouse to the affected screen, input dies (both keyboard and mouse), other screens are unaffected.
This is also the case when no external screens are connected and only the laptop screen is active.
So far it didn't freeze when I didn't run netflix.

Troubleshooting or fixing advise is welcome.

Thanks!

**Comment by displaylink-dkurek** [comment]
Hi @pbartyik 
5.4 kernel is not yet supported by evdi (see #172).
I see that AUR uses patch to adapt evdi to compile on 5.4.
This is actually good input that there probably has to be done
some additional work.

Can you provide crash log?
(hot sure how where it is on arch, but this
https://unix.stackexchange.com/questions/120988/how-to-get-last-crash-log-from-archlinux
seems promising :) ) - it would be a good start to check whats happening.

**Comment by pbartyik** [comment]
Hi @displaylink-dkurek,

I'm not very comfortable uploading full system log here :) If you can provide a secure way of sharing I'd be glad to send it to you.

**Comment by pbartyik** [comment]
Here are some more info, got a crash again. This time all screens froze, however it recovered.

> Dec 06 13:46:06 prometheus kernel: i915 0000:00:02.0: GPU HANG: ecode 9:1:0x00000000, hang on rcs0
Dec 06 13:46:06 prometheus kernel: GPU hangs can indicate a bug anywhere in the entire gfx stack, inclu
ding userspace.
Dec 06 13:46:06 prometheus kernel: Please file a _new_ bug report on bugs.freedesktop.org against DRI -> DRM/Intel
Dec 06 13:46:06 prometheus kernel: drm/i915 developers can then reassign to the right component if it's
 not a kernel issue.
Dec 06 13:46:06 prometheus kernel: The GPU crash dump is required to analyze GPU hangs, so please alway
s attach it.
Dec 06 13:46:06 prometheus kernel: GPU crash dump saved to /sys/class/drm/card0/error
Dec 06 13:46:06 prometheus kernel: i915 0000:00:02.0: Resetting rcs0 for hang on rcs0

[gpudump.txt](https://github.com/DisplayLink/evdi/files/3932224/gpudump.txt)

Checking for this in journalctl for entries since yesterday:
> Dec 05 20:28:06 prometheus kernel: The GPU crash dump is required to analyze GPU hangs, so please always attach it.
Dec 05 20:28:06 prometheus kernel: GPU crash dump saved to /sys/class/drm/card0/error
Dec 06 10:20:31 prometheus kernel: The GPU crash dump is required to analyze GPU hangs, so please always attach it.
Dec 06 10:20:31 prometheus kernel: GPU crash dump saved to /sys/class/drm/card0/error
Dec 06 13:46:06 prometheus kernel: The GPU crash dump is required to analyze GPU hangs, so please always attach it.
Dec 06 13:46:06 prometheus kernel: GPU crash dump saved to /sys/class/drm/card0/error

**Comment by abucodonosor** [comment]
@displaylink-dkurek 

it seems people getting that with or without evdi, I guess is some kernel bug.

https://gitlab.freedesktop.org/drm/intel/issues/736
https://bugzilla.redhat.com/show_bug.cgi?id=1780800

**Comment by displaylink-dkurek** [comment]
Yes. Seems not really related to evdi.
card0 will be always the real GPU, (also card1 if two GPUs in the system, etc).

**Comment by abucodonosor** [comment]
Well, after looking around that bug is present back to 4.14/4.15 kernels and it depends on HW/mesa/X & kernel combos & firmware. Also, 5.3.X kernel has the bug on some HW and it seems Intel guys are playing the chicken & egg game. Solving for a group of people in some particular kernel breaks the same thing for others. One thing I saw as a workaround for some is to boot with i915.enable_rc6=0, however, it seems to not work for everyone.

**Comment by pbartyik** [comment]
in theory this should be fixed in 5.5, main bug: https://gitlab.freedesktop.org/drm/intel/issues/673

closing this as I don't think evdi has anything to do with the crash
