### ISSUE TITLE
evdi_dri.so not present in /usr/lib/x86_64-linux-gnu/dri

### ISSUE THREAD

**Issue by busti** [DisplayLink/evdi#174]
I am trying to get my DisplayLink device working on Debian Buster with a `5.3.10` kernel.  
I have the Ubuntu version of the DL driver from the website. The device is discovered by my machine and shows up in `dmesg`, but when I try to start my desktop environment (sway/wayland) it tells me that it is unable to load evdi when searching `/usr/lib/x86_64-linux-gnu/dri` and indeed there is no such driver present there.  

After searching around a bit, I have discovered that the driver is supposed to be called `evdi_dri.so`.  

I have tried compiling evdi from the latest release and manually adding it using `dkms add` etc.  
It compiles just fine, but the driver file does not show up.

Am I missing something? How (by what process) is the `.so` file placed into `/usr/lib/x86_64-linux-gnu/dri`?

**Comment by busti** [comment]
I am guessing that this is caused by the missing 5.3 kernel support.

**Comment by busti** [comment]
I am keeping this open for now, since I want to learn more about this, but I am well aware that I am probably using too many unsupported technologies at once (kernev v5.3, wayland).

**Comment by pati-ni** [comment]
I can confirm that this error is still present with specific displaylink docking stations. Right now, wayland is not finding `evdi_dri.so` with HP usb-c docking station. This is not the case with lenovo thinkpad docking station.

**Comment by morten-b** [comment]
I have the same issue with with an Asus external display on sway. Is there any way to work around this? And is a error of wayland or evdi?

**Comment by pati-ni** [comment]
If your docking station is displaylink usb3, don't bother. wlroots/sway is not supporting displaylink hardware at the moment

https://github.com/swaywm/wlroots/issues/1823
