### ISSUE TITLE
Ubuntu 19.10 Xorg segfault on browser reload whilst moving cursor (maybe)

### ISSUE THREAD

**Issue by rick-pri** [DisplayLink/evdi#175]
Initially please make sure the problem hasn't been already addressed:
  * [ Y ] Are you using the latest driver?
    - Also, I built v1.6.4.  The segfault still occurs but doesn't hard crash requiring REISUB but rather drops back to gdm3 login screen
  * [ Y ] Are you using the latest EVDI version?
  * [ Y ] If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
  * [ Y/N ] Is this issue related to evdi/kernel?
   - I suspect that it's related to EVDI because I updated and the behaviour changed slightly

Some information for baseline would help a lot:
  * Linux distribution and its version
    - Ubuntu 19.10
  * Linux kernel version
    - `5.3.0-23-generic #25-Ubuntu SMP`
  * Xorg version (if used)
    - 2:1.20.5+git20191008-0ubuntu1
  * Desktop environment in use
    - Ubuntu default Gnome

Here is a capture of the xorg logfile up to the segfault:
https://pastebin.com/xrDBzMXx

What I've noticed is that this crash seems to occur around the same time as I reload a webpage and possibly that I move a cursor, maybe on the same screen maybe on another screen.  It's very erratic in nature.  The version of EVDI with the DisplayLink drivers for Ubuntu (v1.5.2) leads to a total hard crash of Xorg and console access is not available via Ctrl+Alt+F keys.  The machine might be accessible via SSH but I've never tried.
Updating to the v1.6.4 release is better as it segfaults and crashes to gdm login screen, but at least it doesn't require a restart of the OS either via REISUB or a press of the power button to start the shutdown sequence.

Hopefully the logs will help.

**Comment by rick-pri** [comment]
I've just had the segfault into a hard lock.  I'd just had to install the postgresql-11 package to do a db restore to test the effects of a query and this time when it crashed, for the second time today it required me to REISUB to restart.  This was not the behaviour before this package was installed.  The main fix though would be to fix the issue which causes the segfault  in the first place.

I'm getting closer to WSL2 with each passing day :(

**Comment by displaylink-dkurek** [comment]
There hasn't been any updates or discussion. Will close this one.
