### ISSUE TITLE
Kubuntu 18.04 high CPU usage

### ISSUE THREAD

**Issue by hookumsnivy** [DisplayLink/evdi#177]
Specs:
Kubuntu 18.04
Kernel: 5.0.0-37-generic
DisplayLink driver version: 5.2.14
EVDI version: 1.6.1 (installed as part of the above driver)

Issue:
When idle, top shows DisplayLinkManager using anywhere fromi 10~25% CPU. If I start doing anything (moving the mouse, typing, opening a new browser tab) it jumps as high at 70%. If I'm in a video conference call or watching a video, it often spikes to over 100% (obviously multiple cpus). I've also had issues w/ the monitors turning off, but I can't say for sure if that's related to the cpu usage.
Any ideas?

**Comment by funkrusher** [comment]
i also have the same problem. It would be great to have a workaround until this is fixed. I have exactly the same problem with Ubuntu 19.10 and DisplayLink 5.2.14.

Examples:
- Is there a safe DisplayLink driver version with Ubuntu XX.XX, that has run with reasonable low CPU usage?

**Comment by gaviidae** [comment]
I also have this issue.
Xubuntu 18.04
Kernel Version: 5.3.0-26-generic
DisplayLink Version: 5.2.14

Processor load of DisplayLinkManager process (with one 2560x1440 60Hz monitor connected) reaches 14% to 40%, when moving mouse it reaches around 200% in sum. Load is similarly disastrous when watching videos. I used htop to look at load. I have 2 cores and 4 threads so this impacts cpu performance immensely!
Attachment shows load with only mouse movement.
![load](https://user-images.githubusercontent.com/37497159/72660116-655c9f00-39c9-11ea-87c5-58e0c0e546ad.png)

Is this supposed to be normal behavior or can we expect a fix?

**Comment by funkrusher** [comment]
fix is, buy thunderbolt... 
https://www.youtube.com/watch?v=9aOyX49ubK0

**Comment by ndom91** [comment]
Arch with 5.4 kernel also experiencing this behavior here. Moving the mouse brings CPU > 75% most of the time..

**Comment by rghv** [comment]
> Arch with 5.4 kernel also experiencing this behavior here. Moving the mouse brings CPU > 75% most of the time..

Same for Linux Mint 19.3 - with latest 4.X and 5.X kernels. Mouse moves shoots up CPU to almost 90%

**Comment by hookumsnivy** [comment]
I gave up. Instead of using the dock that made things simple, I just used multiple simple connections. Instead of the dock, I have 1 monitor connected via HDMI, 1 monitor connected via USB-C -> adapter -> monitor, a number of peripherals connected by usb and a usb hub. Fortunately I always leave it "docked" so it's not a big deal. All of my display and cpu problems went away after I switched to this approach.
I'll continue to follow this in case I can revert to the simpler setup.

**Comment by funkrusher** [comment]
@hookumsnivy this is actually a good solution for this problem.

**Comment by ndom91** [comment]
Does anyone know which kernel is the latest without these performance problems?

**Comment by arpho** [comment]
I use the dock with two different computers, both with ubuntu 20.04 and the same displaylink driver, one of them  works with no problems, the other shows hi CPU usage, the first is an i7 thew latter an a10
