### ISSUE TITLE
Wrong return value in evdi_get_modes() function

### ISSUE THREAD

**Issue by teddywlq** [DisplayLink/evdi#178]
I'm using DisplayLink devices on my Laptop with Ubuntu18.04. My external monitor can't support 848x480  resoultion. It will show "out of range" on the screen.  I checked my monitor EDID information and didn't find 848 x480 mode. Then I reviewed  EVDI module codes and found there is a wrong return value in the evdi_get_modes() function.

In DRM driver, connector helper ->get_modes() vfunc should be returned with drm_add_edid_modes() return value.

This return value should be the number of modes added.  if we couldn't find any modes, we should return 0;

In EVDI driver, we return the "ret" directly. But this value will be always zero.  It's wrong.  
You can refer to drm_helper_probe_single_connector_modes function in the kernel.

Please help to correct it. Thanks.

**Comment by displaylink-dkurek** [comment]
@teddywlq 
Thanks for spotting this! I will take a look at this :+1:

**Comment by displaylink-dkurek** [comment]
OK, fixed in 46938d954de43ff420f647dbfd8e499fab649d73.
Closing
