### ISSUE TITLE
Strange power/refresh/paint issues with Ubuntu 15.10

### ISSUE THREAD

**Issue by unfulvio** [DisplayLink/evdi#18]
Hey there, I managed to make a __Lenovo ThinkVision LT1421__ to work with the Displaylink driver on __Ubuntu 15.10__ on a __Lenovo Thinkpad T450s__, however I'm still running in issues that make the usage of the display very unreliable. I thought of sharing these findings with you in the hopes you can improve the driver. 

I've originally posted some here
http://askubuntu.com/questions/753164/ubuntu-doesnt-look-like-sending-power-to-an-usb-port-used-by-a-device-that-uses

but I will summarize below:

1. The Displaylink driver will work only if the Intel Linux Graphics Driver is completely removed. Apparently this is due a modified libdrm package which evdi doesn't like. However, I wish this issue could be addressed, as the Intel drivers do in fact improve power management and resolve other issues I had with other programs and hardware acceleration (mainly Chrome).

2. Once intel drivers are uninstalled, the screen will work, but not properly, as detailed below.

3. if I start ubuntu, then connect the display with either 1 or 2 usb, it will work (i can see the refresh rate is better with 2) -- note this display comes with a usb Y cable (the kind that splits into 2-male USB plugs to draw more power if necessary, I tried in my tests to work with either one or 2 plugs connected, it doesn't make a difference)

4. if I disconnect the display, and reconnect it, it won't work. It may turn on and all, but it will refresh very slowly, to the point of being unusable.

5. if anything related to screen displays refreshes/restarts, such as the displaylink service or for example if I update my software for display calibration (DisplayCal), the screen will flash and will enter in this state where it doesn't paint properly

6. if I start my laptop with my display connected already (either to 1 or 2 usb) it won't work, it will only function in this bad state - sometimes it will even keep the same appearance as I left it since last reboot (same partially painted areas)

7. disconnecting and reconnecting again after the screen has entered in this state, no matter what, it will always bring it back in the same unusable mode. I have to restart ubuntu with the screen disconnected, then connect the screen and hope it won't hang

8. very interestingly, whenever the screen is in this failed state, it will show 2 extra displays in my "Screen" settings - one correctly labelled like `Lenovo Thinkvision 14"` and the other labeled as `FNM 0"`

![fnm0](https://cloud.githubusercontent.com/assets/1227930/14436617/2aab7288-ffe3-11e5-8839-3d33a34e244c.png)

**Comment by displaylink-mlukaszek** [comment]
Is this still reproducible with the Ubuntu 1.1.62 release that's just out? Thanks.

**Comment by unfulvio** [comment]
thanks! will try out soon and let you know

**Comment by unfulvio** [comment]
works like a charm on Ubuntu 16.04 Gnome, with 2 more external displays on a Thinkpad T450s, one on dp/hdmi another on vga

I am not running Intel proprietary drivers (technically not ready for 16.04 although there's a hack to install does from Vivid)... so I'm not sure how this would behave then

probably need to test more if there are power issues or strange things happening like with previous drivers on 15.04

thanks a lot! great job

**Comment by unfulvio** [comment]
ps if you need more details just let me know
