### ISSUE TITLE
X Server crash on initial connection to dock

### ISSUE THREAD

**Issue by siduenho** [DisplayLink/evdi#180]
Hi,

I've probably encountered the same problem as mentioned in #153 .

When I boot my machine, login to my desktop and then connect it to the dock, the laptop screen will look strange for a short amount of time. After that I find myself back at the login screen. All running applications will be killed when the crash happens.

When I login to my account for the second time (dock still connected) everything works as expected as soon as I click on Login. After the crash happened, I can disconnect and reconnect the dock as often as I want. The crash will only happen the first time I connect the dock after a fresh boot.

**My machine**:

Schenker N130BU
* Intel Core i5-7200U
* Intel HD Graphics 620
* 16 GiB RAM

**My Dock**: 
Targus DOCK117

**My Configuration**
* DisplayLink Driver: 5.2.14
* Linux Mint 19.3 (based on Ubuntu 18.04 bionic)
* Kernel 4.15.0-74-generic
* X.Org X Server 1.19.6
* Desktop: Cinnamon 4.4.8 
* wm: muffin 
* dm: LightDM

### Crash log

**Before** applying the fix from https://support.displaylink.com/knowledgebase/articles/1859356-x-server-crashes-on-nvidia-systems-when-displaylin

https://pastebin.com/2Wq1jSXJ

**After** applying the given fix from https://support.displaylink.com/knowledgebase/articles/1859356-x-server-crashes-on-nvidia-systems-when-displaylin

https://pastebin.com/3SuGmRhv

**Comment by willmtemple** [comment]
I believe I have this issue too. I originally thought it was an issue with `autorandr`, but seeing someone else with the same issue on a different setup makes me second-guess that.

The system is a Lenovo ThinkPad T490s using Lenovo's USB-C displaylink dock. I'm using Arch Linux and I have my system configured to automatically log me in and start X after decrypting the disk. If my laptop is docked when this happens, X will crash once before restarting itself, after which point it works fine. It ___also___ crashes if I plug the dock in for the first time (i.e. I can unplug/replug fine, but the first time the dock is used always results in a crash.

**Comment by displaylink-dkurek** [comment]
Hi,
can you also check if this 
https://support.displaylink.com/knowledgebase/articles/1883074-ubuntu-16-04-x-server-starts-in-low-graphics-mode
would help?

**Comment by siduenho** [comment]
`echo "options evdi initial_device_count=2" | sudo tee -a /etc/modprobe.d/dkms.conf`

**This fixed the issue at hand** @displaylink-dkurek . Thanks for the hint :tada: 

I would highly appreciate a seperate knowledgebase article for this phenomena :slightly_smiling_face:

**Comment by displaylink-dkurek** [comment]
Yes, you are right. There are a lot of FAQs and those workarounds sometimes helps in other cases than stated.
Thanks for feedback that this worked for you. :)
