### ISSUE TITLE
Input lag on external displays (Kernel 5.3.x & 5.4.x)

### ISSUE THREAD

**Issue by xtrasimplicity** [DisplayLink/evdi#186]
* [x] Are you using the latest driver?
    (https://www.displaylink.com/downloads/ubuntu)
  * [x] Are you using the latest EVDI version?
    (https://github.com/DisplayLink/evdi/releases)
  * [x] If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
    (https://support.displaylink.com/knowledgebase/topics/103927-troubleshooting-ubuntu)
  * [x] Is this issue related to evdi/kernel?
    (if it is rather connected to DisplayLinkManager please take a look at support
    https://support.displaylink.com or forum https://www.displaylink.org/forum/)

**Distribution:** Fedora 31
**Kernel:** 5.3.7-301.fc31.x86_64
**Desktop environment:** GNOME with Wayland compositor.

# Background
I purchased a new Dell XPS 13" 7390 2-in-1 notebook and connected it to a Dell D6000 dock. I have two external 24" Dell displays, connected to the Dock via DisplayPort.
I am intending to use both the 2x 24" external displays **and** my laptop display, at the same time.

Both 24" displays are set to 2560x1440 (with a scale of 100%), the laptop display is set to 1920x1200 (with a scale of 100%).

# Problem
All displays look ok visually (there's no artifacts, etc), but keyboard input is noticeably laggy when using the two external displays. The inbuilt display (which doesn't use evdi) is perfect.

When opening Visual Studio Code, Chrome or any other app that accepts keyboard input, the external displays struggle to "keep up" with my typing speed, resulting in a 1-2 second delay between me inputting the characters and it appearing on the display. The inbuilt, non-evdi display is perfectly fine.

Mouse input doesn't appear to have any noticeable lag. The issue persists regardless of whether there are one or two external displays. I temporarily borrowed a WD19 display from someone (which doesn't use DisplayLink), which works, but I'd rather not have to purchase another dock. :)

# Investigation (so far)
Nothing interesting appears in dmesg, other than continuous log entries for my touchpad device:
```
1561.097505] hid-sensor-hub 001F:8087:0AC2.0002: hid_field_extract() called with n (192) > 32! (kworker/5:1)
```

Resource utilisation is pretty normal:
```
top - 08:58:03 up 27 min,  1 user,  load average: 1.53, 1.74, 1.41
Tasks: 305 total,   2 running, 303 sleeping,   0 stopped,   0 zombie
%Cpu(s): 13.1 us,  0.3 sy,  0.0 ni, 85.6 id,  0.1 wa,  0.7 hi,  0.3 si,  0.0 st
MiB Mem :  31888.3 total,  24148.7 free,   3193.4 used,   4546.3 buff/cache
MiB Swap:  16044.0 total,  16044.0 free,      0.0 used.  26659.1 avail Mem 
```

I've tried the following other kernels, to no avail:
- 5.4.15-200.fc31.x86_64
- 5.4.17-200.fc31.x86_64

Any assistance would be very greatly appreciated. :)

**Comment by xtrasimplicity** [comment]
Here's a gist of the evdi and drm debug logs, from dmesg:
https://gist.github.com/xtrasimplicity/fed28293f014d185e0b9a503f8f3785b

**Comment by Daywalker999** [comment]
I am having the same issue with my Thinkpad T495 and the i-tec Thunderbolt 3 Dual 4K Docking Station. The monitor connected via HDMI works without any issues but the one connected via display port is showing the issues mentioned above. In addition i have extreme mouse lagg when moving the cursor over the display. Dragging window frames results in tearing. Overall the monitor feels like i have extreme resource issues and the laptop is about to freeze, but resource utilization seems to be normal. If i move to the HDMI monitor everything is fine.

**Distribution**: Linux Mint 19.3 Tricia
**Kernel**: 5.0.0-37-generic
**Desktop environment**: Cinnamon 4.4.8

I would be happy to provide any helpful logs / other information if needed.

**Comment by xtrasimplicity** [comment]
Thanks, @Daywalker999. Good to know it's not just a Wayland issue! :)

HDMI works for me, too (using a usb c to hdmi adapter and bypassing Evdi completely). When you connected via HDMI, was it via your dock or direct? If the former, I wonder whether perhaps it's something to do with the higher refresh rates or resolutions supported by DP?

**Comment by xtrasimplicity** [comment]
HDMI-out via my dock (with evdi) has the same issue as DP. Using a USB-C to HDMI adapter and bypassing the dock completely works perfectly, so it's definitely an issue with the DisplayLink adapter.

**Comment by xtrasimplicity** [comment]
@Daywalker999 , does disabling PageFlipping help at all?
https://bbs.archlinux.org/viewtopic.php?id=250035

I've been trying to test this on my machine, but can't work out how to do so in Wayland. :/

**Comment by Daywalker999** [comment]
HDMI was via dock as well. But HDMI was already working before i installed the displaylink drivers.
I've tried my setup with windows and everything seems to work. So its definitely not an hardware issue.

**Comment by Daywalker999** [comment]
`Section "Device"
#   Identifier "AMDGPU"
#   Driver "amdgpu"
    Identifier  "DisplayLink"
    Driver      "modesetting"
    Option      "PageFlip" "false" 
EndSection`
I tried this in several combinations. No success.
A kernel update to 5.3.0-40 didn't do anything.

**Comment by rkeene** [comment]
I had a similar issue (which appears to be the same as #51), and fixed it by disabling VSync by modifying `~/.drirc` to contain

```xml
<device screen="0" driver="dri2">
	<application name="Default">
		<option name="vblank_mode" value="0"/>
	</application>
</device>
```

And then restarting applications that used OpenGL.  For example, before this change "glxgears" would give me 1 FPS and Chromium (with GPU support enabled, as is the default) scrolling and typing was limited to 1 FPS updates.  After this change was able to get 5000 FPS from "glxgears" and Chromium worked normally.

**Comment by afterlastangel** [comment]
Dell Latitude 7490 - Ubuntu 20.04
After a investigation, I choose Wayland in login screen, and the vsync problem with lagging has gone.
 https://www.vsynctester.com/

**Comment by groovyman** [comment]
I am trying to run  a new notebook with usb3.2 gen2 with 10Gb/s with a capable docking station usiing a DL-6000 chip.
The dockingstation comes with 3 display connectors but onyl 2 are working now.

The lack is a desaster. The displaylink process eats up more than 100% CPU time and seems to be part of the very slow overall output. Before i was able to run the same notebook with W10 on an old docking station with max 5Gb/s and i had absolutly no problem with 2 4K monitors and no CPU eating process.

Hardware:  
. Lenovo 16p  with AMD CPU
- Startech DK31C3HDPD
- and 3 4K Monitors

Just let you know:  2 4K Monitor went with the same Hardware quite fast on a older docking station with only an old USB3 Docking station.

**Comment by displaylink-emajewsk** [comment]
Is anyone experiencing this input lag on machines other than AMD?

**Comment by tux-o-matic** [comment]
@displaylink-emajewsk , yes, also on Intel machines where disabling VSync helped.

**Comment by displaylink-emajewsk** [comment]
I'm closing this bug as our investigation showed that's it's too broad in scope. Please, report any new issues related to input lag separately. Preferably with a video so we know we're on the right track. Thank you
