### ISSUE TITLE
Fedora 30 work with this drive on itec USB3HDTRIO (displaylink 3xxx chipset)

### ISSUE THREAD

**Issue by chiddekel** [DisplayLink/evdi#188]
Driver to work (EVDI) - not signed - required to disable in UEFI: secure boot and set in path /etc/GDM*/custom.conf uncomment line: WaylandEnable=false

        I am using the driver for fedora from this repo:
        (https://github.com/displaylink-rpm/displaylink-rpm/releases/tag/v5.2.14-3-rc1)

  * Linux Fedora Workstation (tested on 30 and 31)
  * Linux kernel version - version 5.4.xxx
  * Xorg version - xorg-x11-server-Xorg-1.20.6-1.fc30.x86_64
  * Desktop environment in use - GNOME Wersja 3.32.2

**Comment by displaylink-dkurek** [comment]
Does it still happens? Now both library and module and builds on the end user machine during installation process and should be signed in the process.
