### ISSUE TITLE
Issues with Linux 5.6

### ISSUE THREAD

**Issue by damo2929** [DisplayLink/evdi#189]
using the current devel branch (24/2/20) the module doesn't build against 5.6

CFLAGS="-Werror -Wextra -Wall -Wmissing-prototypes -Wstrict-prototypes -Wno-error=missing-field-initializers" make -C module 
make[1]: Entering directory '/root/evdi/module'
make -C /lib/modules/5.6.0-0.rc2.git0.1.fc32.x86_64/build M=$PWD
make[2]: Entering directory '/usr/src/kernels/5.6.0-0.rc2.git0.1.fc32.x86_64'
  CC [M]  /root/evdi/module/evdi_drv.o
  CC [M]  /root/evdi/module/evdi_modeset.o
  CC [M]  /root/evdi/module/evdi_connector.o
  CC [M]  /root/evdi/module/evdi_encoder.o
  CC [M]  /root/evdi/module/evdi_main.o
  CC [M]  /root/evdi/module/evdi_fb.o
/root/evdi/module/evdi_fb.c: In function ‘evdi_fbdev_unplug’:
/root/evdi/module/evdi_fb.c:568:3: error: implicit declaration of function ‘unlink_framebuffer’; did you mean ‘unregister_framebuffer’? [-Werror=implicit-function-declaration]
  568 |   unlink_framebuffer(info);
      |   ^~~~~~~~~~~~~~~~~~
      |   unregister_framebuffer
cc1: all warnings being treated as errors

**Comment by displaylink-dkurek** [comment]
I hope to have the changes in evdi on time for 5.6 this time :) (I'm assuming we will have up to 5.6-rc7, 
so release should be 03/30). I just need a bit of time to take a look. PR's welcome ^^

**Comment by displaylink-dkurek** [comment]
Commit 34d92e8a78a7a3b8df848b61469c783f352e360c has a fix for compilation with 5.6.
Unfortunately I haven't checked if it's fine in runtime. If you will give it a shot please let me know
if it's fine or not :)
