### ISSUE TITLE
error: drm/drmP.h not found with Kernel 5.5.7-arch1-1

### ISSUE THREAD

**Issue by doniomm** [DisplayLink/evdi#191]
Hello I use arch and have after updated too the new kernel, this error message:

`Building module:
cleaning build area...
make -j8 KERNELRELEASE=5.5.7-arch1-1 all INCLUDEDIR=/lib/modules/5.5.7-arch1-1/build/include KVERSION=5.5.7-arch1-1 DKMS_BUILD=1...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.5.7-arch1-1 (x86_64)
Consult /var/lib/dkms/evdi/1.6.4/build/make.log for more information.
Fehler: Befehl konnte nicht korrekt ausgeführt werden
`

`/var/lib/dkms/evdi/1.6.4/build/evdi_drv.c:11:10: schwerwiegender Fehler: drm/drmP.h: Datei oder Verzeichnis nicht gefunden
   11 | #include <drm/drmP.h>
      |          ^~~~~~~~~~~~
`

`extra/libdrm 2.4.100-1 (245.5 KiB 943.0 KiB) (Installed)
`

**Comment by displaylink-dkurek** [comment]
Are you using latest devel branch from this repository?

**Comment by doniomm** [comment]
this is what I use:

`aur/evdi 1.6.4-2 (+25 1.40%) (Installed)
`

**Comment by displaylink-dkurek** [comment]
We are not maintaining AUR repo, please raise the problem there.

**Comment by doniomm** [comment]
ok sorry

**Comment by displaylink-dkurek** [comment]
No problem :) 
I get that it might be confusing.

**Comment by doniomm** [comment]
thx :-)
