### ISSUE TITLE
EVDI 5.2.14 and MASTER compile error on CentOS 8.1 / kernel 4.18.0-147.5.1.el8_1.x86_64

### ISSUE THREAD

**Issue by sbluhm** [DisplayLink/evdi#193]
EVDI used to work fine on CentOS 8.0. After upgrade to 8.1, EVDI compilation make fails with the following error:

`# make
CFLAGS="-Werror -Wextra -Wall -Wmissing-prototypes -Wstrict-prototypes -Wno-error=missing-field-initializers" make -C module 
make[1]: Verzeichnis „/home/stefan/git/evdi/module“ wird betreten
make -C /lib/modules/4.18.0-147.5.1.el8_1.x86_64/build M=$PWD
make[2]: Verzeichnis „/usr/src/kernels/4.18.0-147.5.1.el8_1.x86_64“ wird betreten
  CC [M]  /home/stefan/git/evdi/module/evdi_drv.o
  CC [M]  /home/stefan/git/evdi/module/evdi_modeset.o
  CC [M]  /home/stefan/git/evdi/module/evdi_connector.o
/home/stefan/git/evdi/module/evdi_connector.c: In Funktion »evdi_get_modes«:
/home/stefan/git/evdi/module/evdi_connector.c:42:3: Fehler: Implizite Deklaration der Funktion »drm_mode_connector_update_edid_property«; meinten Sie »drm_connector_update_edid_property«? [-Werror=implicit-function-declaration]
   drm_mode_connector_update_edid_property(connector, NULL);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   drm_connector_update_edid_property
/home/stefan/git/evdi/module/evdi_connector.c: Auf höchster Ebene:
/home/stefan/git/evdi/module/evdi_connector.c:138:16: Fehler: »drm_helper_probe_single_connector_modes« ist hier (außerhalb einer Funktion) nicht deklariert; meinten Sie »drm_helper_move_panel_connectors_to_head«?
  .fill_modes = drm_helper_probe_single_connector_modes,
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                drm_helper_move_panel_connectors_to_head
/home/stefan/git/evdi/module/evdi_connector.c: In Funktion »evdi_connector_init«:
/home/stefan/git/evdi/module/evdi_connector.c:168:2: Fehler: Implizite Deklaration der Funktion »drm_mode_connector_attach_encoder«; meinten Sie »drm_connector_attach_encoder«? [-Werror=implicit-function-declaration]
  drm_mode_connector_attach_encoder(connector, encoder);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  drm_connector_attach_encoder
cc1: Alle Warnungen werden als Fehler behandelt
make[3]: *** [scripts/Makefile.build:313: /home/stefan/git/evdi/module/evdi_connector.o] Fehler 1
make[2]: *** [Makefile:1547: _module_/home/stefan/git/evdi/module] Fehler 2
make[2]: Verzeichnis „/usr/src/kernels/4.18.0-147.5.1.el8_1.x86_64“ wird verlassen
make[1]: *** [Makefile:67: module] Fehler 2
make[1]: Verzeichnis „/home/stefan/git/evdi/module“ wird verlassen
make: *** [Makefile:8: all] Fehler 2`

This is from the latest git evdi master.

**Comment by displaylink-dkurek** [comment]
So according to 
https://centos.pkgs.org/8/centos-baseos-aarch64/kernel-4.18.0-147.5.1.el8_1.aarch64.rpm.html
> The Linux kernel, based on version 4.18.0, heavily modified with backports

`drm_connector_update_edid_property` is a function name from 4.19 (https://elixir.bootlin.com/linux/v4.19-rc1/source/include/drm/drm_connector.h#L1197).
Before it was `drm_mode_connector_update_edid_property` (https://elixir.bootlin.com/linux/v4.18.20/source/include/drm/drm_connector.h#L1102).

It seems they have ported API breaking changes from 4.19 to 4.18. It will be probably wont fix.

**Comment by sbluhm** [comment]
Wouldn't it just be a patch to change names? (or at least worth a try)

**Comment by displaylink-dkurek** [comment]
Now to differentiate when to use `drm_connector_` and `drm_mode_connector_` we use [this](https://github.com/DisplayLink/evdi/blob/b5c57910e4ef2b706249ddefd066f955e3899b8c/module/evdi_connector.c#L39)
```cpp
#if KERNEL_VERSION(4, 19, 0) <= LINUX_VERSION_CODE
```
(and pretty much for all those compatibility issues we use the same structure of `#if`).
**kernel 4.18.0-147.5.1.el8_1.x86_64** falls into *less then 4.19*.

The `LINUX_VERSION_CODE` is generated based on variables set in Makefile.
In sources from http://vault.centos.org/8.1.1911/BaseOS/Source/SPackages/kernel-4.18.0-147.5.1.el8_1.src.rpm it is
```
VERSION = 4
PATCHLEVEL = 18
SUBLEVEL = 0
EXTRAVERSION =
```

There is also 
```
#
# DRM backport version
#
RHEL_DRM_VERSION = 5
RHEL_DRM_PATCHLEVEL = 1
RHEL_DRM_SUBLEVEL = 21
```
which might be what we need but I don't see it anywhere exported to the code during compilation.

**Comment by sbluhm** [comment]
Thank you for the pointers. I will check it out at some point.

**Comment by sbluhm** [comment]
OK, I had a look at it. Whilst the above error messages can easily be replaced with the recommended functions, there are additional obstacles of now missing functions (probably backports from kernel 5). So all together not a 5 min job. I stopped when the changes in evdi_fb.c got too complex for me for time being.

**Comment by displaylink-dkurek** [comment]
One option would be have a parameter for module Makefile to compile 'as if' it would be different kernel.. but not sure how far it could take us and how problematic it would turn out.

**Comment by sbluhm** [comment]
I finally got round to looking at the deltas and this is quite manageable. Some functions were moved to v5 like header files. Other functions just renamed. So the currently existing version check (#if KERNEL_VERSION(4, 19, 0) <= LINUX_VERSION_CODE) just needs to be extended. I got EVDI to compile on CentOS 8.2. This just needs to be tested next week with an actual DisplayLink device.

@displaylink-dkurek , can you please give me a base on how to continue? I would like to get this sorted for RHEL8. I guess a -D option called EL8 ? Anything upwards of 8.1 would then compile using the updated logic.

**Comment by sbluhm** [comment]
I created #218 .

**Comment by sbluhm** [comment]
@displaylink-dkurek , any chance of merging?

**Comment by displaylink-dkurek** [comment]
@sbluhm Yes, sorry, been working on something else. Will handle it today :)

**Comment by displaylink-dkurek** [comment]
OK, merged :smiley:  Thanks for you patience and contribution :+1:

**Comment by sbluhm** [comment]
Thank you!
