### ISSUE TITLE
Hot-plugging crashes user session

### ISSUE THREAD

**Issue by astromatt42** [DisplayLink/evdi#195]
Initially please make sure the problem hasn't been already addressed:
  * [ yes ] Are you using the latest driver?
    (https://www.displaylink.com/downloads/ubuntu)
  * [ yes ] Are you using the latest EVDI version?
    (https://github.com/DisplayLink/evdi/releases)
  * [ yes ] If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
    (https://support.displaylink.com/knowledgebase/topics/103927-troubleshooting-ubuntu)
  * [ possibly ] Is this issue related to evdi/kernel?
    (if it is rather connected to DisplayLinkManager please take a look at support
    https://support.displaylink.com or forum https://www.displaylink.org/forum/)

Some information for baseline would help a lot:
  * Linux distribution and its version Linux Mint 19.3
  * Linux kernel version 5.3.0.-42
  * Xorg version (if used) 1.20.5
  * Desktop environment in use Cinnamon

The user session crashes on my laptop when I hot-plug the dock. This only happens in Linux, my Windows (dual booting) does not show the same behaviour. I am also using the Nvidia 440 driver out of necessity, the system is unstable with the nouveau open source driver.
Below is a copy of some relevant lines in the kernel log. In particular the 'evdi: [E] evdi_painter_connect:633 Edid length too small' message seems suspicious. However, I am uncertain whether the issue is the DisplayLink software or evdi.

`[Fri Mar 20 10:30:06 2020] evdi: [D] evdi_driver_postclose:144 (dev=3) Process tries to close us, postclose
[Fri Mar 20 10:30:06 2020] evdi: [I] Task 2592 (Xorg) of process 2592 (Xorg)
[Fri Mar 20 10:30:06 2020] evdi: [D] evdi_painter_connect:629 (dev=2) Process is trying to connect
[Fri Mar 20 10:30:06 2020] evdi: [I] Task 2592 (Xorg) of process 2592 (Xorg)
[Fri Mar 20 10:30:06 2020] evdi: [E] evdi_painter_connect:633 Edid length too small
[Fri Mar 20 10:30:06 2020] evdi: [W] evdi_painter_connect_ioctl:755 (dev=2)(pid=2592) disconnect failed
[Fri Mar 20 10:30:06 2020] evdi: [D] evdi_driver_postclose:144 (dev=2) Process tries to close us, postclose
[Fri Mar 20 10:30:06 2020] evdi: [I] Task 2592 (Xorg) of process 2592 (Xorg)
[Fri Mar 20 10:30:06 2020] evdi: [D] evdi_painter_connect:629 (dev=3) Process is trying to connect
[Fri Mar 20 10:30:06 2020] evdi: [I] Task 2592 (Xorg) of process 2592 (Xorg)
[Fri Mar 20 10:30:06 2020] evdi: [E] evdi_painter_connect:633 Edid length too small
[Fri Mar 20 10:30:06 2020] evdi: [W] evdi_painter_connect_ioctl:755 (dev=3)(pid=2592) disconnect failed
[Fri Mar 20 10:30:06 2020] evdi: [D] evdi_driver_postclose:144 (dev=3) Process tries to close us, postclose
[Fri Mar 20 10:30:06 2020] evdi: [I] Task 2592 (Xorg) of process 2592 (Xorg)
`
Regards,

Matt

**Comment by mattmax42** [comment]
This the dmesg log for one of the crash events.
It starts with a wake from sleep, followed by plugging in the docking station with two external monitors (+mouse and keyboard) attached and subsequent crash of the user session to the login window. Login succeeds and display set up is how it was set up after last use.

https://pastebin.com/w9WGbLGN

**Comment by GuitarPikstar** [comment]
I have the same issue using
- Arch Linux (Linux 5.6.14-arch1-1 x86_64)
- Dell Dockingstation D3100
- Two monitors attached via HDMI

**Comment by ipfarher** [comment]
Same issue here:
DELL precision 5550
Kernel: 5.4.0-65-generic
Lubuntu 20.04

Setup 1:
Dockingstation: DELL WD19
One monitor attached via HDMI

Setup 2:
Dockingstation: ICY BOX IB-DK2241AC
One monitor attached via DVI

**Comment by linusw81** [comment]
Any news on that, I have the same issue here for:

Laptop: ASUS N56VZ-S4066H with GeForce GT 650M
Docking Station: WavLink WL-UG69DK1
OS: Ubuntu Mate 21.04
DisplayLink Driver: displaylink-driver-5.4.1-55.174
NVidia Driver: 390.144-0ubuntu0.21.04.1

It worked fine for me in past but I do not know when this started to not work anymore.

**Comment by synaptics-lspintzyk** [comment]
Similar issues with Xorg crashing on hotplug was workarounded in evdi.conf or fixed in Xorg in the past. 
If this still happening to you please raise new issue. 
Thank you. Meanwhile I am closing this issue.
