### ISSUE TITLE
Closed-source NVIDIA driver support

### ISSUE THREAD

**Issue by cepa** [DisplayLink/evdi#2]
Hi,

thanks so much for releasing DisplayLink driver for linux, it is a great commitment for all powerusers who need more screens to work ;)

A question, as mentioned in support, displaylink on linux doesn't work when primary GPU is managed by closed source driver from Nvidia or AMD.

As I saw in dmesg, both evdi and DisplayLinkManager work and they correctly detect attached monitor, so I guess the problem is somewhere in X subsystems like xrandr, right?

Is there any workaround or fix for that?

thanks

**Comment by displaylink-mlukaszek** [comment]
An output related to evdi-connected monitor is added up to modesetting driver (this is what X uses to interface with evdi) including successful retrieval of the mode list. However, this output is not visible anywhere (xrandr, or other UI-backed screen management utilities) and X does not appear to use it in any way.
The same goes for an (already upstreamed to kernel) udl driver that drives USB2.0-era DisplayLink devices.
Any contributions to address this are welcome.
