### ISSUE TITLE
driver for ubuntu 20.04LTS

### ISSUE THREAD

**Issue by jannik8x8** [DisplayLink/evdi#200]
* Ubuuntu 20.04LTS
  * Linux kernel: 5.4.0-28
  * Docking Station: Icy Box IB-DK2241AC
There is no driver at https://www.displaylink.com/downloads/ubuntu for the newly released Ubuntu LTS version 20.04. When will it be available?

I compiled and installed the version from this github site (zip-archive) but had no success with my external monitor. I did two steps:
1) make
2) make install

Both returned with $? => 0
I rebooted my laptop (HP Pavilion Laptop Modell 15-cs2310ng ) but no success.

What did I wrong? Any experience with ubuntu 20.04LTS?

jannik8x8

**Comment by joren485** [comment]
You could try [AdnanHodzic/displaylink-debian](https://github.com/AdnanHodzic/displaylink-debian). It officially supports Ubuntu 20.04.

**Comment by elguero** [comment]
@jannik8x8 FYI, there are new DisplayLink drivers available for Ubuntu 20.04

**Comment by mikldk** [comment]
When using this I get really slow and laggy performance under Xorg, but acceptable under Wayland.

**Comment by kicumkicum** [comment]
I have slow laggy under Xorg and under Wayland.

**Comment by stiobhan** [comment]
There is a new driver that supports Ubuntu 20.04, so I guess this should be closed?

Regarding performance issues, see https://github.com/DisplayLink/evdi/issues/181

**Comment by displaylink-dkurek** [comment]
Closing this one. As @stiobhan noted, performance is a different issue :)
