### ISSUE TITLE
A new release is needed for Arch/AUR kernels >= 5.5

### ISSUE THREAD

**Issue by artscoop** [DisplayLink/evdi#201]
Hi,

The maintainer of the evdi package in the AUR needs a new release/tag to allow a new release in the AUR. The issue has been raised in the AUR comments section, but it seems there was no request made in this repository.

Thanks

**Comment by bnavigator** [comment]
I have an addition for the [evdi-git](https://aur.archlinux.org/packages/evdi-git/#comment-744589) AUR package which jumps through some hoops to get the correct version `1.7.0` of the current devel branch. It would be really nice if the repository had a proper **reachable** tag and the release of a new version that works with recent kernels.

**Comment by displaylink-dkurek** [comment]
Sorry for a delay, tag `v1.7.0` created :)
