### ISSUE TITLE
Latest evdi-git release builds and installs but does not work on Arch 5.6.11 kernel

### ISSUE THREAD

**Issue by kaipee** [DisplayLink/evdi#202]
Some information for baseline would help a lot:
  * Arch Linux 5.6.11-arch1-1 x86_64
  * 5.6.11
  * X.Org X Server 1.20.8
  * Gnome Shell 3.36.2

Installing or upgrading using AUR package for Arch Linux will build and install the EVDI package, but once installed it will not work (screens are blank and no signal detected).

Booting into linux-lts kernel (5.4.39-1) has the same effect.

**Comment by elguero** [comment]
One thing missing from the list.  What version of DisplayLink drivers are you using?

**Comment by kaipee** [comment]
Woops!

Displaylink 5.2.14-1

**Comment by elguero** [comment]
I believe that is your problem.

The devel branch has a newer evdi library which is going to be 1.7.0 once it is released.  It would appear that the interface changed which makes it no longer compatible with Displaylink 5.2.14.  A new DisplayLink driver has been released, 5.3.1, which does work with the evdi library in the devel branch.
