### ISSUE TITLE
Monitor not selectable once I add a conf file in /usr/share/X11/xorg.conf.d

### ISSUE THREAD

**Issue by mauromol** [DisplayLink/evdi#207]
I have Linux Mint KDE 18.4 (based on Ubuntu 16.04).
The following problem occurs with both DisplayLink driver 5.2.14 and 5.3.1.

With the default configuration, all works "fine" (more or less, see later).
Once I add a configuration file in /usr/share/X11/xorg.conf.d, the monitor connected to my DL-3900 docking station is no longer detected.

The contents of the file I add is the following:

```
Section "Device"
   Identifier  "Intel Graphics"
   Driver      "intel"
   Option      "TearFree"    "true"
EndSection
```

The reason I'm adding this file is to enable the `TearFree` option. I was suspecting that was the actual problem, but if I replace that file contents with this:

```
Section "Device"
   Identifier  "Intel Graphics"
   Driver      "intel"
   Option      "TearFree"    "false"
EndSection
```

hence disabling the `TearFree` option (as it is by default, when there's no configuration file at all), still the monitor attached to the docking station is not recognized (missing in the Monitor settings in System Settings, where I see just my laptop internal monitor).
Once I move away that file and restart the X session, all is "fine" again.
Any help/explanation would be really appreciated.

When I say that it works "fine" with no configuration file, I mean it works as expected, however I had a problem with 5.2.14 driver  (still have to see how 5.3.1 behaves in this regard): right after boot, all works fine. With hours passing by, the whole system becomes slower and slower. After a day of work, it becomes almost unusable. Looking at top or similar task manager, I see the DisplayLinkManager process consuming around 2-3% CPU time constantly upon boot, arriving at a constant ~10% at the end of the day. Apart from this, the CPU seems not to be so much under load, the CPU fan is relatively quiet, it seems like the CPU scheduler isn't pushing the CPU at its higher frequencies any more. I can't explain this behaviour, but the fact that the system become slower and slower over time makes me suspect there's some kind of resource leak in DisplayLink driver and/or manager. Probably some kind of I/O wait issue?
The only fix for this I found is a complete system reboot: just restarting X or the DisplayLinkManager or driver services is not enough.
This problem of course does not happen when I connect the secondary monitor to my laptop HDMI port instead of to the docking station one (otherwise I wouldn't have bothered you).
I know this may be the subject for a completely different report, just wanted to know if it is a known issue and/or if there's any hope it's fixed with 5.3.1 driver version.

**Comment by lspintzyk** [comment]
Hi, this is because you are using intel userspace driver, on ubuntu it is installed with xserver-xorg-video-intel. 
You should use modesetting driver that is default and preferred one for evdi virtual gpu and intel gpu device.
DisplayLink is supporting modesetting driver at the moment.

**Comment by mauromol** [comment]
I'm pretty sure Linux Mint 18.3 was still using the Intel driver by default, even if no `xorg.conf.d` was added. Also, I'm pretty sure you once recommended to try the old Intel driver instead of the modesetting one to troubleshoot issues.

Nevertheless, now this Mint/Ubuntu version is not supported any more, I meanwhile switched to Kubuntu 20.04 and the newest DisplayLink drivers work well out-of-the-box there, although the modesetting driver seems not to support the tearfree option yet, as far as I know.

Thank you.
