### ISSUE TITLE
Unable to install displaylink-debian successfully

### ISSUE THREAD

**Issue by engineer22** [DisplayLink/evdi#209]
Hello, I have a HP Pavilion laptop with Debian 10 stable - I'm using an HDMI-USB3 to connect a 2nd external monitor.

Following all the steps, I come to these two errors. First being within the installation:
- ln: failed to create symbolic link '/lib/modules/4.19.0-9-amd64/build/Kconfig' : File exists

After this fails, I try to run 'sudo ./displaylink-debian.sh --debug' which gives me this error:

- cat: /sys/devices/evdi/version: No such file or directory

By digging around I found a solution for what seems to resolve the second error, but again the error doesn't disappear: https://forum.manjaro.org/t/linux56-headers-broke-native-displaylink-1xx-support-on-fresh-manjaro-installation/142981/4

Can someone please tell me what the problem is? Thank you!

**Comment by displaylink-dkurek** [comment]
I see that you have raised it on https://github.com/AdnanHodzic/displaylink-debian/issues/428
(which is probably the package you're using) and closed it already.
Closing.
