### ISSUE TITLE
Firmware?

### ISSUE THREAD

**Issue by hadess** [DisplayLink/evdi#21]
The package available Ubuntu for the DisplayLink docks contains 2 firmware files:
- ella-dock-release.spkg
- firefly-monitor-release.spkg

Those firmware are supposed to be uploaded if necessary to the docks, but there's no code in evdi, library or module, to support it. And no mention as to whether they are freely redistributable.

**Comment by displaylink-mlukaszek** [comment]
evdi doesn't need to worry about firmware packages which are specific for DisplayLink docks.
For distribution, see the [article about porting to other distros](http://support.displaylink.com/knowledgebase/articles/679060-porting-the-displaylink-ubuntu-driver-to-other-lin) and LICENSE text that can be extracted from the archive - in short, we allow repackaging and redistribution under certain conditions - refer to 1.4 in license terms.
