### ISSUE TITLE
Tag missing for version 1.7.0

### ISSUE THREAD

**Issue by thopiekar** [DisplayLink/evdi#210]
I just took a look at the latest version of driver offered on your website and noticed that evdi v1.7.0 is shipped with it. However, when checking here under releases I don't see the version tagged.

Could you be so kind and add the missing release here?

Thanks!

**Comment by displaylink-dkurek** [comment]
Here it is
https://github.com/DisplayLink/evdi/releases/tag/v1.7.0
Or am I missing something?

**Comment by thopiekar** [comment]
Strange. I was checking that in my git clone and it wasn't there. I'm pretty sure I updated my copy recently.

Thank you for the quick reply and excuse the confusion!
