### ISSUE TITLE
Monitor and network disconnects

### ISSUE THREAD

**Issue by MrBrokenHelm** [DisplayLink/evdi#213]
Initially please make sure the problem hasn't been already addressed:
  * [Y ] Are you using the latest driver?
    (https://www.displaylink.com/downloads/ubuntu)
  * [Y ] Are you using the latest EVDI version?
    (https://github.com/DisplayLink/evdi/releases)
  * [Y ] If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
    (https://support.displaylink.com/knowledgebase/topics/103927-troubleshooting-ubuntu)
  * [Y ] Is this issue related to evdi/kernel?
    (if it is rather connected to DisplayLinkManager please take a look at support
    https://support.displaylink.com or forum https://www.displaylink.org/forum/)

Some information for baseline would help a lot:
  * Linux distribution and its version
Arch Linux
  * Linux kernel version
5.7.6-arch1-1
  * Xorg version (if used)
1.20.8-2
  * Desktop environment in use
bspwm 0.9.9-1 

Problem description
Since using kernel 5.7.6-ach1-1 my monitors and network disconnect every 5 minutes, mouse and keyboard via the dock keep working. The monitors recover after a few second due to autorandr detecting the monitors and setting up the display. Network has to be manually reconnected.

I have reverted back to kernel 5.7.5-arch1-1 and the issues seem to be resolved.

The dock in use is the Dell D6000.

Please find attached an extract of the logs displaying the issue:
[journal_evdi.log](https://github.com/DisplayLink/evdi/files/4849947/journal_evdi.log)

Please do let me know if you require more information or want me to test something.

Kind regards,

C.J.

**Comment by displaylink-dkurek** [comment]
This might be caused by the firmware in dock. To upgrade it you have to have Windows computer, as the files provided by the manufacturer can only be used with that operating system.
The file is available at: https://www.dell.com/support/home/uk/en/ukdhs1/product-support/product/dell-universal-dock-d6000/drivers
* When you do the update make sure you do not have anything plugged in to the dock.
* Connect the dock to machine running Windows and run the file downloaded from the website.
* Follow the wizard :)

**Comment by MrBrokenHelm** [comment]
Thank you for the swift reply. 

I have upgrade my dock to the latest version, it was one version behind. After which I have upgrade kernel to the latest version (5.7.6-ach1-1).
After about 10 minutes the disconnect of monitor and network reoccurred again, monitors reconnected again and the network was switch online manually again. After 5 minutes the same issue occurred again.

To be sure that this issue is not caused by the upgrade of the dock, I downgrade my kernel again to 5.7.5-arch1-1 for testing. 
Which seems to work fine again. 

The issue seems to be pointing to the latest kernel.

**Comment by asteriskUser** [comment]
Same behaviour observed here on Ubuntu 20.04 LTS.

Laptop: DELL XPS 13 (9360) - Intel Core i7 7500U, 8GB RAM (latest BIOS etc)
Graphics: Mesa Intel® UHD Graphics 620 (KBL GT2)
Dock: DELL D6000 (2 x 1080p monitors via DisplayPort) (latest firmware provided by DELL)
OS: Ubuntu 20.04 LTS on Wayland (Kernel 5.4.0-40 - UEFI)

I've caught the following in the logs (specifically the segfault in DisplayLinkManager looks suspicious - see error log):
dmesg | grep evdi
[   15.066933] evdi: loading out-of-tree module taints kernel.
[   15.067908] evdi: [I] Initialising logging on level 5
[   15.067908] evdi: [I] Atomic driver:yes
[   15.067959] evdi: [D] evdi_add_devices:156 Increasing device count to 4
[   15.068014] evdi: [D] evdi_crtc_init:389 drm_crtc_init: 0 p0000000029c48e6f
[   15.068023] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   15.068035] evdi: [W] evdi_painter_send_update_ready_if_needed:645 Painter does not exist!
[   15.068873] [drm] Initialized evdi 1.7.0 20200327 for evdi.0 on minor 1
[   15.068933] evdi: [D] evdi_crtc_init:389 drm_crtc_init: 0 p000000003da62d9a
[   15.068940] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   15.068946] evdi: [W] evdi_painter_send_update_ready_if_needed:645 Painter does not exist!
[   15.069016] [drm] Initialized evdi 1.7.0 20200327 for evdi.1 on minor 2
[   15.069244] evdi: [D] evdi_crtc_init:389 drm_crtc_init: 0 p00000000714eb0ff
[   15.069249] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   15.069253] evdi: [W] evdi_painter_send_update_ready_if_needed:645 Painter does not exist!
[   15.069825] [drm] Initialized evdi 1.7.0 20200327 for evdi.2 on minor 3
[   15.069883] evdi: [D] evdi_crtc_init:389 drm_crtc_init: 0 p00000000023da8fb
[   15.069891] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   15.069898] evdi: [W] evdi_painter_send_update_ready_if_needed:645 Painter does not exist!
[   15.070170] [drm] Initialized evdi 1.7.0 20200327 for evdi.3 on minor 4
[   15.441280] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   15.441305] evdi: [D] evdi_driver_postclose:133 (dev=0) Process tries to close us, postclose
[   15.441307] evdi: [I] Task 307 (plymouthd) of process 307 (plymouthd)
[   15.449760] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   15.449777] evdi: [D] evdi_driver_postclose:133 (dev=0) Process tries to close us, postclose
[   15.449778] evdi: [I] Task 307 (plymouthd) of process 307 (plymouthd)
[   15.452583] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   15.452599] evdi: [D] evdi_driver_postclose:133 (dev=0) Process tries to close us, postclose
[   15.452601] evdi: [I] Task 307 (plymouthd) of process 307 (plymouthd)
[   15.454758] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   15.454769] evdi: [D] evdi_driver_postclose:133 (dev=0) Process tries to close us, postclose
[   15.454770] evdi: [I] Task 307 (plymouthd) of process 307 (plymouthd)
[   15.464675] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   15.464690] evdi: [D] evdi_driver_postclose:133 (dev=0) Process tries to close us, postclose
[   15.464691] evdi: [I] Task 307 (plymouthd) of process 307 (plymouthd)
[   15.482003] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   15.482017] evdi: [D] evdi_driver_postclose:133 (dev=0) Process tries to close us, postclose
[   15.482018] evdi: [I] Task 307 (plymouthd) of process 307 (plymouthd)
[   15.491396] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   15.491411] evdi: [D] evdi_driver_postclose:133 (dev=0) Process tries to close us, postclose
[   15.491412] evdi: [I] Task 307 (plymouthd) of process 307 (plymouthd)
[   15.495328] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   15.495340] evdi: [D] evdi_driver_postclose:133 (dev=0) Process tries to close us, postclose
[   15.495342] evdi: [I] Task 307 (plymouthd) of process 307 (plymouthd)
[   15.938033] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   15.938053] evdi: [D] evdi_driver_postclose:133 (dev=0) Process tries to close us, postclose
[   15.938054] evdi: [I] Task 307 (plymouthd) of process 307 (plymouthd)
[   15.949060] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   15.949083] evdi: [D] evdi_driver_postclose:133 (dev=0) Process tries to close us, postclose
[   15.949084] evdi: [I] Task 307 (plymouthd) of process 307 (plymouthd)
[   15.955775] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   15.955792] evdi: [D] evdi_driver_postclose:133 (dev=0) Process tries to close us, postclose
[   15.955793] evdi: [I] Task 307 (plymouthd) of process 307 (plymouthd)
[   15.956195] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
...

root@XPS-13:/home/vas232# dmesg | grep error
[   15.016696] EXT4-fs (dm-1): re-mounted. Opts: errors=remount-ro
[   81.697811] pcieport 0000:00:1c.0: AER: Corrected error received: 0000:00:1c.0
[   81.697829] pcieport 0000:00:1c.0: AER:   device [8086:9d10] error status/mask=00003000/00002000
[   97.137258] ActiveCommandQu[1067]: segfault at 7f318c00f040 ip 0000000000998d9e sp 00007f3123ffd408 error 4 in DisplayLinkManager[400000+937000]
[  206.425664] pcieport 0000:00:1c.0: AER: Corrected error received: 0000:00:1c.0
[  206.425673] pcieport 0000:00:1c.0: AER:   device [8086:9d10] error status/mask=00001000/00002000
[  245.209842] pcieport 0000:00:1c.0: AER: Corrected error received: 0000:00:1c.0
[  245.209852] pcieport 0000:00:1c.0: AER:   device [8086:9d10] error status/mask=00001000/00002000
...

**Comment by asteriskUser** [comment]
In addition to above I've also noticed that the dock doesn't go to standby anymore when shutting down Ubuntu. The led idicator remains white (even when disconnecting the USB-C connection). Only solution is to disconnecting the dock from the mains and connecting it back again. Works fine on Windows 10 though.

**Comment by MrBrokenHelm** [comment]
Currently running on kernel 5.7.7-arch1-1 which seems to have resolved the issue.

I have not closed this issue as I am unsure the Ubuntu kernel is still affecting this.

**Comment by asteriskUser** [comment]
Update on the Ubuntu 20.04 system. The latest update seems to have resolved the issue. Both monitors are running fine now and without any disconnects (almost a week now).
