### ISSUE TITLE
evdi 1.8 module not loading in 5.4 kernel?

### ISSUE THREAD

**Issue by 5472qaywsx** [DisplayLink/evdi#216]
Initially please make sure the problem hasn't been already addressed:
  * [X] Are you using the latest driver? YES
    (https://www.displaylink.com/downloads/ubuntu)
  * [X] Are you using the latest EVDI version? YES
    (https://github.com/DisplayLink/evdi/releases)
  * [X] If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website? YES
    (https://support.displaylink.com/knowledgebase/topics/103927-troubleshooting-ubuntu)
  * [X] Is this issue related to evdi/kernel? YES
    (if it is rather connected to DisplayLinkManager please take a look at support
    https://support.displaylink.com or forum https://www.displaylink.org/forum/)

Some information for baseline would help a lot:
  * Linux distribution and its version: archlinux
  * Linux kernel version: 5.4.57-1-lts
  * Xorg version (if used): 1.20.8
  * Desktop environment in use: (i3)

>$ dmesg | grep -i evdi
>[   11.340401] evdi: loading out-of-tree module taints kernel.
>[   11.340463] evdi: module verification failed: signature and/or required key missing - tainting kernel
>[   11.342528] evdi: [I] Initialising logging on level 5
>[   11.342529] evdi: [I] Atomic driver:yes

Is this something that should be adressed from evdi-side, or something that I should solve specifically on my machine?
There are some comments on archlinux-AUR-evdi page on this.

Cheers,
Dan

**Comment by elguero** [comment]
It looks like it is loading.  The message you are quoting is just an informational message that we all get when running evdi.

Run this `lsmod | grep evdi`.  You should see that the evdi module running.

For example:
```
evdi                   65536  4
drm_kms_helper        249856  3 evdi,amdgpu,i915
drm                   618496  19 gpu_sched,drm_kms_helper,evdi,amdgpu,i915,ttm
```
I believe that in order to use evdi 1.8.0, we are waiting on a new release of the DisplayLink driver (https://www.displaylink.com/downloads/ubuntu).

**Comment by 5472qaywsx** [comment]
Ok, thank you. You're right about loading.
I will switch back to 1.7.0 and wait for the next release of the displaylink driver.

**Comment by kvaps** [comment]
Any information about release date?

**Comment by specialworld83** [comment]
New release date?

**Comment by Square252** [comment]
Don't want to be rude, but some people are required to use this piece of... software. To make USB-C in any kind a useable standard we NEED working software as a minimun. Lets not repeat the fuck ups the the shitty usb 3 standards.

**Comment by technoo10201** [comment]
Hi guys, any news ?

**Comment by displaylink-dkurek** [comment]
The DLM on the website (5.3.1) should be working with kernel 5.4, it actually should be compatible with kernel 5.6.
As in the description - EVDI module is loaded.
@technoo10201, what is the problem you are seeing? Can you show `dmesg | grep evdi` and DLM logs?
**/var/log/displaylink/DisplayLinkManager.log**

**Comment by displaylink-dkurek** [comment]
The DLM on the website (5.3.1) contains EVDI **v1.7.0** which should be working up to kernel **5.8** (included).
5.9 will indeed need some modifications, but we are currently on **v5.9-rc6** so we have around 2 weeks before **v5.9** will actually happen. At the moment there is no need to upgrade EVDI to 1.8.0 for DLM :)

**Comment by technoo10201** [comment]
> The DLM on the website (5.3.1) contains EVDI **v1.7.0** which should be working up to kernel **5.8** (included).
> 5.9 will indeed need some modifications, but we are currently on **v5.9-rc6** so we have around 2 weeks before **v5.9** will actually happen. At the moment there is no need to upgrade EVDI to 1.8.0 for DLM :)

Hi ! Thanks for your fast reply, i appreciate. I'm trying to install DLM 5.3.1 but i have this error message :

' sudo LANG=C ./displaylink-driver-5.3.1.34.run 
Verifying archive integrity...  100%   All good.
Uncompressing DisplayLink Linux Driver 5.3.1.34  100%  
DisplayLink Linux Software 5.3.1.34 install script called: 
Distribution discovered: "Manjaro Linux"
Unsatisfied dependencies. Missing component: libdrm.
This is a fatal error, cannot install DisplayLink Linux Software.
'

Do you have a work around to fix this issue ?
Thanks in advance !

**Comment by displaylink-dkurek** [comment]
I've found this topic
https://forum.manjaro.org/t/displaylink-driver-installation-issue/22176
Which describes the same problem. There is AUR package with 
DisplayLinkManager 5.3.1 (it's maintained by community).
I'm not familiar with manjaro but it seems it's enough to just call
`pamac build displaylink`
