### ISSUE TITLE
Build fail on Manjaro

### ISSUE THREAD

**Issue by supermarille** [DisplayLink/evdi#217]
I'm using 5.7.14-1-MANJARO (with Cinnamon).
I was trying to install the displaylink driver according to the[ tutorial in the archwiki](https://wiki.archlinux.org/index.php/DisplayLink), but got the following error during build:
```==> Lancement de build()…
CFLAGS="-Werror -Wextra -Wall -Wmissing-prototypes -Wstrict-prototypes -Wno-error=missing-field-initializers" make -C module -j13 --jobserver-auth=3,4
make[1]: warning: -j13 forced in submake: resetting jobserver mode.
make[1] : on entre dans le répertoire « /home/marie/.cache/yay/evdi-git/src/evdi/module »
make -C /lib/modules/5.7.14-1-MANJARO/build M=$PWD
make[2] : on entre dans le répertoire « /usr/lib/modules/5.7.14-1-MANJARO/build »
make[2]: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.
make[2] : on quitte le répertoire « /usr/lib/modules/5.7.14-1-MANJARO/build »
make[1]: *** [Makefile:71 : module] Erreur 2
make[1] : on quitte le répertoire « /home/marie/.cache/yay/evdi-git/src/evdi/module »
make: *** [Makefile:8 : all] Erreur 2
==> ERREUR : Une erreur s’est produite dans build().
/usr/share/makepkg/util/message.sh: ligne 51: QUIET : variable sans liaison
/usr/bin/makepkg: ligne 132: logpipe : variable sans liaison
erreur lors de la construction : %!s(func() string=0x5638e267d410)
```
I couldn't find any piece of information on that error. Anyone has a clue ?

**Comment by displaylink-dkurek** [comment]
Is this a regression or was it like that always? Seems we are looking for
`/lib/modules/5.8.1-arch1-1/build` directory, but it's missing.
Can you post result of `ls /lib/modules` command? Also, do you have linux headers installed?

**Comment by supermarille** [comment]
I have linux414-headers 4.14.193-1 and linux-api-headers 5.6.11-1 installed.
I don't know if it's a regression or not, it's the first time that I try to use a dock.
```
ls /lib/modules
4.14.193-1-MANJARO  5.7.15-1-MANJARO  extramodules-5.7-MANJARO
```

**Comment by displaylink-dkurek** [comment]
@supermarille  could you try to install linux headers for version 5.7.14  (or 5.7.15, not sure which version you are using currently).
Can you post also output of `ls /lib/modules/5.7.15-1-MANJARO` ?
It seems we are missing the directory, not sure if this is an issue in how we designating it or missing package :)

**Comment by supermarille** [comment]
You might laugh but I unplugged the monitor and plugged it back in and now it's working (I promise that I already did that before) so it seems I don't need more drivers.
I'm going to try anyway, but maybe @walialu will have more interesting outputs. After the installation of the headers for version 5.7.15:
```
ls /lib/modules/5.7.15-1-MANJARO
build          modules.alias.bin          modules.dep      modules.symbols
extramodules   modules.builtin            modules.dep.bin  modules.symbols.bin
kernel         modules.builtin.alias.bin  modules.devname  pkgbase
kernelbase     modules.builtin.bin        modules.order    vmlinuz
modules.alias  modules.builtin.modinfo    modules.softdep
```

**Comment by walialu** [comment]
Installation was flawless now. IDK, I changed nothing. Just tried yay -S displaylink yesterday and it worked lik a charm.

**Comment by displaylink-dkurek** [comment]
Can we close this now? seems it's currently working fine? :D

**Comment by walialu** [comment]
Yes, close it, please!

**Comment by displaylink-dkurek** [comment]
OK, closing. Thanks :)
