### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Square252** [DisplayLink/evdi#222]
That displaylink shit is basically dead. 
Look at the commit history of the development branch, 3 or 4 people with 20 commits in the past year. There is obvsly no develompment backing behind this whole mess. U should fully open source this displaylink shit it or give up and let this stuff be. After 5 years you basically accomplished nothing besides vendors of docking stations using that stuff, but there is not even one release that one could call "stable". Every other "old" Docking Station with AGP worked a thousand times better. It even survived updates without an issue. Right now, we need to wait for u guys after every second x or kernel update. It sucks. If this is a hobby project to you, admit it and declare this stuff for dead. Or start developing this stuff for real like it would be your business.

**Comment by displaylink-dkurek** [comment]
In the last year there were 9 committers with total of 72 commits, if you want to speak numbers.

It's true every other X release is causing problems and additional fixes/workarounds are needed. Usually some additional environment setup - like disabling PageFlip or forcing specific driver - does the trick.

There is no need to wait for us with kernel changes, everyone is welcome to make a PR :)

This repo is related to EVDI specifically, not DisplayLinkManager. If you have a question or a further feedback to the latter please contact our support https://support.displaylink.com.

By the way: isn't github issue template working? I might need to fix it.

**Comment by elguero** [comment]
Why not step up and contribute some code? Submitting bug reports with actual logs or debug messages (constructive reports) would be a way to contribute and speed things up.
