### ISSUE TITLE
Disconnected/Output does not exists with evdi 1.8.0

### ISSUE THREAD

**Issue by blackPantherOS** [DisplayLink/evdi#223]
Initially please make sure the problem hasn't been already addressed:
  * [ ] Are you using the latest driver?
**Tested version: 5.3.1.34**
  * [ ] Are you using the latest EVDI version?
**Tested version: 1.8.0 stable and Git as well**
  * [ ] If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
**Yes**
  * [ ] Is this issue related to evdi/kernel?
**Yes**

Some information for baseline would help a lot:
  * Linux distribution and its version = blackPanther OS v18.1SE
  * Linux kernel version = **Tested with 5.1.15 - 5.6.14** 
  * Xorg version (if used)  = **1.20.8**
  * Desktop environment in use = **KDE/Plasma**

Please provide good title for the issue and description.
The latest version evdi build, module loaded correctly, DisplayLink service running fine, but device won't show at xrandr output

**First test: Kernel: 5.1.15   evdi 1.6.1 DisplayLink 5.1.26** = WORKING FINE!

**Second test: Kernel: 5.1.15   evdi 1.8.0 DisplayLink  5.3.1.34**

module load manually with `initial_loglevel=10 initial_device_count=1`

```
szept 28 18:36:12 local kernel: evdi: [V] evdi_detect:88 
szept 28 18:36:12 local kernel: evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected

for i in $(find /sys/devices/evdi/ -type f) ; do echo -n $i ; echo " -> $(cat $i 2>/dev/null)" ;done
/sys/devices/evdi/uevent -> Permission denied
/sys/devices/evdi/remove_all -> Permission denied
/sys/devices/evdi/count -> 1
/sys/devices/evdi/power/runtime_active_time -> 0
/sys/devices/evdi/power/runtime_status -> unsupported
/sys/devices/evdi/power/autosuspend_delay_ms -> Permission denied
/sys/devices/evdi/power/runtime_suspended_time -> 0
/sys/devices/evdi/power/control -> auto
/sys/devices/evdi/add -> Permission denied
/sys/devices/evdi/version -> 1.8.0
/sys/devices/evdi/loglevel -> 10


systemctl status displaylink.service 
● displaylink.service - DisplayLink Driver Service
   Loaded: loaded (/usr/lib/systemd/system/displaylink.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-09-28 18:35:02 CEST; 5min ago
  Process: 2056 ExecStartPre=/usr/sbin/modprobe evdi (code=exited, status=0/SUCCESS)
 Main PID: 2066 (DisplayLinkMana)
   Memory: 11.6M

```

**Comment by displaylink-dkurek** [comment]
Hi blackPantherOS,

In short: EVDI v1.8 is incompatible with DisplayLinkManager 5.3.

The DLM on the website (5.3.1) contains EVDI v1.7.0 which should be working up to kernel 5.8 (included).
5.9 will indeed need some modifications, but we are currently on v5.9-rc7 so at the moment there is no need to upgrade EVDI to 1.8.0 for DLM.

Closing.

**Comment by blackPantherOS** [comment]
Thanks, We replaced dkms-evdi-1.8.0 package to 1.7 in system repository and now working fine again. The first few times got hard freezes if I tried to run an applicaton which uses the DRM, ex.: Chrome, on DisplayLink-monitor, but now this issue is gone. I couldn't logging or debugging anything because the hardware is absolutily freezed immeditally.
