### ISSUE TITLE
Kernel 5.9 breaks DisplayLink

### ISSUE THREAD

**Issue by robotard** [DisplayLink/evdi#225]
Initially please make sure the problem hasn't been already addressed:
  * [ X] Are you using the latest driver?
    (https://www.displaylink.com/downloads/ubuntu)
  * [X ] Are you using the latest EVDI version?
    (https://github.com/DisplayLink/evdi/releases)
  * [X ] If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
    (https://support.displaylink.com/knowledgebase/topics/103927-troubleshooting-ubuntu)
  * [X ] Is this issue related to evdi/kernel?
    (if it is rather connected to DisplayLinkManager please take a look at support
    https://support.displaylink.com or forum https://www.displaylink.org/forum/)

Some information for baseline would help a lot:
  * Linux distribution and its version
  * Linux kernel version
  * Xorg version (if used)
  * Desktop environment in use

Please provide good title for the issue and description.
If you can give us logs they will be welcome but please don't paste long listings
as they will make it hard to read the thread, instead you can use other services
for sharing raw text like pastebin or gist.
Also anything that may help to understand the problem will be appreciated
(configuration files, screenshots, photos, video capturing the problem).

Thanks!

**Comment by abucodonosor** [comment]
If you wish I have a testing patch, untested since I don't have any HW to test right now and will only work with a 5.9 kernel.

Patch against latest release:

https://crazy.dev.frugalware.org/evdi-kernel-5.9-test.patch

**Comment by robotard** [comment]
That’s great. Will test when back home. Guessing it was just a one liner allowing 5.9.x to pass? Or is there more to it?

**Comment by abucodonosor** [comment]
@robotard 

It is a bit more than a one-liner:).

The Intel workaround is now somewhat strange but it should, in theory, work like this.

**Comment by robotard** [comment]
Oooof, n00b to patching (can read them, but not applied before)... Where's
likely to be the path to my DisplayLink?

Ubuntu... Latest DL from website...

Seeing this:

"patch < '/home/robsta/Downloads/evdi-kernel-5.9-test.patch'
can't find file to patch at input line 4
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff -Naur evdi-1.8.0/module/evdi_cursor.c
evdi-1.8.0-p/module/evdi_cursor.c
|--- evdi-1.8.0/module/evdi_cursor.c 2020-07-31 12:07:08.000000000 +0200
|+++ evdi-1.8.0-p/module/evdi_cursor.c 2020-10-12 16:05:56.615556087 +0200
--------------------------
File to patch: "

**Comment by displaylink-dkurek** [comment]
@robotard 
Try with `patch -Np1` instead of `patch`

@abucodonosor 
You are delivering great patches, as always :+1:, thanks :)
Are you interested in creating PR? :)

I've just checked it with evdi master and v1.7.0 tag - compiles fine.

Note: For usage with **DisplayLinkManager 5.3.1** please apply it on
top of tag **v1.7.0** (in v1.8.0 there was API change).

Something like this should work:
```bash
# get sources
git clone https://github.com/DisplayLink/evdi.git
cd evdi
git checkout v1.7.0

# patch
curl https://crazy.dev.frugalware.org/evdi-kernel-5.9-test.patch | patch -Np1

# install
make
sudo make install

# reboot
```

**Comment by displaylink-dkurek** [comment]
Yes, exactly. Please use only `KERNEL_VERSION(X, Y, Z) <= LINUX_VERSION_CODE` format, newest top.
Thanks!

**Comment by abucodonosor** [comment]
@displaylink-dkurek 

Ok done.

https://github.com/DisplayLink/evdi/pull/227

**Comment by sickcodes** [comment]
Works for the 1.7.0 tag too, thanks @abucodonosor & @displaylink-dkurek! 


https://github.com/DisplayLink/evdi/pull/228

Master was 1 ahead of 1.7.0 tag which worked for me too, any reason why tag was one behind, @displaylink-dkurek?

**Comment by robotard** [comment]
Unfortunately no bueno for me 

> @robotard
> Try with `patch -Np1` instead of `patch`
> 
> @abucodonosor
> You are delivering great patches, as always , thanks :)
> Are you interested in creating PR? :)
> 
> I've just checked it with evdi master and v1.7.0 tag - compiles fine.
> 
> Note: For usage with **DisplayLinkManager 5.3.1** please apply it on
> top of tag **v1.7.0** (in v1.8.0 there was API change).
> 
> Something like this should work:
> 
> ```shell
> # get sources
> git clone https://github.com/DisplayLink/evdi.git
> cd evdi
> git checkout v1.7.0
> 
> # patch
> curl https://crazy.dev.frugalware.org/evdi-kernel-5.9-test.patch | patch -Np1
> 
> # install
> make
> sudo make install
> 
> # reboot
> ```

Thanks again for another swift response :)

Unfortunately no bueno for me here... I dis mention that I'm a Groovy Gorilla (20.10) too right? Here's my kernel info:
`uname -a
Linux robstas-um433iq 5.9.0-050900-generic #202010112230 SMP Sun Oct 11 22:34:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
`

I've attached the DLSupportTool output for your perusal too, and am more than happy to do any testing you need for both this fix, and anything that I may be able to help with in the future... Am usually close to latest Ubuntu/Kernel versions too :)
[DLSupportTool_Output_2020-10-15T07:16:25.723360.zip](https://github.com/DisplayLink/evdi/files/5382822/DLSupportTool_Output_2020-10-15T07.16.25.723360.zip)

**Comment by sickcodes** [comment]
Working on 5.9 with 1.7.0, love you @abucodonosor 

```bash
git clone https://github.com/DisplayLink/evdi
cd evdi
git remote add abucodonosor https://github.com/abucodonosor/evdi.git
git fetch --all
git cherry-pick abucodonosor/issue-225 --no-commit
make
```

Or

```bash
git clone https://github.com/sickcodes/evdi
cd evdi
make
```

**Comment by displaylink-dkurek** [comment]
@sickcodes
Tag v1.7.0 is made on devel branch, and then devel is merged to master. So master has one extra 'merge' commit on it.
This is made this way so tagged version is the same commit as we are shipping with DisplayLinkManager.

**Comment by PathosEthosLogos** [comment]
> Working on 5.9 with 1.7.0, love you @abucodonosor
> 
> ```shell
> git clone https://github.com/DisplayLink/evdi
> cd evdi
> git remote add abucodonosor https://github.com/abucodonosor/evdi.git
> git fetch --all
> git cherry-pick abucodonosor/issue-225 --no-commit
> make
> ```
> 
> Or
> 
> ```shell
> git clone https://github.com/sickcodes/evdi
> cd evdi
> make
> ```

I tried both of these methods and it gives me error 2. 

```
cat: /etc/redhat-release: No such file or directory
CFLAGS="-Werror -Wextra -Wall -Wmissing-prototypes -Wstrict-prototypes -Wno-error=missing-field-initializers" make -C module
make -C /lib/modules/5.8.11-1-MANJARO/build M=$PWD
make[2]: Entering directory '/usr/lib/modules/5.8.11-1-MANJARO/build'
make[2]: *** No targets specified and no makefile found.  Stop.
make[2]: Leaving directory '/usr/lib/modules/5.8.11-1-MANJARO/build'
make[1]: *** [Makefile:71: module] Error 2
make: *** [Makefile:13: all] Error 2
```

I also tried the code block in the comments of https://aur.archlinux.org/packages/displaylink but even the first line `sudo pacman -R evdi-git #used -Rns` does not seem to work, saying that `evdi-git` is not found.

**Comment by abucodonosor** [comment]
@PathosEthosLogos 

there is something wrong with your kernel source. You are also compiling against 5.8.11, while that should work just fine with the patch, it should work the same without. The patch only adjusts some API changes for the 5.9 kernel.

**Comment by bnavigator** [comment]
> I also tried the code block in the comments of https://aur.archlinux.org/packages/displaylink but even the first line `sudo pacman -R evdi-git #used -Rns` does not seem to work, saying that `evdi-git` is not found.

If you haven't installed evdi-git you don't need to uninstall it.

**Comment by PathosEthosLogos** [comment]
Yeah I tried installing `evdi-git` as well, but that didn't work.

I think I'll just install 5.9 kernel. Hopefully other things won't break and hopefully this will work.

**Comment by bnavigator** [comment]
@PathosEthosLogos, do you understand the commands you are trying to execute? Because if not, please stay away from any AUR package, because [you are exposing yourself to a big security risk](https://wiki.archlinux.org/index.php/Arch_User_Repository).

@sickcodes' code block does this:

- `sudo pacman -R evdi-git` remove a previously installed evdi-git. If you don't have it don't execute this line. As an Archlinux user, [you should learn how to operate `pacman`](https://wiki.archlinux.org/index.php/General_recommendations#pacman).
- `yay --getpkgbuild evdi-git` Get the build recipe.
- `sed -i -e s/DisplayLink/sickcodes/g PKGBUILD` replace the source repository from DisplayLinkt to @sickcodes' one. Big security risk if you can't trust @sickcodes and did not check the current contents of @sickcodes' master branch. (Note for the intermediate user: Better apply the patch from #228, which you checked yourself.)
- `makepkg -s` build the recipe. Basically the Archlinux version of your failed `make` tries above. It will make sure you have dkms installed. Also make sure to install the correct `linux-headers` for your kernel (Listed as optional requirements with `pacman -Qi dkms`).

Note: I do not say, you can't trust @sickcodes, but he is a random person on the internet as anyone else here is.

**Comment by abucodonosor** [comment]
@bnavigator 

Well, you are right but one can compare the fork and the original online even, right now no difference.

@sickcodes 

I think you forgot to push something out in your fork? :)

**Comment by bnavigator** [comment]
> @bnavigator
> 
> Well, you are right but one can compare the fork and the original online even, right now no difference.

Yes, of course.  https://github.com/DisplayLink/evdi/compare/master...sickcodes:master  is the same as just examining https://github.com/DisplayLink/evdi/pull/228/files. But if you just replace the repo in the PKGBUILD and don't look at anything, this is dangerous.

> 
> @sickcodes
> 
> I think you forgot to push something out in your fork? :)

?
It's all there, otherwise no PR would have been possible.

**Comment by sickcodes** [comment]
I forgot to insert the malware 🤪

**Comment by PathosEthosLogos** [comment]
Haha yeah, I knew all except `sed`.

But it seems like updating to 5.9 kernel didn't fix it. Same 'Error 2' with some additions.

```
cat: /etc/redhat-release: No such file or directory
CFLAGS="-Werror -Wextra -Wall -Wmissing-prototypes -Wstrict-prototypes -Wno-error=missing-field-initializers" make -C module 
make -C /lib/modules/5.9.0-1-MANJARO/build M=$PWD
make[2]: Entering directory '/usr/lib/modules/5.9.0-1-MANJARO/build'
  AR      ~/evdi/module/built-in.a
  CC [M]  ~/evdi/module/evdi_drv.o
/home/pathos/evdi/module/evdi_drv.c:94:3: error: 'struct drm_driver' has no member named 'gem_free_object'; did you mean 'gem_open_object'?
   94 |  .gem_free_object = evdi_gem_free_object,
      |   ^~~~~~~~~~~~~~~
      |   gem_open_object
/home/pathos/evdi/module/evdi_drv.c:94:21: error: initialization of 'void (*)(struct drm_device *)' from incompatible pointer type 'void (*)(struct drm_gem_object *)' [-Werror=incompatible-pointer-types]
   94 |  .gem_free_object = evdi_gem_free_object,
      |                     ^~~~~~~~~~~~~~~~~~~~
/home/pathos/evdi/module/evdi_drv.c:94:21: note: (near initialization for 'driver.lastclose')
/home/pathos/evdi/module/evdi_drv.c: In function 'evdi_platform_probe':
/home/pathos/evdi/module/evdi_drv.c:175:20: error: 'struct dev_archdata' has no member named 'iommu'
  175 |  pdev->dev.archdata.iommu = INTEL_IOMMU_DUMMY_DOMAIN;
      |                    ^
cc1: all warnings being treated as errors
make[3]: *** [scripts/Makefile.build:283: /home/pathos/evdi/module/evdi_drv.o] Error 1
make[2]: Leaving directory '/usr/lib/modules/5.9.0-1-MANJARO/build'
make[1]: *** [Makefile:71: module] Error 2
make: *** [Makefile:13: all] Error 2
```

**Comment by sickcodes** [comment]
You haven't cherry-picked @abucodonosor's changes yet you're building the DisplayLink/master

**Comment by abucodonosor** [comment]
> I forgot to insert the malware

No, you forgot devel is the default branch. so one need to clone your fork and checkout master :)

**Comment by abucodonosor** [comment]
@PathosEthosLogos 

That error is now different you are missing my patch :)

**Comment by sickcodes** [comment]
Yeah you're right, need to checkout master first. The AUR PKGBUILD from @bnavigator checks out master so I am missing that in my above comment.

I was supposed to commit to devel tag 1.7.0?

**Comment by bnavigator** [comment]
> I was supposed to commit to devel tag 1.7.0?

No master is correct. There is no 1.7.0 branch.

**Comment by bnavigator** [comment]
> The AUR PKGBUILD from @bnavigator checks out master so I am missing that in my above comment.

Its not mine. Check https://aur.archlinux.org/packages/evdi-git/ for a list of maintainers. I am preparing a evdi-1.7 package with your patch applied though.

**Comment by PathosEthosLogos** [comment]
Ah oops -- now cherry picked, but then:

```
cat: /etc/redhat-release: No such file or directory
make -C module install
make[1]: Entering directory '~/evdi/module'
make -C /lib/modules/5.9.0-1-MANJARO/build M=$PWD INSTALL_MOD_PATH= INSTALL_MOD_DIR=/kernel/drivers/gpu/drm/evdi modules_install
make[2]: Entering directory '/usr/lib/modules/5.9.0-1-MANJARO/build'
  INSTALL ~/evdi/module/evdi.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: crypto/bio/bss_file.c:69
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: crypto/bio/bss_file.c:76
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  5.9.0-1-MANJARO
```

Now SSL error... why?

**Comment by bnavigator** [comment]
@PathosEthosLogos building on Arch/Manjaro without a PKGBUILD requires you to prepare everything yourself. Adjust evdi-git yourself according to the instructions or wait on the evdi-1.7 package.

**Comment by abucodonosor** [comment]
@PathosEthosLogos 

probably because Manjaro wants to sign the modules by default if they don't enforce that you can ignore the SSL warnings/errors.

However, I don't have any idea what Arch/Manjaro is doing but I guess @bnavigator and @sickcodes can help :)

**Comment by sickcodes** [comment]
> > The AUR PKGBUILD from @bnavigator checks out master so I am missing that in my above comment.
> 
> 
> 
> Its not mine. Check https://aur.archlinux.org/packages/evdi-git/ for a list of maintainers. I am preparing a evdi-1.7 package with your patch applied though.

Good idea! It's @abucodonosor patch btw, I'm just the cherry-picking backporter 😆

**Comment by sickcodes** [comment]
@bnavigator Great! You gonna change it as the requirement on DisplayLink too?

**Comment by bnavigator** [comment]
> @bnavigator Great! You gonna change it as the requirement on DisplayLink too?

You mean to explicitely require the `evdi-1.7` package? I would rather not. `evdi-git` or `evdi` could get updated and provide the patch too.

**Comment by dummys** [comment]
hey guys,

Thanks for the hard work. On my Arch linux box with latest kernel in the package, I still can't restart lightdm when displaylink is started.

when I connect displaylink, I can switch to the screen, whitout problem, but when restarting lightdm, no more screen, and huge crash in the journalctl. I tried connecting usb before boot, same problem. I tried switching back to the laptop screen before restarting lightdm, same problem, lightdm wont start anymore. My kernel version is: 5.8.14-arch1-1

Do you have such problem ?

**Comment by bnavigator** [comment]
> On my Arch linux box with latest kernel in the package, 

:zap: 

> My kernel version is: 5.8.14-arch1-1 and evdi 1.7

I thought we are talking about kernel 5.9 now? Did you restart yet?

**Comment by robotard** [comment]
Now, I know that my above post was opened as Kernel and DL versions, but I'm a Groovy Gorilla Ubuntu guy, so a lot of the commands don't apply too well for me... 

Is there a version agnostic patch available, so after testing on 5.9 I can then still boot back into 5.8.14 and use my extra screen?

Have given my DL Logger output above...

**Comment by robotard** [comment]
Also, did we not begin here with a patch file rather than a switch of repository for EVDI? 

Now I've not been playing around with DisplayLink for a while, but I remember that @AdnanHodzic brought together a bunch of patches (https://github.com/AdnanHodzic/) prior to when the current DisplayLink build did not play nicely with Ubuntu... It worked very well, and was back then superceded by a new official DisplayLink Build...

There were issues when patching relating to Kernel versions breaking bits and pieces, so can't see why we couldn't put together a universal patch, and then after testing, get that pushed into the actual EVDI repo (avoiding other repos)?

I've raised this thread across there discussing the original patch as the item of work, as they have a great team together...
https://github.com/AdnanHodzic/displaylink-debian/issues/474

**Comment by abucodonosor** [comment]
@robotard 

I have no idea what do you mean with a 'universal patch'.
The patch and the PR https://github.com/DisplayLink/evdi/pull/227 is against official evdi code.

If you mean 'distribution' packages/packaging with the patch/PR this is up2 whoever maintains the package.

**Comment by bnavigator** [comment]
> Is there a version agnostic patch available, so after testing on 5.9 I can then still boot back into 5.8.14 and use my extra screen?

The evdi kernel module has to be compiled for every kernel version. But you can also compile the module for 5.8, because #227 and #228 use preprocessor macros like `#if KERNEL_VERSION(5, 9, 0) <= LINUX_VERSION_CODE`.

**Comment by bnavigator** [comment]
@robotard 

(untested) instructions for Ubuntu:



1. get and unzip the DisplayLink package and extract the inner archive

        $ unzip 'DisplayLink USB Graphics Software for Ubuntu 5.3.1.zip'
        $ chmod +x displaylink-driver-5.3.1.34.run
        $ ./displaylink-driver-5.3.1.34.run --noexec --keep

2. get evdi 1.7 and patch it with #228 or clone directly

         $ wget https://github.com/DisplayLink/evdi/archive/v1.7.0.tar.gz
         $ tar xf v1.7.0.tar.gz
         $ pushd evdi-1.7.0
         $ wget https://github.com/DisplayLink/evdi/pull/228.patch
         $ patch -p1 < 228.patch
         $ popd

   or 

         $ git clone https://github.com/DisplayLink/evdi.git evdi-1.7.0
         $ pushd evdi-1.7.0
         $ git fetch origin pull/228/head
         $ git checkout -b pr228 FETCH_HEAD
         $ popd

3. replace evdi

        $ rm displaylink-driver-5.3.1.34/evdi.tar.gz
        $ pushd evdi-1.7.0
        $ tar cf evdi.tar.gz *
        $ cp evdi.tar.gz ../displaylink-driver-5.3.1.34/
        $ popd

4. install displaylink

        $ cd displaylink-driver-5.3.1.34
        $ sudo ./displaylink-installer.sh install

**Comment by robotard** [comment]
Thanks for further instructions. These seem more rounded than in the earlier post that I had replied to. 

Will let you know the outcome...

**Comment by sickcodes** [comment]
>   $ wget https://github.com/DisplayLink/evdi/pull/228.patch

Woahhhh did not know you could download PR's as patches, that's awesome

**Comment by robotard** [comment]
I did not... That's wicked sick!

Thanks bro!

**Comment by robotard** [comment]
Is there a way to get around the "Xorg is running" reboot loop?

**Comment by robotard** [comment]
Ok, booted without GDM and installed... Still no joy... Here are my
DLSupport logs...

**Comment by robotard** [comment]
Ah, just noticed this:
patch -pl < 228.patch
patch: **** strip count l is not a number

**Comment by robotard** [comment]
ignore... used i instead of 1...

Doesn't appear to want to play ball... See above logs

>

**Comment by sickcodes** [comment]
@robotard try removing this file from udev, it fixes Xorg crash for me.


Remove the udev rule.

Disable DisplayLink service

```bash

sudo modprobe evdi
sudo systemctl disable displaylink.service
# removing 99-displaylink.rules is necessary for me
sudo mv sudo /etc/udev/rules.d/99-displaylink.rules .
reboot
```

And then start X, xfce etc.

When you're inside the desktop run:

```bash
sudo systemctl start displaylink
```


This is necessary for me on Xorg latest

**Comment by bnavigator** [comment]
> sudo mv sudo /etc/udev/rules.d/99-displaylink.rules .

Looks wrong. Use

        sudo rm /etc/udev/rules.d/99-displaylink.rules

or

        sudo mv /etc/udev/rules.d/99-displaylink.rules /root/99-displaylink.rules.bak

**Comment by sickcodes** [comment]
> > sudo mv sudo /etc/udev/rules.d/99-displaylink.rules .
> 
> 
> 
> Looks wrong. Use
> 
> 
> 
>         sudo rm /etc/udev/rules.d/99-displaylink.rules
> 
> 
> 
> or
> 
> 
> 
>         sudo mv /etc/udev/rules.d/99-displaylink.rules /root/99-displaylink.rules.bak
> 
> 
> 
>  
> 
> 

Same effect really, I moved it to current directory to have a look at it 🙃

**Comment by bnavigator** [comment]
`sudo mv sudo` is one `sudo` too much. Given @robotard confuses `1`s with `l`s you have to be careful. You could tell him to execute `sudo rm -rf /` and he probably would try... :angry:

**Comment by bnavigator** [comment]
> Here are my
DLSupport logs...

I see no logs. As I said, I did not test the instructions. Are you sure the patched evdi is being compiled and installed?

Also, did you consult https://support.displaylink.com/knowledgebase/topics/103927-troubleshooting-ubuntu ?

**Comment by abucodonosor** [comment]
@bnavigator @sickcodes 

This is not the place to teach people how to do basic packaging tasks for random distributions.

This is getting ridiculous, seriously.

**Comment by robotard** [comment]
Oof. Before trying to call others a tool, perhaps check that your very own
DLSupportTool functions correctly.

You are hardly being useful with this necessity to have the biggest pair
here!

If you have someone willing to test your fixes, then stop being a dick
about it! Given that I had to apparently boot into a TTY session to avoid
hitting XOrg, then a small typo between retyping from my phone to my laptop
should be f*#cking acceptable.

Logs attached for you again Ben.

**Comment by robotard** [comment]
Thanks for the helpful advice sickcodes...

I don't appear to have a rules file under udev/rules.d:

/etc/udev/rules.d$ ls
70-snap.snapd.rules  70-snap.snap-store.rules

**Comment by bnavigator** [comment]
People have repeatedly told you, there are no logs attached. Please check the GitHub issue page and clean your posts. The e-mail reply feature of Github apparently does not support attachments.

The fact that you don't have a udev rule, indicates you did either not run displaylink-installer.sh properly or you messed with your installation afterwards, by entering commands, which you don't understand.

In any case, my patience is almost exhausted. Perhaps you should try to fix your system with the help of people over at the Ubuntu user forums instead of insulting people here. Maybe @abucodonosor is right, despite Ubuntu being the only "officially" supported distribution by DisplayLink.

**Comment by bnavigator** [comment]
BTW, the official displaylink-installer.sh installs the systemd service as `displaylink-driver.service`. I am not sure what disabling and manually starting the service achieves (I do not need such a workaround on my system), but here is @sickcodes' code adjusted for that:

> Disable DisplayLink service
> 
> ```shell
> sudo modprobe evdi
> sudo systemctl disable displaylink-driver.service
> # removing 99-displaylink.rules is necessary for me
> sudo mv /etc/udev/rules.d/99-displaylink.rules /root/99-displaylink.rules.bak
> reboot
> ```
> 
> And then start X, xfce etc.
> 
> When you're inside the desktop run:
> 
> ```shell
> sudo systemctl start displaylink-driver
> ```

**Comment by sickcodes** [comment]
Here's my 2¢ for anyone lurking:

DisplayLink only works on kernel <=5.8 kernel with evdi 1.7.

Evdi 1.7 is also known as evdi master because evdi 1.8 doesn't work for anyone yet, which is why there are 2 pull requests: one to fix evdi 1.8 by @abucodonosor and one to fix evdi 1.8, cherry picked by me from @abucodonosor.

If you want test your DisplayLink device to work on Linux Kernel >=5.9 then you need to cherry pick @abucodonosor's perfect fix onto the master branch as seen in:
https://github.com/DisplayLink/evdi/pull/227

But the kicker is, evdi MUST be on 1.7, hence:
https://github.com/DisplayLink/evdi/pull/228

To test @abucodonosor's fix, Ubuntu/Debian/Arch/Manjaro/Fedora/RHEL/CentOS/Pop users would only need to force install DisplayLink, then manually install evdi 1.7 from my PR.

Xorg 1.20.9 MAY crash without deleting the udev rule as specified above.

In which case, try removing the udev rule as indicated above and disabling DisplayLink systemd service, and adding DisplayLink service to start AFTER your desktop loads.

Arch users should use https://aur.archlinux.org/packages/evdi-1.7/ from @bnavigator.

I think DisplayLink may benefit from a PPA or a custom APT sources repository (like Spotify sources https://www.spotify.com/us/download/linux/) instead of a shell script installer.

**Comment by sickcodes** [comment]
Nobody can test 1.8 devel branch, they can only build it, hence why we are all hacking each respective distro's installer to test @abucodonosor fantastic fix on 1.7

**Comment by bnavigator** [comment]
> To test @abucodonosor's fix, Ubuntu/Debian/Arch/Manjaro/Fedora/RHEL/CentOS/Pop users would only need to force install DisplayLink, then manually install evdi 1.7 from my PR

But that installs the unpatched evdi first. How are you gonna make sure users correctly replace the evdi afterwards?

Not to mention that DKMS has to recompile the evdi kernel module.

> I think DisplayLink may benefit from a PPA or a custom APT sources repository (like Spotify sources https://www.spotify.com/us/download/linux/) instead of a shell script installer.

.. which also would be outdated until some developer there would bother to merge the patches and release a new package.

DisplayLink should really make it possible for distributions to include a proper package into their official repositories. But this requires DisplayLinkManager to be open-sourced.

**Comment by bnavigator** [comment]
> In which case, try removing the udev rule as indicated above and disabling DisplayLink systemd service, and adding DisplayLink service to start AFTER your desktop loads.

Depends on your dm. The original systemd service unit has `After=display-manager.service` to take car of that. If you start X differently, you have to adjust, obviously.

**Comment by bnavigator** [comment]
@robotard In reply to your logs in https://github.com/DisplayLink/evdi/pull/228#issuecomment-712149736

machine_info.txt
> EVDI kernel module version: None

What is the output of `sudo dkms list`? I guess `lsmod | grep evdi` is empty? Likely, you did not compile the kernel module. Or rather DKMS did not do it. Did you check the output during the installer for relevant information? Did you finally consult https://support.displaylink.com/knowledgebase/topics/103927-troubleshooting-ubuntu and also https://github.com/AdnanHodzic/displaylink-debian/blob/master/post-install-guide.md?

And your dmesg.txt is empty, probably because you didn't run with enough privileges.

**Comment by bnavigator** [comment]
Ubuntu related problems should probably go here https://www.displaylink.org/forum/showthread.php?t=67372 or any other suitable [Ubuntu support forum](https://discourse.ubuntu.com/t/community-support/709)

**Comment by robotard** [comment]
Hi Ben,

Sorry for the late response, I had a nasty accident recently that's put me
out for over a week... From looking back through terminal, it looks as
though I didn't sudo the DLSupportTool, so have reattached here...

I've tried the following as above
sudo dkms list
Usage: /usr/sbin/dkms [action] [options]
  [action]  = { add | remove | build | install | uninstall | match |
autoinstall | mkdriverdisk |
                mktarball | ldtarball | mkrpm | mkkmp | mkdeb | mkdsc |
mkbmdeb | status }
  [options] = [-m module] [-v module-version] [-k kernel-version] [-a arch]
              [-d distro] [-c dkms.conf-location] [-q] [--force]
[--force-version-override] [--all]
              [--templatekernel=kernel]
[--directive='cli-directive=cli-value']
              [--config=kernel-.config-location]
[--archive=tarball-location]
              [--kernelsourcedir=source-location] [--no-prepare-kernel]
[--no-initrd]
              [--binaries-only] [--source-only] [-r release (SuSE)]
[--verbose]
              [--size] [--spec=specfile] [--media=floppy|iso|tar]
[--legacy-postinst=0|1]
              [--no-depmod] [-j number] [--version]
Error! No action was specified.

You were also correct with lsmod | grep evdi running correctly but
returning nothing...

Not going to lie, my injury entailed a cracked rib, and a blow to the head,
so if you may kindly run me through the steps that are required to get
latest DisplayLink, evdi, then exchange the evdi in once more, I'd be
extremely grateful, and also very happy to test...

Thanks for all the help so far... (some things, like my injury, are a
little wakeup call to be kind)

**Comment by bnavigator** [comment]
> I had a nasty accident recently that's put me out for over a week...

Sorry to hear that. Please focus on your recovery rather than on a silly experimental software problem on the internet.

> From looking back through terminal, it looks as though I didn't sudo the DLSupportTool, so have reattached here... 

You maybe did that in your mail client, but they do not appear on the Github page and the attachment is not sent to anybody. Yet Again. But it will be useless anyway until you resolve the already identified issues.

> I've tried the following as above
> sudo dkms list
> ...
> Error! No action was specified.

Again, please check the Github issue page directly and stop replying by e-mail. I had noticed my mistake and corrected my comment immediately after I posted it. You likely did not get that by mail notification. The correct command is `dkms status`

> You were also correct with lsmod | grep evdi running correctly but returning nothing... 

So the install or module load was not successful.

> Not going to lie, my injury entailed a cracked rib, and a blow to the head, so if you may kindly run me through the steps that are required to get latest DisplayLink, evdi, then exchange the evdi in once more, I'd be extremely grateful, and also very happy to test... Thanks for all the help so far..

Please read the comments in this thread directly on the Github page. Some posts were updated and should contain what you need to get started. For everything else, please refer to the linked forums. The Github issue page is not the right place for this. The patch has been tested by enough people and has been merged. We are just waiting on the release by the Displaylink guys.

**Comment by robotard** [comment]
sudo dkms status
bbswitch, 0.8, 5.8.0-23-generic, x86_64: installed
bbswitch, 0.8, 5.8.0-25-generic, x86_64: installed
bbswitch, 0.8, 5.8.12-050812-generic, x86_64: installed
bbswitch, 0.8, 5.8.13-050813-generic, x86_64: installed
bbswitch, 0.8, 5.8.14-050814-generic, x86_64: installed
bbswitch, 0.8, 5.8.16-050816-generic, x86_64: installed
bbswitch, 0.8, 5.9.0-050900-generic, x86_64: installed
evdi, 1.7.0, 5.9.0-050900-generic, x86_64: installed
nvidia, 455.28, 5.8.0-23-generic, x86_64: installed
nvidia, 455.28, 5.8.0-25-generic, x86_64: installed
nvidia, 455.28, 5.8.14-050814-generic, x86_64: installed
nvidia, 455.28, 5.8.16-050816-generic, x86_64: installed
nvidia, 455.28, 5.9.0-050900-generic, x86_64: installed

Pulled all as described above, and replying to you directly from GitHub....

FWIW, I had to `sudo ./displaylink-installer.sh uninstall` then `sudo ./displaylink-installer.sh install` (see attached).

Also, I'm not sure I follow what you mean regarding the other issues (227 + 228)?

Am I missing the fleetingly obvious? Seemed to build into DKMS ok... ?

[DisplayLink Un-Inst.txt](https://github.com/DisplayLink/evdi/files/5448921/DisplayLink.Un-Inst.txt)
[DLSupportTool_Output_2020-10-28T01:08:54.479783.zip](https://github.com/DisplayLink/evdi/files/5448924/DLSupportTool_Output_2020-10-28T01.08.54.479783.zip)

**Comment by joren485** [comment]
@robotard Could you please move your support questions to the [support forum](https://www.displaylink.org/forum/forumdisplay.php?f=29)?

People are following this issue to stay up to date with the status of this problem.

**Comment by bnavigator** [comment]
This looks much better now.

There is no proof, that you patched the evdi module, but if it is the case, then you can seek help with these logs on the mentioned forums. You can also post a bugreport on https://bugs.launchpad.net/ubuntu/

Please don't use this issue page here. Your problems are not directly connected with Kernel 5.9

**Comment by robotard** [comment]
Thanks Ben, but all was well and good with 5.8?

It’s only since 5.9 I’ve had issues, and thus applied the patches that you guys are providing. Unfortunately do not seem to have fixed evdi since it appears to be loading now and on 5.9. 

I’m more than happy to keep testing and offer you relevant logs, but this does seem to revolve around the kernel change directly.

Thanks,

R

**Comment by displaylink-dkurek** [comment]
OK, so I've just pushed new branch `v1.7.x` which is basically `v1.7.0` with cherry-picked changes for kernel 5.9 and 5.10.
Hope it is fine :)

**Comment by displaylink-dkurek** [comment]
OK, with all of this i will close the issue. Thanks all for your involvement and comments :)

**Comment by mknw** [comment]
It took me a couple hours to understand how to apply the latest changes to DisplayLink for Ubuntu.
Since this seems to be the main thread of reference for incompatibility issues with kernel versions 5.9/10, I think it makes sense to paste here the instructions. I believe the issue isn't about a specific distro, although Arch is here mentioned more often.

1. Download the DisplayLink driver from [the official download page](https://www.displaylink.com/downloads/ubuntu). Then run the following commands:

    unzip 'DisplayLink USB Graphics Software for Ubuntu 5.3.1.zip'
    chmod +x displaylink-driver-5.3.1.34.run
    ./displaylink-driver-5.3.1.34.run --noexec --keep

2. Get the updated evdi version by typing:

    git clone https://github.com/DisplayLink/evdi.git
    cd evdi
    git checkout v1.7.x
    tar cf evdi.tar.gz *
    cp evdi.tar.gz ../displaylink-driver-5.3.1.34

3. Install displaylink:

    cd ../displaylink-driver-5.3.1.34
    sudo ./displaylink-installer.sh install


This has also been reported [here](https://displaylink.org/forum/showpost.php?p=91259&postcount=19).
If this issue isn't the right place to share this (sorry) please let me know where I can share them. Happy new year!
