### ISSUE TITLE
Suggestion for issue template

### ISSUE THREAD

**Issue by Barabazs** [DisplayLink/evdi#226]
This is more of a suggestion than an issue. While browsing the issues  I realised a lot of users submit the default content of the issue  template without cleaning up the post.
 This could be avoided by using comment tags in the default template  which hides text that is only useful to the user submitting the issue.

A minor adjustment that will drastically improve readability for the collaborators.

As an example I include my suggestion in a code block and as a regular post so you can see the difference:

  * [x] Are you using the latest driver?

  * [x] Are you using the latest EVDI version?

  * [x] If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?

  * [x] Is this issue related to evdi/kernel?
 

  * Linux distribution and its version :
  * Linux kernel version: 
  * Xorg version (if used): 
  * Desktop environment in use:

```
<!-- Initially please make sure the problem hasn't been already addressed: -->
  * [ ] Are you using the latest driver?
<!--  (https://www.displaylink.com/downloads/ubuntu) -->
  * [ ] Are you using the latest EVDI version?
<!--  (https://github.com/DisplayLink/evdi/releases) -->
  * [ ] If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
<!--     (https://support.displaylink.com/knowledgebase/topics/103927-troubleshooting-ubuntu) -->
  * [ ] Is this issue related to evdi/kernel?
 <!--    (if it is rather connected to DisplayLinkManager please take a look at support
    https://support.displaylink.com or forum https://www.displaylink.org/forum/) -->

<!--
Some information for baseline would help a lot: -->
  * Linux distribution and its version :
  * Linux kernel version: 
  * Xorg version (if used): 
  * Desktop environment in use:

<!-- Please provide good title for the issue and description.
If you can give us logs they will be welcome but please don't paste long listings
as they will make it hard to read the thread, instead you can use other services
for sharing raw text like pastebin or gist.
Also anything that may help to understand the problem will be appreciated
(configuration files, screenshots, photos, video capturing the problem).

Thanks!
-->
```

**Comment by displaylink-dkurek** [comment]
Hi @Barabazs,

thanks for the suggestion. I've been thinking about improving the template.
It's great to see that others also think so ;)

**Comment by Robert-L-Turner** [comment]
Very constructive comment indeed @Barabazs!  Thank you!

**Comment by displaylink-dkurek** [comment]
Hi @Barabazs,
after a while the updated version is finally live. Thanks for great suggestion :+1: 

Closing :smile:
