### ISSUE TITLE
can't extract any version of the displayLink drivers on Arch linux

### ISSUE THREAD

**Issue by dummys** [DisplayLink/evdi#229]
Hi,

I'm still trying to install this driver but definitely can't extract it under arch linux. Also tried the old version, same problem.

-> $ ./displaylink-driver-5.3.1.34.run --target test --noexec 
Verifying archive integrity...  100%  Error in MD5 checksums: print mode:  md5sum <file> <file
check mode:  md5sum -c <checksum is different from 7ba0e635b6284f0651177ec1e63381d0

When I check your script, it appears that you are using md5sum to check against binary data from stdin, which I can't reproduce. The only way getting your stuff working is with "md5" and not md5sum. But then after patching this, I still get error in extracting with gzip.

I know it is for ubuntu, but it should extract correctly on all linux distro.

**Comment by bnavigator** [comment]
To quote myself from the AUR page:

Looks like your md5sum command is broken.

```
Here is what it should look like:

% export LC_ALL=C
% which md5sum
/usr/bin/md5sum
% pacman -Qo /usr/bin/md5sum
/usr/bin/md5sum is owned by coreutils 8.32-1
% md5sum --version
md5sum (GNU coreutils) 8.32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Ulrich Drepper, Scott Miller, and David Madore.
%
```

**Comment by bnavigator** [comment]
Looking into the script: you could just set `SETUP_NOCHECK=1`.

Or get to the root of this. What's your output of

```sh
env

OLD_PATH="$PATH"
PATH=${GUESS_MD5_PATH:-"$OLD_PATH:/bin:/usr/bin:/sbin:/usr/local/ssl/bin:/usr/local/bin:/opt/openssl/bin"}
MD5_ARG=""
MD5_PATH=`exec <&- 2>&-; which md5sum || command -v md5sum || type md5sum`
echo "0: $MD5_PATH"
test -x "$MD5_PATH" || MD5_PATH=`exec <&- 2>&-; which md5 || command -v md5 || type md5`
echo "1: $MD5_PATH"
test -x "$MD5_PATH" || MD5_PATH=`exec <&- 2>&-; which digest || command -v digest || type digest`
echo "2: $MD5_PATH"
PATH="$OLD_PATH"
```
?

**Comment by dummys** [comment]
I think my md5sum is working.
> pacman -Qo /usr/bin/md5sum

```bash
pacman -Qo /usr/bin/md5sum
/usr/bin/md5sum is owned by coreutils 8.32-1
```
```bash
md5sum --version
md5sum (GNU coreutils) 8.32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Ulrich Drepper, Scott Miller, and David Madore.
```
Here is the result of your test:
```bash
env
SHELL=/bin/bash
WINDOWID=20971531
COLORTERM=truecolor
GDK_DPI_SCALE=0
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
LC_ADDRESS=fr_CH.UTF-8
LC_NAME=fr_CH.UTF-8
GRADLE_HOME=/usr/share/java/gradle
DESKTOP_SESSION=awesome
LC_MONETARY=fr_CH.UTF-8
EDITOR=/usr/bin/vim
GTK_MODULES=canberra-gtk-module
ANDROID_NDK=/opt/android-ndk
XDG_SEAT=seat0
XDG_SESSION_DESKTOP=awesome
XDG_SESSION_TYPE=x11
XAUTHORITY=/home/user/.Xauthority
DESKTOP_STARTUP_ID=awesome/kitty/918-28-user_TIME842238358
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/user
MOTD_SHOWN=pam
HOME=/home/user
AUTOJUMP_ERROR_PATH=/home/user/.local/share/autojump/errors.log
LC_PAPER=fr_CH.UTF-8
LANG=en_US.UTF-8
KITTY_WINDOW_ID=1
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
ANDROID_NDK_HOME=/opt/android-ndk
XDG_SESSION_CLASS=user
ANDROID_HOME=/opt/android-sdk
TERMINFO=/usr/lib/kitty/terminfo
TERM=xterm-kitty
LC_IDENTIFICATION=fr_CH.UTF-8
LESSOPEN=|/usr/bin/lesspipe.sh %s
USER=user
AUTOJUMP_SOURCED=1
DISPLAY=:0
SHLVL=1
LC_TELEPHONE=fr_CH.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_MEASUREMENT=fr_CH.UTF-8
XDG_VTNR=7
XDG_SESSION_ID=2
MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
LC_CTYPE=fr_CH.UTF-8
XDG_RUNTIME_DIR=/run/user/1000
LC_TIME=fr_CH.UTF-8
QT_AUTO_SCREEN_SCALE_FACTOR=1
LC_COLLATE=fr_CH.UTF-8
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/android-ndk:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
GDK_SCALE=1
GDMSESSION=awesome
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
HG=/usr/bin/hg
MAIL=/var/spool/mail/user
LC_NUMERIC=fr_CH.UTF-8
_=/usr/bin/env

OLD_PATH="$PATH"
PATH=${GUESS_MD5_PATH:-"$OLD_PATH:/bin:/usr/bin:/sbin:/usr/local/ssl/bin:/usr/local/bin:/opt/openssl/bin"}
MD5_ARG=""
MD5_PATH=`exec <&- 2>&-; which md5sum || command -v md5sum || type md5sum`
echo "0: $MD5_PATH"
0: /usr/bin/md5sum
test -x "$MD5_PATH" || MD5_PATH=`exec <&- 2>&-; which md5 || command -v md5 || type md5`
echo "1: $MD5_PATH"
1: /usr/bin/md5sum
test -x "$MD5_PATH" || MD5_PATH=`exec <&- 2>&-; which digest || command -v digest || type digest`
echo "2: $MD5_PATH"
2: /usr/bin/md5sum
```

**Comment by dummys** [comment]
ok I think you are right, my md5sum is broken because on another computer I can do it correctly. Do you have an idea what can make this probem on my other arch linux box ? both box has kitty as termina and fish as shell.

**Comment by bnavigator** [comment]
> Error in MD5 checksums: **print mode: md5sum <file
check mode: md5sum -c <checksum** is different from 7ba0e635b6284f0651177ec1e63381d0

The bold part is the result of a failed `md5sum` call fed with the binary data in `displaylink-driver-5.3.1.34.run`. But that string does not appear in the coreutils' md5sum help text. Is `/bin/sh` a custom shell which brings its own `md5sum` command? Do you execute `displaylink-driver-5.3.1.34.run` with a nonstandard shell despite the /bin/sh shebang? I do not know much about fish.

You could edit `displaylink-driver-5.3.1.34.run` and find out what the actual call including arguments looks like. Between line 187 and 188  insert
```sh
echo "$MD5_PATH $MD5_ARG"
```
and work your way backwards from there.

**Comment by dummys** [comment]
yes I tried all this already. It's where I discovered that when running "cat /bin/ls | md5sum" was giving nothing. Then I tried just for test to remove in the script the `which md5sum` part and then I get that gzip stuff is not right. Now that I have a computer where the stuff is working I will try to see what different between both. Fish shell is very nice but it is not posix compliant, so perhaps that's why . Will investigate and keep you posted.

As for the 5.9 kernel patch, I will upgrade my Arch tonight to move from 5.8 to 5.9 and test again, keep you posted on lightdm story. I would be very happy to help you debug this issue, but I think I need to have somehow my kernel is a debugging version or something ? I never debugged my kernel in linux, but I would be vbery happy to take my hand on.

**Comment by bnavigator** [comment]
No need to debug. The patch is working with 5.9.

**Comment by bnavigator** [comment]
> Fish shell is very nice but it is not posix compliant, so perhaps that's why

Bu it should still adhere to the shebang and execute the installer with `/bin/sh`

**Comment by dummys** [comment]
> No need to debug. The patch is working with 5.9.

even when reluanching login manager ?

**Comment by dummys** [comment]
> > Fish shell is very nice but it is not posix compliant, so perhaps that's why
> 
> Bu it should still adhere to the shebang and execute the installer with `/bin/sh`

agreed. In fact my way of calling fish is in `.bashrc` with `exec fish`

**Comment by bnavigator** [comment]
> even when reluanching login manager ? so do you think my problem comes only because of kernel 5.8.x ?

No, the lightdm crash would be independent from kernel version and patch. You would have to post your crashlogs (in a separate thread, maybe in a more suitable forum). Maybe @sickcodes' advice in #225 about disabling the udev rule and starting the service manually also helps in your case.


> agreed. In fact my way of calling fish is in `.bashrc` with `exec fish`

Ooh, does that mean that even for `/bin/sh`, which is a link to `/bin/bash` you drop into fish? That is calling for trouble. I see that the Arch wiki recommends that option. Not sure if it is a wise one.

**Comment by dummys** [comment]
ỳeah I will have to test

**Comment by sickcodes** [comment]
@dummys 

You can change the default shell to fish using `chsh`

**Comment by bnavigator** [comment]
You probably meant to quote the paragraph below the one you were quoting where it talks about being called as `sh`. Probably your way of enabling fish is not interfering with the script.

Still, you have to check why you get a non-standard md5sum error message instead of the desired hash value.

**Comment by dummys** [comment]
yeah that's crazy, I don't know why... Will do more testing and keep you posted. Thanks both of you to help :D

**Comment by dummys** [comment]
found a `md5sum` binary in /usr/local/bin... weird

**Comment by dummys** [comment]
Even when removing the udev rules -> crash

**Comment by bnavigator** [comment]
Okay so you resolved the `can't extract` issue. Please close #229 and open a new issue for the crash. But first try to find out, if this is really an evdi problem, e.g whether " Error getting user list" is relevant or unrelated.

**Comment by dummys** [comment]
yep ok. But how can I debug this ? To be honest I don't know from where this crash occurs, as if I remove evdi, no more crash when restarting lightdm.

**Comment by bnavigator** [comment]
> yep ok. But how can I debug this ? To be honest I don't know from where this crash occurs, as if I remove evdi, no more crash when restarting lightdm., so should be evdi right ?

See https://wiki.archlinux.org/index.php/Core_dump and https://wiki.archlinux.org/index.php/Debug_-_Getting_Traces

**Comment by dummys** [comment]
ok thanks for advice

**Comment by sickcodes** [comment]
> yep ok. But how can I debug this ? To be honest I don't know from where this crash occurs, as if I remove evdi, no more crash when restarting lightdm., so should be evdi right ? anyway it's xorg that crash


@dummys sounds like same issue as me!


Disable DisplayLink service

```bash
sudo systemctl disable displaylink.service
# removing 99-displaylink.rules is necessary for me
sudo rm /etc/udev/rules.d/99-displaylink.rules
reboot
```

And then start X, display manager, or xfce etc.

When you're inside the desktop run:

```bash
sudo systemctl start displaylink
```


This is necessary for me on Xorg latest

**Comment by dummys** [comment]
@sickcodes it's not working in my case. I tried your solution already.

**Comment by dummys** [comment]
@sickcodes not working.

**Comment by dummys** [comment]
@sickcodes are you able to do it ?

**Comment by sickcodes** [comment]
I don't use a DM, I boot to command line and run startxfce4

**Comment by dummys** [comment]
ok I see. I retried again, without any udev rules at all, same shit. What I need to give to displaylink guy to troubleshoot the issue ?
