### ISSUE TITLE
Update evdi to 1.8 for support 5.6.xxx 5.7.xxx 5.8.xxx and 5.9.xxx Kernel line

### ISSUE THREAD

**Issue by chiddekel** [DisplayLink/evdi#233]
Update evdi to 1.8 for support latest Kernel.

**Comment by displaylink-dkurek** [comment]
EVDI already supports kernels up to 5.9. Not sure what is it about?

**Comment by chiddekel** [comment]
Sorry - page refresh and hook in to this issue list. This issue was target to this page 
 https://github.com/displaylink-rpm/displaylink-rpm

**Comment by displaylink-dkurek** [comment]
OK. Closing
