### ISSUE TITLE
Recently, it doesn't compile / work on Ubuntu 20_04

### ISSUE THREAD

**Issue by udippel** [DisplayLink/evdi#235]
Just up to date with 20_04, with the recent kernel update to 5.4.0-53-generic it broke during the automatic recompilation:

ERROR (dkms apport): binary package for evdi: 5.2.14 not found
Error! Bad return status for module build on kernel: 5.4.0-53-generic (x86_64)

uninstalled, and reinstalled 5.3.1.

Now it throws dozens of 

[   31.567621] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   31.567675] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   31.567717] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   31.567753] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected

**Comment by abucodonosor** [comment]
Well and how is this an evdi bug?

Try to report to Ubuntu evdi maintainers.

**Comment by udippel** [comment]
My excuses. As end user I have no clue on responsibilities. I'll resort to Ubuntu.

Thanks anyway,

Uwe
