### ISSUE TITLE
xrandr cannot find new providers after using nvidia-settings

### ISSUE THREAD

**Issue by xevilstar** [DisplayLink/evdi#236]
Initially please make sure the problem hasn't been already addressed:
  * [ x] Are you using the latest driver? just cloned from git
ls -la /usr/local/lib/*evdi*
lrwxrwxrwx 1 root root    12 Nov 29 09:34 /usr/local/lib/libevdi.so -> libevdi.so.0
lrwxrwxrwx 1 root root    16 Nov 29 09:34 /usr/local/lib/libevdi.so.0 -> libevdi.so.1.8.0
-rwxr-xr-x 1 root root 31976 Nov 29 09:34 /usr/local/lib/libevdi.so.1.8.0

    (https://www.displaylink.com/downloads/ubuntu)
  * [ x] Are you using the latest EVDI version?  just cloned from git
    (https://github.com/DisplayLink/evdi/releases)
  * [ x] If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website? yes and it was working previously
    (https://support.displaylink.com/knowledgebase/topics/103927-troubleshooting-ubuntu)
  * [ ] Is this issue related to evdi/kernel? dunno
    (if it is rather connected to DisplayLinkManager please take a look at support
    https://support.displaylink.com or forum https://www.displaylink.org/forum/)

Some information for baseline would help a lot:
  * Linux distribution and its version    debian bullseye
  * Linux kernel version  
uname -a
Linux zukov 5.9.0-3-amd64 #1 SMP Debian 5.9.9-1 (2020-11-19) x86_64 GNU/Linux

  * Xorg version (if used)
Xorg -version

X.Org X Server 1.20.8
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.19.0-8-amd64 x86_64 Debian
Current Operating System: Linux zukov 5.9.0-3-amd64 #1 SMP Debian 5.9.9-1 (2020-11-19) x86_64
Kernel command line: BOOT_IMAGE=/vmlinuz-5.9.0-3-amd64 root=/dev/mapper/zukov--vg-root ro btusb.enable_autosuspend=n quiet
Build Date: 31 March 2020  10:14:40AM
xorg-server 2:1.20.8-2 (https://www.debian.org/support) 
Current version of pixman: 0.36.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.

  * Desktop environment in use
gnome
Please provide good title for the issue and description.
If you can give us logs they will be welcome but please don't paste long listings
as they will make it hard to read the thread, instead you can use other services
for sharing raw text like pastebin or gist.
Also anything that may help to understand the problem will be appreciated
(configuration files, screenshots, photos, video capturing the problem).

Thanks!

I have an nvidia graphics card
I have one monitor and one tv connected to the card
I have 2 monitors connected via usb displaylink devices. 
The framebuffer shows on all monitors
xrandr cannot find the additional providers anymore

after changing the tv resolution via nvidia-settings I am unable to find all the xrandr providers and I get those errors in the dmesg 

dmesg|grep evdi
[   16.324224] evdi: loading out-of-tree module taints kernel.
[   16.324358] evdi: module verification failed: signature and/or required key missing - tainting kernel
[   16.329121] evdi: [I] Initialising logging on level 5
[   16.329122] evdi: [I] Atomic driver:yes
[   16.329148] evdi: [D] evdi_add_devices:165 Increasing device count to 2
[   16.329188] evdi: [D] evdi_crtc_init:392 drm_crtc_init: 0 p0000000054e030ed
[   16.329194] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   16.329198] evdi evdi.0: [drm] Cannot find any crtc or sizes
[   16.329203] evdi: [W] evdi_painter_send_update_ready_if_needed:659 Painter does not exist!
[   16.329530] [drm] Initialized evdi 1.8.0 20200707 for evdi.0 on minor 2
[   16.329571] evdi: [D] evdi_crtc_init:392 drm_crtc_init: 0 p00000000a29a15cd
[   16.329575] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[   16.329578] evdi evdi.1: [drm] Cannot find any crtc or sizes
[   16.329581] evdi: [W] evdi_painter_send_update_ready_if_needed:659 Painter does not exist!
[   16.329788] [drm] Initialized evdi 1.8.0 20200707 for evdi.1 on minor 3
[   63.033924] evdi: [D] evdi_driver_postclose:133 (dev=0) Process tries to close us, postclose
[   63.033928] evdi: [I] Task 1646 (Xorg.wrap) of process 1646 (Xorg.wrap)
[   63.033950] evdi: [D] evdi_driver_postclose:133 (dev=0) Process tries to close us, postclose
[   63.033952] evdi: [I] Task 1646 (Xorg.wrap) of process 1646 (Xorg.wrap)
[   65.641232] evdi: [D] evdi_driver_postclose:133 (dev=0) Process tries to close us, postclose
[   65.641233] evdi: [I] Task 1646 (Xorg) of process 1646 (Xorg)
[   65.641807] evdi: [D] evdi_driver_postclose:133 (dev=0) Process tries to close us, postclose
[   65.641808] evdi: [I] Task 1646 (Xorg) of process 1646 (Xorg)
[ 1705.916059] evdi: [D] evdi_driver_postclose:133 (dev=0) Process tries to close us, postclose
[ 1705.916061] evdi: [I] Task 15266 (Xorg.wrap) of process 15266 (Xorg.wrap)
[ 1705.916067] evdi: [D] evdi_driver_postclose:133 (dev=0) Process tries to close us, postclose
[ 1705.916067] evdi: [I] Task 15266 (Xorg.wrap) of process 15266 (Xorg.wrap)
[ 1713.156126] evdi: [D] evdi_driver_postclose:133 (dev=0) Process tries to close us, postclose
[ 1713.156128] evdi: [I] Task 15282 (Xorg.wrap) of process 15282 (Xorg.wrap)
[ 1713.156135] evdi: [D] evdi_driver_postclose:133 (dev=0) Process tries to close us, postclose
[ 1713.156135] evdi: [I] Task 15282 (Xorg.wrap) of process 15282 (Xorg.wrap)

**Comment by abucodonosor** [comment]
From what I can tell, you'll need evdi 1.7.0, 1.8.0 won't work.

**Comment by displaylink-dkurek** [comment]
@abucodonosor  may be right here. Can you try v1.7.1 - it should work with kernel 5.9.

**Comment by displaylink-dkurek** [comment]
Just created #245 to gather those problems. Hope it's title is a bit more useful for users.
Closing this one, thanks.
