### ISSUE TITLE
Release 1.7.1 generates libevdi.so.1.7.0

### ISSUE THREAD

**Issue by sbluhm** [DisplayLink/evdi#239]
Initially please make sure the problem hasn't been already addressed:
  * [X] Are you using the latest driver?
    (https://www.displaylink.com/downloads/ubuntu)
  * [X] Are you using the latest EVDI version?
    (https://github.com/DisplayLink/evdi/releases)

Some information for baseline would help a lot:
  * CentOS 8.2
  * 4.18.0-193.28.1.el8_2.x86_64

Release 1.7.1 generates libevdi.so.1.7.0.
Reproduction steps:
cd /tmp
wget https://github.com/DisplayLink/evdi/archive/v1.7.1.tar.gz
tar xf v1.7.1.tar.gz 
cd evdi-1.7.1/
make
ls library 

Expected output:
libevdi.so.1.7.1

Actual output:
libevdi.so.1.7.0

Is the actual output version intentional?

**Comment by elguero** [comment]
It is just an oversight.  Please see pull request that will help with the 1.7.2 release, #240

When kernel 5.10 is released, 1.7.2 will be tagged for us.

**Comment by displaylink-dkurek** [comment]
Ah yes, my mistake - I've forgot to change the versions.
Thanks @elguero for the PR :)
PS. there is a script `ci/set_version` which can help with the changes ;)

**Comment by elguero** [comment]
@displaylink-dkurek Well, that sure makes it easier :)  Thanks!!

Just updated the PR.

**Comment by displaylink-dkurek** [comment]
`v1.7.2` has been tagged  :)
Checked and this time the library name is correct - hope there isn't anything else I've forgot ;)

Closing.
