### ISSUE TITLE
Debian 4.5.x kernel issues

### ISSUE THREAD

**Issue by TheSin-** [DisplayLink/evdi#24]
It seems that at lest with Debian this code is not working in evdi_fb.c

```
#if KERNEL_VERSION(4, 5, 0) >= LINUX_VERSION_CODE
                                       0, ufb->obj->base.size,
#endif
```

here is the top of the dams log

```
DKMS make.log for evdi-1.0.453 for kernel 4.5.0-1-armmp (armv7l)
Wed May  4 18:28:39 UTC 2016
make KBUILD_VERBOSE=1 SUBDIRS=/var/lib/dkms/evdi/1.0.453/build SRCROOT=/var/lib/
dkms/evdi/1.0.453/build CONFIG_MODULE_SIG= -C /lib/modules/4.5.0-1-armmp/build m
modules
```

and here is the error from the log

```
/var/lib/dkms/evdi/1.0.453/build/evdi_fb.c: In function ‘evdi_user_framebuffer_d
irty’:
/var/lib/dkms/evdi/1.0.453/build/evdi_fb.c:240:4: error: too few arguments to fu
nction ‘dma_buf_begin_cpu_access’
    dma_buf_begin_cpu_access(
    ^
In file included from /var/lib/dkms/evdi/1.0.453/build/evdi_fb.c:15:0:
/usr/src/linux-headers-4.5.0-1-common/include/linux/dma-buf.h:227:5: note: decla
red here
 int dma_buf_begin_cpu_access(struct dma_buf *dma_buf, size_t start, size_t len,
     ^
/var/lib/dkms/evdi/1.0.453/build/evdi_fb.c:259:3: error: too few arguments to fu
nction ‘dma_buf_end_cpu_access’
   dma_buf_end_cpu_access(ufb->obj->base.import_attach->dmabuf,
   ^
In file included from /var/lib/dkms/evdi/1.0.453/build/evdi_fb.c:15:0:
/usr/src/linux-headers-4.5.0-1-common/include/linux/dma-buf.h:229:6: note: decla
red here
 void dma_buf_end_cpu_access(struct dma_buf *dma_buf, size_t start, size_t len,
      ^
/usr/src/linux-headers-4.5.0-1-common/scripts/Makefile.build:263: recipe for tar
get '/var/lib/dkms/evdi/1.0.453/build/evdi_fb.o' failed
```

**Comment by DawidKurek** [comment]
Hi,
thanks for reporting this issue. 
Can you please give us output of `uname -a` command?

**Comment by TheSin-** [comment]
sure sorry should have given that to ya

```
Linux localhost.bluefalls.intra 4.5.0-1-armmp #1 SMP Debian 4.5.1-1 (2016-04-14) armv7l GNU/Linux
```

**Comment by TheSin-** [comment]
Just going through the rest of the cpp for 4.5.x and I'm curious on this one too

```
#if KERNEL_VERSION(4, 5, 0) <= LINUX_VERSION_CODE
        drm_dev_set_unique(dev, dev_name(dev->dev));
#elif KERNEL_VERSION(3, 16, 0) <= LINUX_VERSION_CODE
        drm_dev_set_unique(dev, "%s", dev_name(dev->dev));
#endif
```

this means anything grater then 4.5.0 won't set a unique dev?

Maybe this was meant?

```
#if KERNEL_VERSION(3, 16, 0) <= LINUX_VERSION_CODE
        drm_dev_set_unique(dev, "%s", dev_name(dev->dev));
#else
        drm_dev_set_unique(dev, dev_name(dev->dev));
#endif
```

**Comment by TheSin-** [comment]
Also in evdi_encoder.c

```
#if KERNEL_VERSION(4, 5, 0) <= LINUX_VERSION_CODE
        ret = drm_encoder_init(dev, encoder, &evdi_enc_funcs,
                               DRM_MODE_ENCODER_TMDS, dev_name(dev->dev));
#else
        ret = drm_encoder_init(dev, encoder, &evdi_enc_funcs,
                               DRM_MODE_ENCODER_TMDS);
#endif
```

so this means the call changed in 4.5.1?  I assume you meant

```
#if KERNEL_VERSION(4, 5, 0) >= LINUX_VERSION_CODE
        ret = drm_encoder_init(dev, encoder, &evdi_enc_funcs,
                               DRM_MODE_ENCODER_TMDS, dev_name(dev->dev));
#else
        ret = drm_encoder_init(dev, encoder, &evdi_enc_funcs,
                               DRM_MODE_ENCODER_TMDS);
#endif
```

**Comment by TheSin-** [comment]
okay tested with

```
#if KERNEL_VERSION(4, 5, 0) <= LINUX_VERSION_CODE
                                       0, ufb->obj->base.size,
#endif
```

so <= instead of >= and it fixes it.

**Comment by TheSin-** [comment]
so after lots of code reading I can see this

udl is USB2 only, it checks for bInterfaceProtocol = 0, and on at least my USB3 device it's = 3, hence udl isn't finding and not making a fb for it.  evdi, does nothing at all with usb, it's a platform driver and so I can only assume DisplayLinkManager is required for attaching the driver/USB/FB together.  So in short evdi will not help me at all with DL and arm.  I'd be better off trying to mod udl which has the USB stuff in it to enable this device and see how bad things are.  Is this correct?

**Comment by displaylink-mlukaszek** [comment]
Thanks for spotting those inconsistencies with ifdefs.

USB 2.0 devices and newer USB 3.0 devices are quite different - that's why there are separate modules for driving them. The newer requires a helper application that talks to both the device and evdi.

As you noted, we currently don't release an ARM build - but this doesn't mean we wouldn't do it ever. What is your use case? There are certain requirements for evdi to work - see [this forum post](http://displaylink.org/forum/showpost.php?p=79552&postcount=4) for a bit more details. Unfortunately, I have not yet found an ARM-based platform that had a compatible GPU driver for main graphics.

**Comment by TheSin-** [comment]
hmm, could you build me 3 variants just so I can try?  arm-linux-gnueabi, arm-linux-gnueabihf, and aarch64-linux-gnu.

I'm currently working the VideoCore4 as the GPU.  DisplayLink would be 100% perfect for this project as I can now have the display near the CPU/GPU do to env variables so I need to be 15 feet away.  4 wires over 4+19 for usb and hdmi, sure would me life so much better.

Hmm I had no idea Display link used the GPU, I thought it would have it's own hence why the chip needs SDRAM, I assume that is just a buffer then?

**Comment by TheSin-** [comment]
here is the first reply from @popcornmix

> I suspect the vc4 kms driver will already handle this, as it is designed to be a standard linux DRM driver.
> It depends on what features are required.
> Currently no hardware video / camera support with Eric's driver, although they will be supported eventually (but I wouldn't expect it in the next few months).
> If that is not an issue, then that's probably the best route.
> 
> The only alternative without Eric's driver is something like: https://www.raspberrypi.org/forums/viewtopic.php?t=49707
> but that would likely need support from display link
> 
> Requests for the vc4 kms driver are best asked here:
> https://github.com/anholt/linux/issues.

**Comment by TheSin-** [comment]
here is a reply from @anholt

> I haven't worked with displaylink adapters at all, because I don't have
> any.  I don't think they'd be hard to support.

I offered to donate a USB3 display link adaptor to the cause, haven' third back but I'm getting excited, Maybe Eric and someone form the display link team could talk?  My understanding is that Eric works for Boardroom so it'd be nice to have official support for with videoCore and thus true arm support for at least the BCM-2835, 36 and 37

**Comment by TheSin-** [comment]
okay a new week, so I now have @anholt vc4 model from debian testing loaded up.

```
linux-image-4.5.0-1-armmp: /lib/modules/4.5.0-1-armmp/kernel/drivers/gpu/drm/vc4/vc4.ko
```

I then load the evdi driver.

```
evdi                   36972  0
vc4                    66648  0
drm_kms_helper        105048  2 vc4,evdi
drm                   277626  3 vc4,evdi,drm_kms_helper
```

dmesg for both of them I see

[   49.059547] evdi: [I] Initialising logging on level 5

I then plugin my USB3 Display link adaptor and see

```
[  786.938936] usb 1-1.3: USB disconnect, device number 5
[  791.490681] usb 1-1.3: new high-speed USB device number 6 using dwc2
[  791.580863] usb 1-1.3: New USB device found, idVendor=17e9, idProduct=4301
[  791.580890] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  791.580906] usb 1-1.3: Product: StarTech.com USB to HDMI
[  791.580921] usb 1-1.3: Manufacturer: DisplayLink
[  791.580935] usb 1-1.3: SerialNumber: 000001210015901
[  791.590861] usb 1-1.3: Warning! Unlikely big volume range (=511), cval->res is probably wrong.
[  791.590894] usb 1-1.3: [14] FU [StarTech.com Audio Playback Volume] ch = 6, val = -8176/0/16
```

still no /dev/fb1, so next I'm going to try and use qemu-static, and copy all the 386 libs linked in DisplayLinkManager (32bit version) and try to run that since i have no arm version.  I assume the DisplayLinkManager is what will get the ball rolling?  Is there anything else I can test, try, look for?  I'm not user trying to run the x86 binary on arm using an emulator will work at all, I'm sure an arm binary would be better, though it would be support nice if the driver could just do it instead of having to run a daemon for it.  But that aside, trying to do what i can to test this.

**Comment by DawidKurek** [comment]
@TheSin- great stuff.
Thanks for log, we are investigating it.

**EVDI** by default use `EVDI_LOGLEVEL_DEBUG`.
You can use more verbose `EVDI_LOGLEVEL_VERBOSE` by setting `loglevel` to `6`, simply run
```bash
echo 6 > /sys/devices/evdi/loglevel
```
as root :-)

Please refer to
[module/evdi_drv.c#L218](https://github.com/DisplayLink/evdi/blob/ac3f7bcc1bbbf8a71d0650a41cb76d41d2405468/module/evdi_drv.c#L218)
and
[module/evdi_debug.h#L17](https://github.com/DisplayLink/evdi/blob/ac3f7bcc1bbbf8a71d0650a41cb76d41d2405468/module/evdi_debug.h#L17)
for more details 

Also I have pushed change for `#if` that should fix compilation issue on 4.5.1 kernel.

**Comment by TheSin-** [comment]
great I'll test it today and report back on the 4.5 compile stuff.

As for verbose, I read the files so I saw that, but verbose 6 doesn't add anything of interest sadly.  5 is more thing enough to see if it's loading.  6 only adds 2 more lines and it's about the painter, so no help at this point in the process.

At this point I'm not sure I can provide anything else sadly, I'm not sure if running DisplayLinkManager in qemu-static is an issue or if DisplayLinkManager is.  I think if I had a armhf build version of it at least for now to run it and see if I get more info would be helpful, short of that I'm at the length of what I can do, and @anholt is at the same point, without DisplayLinkManager to link the kms/drm driver with evdi, there is nothing to even start the process.  Unless you have a part of DisplayLinkManager you can share so we can build an app to start the process to make sure the vc4 driver is sufficient.

**Comment by displaylink-mlukaszek** [comment]
Hi,

This is great. I had a look at the current state of vc4 driver from @anholt and it looks promising.
I'm not sure if DLM running in qemu can work either - the log you pasted indicates it has problems with initialising libusb, so I'm rather sceptical.

However, technically speaking you don't need DLM to verify and prove both vc4 and evdi can work together on a Pi.
Admittedly, libevdi lacks documentation badly, but you _can_ write a simple app that basically does what DLM does, just without outputting pixels to a DisplayLink device.

You can even add a new DRM card without writing any code at all. First thing that any client app would to is to call `evdi_check_device` to see if any of `/dev/dri/card*` are EVDI. If none is, then the app would use `evdi_add_device` to add as many new cards the device it controls has outputs available. Since adding devices is currently just writing a number to sysfs entry, you can use

`# echo 1 > /sys/devices/evdi/add`

and you'd create a new DRI card that's good for evdi.

With this, your app can now use `evdi_open` and call `evdi_connect` - using any EDID data that's either cloned from your built-in screen, or sourced from the Internet (e.g. from [Google](https://chromium.googlesource.com/chromiumos/third_party/autotest/+/master/server/site_tests/display_EdidStress/test_data/edids/daily/)).

**Comment by TheSin-** [comment]
Excellent I'll see if I can built a test, lets see if my C foo is up to the task to confirm things, I sure hope so at any rate.  I'm getting excited about this again ;)

**Comment by TheSin-** [comment]
I've been trying to figure it out but admittedly my C fu is beginner at best.  Any chance you guys might want to provide an open util for testing this?  Something that i could just had a switch to the edid on the cli, like dlcheck -e /tmp/edid and it would just say compat or not ?

I know have to extract he edid so that is easy enough, I'm just having a hard time with open/connect/disconnect and close.  I'm trying to do it by reading the libevdi source, but against my C isn't super strong.  Might be something good for others too though, so they could at least test things pre DLM, or if DLM isn't avail for their arch/setup.

**Comment by displaylink-mlukaszek** [comment]
Would it help if we released a Python wrapper for libevdi so you can code it in Python?

**Comment by TheSin-** [comment]
not for me sadly.  I thought a little gfxcard-text.c in this repo would help others is all.  I'll keep trying with C, I prefer C over python anyhow.

Plus if there is no chance of DLM in the 3 debian arm variants I'm not sure much effort here is required.

Kind of at a loss with this project, I really wanted to build a Display link touch display to sell for Pi users and for my project, which if it went to full production I'd be around the 10k units a year mark.  But I might just have to let this dream go, the DL USB3 stuff just really complicated DL usage for the embedded ppl sadly.  And I'm to scared to base if on the DL-1xx chipset as I have no idea how long those will be avail for.

That being said thank for all your help with it thus far, it's nice to see it compile with dkms in current debian at least, even if in the end it doesn't help me, I'd assume it will help others.  I'm going to close this ticket since the convo here is no longer relevant to the ticket anymore, and I'll see if I get muster up some sort of test C app, and if so I'll open an other ticket asking for arm support though I'm not even sure it's relevant to this git repo, since DLM isn't in it, so I guess maybe I'll have to go get lost in the forms ;)

**Comment by TheSin-** [comment]
Wish I had tried this first, I did the echo and got lots of output

```
[ 6671.388299] evdi: [I] Initialising logging on level 5
[ 6689.210563] usb 1-1.2: new high-speed USB device number 5 using dwc_otg
[ 6689.300325] usb 1-1.2: New USB device found, idVendor=17e9, idProduct=4301
[ 6689.300351] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber
=3
[ 6689.300368] usb 1-1.2: Product: StarTech.com USB to HDMI
[ 6689.300384] usb 1-1.2: Manufacturer: DisplayLink
[ 6689.300400] usb 1-1.2: SerialNumber: 000001210015901
[ 6689.376666] usb 1-1.2: Warning! Unlikely big volume range (=511), cval->res i
s probably wrong.
[ 6689.376700] usb 1-1.2: [14] FU [StarTech.com Audio Playback Volume] ch = 6, v
al = -8176/0/16
[ 6689.378016] usbcore: registered new interface driver snd-usb-audio
[ 6704.296810] evdi: [D] add_store:195 Increasing device count to 1
[ 6704.299968] evdi: [D] evdi_crtc_init:304 drm_crtc_init: 0
[ 6704.301038] evdi: [W] evdi_painter_crtc_state_notify:362 Painter does not exi
st!
[ 6704.301065] evdi: [D] evdi_detect:72 Painter is disconnected
[ 6704.301166] evdi evdi.0: No connectors reported connected with modes
[ 6704.301200] [drm] Cannot find any crtc or sizes - going 1024x768
[ 6704.312856] evdi evdi.0: fb1: evdidrmfb frame buffer device
[ 6704.334613] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[ 6704.334642] [drm] No driver support for vblank timestamp query.
[ 6704.334656] [drm] evdi: evdi_stats_init
[ 6704.334719] [drm] Initialized evdi 1.1.65 20160512 on minor 0
[ 6704.335045] evdi: [W] evdi_painter_disconnect:462 (dev=0) An unknown connecti
on to b80e7700 tries to close us
[ 6704.335062] evdi: [W] evdi_painter_disconnect:463  - ignoring
[ 6704.337825] evdi: [W] evdi_painter_disconnect:462 (dev=0) An unknown connecti
on to b80e7700 tries to close us
[ 6704.337846] evdi: [W] evdi_painter_disconnect:463  - ignoring
[ 6704.338247] ------------[ cut here ]------------
[ 6704.338312] WARNING: CPU: 2 PID: 1400 at /usr/src/linux-headers-4.5.0-2-commo
n/include/drm/drm_gem.h:217 evdi_dumb_create+0x124/0x134 [evdi]()
[ 6704.338324] Modules linked in: snd_usb_audio(E) snd_hwdep(E) snd_usbmidi_lib(
E) snd_rawmidi(E) snd_seq_device(E) evdi(OE) drm_kms_helper(E) drm(E) syscopyare
a(E) sysfillrect(E) sysimgblt(E) fb_sys_fops(E) cfg80211(E) rfkill(E) evdev(E) j
oydev(E) hid_generic(E) bcm2835_gpiomem(E) bcm2835_wdt(E) snd_bcm2835(E) snd_pcm
(E) snd_timer(E) snd(E)
[ 6704.338458] CPU: 2 PID: 1400 Comm: Xorg Tainted: G           OE   4.5.0-2-rpi
2 #1 Debian 4.5.4-1.20160513
[ 6704.338469] Hardware name: BCM2709
[ 6704.338515] [<8001b0a0>] (unwind_backtrace) from [<800157a4>] (show_stack+0x2
0/0x24)
[ 6704.338545] [<800157a4>] (show_stack) from [<80402ea8>] (dump_stack+0xcc/0x11
0)
[ 6704.338577] [<80402ea8>] (dump_stack) from [<8002c62c>] (warn_slowpath_common
+0x94/0xc4)
[ 6704.338602] [<8002c62c>] (warn_slowpath_common) from [<8002c760>] (warn_slowp
ath_null+0x2c/0x34)
[ 6704.338643] [<8002c760>] (warn_slowpath_null) from [<7f1b3c54>] (evdi_dumb_cr
eate+0x124/0x134 [evdi])
[ 6704.338838] [<7f1b3c54>] (evdi_dumb_create [evdi]) from [<7f138154>] (drm_mod
e_create_dumb_ioctl+0xd8/0xec [drm])
[ 6704.339014] [<7f138154>] (drm_mode_create_dumb_ioctl [drm]) from [<7f127910>]
 (drm_ioctl+0x168/0x4a8 [drm])
[ 6704.339110] [<7f127910>] (drm_ioctl [drm]) from [<801b09d8>] (do_vfs_ioctl+0x
c0/0x85c)
[ 6704.339148] [<801b09d8>] (do_vfs_ioctl) from [<801b11f0>] (SyS_ioctl+0x7c/0x8
c)
[ 6704.339189] [<801b11f0>] (SyS_ioctl) from [<80010d60>] (ret_fast_syscall+0x0/
0x1c)
[ 6704.339283] ---[ end trace 39a4bc83ae25b4d3 ]---
[ 6704.461345] evdi: [D] evdi_detect:72 Painter is disconnected
[ 6704.461893] evdi: [D] evdi_detect:72 Painter is disconnected
[ 6704.495244] evdi: [W] evdi_painter_disconnect:462 (dev=0) An unknown connecti
on to b80e7700 tries to close us
[ 6704.495272] evdi: [W] evdi_painter_disconnect:463  - ignoring
```

At this point no display was connected to the DL adaptor, but I wanted to past the fact that something is happening ;)

**Comment by TheSin-** [comment]
Here is with display plugged in and XOrg not running yet.

```
[   47.404009] [drm] Initialized drm 1.1.0 20060810
[   47.432284] evdi: [I] Initialising logging on level 5
[   49.519129] evdi: [D] add_store:195 Increasing device count to 1
[   49.521149] evdi: [D] evdi_crtc_init:304 drm_crtc_init: 0
[   49.522327] evdi: [W] evdi_painter_crtc_state_notify:362 Painter does not exi
st!
[   49.522373] evdi: [D] evdi_detect:72 Painter is disconnected
[   49.522409] evdi evdi.0: No connectors reported connected with modes
[   49.522538] [drm] Cannot find any crtc or sizes - going 1024x768
[   49.532973] evdi evdi.0: fb1: evdidrmfb frame buffer device
[   49.546535] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[   49.546571] [drm] No driver support for vblank timestamp query.
[   49.546589] [drm] evdi: evdi_stats_init
[   49.546651] [drm] Initialized evdi 1.1.65 20160512 on minor 0
```

**Comment by TheSin-** [comment]
trying to start XOrg now that i have fb1

```
gbm: failed to open any driver (search paths /usr/lib/arm-linux-gnueabihf/dri:${
ORIGIN}/dri:/usr/lib/dri)
gbm: Last dlopen error: /usr/lib/dri/evdi_dri.so: cannot open shared object file
: No such file or directory
failed to load driver: evdi
```

**Comment by TheSin-** [comment]
So is it safe to say I won't be seeing a DLM for armhf (armel or arm64) anytime soon then? I'm kinda of stalled here now I think.  Done everything I can to show compat with vc4

**Comment by displaylink-mlukaszek** [comment]
No, we're not saying that, and thanks for all the analysis above. We are currently gathering feedback for the idea of releasing a binary for ARM as well - see DisplayLink's [support page](http://support.displaylink.com/). We are also trying things on our end, but it's too early to say more.
Having said all that, we've now reached the point where the problem does not apply to evdi nor libevdi, but a specific client for it (DLM, used for DisplayLink devices), so please see DL's forum or support page for further info.

**Comment by linshenghuan123** [comment]
I use arm64 usb3 contect displaylink。 I have not displaylinkmanage code . can you give me ?root@localhost:~/displaylink# ./DisplayLinkManager

**Comment by linshenghuan123** [comment]
my email linsheng_111@163.com

**Comment by linshenghuan123** [comment]
insmod evdi.ko how can I step by step to drive displaylink？ like  echo 2 > /sys/devices/evdi/add
arm64  aarch64-linux-gcc debain9
