### ISSUE TITLE
opensuse 15.2 set up signle display Cause frezze

### ISSUE THREAD

**Issue by mctlukewang** [DisplayLink/evdi#244]
* Are you using the latest driver?
    
  * Are you using the latest EVDI version?
    
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
    
  * Is this issue related to evdi/kernel?
    

  * Linux distribution and its version
  * Linux kernel version
  * Xorg version (if used)
  * Desktop environment in use

**Comment by mctlukewang** [comment]
xsever 1.20.3
evdi 1.8
kernel 5.3.18-lp152.50

**Comment by mctlukewang** [comment]
I frist set up display adapter signle  view cause freeze and crash

**Comment by displaylink-dkurek** [comment]
As in #236 - DisplayLink Manager 5.3.1 is incompatible with evdi 1.8.0. You should use 1.7.x.

**Comment by displaylink-dkurek** [comment]
Just created one issue to gather all those. #245
Closing this one

**Comment by mctlukewang** [comment]
i just use evdi 1.7.2   but opensuse 15.2  set up signal view  always cause freeze
