### ISSUE TITLE
DisplayLink Manager 5.3.1 and EVDI

### ISSUE THREAD

**Issue by displaylink-dkurek** [DisplayLink/evdi#245]
**DisplayLink Manager 5.3.1** is incompatible with **EVDI** newer then **v1.7**.
Please make sure you are using EVDI version **v1.7.2** (newest 1.7.x at the time of writing).
You will need to use this version especially for **kernel 5.9, 5.10**, ...

**Comment by displaylink-dkurek** [comment]
@abucodonosor  what do you think, is it more or less clearly explained what's going on?

**Comment by abucodonosor** [comment]
@displaylink-dkurek yes :)

**Comment by LDuncAndroid** [comment]
> **DisplayLink Manager 5.3.1** is incompatible with **EVDI** newer then **v1.7**.
> Please make sure you are using EVDI version **v1.7.2** (newest 1.7.x at the time of writing).
> You will need to use this version especially for **kernel 5.9, 5.10**, ...

If DisplayLink Manager 5.3.1 is incompatible with EVDI newer than v1.7, what version of DisplayLink Manager do we use if we're using v1.7.2 of EVDI? I have been trying to get **DLM 5.3.1.34** running on **Kubuntu 20.0.4** with various kernels:
- **v5.8.14-050814**
- **v5.9.1-050901**
- **v5.10.2**
- **v5.10.4-051004**

I'd been following threads on the DIsplayLink forums that seemingly are supposed to solve these issues:
- https://displaylink.org/forum/showthread.php?t=67148
- https://displaylink.org/forum/showthread.php?t=67372
- https://displaylink.org/forum/showthread.php?t=67007

I've yet to have a solution working where the session doesn't freeze and EVDI complains about painting.

**Comment by abucodonosor** [comment]
Yes, 1.7.2.
