### ISSUE TITLE
Monitor doesnt show up after update

### ISSUE THREAD

**Issue by Zetabite** [DisplayLink/evdi#246]
* Are you using the latest driver?
`displaylink 5.3.1.34-4`
* Are you using the latest EVDI version?
`evdi 1.7.2-1`
* If you are using a DisplayLink device, have you checked 'troubleshooting'
on DisplayLink's website?
`Yes, there is no solution to my problem`
* Is this issue related to evdi/kernel?
`Possibly.`
* Information:
```
Distro: Arch Linux x86_64
Kernel: 5.10.1-zen1-1-zen
Xorg: xorg-server 1.20.10-3
DE: Plasma 5.20.4

GPU: Intel UHD Graphics 620
```

* Logs:
Pacman: https://paste.ee/p/oMJsF

/usr/share/sddm/scripts/Xsetup:
`#!/bin/sh
$(xrandr --listproviders | grep -q "modesetting") && xrandr --setprovideroutputsource 1 0`

xrandr --listproviders:
`Providers: number : 1
Provider 0: id: 0x47 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 5 associated providers: 0 name:modesetting`

/usr/share/X11/xorg.conf.d/20-evdidevice.conf:
`Section "Device"
  Identifier "DisplayLink"
  Driver "modesetting"
  Option "PageFlip" "false"
EndSection `

* Description:
Displaylink worked without issues on 5.9.14 until i upgraded 5.10 today, after reboot it first didnt load in system, after rebuilding it for 5.10, it started on reboot, but the monitor connected to the docking station doesnt show up in display menu. Downgrading linux kernel didnt make it work on 5.9.14 again.

**Comment by elguero** [comment]
> [2020-12-16T12:29:45+0100] [ALPM-SCRIPTLET] ==> Unable to install module evdi/1.7.2 for kernel 5.9.14-arch1-1: Missing kernel modules tree.
>[2020-12-16T12:29:45+0100] [ALPM-SCRIPTLET] ==> Unable to install module evdi/1.7.2 for kernel 5.10.1-zen1-1-zen: Missing kernel modules tree.

@Zetabite Are the kernel headers installed?

What is the output of `/var/lib/dkms/evdi/1.7.2/build/make.log`?

**Comment by Zetabite** [comment]
> @Zetabite Are the kernel headers installed?
Yes:
`2 testing/linux-zen-headers 5.10.1.zen1-1 (23.8 MiB 127.8 MiB) (Installed)
    Headers and scripts for building modules for the Linux ZEN kernel
1 testing/linux-headers 5.10.1.arch1-1 (23.0 MiB 126.7 MiB) (Installed)
    Headers and scripts for building modules for the Linux kernel`
> What is the output of `/var/lib/dkms/evdi/1.7.2/build/make.log`?
There is no log

**Comment by Zetabite** [comment]
After reinstalling the headers and building again, it now works without issues
