### ISSUE TITLE
5.10.5 Broken Since 5.10.4 fix

### ISSUE THREAD

**Issue by robotard** [DisplayLink/evdi#252]
Working on 5.10.4, not 5.10.5 Following these instructions:

Download the DisplayLink driver from the official download page. Then run the following commands:

unzip 'DisplayLink USB Graphics Software for Ubuntu 5.3.1.zip'
chmod +x displaylink-driver-5.3.1.34.run
./displaylink-driver-5.3.1.34.run --noexec --keep

Get the updated evdi version by typing:

git clone https://github.com/DisplayLink/evdi.git
cd evdi
git checkout v1.7.x
tar cf evdi.tar.gz *
cp evdi.tar.gz ../displaylink-driver-5.3.1.34

Install displaylink:

cd ../displaylink-driver-5.3.1.34
sudo ./displaylink-installer.sh install

LOGS ATTACHED

[DLSupportTool_Output_2021-01-07T03:19:04.772502.zip](https://github.com/DisplayLink/evdi/files/5779442/DLSupportTool_Output_2021-01-07T03.19.04.772502.zip)

**Comment by a-anjos** [comment]
Thanks @robotard.
I can confirm it works on Debian 10:
Linux 5.10.0-1-amd64 #1 SMP Debian 5.10.4-1 (2020-12-31) x86_64 GNU/Linux

**Comment by abucodonosor** [comment]
What is not working?

**Comment by robotard** [comment]
Working fine now on 5.10.6... What wasn't working was from USB hub over 3.0 to external display... Basically what DisplayLink is for... 

I've updated my script which I use to install, which may help explain the process that works for me...

https://github.com/robotard/setup-ubuntu/blob/master/scripts/displaylinkdownloader.sh

**Comment by elguero** [comment]
@robotard Should this issue be closed if everything is working now?

Fedora 33 went from 5.9.x to 5.10.6 and it has been working fine for me.  Maybe there was a reason why they didn't switch to 5.10.x right away... Not sure.

Fedora just updated to 5.10.7 and it is working fine here as well.

**Comment by robotard** [comment]
Not working in 10.7 and 10.8

**Comment by displaylink-emajewsk** [comment]
Closing. Evdi should support kernels up to 5.13 now.
