### ISSUE TITLE
Kernel 5.10.8 - Logs from upgrade 

### ISSUE THREAD

**Issue by robotard** [DisplayLink/evdi#253]
Kernel 5.10.6 working until upgrade to Kernel 5.10.8 (Ubuntu 20.10 Nvidia HDMI output + DisplayLink over USB 3.0)
systemctl status:
"displaylink-driver.service - DisplayLink Driver Service
     Loaded: loaded (/lib/systemd/system/displaylink-driver.service; static)
     Active: activating (auto-restart) (Result: exit-code) since Sun 2021-01-17 21:45:53 GMT; 4s ago
    Process: 6555 ExecStartPre=/bin/sh -c modprobe evdi || (dkms install $(ls -t /usr/src | grep evdi | head -n1  | sed -e "s:-:/:") && modprobe evdi) (code=exited, status=10)"

Kernel upgrade logs and DisplayLink Error Logs attached below:

[DLSupportTool_Output_2021-01-17T21:47:09.311048.zip](https://github.com/DisplayLink/evdi/files/5826888/DLSupportTool_Output_2021-01-17T21.47.09.311048.zip)
[UKUU_5_10_8.log](https://github.com/DisplayLink/evdi/files/5826889/UKUU_5_10_8.log)
[_var_lib_dkms_evdi_1.9.0_build_make.log](https://github.com/DisplayLink/evdi/files/5826890/_var_lib_dkms_evdi_1.9.0_build_make.log)
[_var_lib_dkms_nvidia_460.32.03_build_make.log](https://github.com/DisplayLink/evdi/files/5826891/_var_lib_dkms_nvidia_460.32.03_build_make.log)

**Comment by robotard** [comment]
Not sure if helpful, but receiving a slightly varied after some minutes : 

systemctl status displaylink-driver.service

displaylink-driver.service - DisplayLink Driver Service
     Loaded: loaded (/lib/systemd/system/displaylink-driver.service; static)
     Active: activating (start-pre) since Sun 2021-01-17 21:58:29 GMT; 22ms ago
Cntrl PID: 95281 (sh)
      Tasks: 3 (limit: 8735)
     Memory: 1.9M
     CGroup: /system.slice/displaylink-driver.service
             ├─95281 /bin/sh -c modprobe evdi || (dkms install $(ls -t /usr/src>
             ├─95283 /bin/sh -c modprobe evdi || (dkms install $(ls -t /usr/src>
             └─95289 /bin/bash /usr/sbin/dkms install evdi/1.9.0

Jan 17 21:58:29 Robstas-UX434IQ systemd[1]: Starting DisplayLink Driver Service>
Jan 17 21:58:29 Robstas-UX434IQ sh[95282]: modprobe: FATAL: Module evdi not fou>


Then:

sudo systemctl start displaylink-driver.service 
Job for displaylink-driver.service failed because the control process exited with error code.
See "systemctl status displaylink-driver.service" and "journalctl -xe" for details.


As logs above, also not seeing any NVidia only AMD Renoir 7 4700U....

strangely also still:

"prime-select query
nvidia"

At current config below, will attempt and update/full-upgrade, and report back logs (prior logs show where this began).
Linux Robstas-UX434IQ 5.10.8-051008-generic #202101171440 SMP Sun Jan 17 15:04:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

![Screenshot from 2021-01-17 22-07-59](https://user-images.githubusercontent.com/4448625/104857491-ca1a4480-5910-11eb-959f-a407edc0869d.png)

**Comment by elguero** [comment]
@robotard It looks like you are trying to use a combination of the EVDI driver and Displaylink manager that does not work.

Please see the post for #245
