### ISSUE TITLE
Is there native wayland support planned?

### ISSUE THREAD

**Issue by mfs12** [DisplayLink/evdi#257]
Hey,

is there native wayland support planned?

**Comment by displaylink-mlukaszek** [comment]
Hi @blnagain, GNOME on Wayland is now supported - we've worked with the community to ensure that GNOME's compositor, Mutter is working well with evdi. Other compositors may need more work to fully support running on secondary graphics adapters.

**Comment by blnagain** [comment]
I am not sure about the terminology. But it sounds like every window-manager needs specifically support evdi?

How is the process for other DE like sway, KDE...?

**Comment by displaylink-emajewsk** [comment]
It is not the case that every WM or DE has to support specifically evdi, rather they need to implement Wayland itself (like in Mutter).
Only then we are able to tackle issues related to that implementation specifically.

In any case, I'm closing this as the topic is too broad. In the future, please, create WM/DE specific issues to discuss their Wayland implementations. Thanks. 😇
