### ISSUE TITLE
kernel-5.11.1 break evdi-1.7 again

### ISSUE THREAD

**Issue by jerome-diver** [DisplayLink/evdi#258]
Archlinux
kernel:
linux-5.11.1
and linux-zen-5.11.1

there is no dkms evdi module in the tree, because last kernel update break the evdi-1.7 module to be build (any other evdi last update module doesn't want to build and then, doesn't work)

**Comment by joren485** [comment]
This looks like a duplicate of #249.

**Comment by jerome-diver** [comment]
yes, thank you

**Comment by dzackgarza** [comment]
Also seeing this issue on Arch as of this/last week. The patch mentioned in the linked thread seems to be working for the moment:
https://github.com/DisplayLink/evdi/issues/249#issuecomment-780332761

**Comment by Morta1985** [comment]
This new Patch for evdi 1.7.2 freeze Arch Linux and Cinnamon Desktop when i switch off the screen. Poweroff and reboot is during very long but its works more or less.

**Comment by dzackgarza** [comment]
> This new Patch for evdi 1.7.2 freeze Arch Linux and Cinnamon Desktop when i switch off the screen. Poweroff and reboot is during very long but its works more or less.

Yep, I'm also seeing all kinds of issues after applying that patch....various wake-from-suspend and startup problems, and (maybe unrelated) somehow having certain BIOS settings reset periodically.

**Comment by timnolte** [comment]
Seeing this issue on the latest Pop!_OS as well.

**Comment by toniToniDev** [comment]
Yep... Pop!_OS affected and my working docking station, stopped working for the displays...

**Comment by cement-head** [comment]
Fix is in master, needs to be built for Ubuntu: https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/1931547
