### ISSUE TITLE
Missing header drm/drmP.h

### ISSUE THREAD

**Issue by IvoAnderson** [DisplayLink/evdi#259]
Hello everyone, 

I've been trying to set up my USB display for a while without success and I finally decided to post my issue here. 

I want to install DisplayLink but it does not work. The issue is with evdi. When I run make, I get the following error:

```
make[1]: Entering directory '/home/Downloads/evdi-1.9.0/module'
make -C /lib/modules/4.18.0-277.el8.x86_64/build M=$PWD
make[2]: Entering directory '/usr/src/kernels/4.18.0-277.el8.x86_64'
  CC [M]  /home/Downloads/evdi-1.9.0/module/evdi_platform_drv.o
  CC [M]  /home/Downloads/evdi-1.9.0/module/evdi_platform_dev.o
In file included from /home/Downloads/evdi-1.9.0/module/evdi_platform_dev.c:30:
/home/Downloads/evdi-1.9.0/module/evdi_drm_drv.h:26:10: fatal error: drm/drmP.h: No such file or directory
 #include <drm/drmP.h>
          ^~~~~~~~~~~~
compilation terminated.
make[3]: *** [scripts/Makefile.build:316: /home/Downloads/evdi-1.9.0/module/evdi_platform_dev.o] Error 1
make[2]: *** [Makefile:1545: _module_/home/Downloads/evdi-1.9.0/module] Error 2
make[2]: Leaving directory '/usr/src/kernels/4.18.0-277.el8.x86_64'
make[1]: *** [Makefile:77: module] Error 2
make[1]: Leaving directory '/home/Downloads/evdi-1.9.0/module'
make: *** [Makefile:8: all] Error 2
```
This happens with both the last version 1.9.0 and the version which was included in the DisplayLink folder (1.7.2). 

I am using CentOS Stream 8 with the X11 display server. 

- Kernel versions: 4.18.0-277.el8.x86_64 and 4.18.0-269.el8.x86_64 installed
- Kernel headers: only 4.18.0-277.el8

The packages drm and drm-devel are installed:
```
Package libdrm-2.4.103-1.el8.x86_64 is already installed.
Package libdrm-devel-2.4.103-1.el8.x86_64 is already installed.
```
Xorg version: xorg-x11-server-Xorg-1.20.10-1.el8.x86_64

Thanks in advance!

**Comment by displaylink-emajewsk** [comment]
Hi. I recall we've had some issues with CentOS before. I would need to double-check. Have you tried user solutions for CentOS, such as this one? https://github.com/displaylink-rpm/displaylink-rpm

**Comment by sickcodes** [comment]
> Hi. I recall we've had some issues with CentOS before. I would need to double-check. Have you tried user solutions for CentOS, such as this one? https://github.com/displaylink-rpm/displaylink-rpm

1.8 and 1.9 haven't worked in two years

**Comment by KeXu001** [comment]
@IvoAnderson Not sure if you found a solution but I was also having trouble installing evdi on CentOS Stream 8 and this is what I ended up doing
https://github.com/KeXu001/evdi/commit/4a369a7db8b4e7972228be7a8c72195506c5ab17
Note all I did was manually override the LINUX_VERSION_CODE macro with a value for which it would compile
