### ISSUE TITLE
Distribute firmware in linux-firmware repo

### ISSUE THREAD

**Issue by victoredwardocallaghan** [DisplayLink/evdi#26]
Firmware ucode is most usually distributed within the following repo:

http://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git

Please distribute DisplayLink ucode in this manner so distro's may automagically pick it up.

Thanks

**Comment by displaylink-mlukaszek** [comment]
This has already been answered in #21. As a separate project, evdi and the library has nothing to do with specific client implementation that was developed for DisplayLink Ubuntu Graphics Software (DisplayLinkManager).
