### ISSUE TITLE
Is DisplayLink Abandoned?

### ISSUE THREAD

**Issue by sickcodes** [DisplayLink/evdi#261]
One month since a devel branch update and no response about 5.11 (three months + two weeks since 5.11 released)?

Can't really do much with the hardware if it doesn't work, out of the box.

**Comment by olof-nord** [comment]
Not maintainer or developer, but I just tried to install it but it fails. Running 5.11.1 x86_64. Is Linux 5.11 not supported?

**Comment by displaylink-emajewsk** [comment]
Hi. Kernel version 5.11 is not supported yet. Sorry for the inconvenience.
