### ISSUE TITLE
Which Linux kernel version(s) are supported?

### ISSUE THREAD

**Issue by olof-nord** [DisplayLink/evdi#262]
* Are you using the latest driver?
    
  * Are you using the latest EVDI version?
    
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
    
  * Is this issue related to evdi/kernel?
    

  * Linux distribution and its version
  * Linux kernel version
  * Xorg version (if used)
  * Desktop environment in use

-----

Using evdi 1.7.2-1 on Arch Linux, Kernel 5.11.1 x86_64 with GNOME.

Just came here to ask which Linux kernel versions are supported?

I am currently failing to add the evdi module, it is failing with the following message:

```
➜  ~ sudo modprobe evdi 
modprobe: FATAL: Module evdi not found in directory /lib/modules/5.11.1-arch1-1
➜  ~
```

Many thanks in beforehand!

**Comment by bnavigator** [comment]
See the kids playing in #256

**Comment by olof-nord** [comment]
> See the kids playing in #256

Thank you!

**Comment by displaylink-emajewsk** [comment]
Hi. Unfortunately, Linux kernel version 5.11 is not supported yet. Sorry for the inconvenience.

Evdi on branch v1.7.x should support kernels up to 5.10.

**Comment by GraemeDBlue** [comment]
Broken on latest Groovy Gorilla Ubuntu 20.10

**Comment by xtermi2** [comment]
> Broken on latest Groovy Gorilla Ubuntu 20.10
> 5.8.0-44-generic
> 
> ```
> sudo modprobe evdi 
> modprobe: FATAL: Module evdi not found in directory /lib/modules/5.8.0-44-generic
> ```

@GraemeDBlue: I had the same issue. in my kernel sources in 5.8 was `include/generated/autoconf.h` missing.
```bash
# test it with
ls -l /usr/src/linux-headers-5.8.0-44-generic/include/generated/autoconf.h
```
When the file is missing, I could fix this with:
```bash
sudo apt install --reinstall linux-headers-$(uname -r)
sudo apt install --reinstall build-essential
sudo apt install --reinstall dkms
sudo apt install --reinstall linux-generic
sudo apt install --reinstall linux-signed-generic
# maybe this again, I have played around a lot to get my sources fixed
sudo apt install --reinstall linux-headers-$(uname -r)
```
Then maybe you haver to reinstall the driver with evdi 1.7.2, but first uninstall, reboot and then install the driver ;)
On my Ubuntu 20.10 all kernels are now working fine with evdi 1.7.2: 5.4.0-66, 5.8.0-44, 5.9.16 and 5.10.20 (5.9/5.10 installed via [Mainline](https://ubuntuhandbook.org/index.php/2020/08/mainline-install-latest-kernel-ubuntu-linux-mint/))

**Comment by ascju** [comment]
Hey @xtermi2 ... I have the same thing.

Distro: Ubuntu 20.10
Release: groovy
Kernel: 5.8.0-44-generic

autoconf.h missing (I checked like you also mentioned and it is not there).

I tried following your steps to solve this but trying to install "linux signed headers" fails with "E: Unable to locate package linux-signed-generic" ... looking at the Ubuntu site, I can really only find it for 16.04 & 18.04 - [here](https://packages.ubuntu.com/search?keywords=linux-signed-generic&searchon=names&suite=all&section=all)

... sure, this might be unrelated and me being dumb, but what am I doing wrong? :rofl: 

Thanks!

**Comment by GraemeDBlue** [comment]
@xtermi2 

I jsut get a load of

> > Broken on latest Groovy Gorilla Ubuntu 20.10
> > 5.8.0-44-generic
> > ```
> > sudo modprobe evdi 
> > modprobe: FATAL: Module evdi not found in directory /lib/modules/5.8.0-44-generic
> > ```
> 
> @GraemeDBlue: I had the same issue. in my kernel sources in 5.8 was `include/generated/autoconf.h` missing.
> 
> ```shell
> # test it with
> ls -l /usr/src/linux-headers-5.8.0-44-generic/include/generated/autoconf.h
> ```
> 
> When the file is missing, I could fix this with:
> 
> ```shell
> sudo apt install --reinstall linux-headers-$(uname -r)
> sudo apt install --reinstall build-essential
> sudo apt install --reinstall dkms
> sudo apt install --reinstall linux-generic
> sudo apt install --reinstall linux-signed-generic
> # maybe this again, I have played around a lot to get my sources fixed
> sudo apt install --reinstall linux-headers-$(uname -r)
> ```
> 
> Then maybe you haver to reinstall the driver with evdi 1.7.2, but first uninstall, reboot and then install the driver ;)
> On my Ubuntu 20.10 all kernels are now working fine with evdi 1.7.2: 5.4.0-66, 5.8.0-44, 5.9.16 and 5.10.20 (5.9/5.10 installed via [Mainline](https://ubuntuhandbook.org/index.php/2020/08/mainline-install-latest-kernel-ubuntu-linux-mint/))


`$ sudo apt install --reinstall linux-headers-$(uname -r)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libevdi0
Use 'sudo apt autoremove' to remove it.
0 to upgrade, 0 to newly install, 1 reinstalled, 0 to remove and 0 not to upgrade.
Need to get 0 B/1,261 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 337635 files and directories currently installed.)
Preparing to unpack .../linux-headers-5.8.0-44-generic_5.8.0-44.50_amd64.deb ...
Unpacking linux-headers-5.8.0-44-generic (5.8.0-44.50) over (5.8.0-44.50) ...
Setting up linux-headers-5.8.0-44-generic (5.8.0-44.50) ...
/etc/kernel/header_postinst.d/dkms:
 * dkms: running auto installation service for kernel 5.8.0-44-generic

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...(bad exit status: 2)
make -j8 KERNELRELEASE=5.8.0-44-generic all INCLUDEDIR=/lib/modules/5.8.0-44-generic/build/include KVERSION=5.8.0-44-generic DKMS_BUILD=1...(bad exit status: 2)
ERROR (dkms apport): binary package for evdi: 5.2.14 not found
Error! Bad return status for module build on kernel: 5.8.0-44-generic (x86_64)
Consult /var/lib/dkms/evdi/5.2.14/build/make.log for more information.
   ...done.`


then 

`$ sudo apt install --reinstall linux-signed-generic
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-signed-generic
`

**Comment by ascju** [comment]
> @xtermi2
> 
> I jsut get a load of
> 
> > > Broken on latest Groovy Gorilla Ubuntu 20.10
> > > 5.8.0-44-generic
> > > ```
> > > sudo modprobe evdi 
> > > modprobe: FATAL: Module evdi not found in directory /lib/modules/5.8.0-44-generic
> > > ```
> > 
> > 
> > @GraemeDBlue: I had the same issue. in my kernel sources in 5.8 was `include/generated/autoconf.h` missing.
> > ```shell
> > # test it with
> > ls -l /usr/src/linux-headers-5.8.0-44-generic/include/generated/autoconf.h
> > ```
> > 
> > 
> > When the file is missing, I could fix this with:
> > ```shell
> > sudo apt install --reinstall linux-headers-$(uname -r)
> > sudo apt install --reinstall build-essential
> > sudo apt install --reinstall dkms
> > sudo apt install --reinstall linux-generic
> > sudo apt install --reinstall linux-signed-generic
> > # maybe this again, I have played around a lot to get my sources fixed
> > sudo apt install --reinstall linux-headers-$(uname -r)
> > ```
> > 
> > 
> > Then maybe you haver to reinstall the driver with evdi 1.7.2, but first uninstall, reboot and then install the driver ;)
> > On my Ubuntu 20.10 all kernels are now working fine with evdi 1.7.2: 5.4.0-66, 5.8.0-44, 5.9.16 and 5.10.20 (5.9/5.10 installed via [Mainline](https://ubuntuhandbook.org/index.php/2020/08/mainline-install-latest-kernel-ubuntu-linux-mint/))
> 
> `$ sudo apt install --reinstall linux-headers-$(uname -r)
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> The following package was automatically installed and is no longer required:
> libevdi0
> Use 'sudo apt autoremove' to remove it.
> 0 to upgrade, 0 to newly install, 1 reinstalled, 0 to remove and 0 not to upgrade.
> Need to get 0 B/1,261 kB of archives.
> After this operation, 0 B of additional disk space will be used.
> (Reading database ... 337635 files and directories currently installed.)
> Preparing to unpack .../linux-headers-5.8.0-44-generic_5.8.0-44.50_amd64.deb ...
> Unpacking linux-headers-5.8.0-44-generic (5.8.0-44.50) over (5.8.0-44.50) ...
> Setting up linux-headers-5.8.0-44-generic (5.8.0-44.50) ...
> /etc/kernel/header_postinst.d/dkms:
> 
> * dkms: running auto installation service for kernel 5.8.0-44-generic
> 
> Kernel preparation unnecessary for this kernel. Skipping...
> 
> Building module:
> cleaning build area...(bad exit status: 2)
> make -j8 KERNELRELEASE=5.8.0-44-generic all INCLUDEDIR=/lib/modules/5.8.0-44-generic/build/include KVERSION=5.8.0-44-generic DKMS_BUILD=1...(bad exit status: 2)
> ERROR (dkms apport): binary package for evdi: 5.2.14 not found
> Error! Bad return status for module build on kernel: 5.8.0-44-generic (x86_64)
> Consult /var/lib/dkms/evdi/5.2.14/build/make.log for more information.
> ...done.`
> 
> then
> 
> `$ sudo apt install --reinstall linux-signed-generic Reading package lists... Done Building dependency tree Reading state information... Done E: Unable to locate package linux-signed-generic `

@GraemeDBlue exactly what is happening on my machine.

**Comment by xtermi2** [comment]
Ah, `linux-signed-generic` seems to be some zombie from an older Ubuntu version. I have version `5.3.0.59.49` still installed, but it's not available in the repo any more. I think you can skip this part.

**Comment by ascju** [comment]
> Ah, `linux-signed-generic` seems to be some zombie from an older Ubuntu version. I have version `5.3.0.59.49` still installed, but it's not available in the repo any more. I think you can skip this part.

Unfortunately it does not work for me this way... still stuck :(

**Comment by GraemeDBlue** [comment]
> > Ah, `linux-signed-generic` seems to be some zombie from an older Ubuntu version. I have version `5.3.0.59.49` still installed, but it's not available in the repo any more. I think you can skip this part.
> 
> Unfortunately it does not work for me this way... still stuck :(

yep me too, luckily I still have my work laptop on  Ubuntu 18.04 so can still use the dock that way

**Comment by shaycraft** [comment]
My dock stopped working this morning just by updating the kernel in Ubuntu via `apt-get.`  I'm thinking my best solution is to return it to Amazon and instead purchase a dock from a company that actually cares about updating its drivers.

**Comment by GraemeDBlue** [comment]
> My dock stopped working this morning just by updating the kernel (5.11) in Ubuntu via `apt-get.` I'm thinking my best solution is to return it to Amazon and instead purchase a dock from a company that actually cares about updating its drivers.

I gave up on DisplayLink and bought a Thunderbolt hub on Amazon instead, so much cheaper than my Dell d3100

**Comment by olof-nord** [comment]
> My dock stopped working this morning just by updating the kernel (5.11) in Ubuntu via `apt-get.`  I'm thinking my best solution is to return it to Amazon and instead purchase a dock from a company that actually cares about updating its drivers.

I have really been looking for alternatives, but it seems DisplayLink is dominating the usb dock driver market. 

My dock is also nonfunctional. I use it as an expensive usb hub, hoping for progress.

**Comment by GraemeDBlue** [comment]
@olof-nord @shaycraft I got this (  https://www.amazon.co.uk/gp/product/B08SM1PDP8/ )and it works sooo much better than any of the 3 DisplayLink devices I have for 1/3 of the price, I'm soo disappointed that my expensive Dell DisplayLink docks are now useless

**Comment by ffgiff** [comment]
@olof-nord For the original question, CI tests from 4.15 to 5.11 (https://travis-ci.org/github/DisplayLink/evdi/builds), so that should give some indication of which tag works for which kernel.

**Comment by cement-head** [comment]
@GraemeDBlue Does that MOKIN docking station require a driver installation for LINUX? Which LINUX distro are you using? Ubuntu?  TIA

**Comment by displaylink-emajewsk** [comment]
To answer the question, on paper we support Ubuntu LTS kernels. However we try to support non-LTS kernels as well if time allows.
