### ISSUE TITLE
Display info not present in i915_displayinfo

### ISSUE THREAD

**Issue by wenchunpeng** [DisplayLink/evdi#263]
1. Boot up to OS
2. Connect Acer dock N18D1
3. Connect 2K display

What is the expected output?
cat /sys/kernel/debug/dri/0/i915_display_info   should show display resolution

What do you see instead?
Pipe B doesn't show proper info.

CRTC info
---------
[CRTC:91:pipe A]:
        uapi: enable=yes, active=yes, mode="2256x1504": 60 235690 2256 2304 2336 2536 1504 1507 1513 1549 0x48 0x9
        hw: active=yes, adjusted_mode="2256x1504": 60 235690 2256 2304 2336 2536 1504 1507 1513 1549 0x48 0x9
        pipe src size=2256x1504, dither=no, bpp=24
        num_scalers=2, scaler_users=0 scaler_id=-1, scalers[0]: use=no, mode=0, scalers[1]: use=no, mode=0
        [ENCODER:275:DDI A]: connectors:
                [CONNECTOR:276:eDP-1]
        [PLANE:31:plane 1A]: type=PRI
                uapi: fb=339,XR24 little-endian (0x34325258),2256x1504, src=2256.000000x1504.000000+0.000000+0.000000, dst=2256x1504+0+0, rotation=0 (0x00000001)
                hw: fb=339,XR24 little-endian (0x34325258),2256x1504, visible=yes, src=2256.000000x1504.000000+0.000000+0.000000, dst=2256x1504+0+0, rotation=0 (0x00000001)
        [PLANE:39:plane 2A]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:47:plane 3A]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:55:plane 4A]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:63:plane 5A]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:71:plane 6A]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:79:plane 7A]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:87:cursor A]: type=CUR
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        underrun reporting: cpu=yes pch=yes
[CRTC:152:pipe B]:
        uapi: enable=no, active=no, mode="": 0 0 0 0 0 0 0 0 0 0 0x0 0x0
        [PLANE:92:plane 1B]: type=PRI
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:100:plane 2B]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:108:plane 3B]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:116:plane 4B]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:124:plane 5B]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:132:plane 6B]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:140:plane 7B]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:148:cursor B]: type=CUR
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        underrun reporting: cpu=yes pch=yes
[CRTC:213:pipe C]:
        uapi: enable=no, active=no, mode="": 0 0 0 0 0 0 0 0 0 0 0x0 0x0
        [PLANE:153:plane 1C]: type=PRI
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:161:plane 2C]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:169:plane 3C]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:177:plane 4C]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:185:plane 5C]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:193:plane 6C]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:201:plane 7C]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:209:cursor C]: type=CUR
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        underrun reporting: cpu=yes pch=yes
[CRTC:274:pipe D]:
        uapi: enable=no, active=no, mode="": 0 0 0 0 0 0 0 0 0 0 0x0 0x0
        [PLANE:214:plane 1D]: type=PRI
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:222:plane 2D]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:230:plane 3D]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:238:plane 4D]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:246:plane 5D]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:254:plane 6D]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:262:plane 7D]: type=OVL
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        [PLANE:270:cursor D]: type=CUR
                uapi: fb=0,n/a,0x0, src=0.000000x0.000000+0.000000+0.000000, dst=0x0+0+0, rotation=0 (0x00000001)
        underrun reporting: cpu=yes pch=yes

**Comment by displaylink-mlukaszek** [comment]
No screen driven by evdi will have any impact on what you can see in sysfs entries for an Intel driver. This is expected.
