### ISSUE TITLE
Make compatibility version part of public api

### ISSUE THREAD

**Issue by danielzfranklin** [DisplayLink/evdi#264]
I would like to be able to check if my library version is compatible with the kernel module version on a user's machine.

I could do this if there was a similar API to `evdi_get_lib_version` that returned the value of the private constants `EVDI_MODULE_COMPATIBILITY_VERSION_MAJOR`, `EVDI_MODULE_COMPATIBILITY_VERSION_MAJOR`, and `EVDI_MODULE_COMPATIBILITY_VERSION_PATCH` and there was a guarantee that the comparison algorithm in `is_evdi_compatible(fd)` is stable (actual_major == compatibility_major && actual_minor >= compatibility_minor).

**Comment by displaylink-emajewsk** [comment]
We'll be taking this under consideration. Thanks for the suggestion. 😇
