### ISSUE TITLE
Should evdi_handle_events be called in a loop?

### ISSUE THREAD

**Issue by danielzfranklin** [DisplayLink/evdi#265]
Based on the implementation, it seems to me that if I want to receive events in perpetuity I need to call `evdi_handle_events` in an infinite loop.

This was not what I expected based on the documentation. Based on the docs I expected it to behave like `evdi_set_logging`.

Is my understanding correct?

**Comment by displaylink-mlukaszek** [comment]
No, evdi_handle_events should only be called when evdi signals you there is an event your app should react to. See https://displaylink.github.io/evdi/details/#evdi_selectable

An example usage is in the evdipp C++ wrapper for evdi - see https://github.com/mlukaszek/evdipp/blob/master/example/driver.cpp for an example of implementing this with libev++, or https://github.com/mlukaszek/evdipp/blob/master/monitorsim/qevdiscreen.cpp to see how it could be achieved with Qt's QSocketNotifier.
