### ISSUE TITLE
Document that not calling request_update and grab_pixels will cause the main display to freeze

### ISSUE THREAD

**Issue by danielzfranklin** [DisplayLink/evdi#268]
```
Linux daniel-darter 5.8.0-7642-generic #47~1614007149~20.10~82fb226-Ubuntu SMP Tue Feb 23 02:59:01 UTC  x86_64 x86_64 x86_64 GNU/Linux

Pop-Shell (GNOME)
```

I decided to first implement a trivial example that just logged the current `evdi_mode`. I was confused by the fact that this caused my laptop's built-in display to freeze (becomes black, cursor visible and movable, moving cursor off real display to virtual display causes cursor to stutter and freeze).

Calling `evdi_request_update` and `evdi_grab_pixels` in a loop fixed this issue. This isn't a serious issue, as I don't think I would ever want to have a connected handle that I don't care updates to. However, it was non-intuitive to debug (I eventually tracked it down by commenting out lines in evdipp monitorsim until I got the same behaviour).

Would you accept a PR that adds this to the docs for the function?

**Comment by displaylink-emajewsk** [comment]
> Would you accept a PR that adds this to the docs for the function?

Sure. 😇
