### ISSUE TITLE
DisplayLink on D3100 is incredibly slow

### ISSUE THREAD

**Issue by cajus** [DisplayLink/evdi#27]
Just tried the new release. I've a Dell D3100 dock connected to a Fedora system, compiled the kernel module and installed the DisplayLinkManager and companions. I've disabled selinux because of tons of complaints I didn't want to investigate for testing.

Now - for the first time, I can see something on the secondary monitor. BUT it is so incredibly slow, that it can't be used at all. I'm not sure how I can debug that. Any ideas?

**Comment by displaylink-mlukaszek** [comment]
Let's keep GitHub for evdi only. Could you please raise this at [DisplayLink Forum](http://displaylink.org/forum/forumdisplay.php?f=29)? [This post](http://displaylink.org/forum/showthread.php?t=64503) has link to a log gathering tool - but if you experience high CPU usage of DLM then it would be great if you could also use gdb to make a core file while the app is running (see [this](http://displaylink.org/forum/showthread.php?t=64039) for more info and potentially also a fix?). Thanks.

**Comment by cajus** [comment]
Sigh. I really don't like this forum stuff. But if it's the correct place for it, I'll have no choice. Thanks.

**Comment by cajus** [comment]
The forum works as I know forums. No reaction for two days. Not even a download of the core file :-(

**Comment by displaylink-mlukaszek** [comment]
Don't worry, analysis of the dump already sits in the backlog of things to do this sprint. I wonder if you see [this](http://www.displaylink.org/forum/showthread.php?t=64523) when things are slow?

**Comment by cajus** [comment]
No. The only vblank messages are these:

```
Mai 12 09:44:50 localhost kernel: [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
Mai 12 09:44:50 localhost kernel: [drm] Driver supports precise vblank timestamp query.
```
