### ISSUE TITLE
Mesa 21 not supported

### ISSUE THREAD

**Issue by joren485** [DisplayLink/evdi#274]
### Issue Questions
  * Are you using the latest driver?
Yes
  * Are you using the latest EVDI version?
1.7.2, the most recent supported EVDI version for the latest Displaylink version.
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
Yes
  * Is this issue related to evdi/kernel?
 Yes

### System Information
  * Arch Linux
  * Kernel version `5.10.26-1-lts`
  * `xorg-server`, version `1.20.10-3`
  * `i3`, version `4.19.2-1`

### Description
A few days ago [version 21.0.1 of Mesa was released](https://gitlab.freedesktop.org/mesa/mesa/-/tags/mesa-21.0.1). When I try to connect a screen connected via the dock with this new Mesa version installed, I get error `Configure crtc 3 failed`.

If I try to use Sway (the i3 port in Wayland), I get the following error:
```
MESA-LOADER: failed to open evdi: /usr/lib/dri/evdi_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/dri)
failed to load driver: evdi
```

**Comment by al12gamer** [comment]
Can confirm. Have a customer with the same issue, they would rather wait for a fix than downgrade mesa though.

**Comment by joren485** [comment]
This issue seems to be fixed in the latest release of evdi and DLM.

**Comment by bnavigator** [comment]
https://github.com/DisplayLink/evdi/issues/275#issuecomment-814108417 @moodyhunter is it resolved for you as well?

**Comment by moodyhunter** [comment]
@bnavigator Unfortunately no, `X` complains there's no `evdi_dri.so` under `/usr/lib/dri/`.
My `displaylink` and `evdi` (`evdi-git`) is installed via the AUR package.

**Comment by joren485** [comment]
I sometimes get that error too on X (on both DLM 5.3 and 5.4). I try to setup a Displaylink monitor and it crashes because it cannot find `evdi_dri.so`. For me it is always fixed by either rebooting or by restarting X.

**Comment by moodyhunter** [comment]
Sorry for the late reply, I upgraded mesa and it now works well, [this](https://github.com/DisplayLink/evdi/issues/275#issuecomment-814108417) was a false alarm.
