### ISSUE TITLE
only once - ethernet fails to recover after sleep, but also reports itself "up" - "transmit queue 0 timed out" - race?

### ISSUE THREAD

**Issue by thx1111** [DisplayLink/evdi#278]
Arch Linux
linux 5.11.13-arch2-1
evdi-git 1.9.1.r4.gb0b3d13-1
displaylink 5.4-2
```
$ lsusb
...
Bus 001 Device 007: ID 17e9:436e DisplayLink Dell D3100 Docking Station
Bus 001 Device 008: ID 17e9:436e DisplayLink Dell D3100 Docking Station
```
```
$ usb-devices
...
T:  Bus=01 Lev=03 Prnt=03 Port=00 Cnt=01 Dev#=  8 Spd=480 MxCh= 0
D:  Ver= 2.10 Cls=ef(misc ) Sub=02 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=17e9 ProdID=436e Rev=31.24
S:  Manufacturer=DisplayLink
S:  Product=Dell D3100 USB3.0 Dock
S:  SerialNumber=1712190754B
C:  #Ifs= 2 Cfg#= 1 Atr=e0 MxPwr=2mA
I:  If#=0x0 Alt= 0 #EPs= 2 Cls=ff(vend.) Sub=00 Prot=03 Driver=usbfs
I:  If#=0x1 Alt= 0 #EPs= 0 Cls=fe(app. ) Sub=01 Prot=01 Driver=usbfs

T:  Bus=01 Lev=03 Prnt=03 Port=02 Cnt=03 Dev#=  7 Spd=480 MxCh= 0
D:  Ver= 2.10 Cls=ef(misc ) Sub=02 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=17e9 ProdID=436e Rev=31.24
S:  Manufacturer=DisplayLink
S:  Product=Dell D3100 USB3.0 Dock
S:  SerialNumber=1712190754
C:  #Ifs= 7 Cfg#= 1 Atr=e0 MxPwr=2mA
I:  If#=0x0 Alt= 0 #EPs= 2 Cls=ff(vend.) Sub=00 Prot=03 Driver=usbfs
I:  If#=0x1 Alt= 0 #EPs= 0 Cls=fe(app. ) Sub=01 Prot=01 Driver=usbfs
I:  If#=0x2 Alt= 0 #EPs= 1 Cls=01(audio) Sub=01 Prot=20 Driver=snd-usb-audio
I:  If#=0x3 Alt= 0 #EPs= 0 Cls=01(audio) Sub=02 Prot=20 Driver=snd-usb-audio
I:  If#=0x4 Alt= 0 #EPs= 0 Cls=01(audio) Sub=02 Prot=20 Driver=snd-usb-audio
I:  If#=0x5 Alt= 0 #EPs= 1 Cls=02(commc) Sub=0d Prot=00 Driver=cdc_ncm
I:  If#=0x6 Alt= 1 #EPs= 2 Cls=0a(data ) Sub=00 Prot=01 Driver=cdc_ncm
```
Those last two interfaces, "commc" and "data" are "Dell GigabitEthernet", using driver "cdc_ncm".

Everything seems to be working fine now, after boot - video, USB, ethernet, and audio interfaces.

But, after wake from sleep, ethernet reports itself working, the kernel throws a warning, and there is no actual network function.

I have only seen this happen once, though.

```
$ sudo ethtool enp0s26u1u6u3i5
Settings for enp0s26u1u6u3i5:
        Current message level: 0x00000007 (7)
                               drv probe link
        Link detected: yes
```

Note here that "usb 1-1.6.3" includes the ethernet device interfaces.
```
 kernel: bond0: (slave bridge1): link status definitely up, 0 Mbps full duplex
 kernel: usb 1-1.6.3: usbfs: process 422 (DeviceManager_0) did not claim interface 0 before use
 kernel: ------------[ cut here ]------------
 kernel: NETDEV WATCHDOG: enp0s26u1u6u3i5 (cdc_ncm): transmit queue 0 timed out
 kernel: WARNING: CPU: 0 PID: 0 at net/sched/sch_generic.c:442 dev_watchdog+0x25e/0x270
...
 kernel: Call Trace:
 kernel:  <IRQ>
 kernel:  ? pfifo_fast_init+0x110/0x110
```
Of course, with the interface still claiming to be "up", even the automatic bonding roll-ever fails, but that is incidental.

Unplugging and replugging the ethernet cable, the kernel does not throw another warning, but the interface returns to the exact same state, with a link, yet still not working.

However, repeating a lid-close, sleep and wake, a second time, and repeatedly, the kernel did *not* throw a warning, and the ethernet interface comes-up working normally again.  The `sudo ethtool enp0s26u1u6u3i5` report stays exactly the same for the interface when it is working .

Maybe a possible race condition?  This has not been repeatable, but anyone "stuck" with no ethernet may need to know to simply close, then open, the lid again.

**Comment by displaylink-emajewsk** [comment]
Closing as this is unrelated to evdi.
Please, raise other issues using the "Contact DisplayLink" form at https://support.displaylink.com/ 😇

In this particular case however, I'm not sure we could help you, as we're not responsible for the ethernet driver.
