### ISSUE TITLE
Download page for drivers down. Displaylink.com as well. 

### ISSUE THREAD

**Issue by antoineclaval** [DisplayLink/evdi#280]
Hi,

I'm trying to debug an docking station that stopped to function, most likely due to a kernel imcompatibility. Fine. that's the game. 

However I'm kinda stuck by the non availability of the display page. 

www.displaylink.com/downloads/ubuntu.php
or 
https://www.displaylink.com/downloads
or 
https://www.displaylink.com/

I get the same result as bellow for the 3 links above. 
is there a know direct download link to mitigate that ? 

Thanks!

![displayLink](https://user-images.githubusercontent.com/211455/115121898-b6679400-9f7a-11eb-925c-14863d326f43.png)

**Comment by antoineclaval** [comment]
displaylink.com is back, without HTTPS certificate. I guess someone is working on it.

**Comment by displaylink-emajewsk** [comment]
Might have been a temporary issue. In either case, I'm closing this as not directly related to evdi.
