### ISSUE TITLE
Mobile Pixels Trio and this driver

### ISSUE THREAD

**Issue by lerenn** [DisplayLink/evdi#281]
Hello there,

I recently bought a Mobile Pixels Trio which is marked as Ubuntu compatible and their website redirect to this driver (on the official DisplayLink website).

I installed the latest version but it's not working. The driver is well installed and the screen is detected but there is no interaction between those two. Also the DisplayLink systemd service is not up and not enable-able.

The thing is, even the vendor/product ID is strange on the device (ID 0711:560b Magic Control Technology Corp. T6 USB Station). If someone has an idea, I'm all ears. 

I contacted the Mobile pixels support but all they are telling me is that they don't have a Linux driver and I just need to connect it over USB-C, which is not helpful.

Here are some informations :

DMESG (grep on evdi):
frd@msi-station:~$ dmesg |grep evdi
[ 4.693452] evdi: loading out-of-tree module taints kernel.
[ 4.693521] evdi: module verification failed: signature and/or required key missing - tainting kernel
[ 4.695400] evdi: [I] Initialising logging on level 5
[ 4.695400] evdi: [I] Atomic driver: yes
[ 4.695464] evdi: [D] evdi_platform_add_devices:158 Increasing device count to 4
[ 4.695551] evdi: [D] evdi_crtc_init:413 drm_crtc_init: 0 p000000006ac7cd06
[ 4.695565] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 4.695572] evdi evdi.0: [drm] Cannot find any crtc or sizes
[ 4.695584] evdi: [W] evdi_painter_send_update_ready_if_needed:706 Painter does not exist!
[ 4.695706] [drm] Initialized evdi 1.9.1 20210126 for evdi.0 on minor 2
[ 4.695724] evdi: [I] Evdi platform_device create
[ 4.695805] evdi: [D] evdi_crtc_init:413 drm_crtc_init: 0 p0000000003ab9b37
[ 4.695814] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 4.695819] evdi evdi.1: [drm] Cannot find any crtc or sizes
[ 4.695826] evdi: [W] evdi_painter_send_update_ready_if_needed:706 Painter does not exist!
[ 4.695968] [drm] Initialized evdi 1.9.1 20210126 for evdi.1 on minor 3
[ 4.695982] evdi: [I] Evdi platform_device create
[ 4.696047] evdi: [D] evdi_crtc_init:413 drm_crtc_init: 0 p000000005b02442b
[ 4.696055] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 4.696059] evdi evdi.2: [drm] Cannot find any crtc or sizes
[ 4.696065] evdi: [W] evdi_painter_send_update_ready_if_needed:706 Painter does not exist!
[ 4.696153] [drm] Initialized evdi 1.9.1 20210126 for evdi.2 on minor 4
[ 4.696166] evdi: [I] Evdi platform_device create
[ 4.696227] evdi: [D] evdi_crtc_init:413 drm_crtc_init: 0 p00000000f95d3ee4
[ 4.696235] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 4.696239] evdi evdi.3: [drm] Cannot find any crtc or sizes
[ 4.696244] evdi: [W] evdi_painter_send_update_ready_if_needed:706 Painter does not exist!
[ 4.696349] [drm] Initialized evdi 1.9.1 20210126 for evdi.3 on minor 5
[ 4.696362] evdi: [I] Evdi platform_device create
[ 5.472720] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 5.472740] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 5.472742] evdi: [I] Task 322 (plymouthd) of process 322 (plymouthd)
[ 5.487440] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 5.487464] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 5.487465] evdi: [I] Task 322 (plymouthd) of process 322 (plymouthd)
[ 5.501444] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 5.501467] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 5.501469] evdi: [I] Task 322 (plymouthd) of process 322 (plymouthd)
[ 5.512508] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 5.512532] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 5.512534] evdi: [I] Task 322 (plymouthd) of process 322 (plymouthd)
[ 5.710587] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 5.710610] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 5.710612] evdi: [I] Task 322 (plymouthd) of process 322 (plymouthd)
[ 5.717333] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 5.717356] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 5.717358] evdi: [I] Task 322 (plymouthd) of process 322 (plymouthd)
[ 5.747884] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 5.747909] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 5.747911] evdi: [I] Task 322 (plymouthd) of process 322 (plymouthd)
[ 5.878608] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 5.878633] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 5.878634] evdi: [I] Task 322 (plymouthd) of process 322 (plymouthd)
[ 5.966079] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 5.966103] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 5.966104] evdi: [I] Task 322 (plymouthd) of process 322 (plymouthd)
[ 6.014180] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 6.014203] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 6.014205] evdi: [I] Task 322 (plymouthd) of process 322 (plymouthd)
[ 6.117557] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 6.117580] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 6.117582] evdi: [I] Task 322 (plymouthd) of process 322 (plymouthd)
[ 6.270462] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 6.270485] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 6.270487] evdi: [I] Task 322 (plymouthd) of process 322 (plymouthd)
[ 6.327987] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 6.328011] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 6.328013] evdi: [I] Task 322 (plymouthd) of process 322 (plymouthd)
[ 6.328734] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 6.328753] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 6.328754] evdi: [I] Task 322 (plymouthd) of process 322 (plymouthd)
[ 6.337183] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 6.337208] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 6.337210] evdi: [I] Task 322 (plymouthd) of process 322 (plymouthd)
[ 6.349405] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 6.349426] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 6.349427] evdi: [I] Task 322 (plymouthd) of process 322 (plymouthd)
[ 10.021749] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 10.021752] evdi: [I] Task 1178 (gpu-manager) of process 1178 (gpu-manager)
[ 10.021764] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 10.021765] evdi: [I] Task 1178 (gpu-manager) of process 1178 (gpu-manager)
[ 10.021774] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 10.021775] evdi: [I] Task 1178 (gpu-manager) of process 1178 (gpu-manager)
[ 10.021784] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 10.021785] evdi: [I] Task 1178 (gpu-manager) of process 1178 (gpu-manager)
[ 10.022028] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 10.022029] evdi: [I] Task 1178 (gpu-manager) of process 1178 (gpu-manager)
[ 10.022038] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 10.022039] evdi: [I] Task 1178 (gpu-manager) of process 1178 (gpu-manager)
[ 10.022049] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 10.022050] evdi: [I] Task 1178 (gpu-manager) of process 1178 (gpu-manager)
[ 10.022058] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 10.022059] evdi: [I] Task 1178 (gpu-manager) of process 1178 (gpu-manager)
[ 10.022294] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 10.022296] evdi: [I] Task 1178 (gpu-manager) of process 1178 (gpu-manager)
[ 10.022305] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 10.022307] evdi: [I] Task 1178 (gpu-manager) of process 1178 (gpu-manager)
[ 10.022317] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 10.022318] evdi: [I] Task 1178 (gpu-manager) of process 1178 (gpu-manager)
[ 10.022328] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 10.022329] evdi: [I] Task 1178 (gpu-manager) of process 1178 (gpu-manager)
[ 10.022573] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 10.022574] evdi: [I] Task 1178 (gpu-manager) of process 1178 (gpu-manager)
[ 10.022586] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 10.022587] evdi: [I] Task 1178 (gpu-manager) of process 1178 (gpu-manager)
[ 10.022598] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 10.022599] evdi: [I] Task 1178 (gpu-manager) of process 1178 (gpu-manager)
[ 10.022611] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 10.022612] evdi: [I] Task 1178 (gpu-manager) of process 1178 (gpu-manager)
[ 11.328626] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 11.335389] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 11.339858] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 11.342677] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 13.378589] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 13.378592] evdi: [I] Task 1584 (Xwayland) of process 1584 (Xwayland)
[ 14.477640] evdi: [D] evdi_painter_dpms_notify:715 (dev=0) Notifying dpms mode: 3
[ 14.477642] evdi: [W] evdi_painter_send_event:321 Painter is not connected!
[ 14.477651] evdi: [D] evdi_painter_dpms_notify:715 (dev=0) Notifying dpms mode: 3
[ 14.477651] evdi: [W] evdi_painter_send_event:321 Painter is not connected!
[ 14.477657] evdi: [D] evdi_painter_dpms_notify:715 (dev=0) Notifying dpms mode: 3
[ 14.477658] evdi: [W] evdi_painter_send_event:321 Painter is not connected!
[ 14.477663] evdi: [D] evdi_painter_dpms_notify:715 (dev=0) Notifying dpms mode: 3
[ 14.477664] evdi: [W] evdi_painter_send_event:321 Painter is not connected!
[ 19.399456] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 19.399459] evdi: [I] Task 1971 (Xorg.wrap) of process 1971 (Xorg.wrap)
[ 19.399479] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 19.399481] evdi: [I] Task 1971 (Xorg.wrap) of process 1971 (Xorg.wrap)
[ 19.399494] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 19.399496] evdi: [I] Task 1971 (Xorg.wrap) of process 1971 (Xorg.wrap)
[ 19.399508] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 19.399510] evdi: [I] Task 1971 (Xorg.wrap) of process 1971 (Xorg.wrap)
[ 19.805629] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 19.805766] evdi: [D] evdi_painter_framebuffer_size:594 Scanout buffer not set.
[ 19.805767] evdi: [D] evdi_painter_mark_dirty:621 (dev=0) Skip clip rect. Scanout buffer not set.
[ 19.805777] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 19.825074] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 19.825214] evdi: [D] evdi_painter_framebuffer_size:594 Scanout buffer not set.
[ 19.825215] evdi: [D] evdi_painter_mark_dirty:621 (dev=0) Skip clip rect. Scanout buffer not set.
[ 19.825226] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 19.840697] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 19.840836] evdi: [D] evdi_painter_framebuffer_size:594 Scanout buffer not set.
[ 19.840838] evdi: [D] evdi_painter_mark_dirty:621 (dev=0) Skip clip rect. Scanout buffer not set.
[ 19.840847] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 19.855380] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 19.855524] evdi: [D] evdi_painter_framebuffer_size:594 Scanout buffer not set.
[ 19.855526] evdi: [D] evdi_painter_mark_dirty:621 (dev=0) Skip clip rect. Scanout buffer not set.
[ 19.855536] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 20.506851] evdi: [D] evdi_painter_dpms_notify:715 (dev=0) Notifying dpms mode: 3
[ 20.506853] evdi: [W] evdi_painter_send_event:321 Painter is not connected!
[ 20.508150] evdi: [D] evdi_painter_dpms_notify:715 (dev=0) Notifying dpms mode: 3
[ 20.508152] evdi: [W] evdi_painter_send_event:321 Painter is not connected!
[ 20.509475] evdi: [D] evdi_painter_dpms_notify:715 (dev=0) Notifying dpms mode: 3
[ 20.509477] evdi: [W] evdi_painter_send_event:321 Painter is not connected!
[ 20.510879] evdi: [D] evdi_painter_dpms_notify:715 (dev=0) Notifying dpms mode: 3
[ 20.510881] evdi: [W] evdi_painter_send_event:321 Painter is not connected!
[ 20.712922] evdi: [D] evdi_painter_dpms_notify:715 (dev=0) Notifying dpms mode: 3
[ 20.712924] evdi: [W] evdi_painter_send_event:321 Painter is not connected!
[ 20.712946] evdi: [D] evdi_painter_dpms_notify:715 (dev=0) Notifying dpms mode: 3
[ 20.712946] evdi: [W] evdi_painter_send_event:321 Painter is not connected!
[ 20.712963] evdi: [D] evdi_painter_dpms_notify:715 (dev=0) Notifying dpms mode: 3
[ 20.712964] evdi: [W] evdi_painter_send_event:321 Painter is not connected!
[ 20.712979] evdi: [D] evdi_painter_dpms_notify:715 (dev=0) Notifying dpms mode: 3
[ 20.712980] evdi: [W] evdi_painter_send_event:321 Painter is not connected!
[ 21.644637] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 21.644661] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 21.644681] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 21.644705] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 26.936713] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 26.936716] evdi: [I] Task 1 (systemd) of process 1 (systemd)
[ 26.936807] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 26.936808] evdi: [I] Task 1 (systemd) of process 1 (systemd)
[ 26.952234] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 26.952237] evdi: [I] Task 1 (systemd) of process 1 (systemd)
[ 27.680048] evdi: [D] evdi_driver_postclose:230 (dev=0) Process tries to close us, postclose
[ 27.680050] evdi: [I] Task 1 (systemd) of process 1 (systemd)
[ 229.289520] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 229.289547] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 229.289732] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 229.289758] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 229.289933] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 229.289951] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 229.290239] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 229.290257] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 229.998578] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 229.998591] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 230.000818] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 230.000833] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 230.001220] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 230.001230] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 230.001412] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected
[ 230.001422] evdi: [D] evdi_detect:94 (dev=0) poll connector state: disconnected

lsusb:
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 0bda:0129 Realtek Semiconductor Corp. RTS5129 Card Reader Controller
Bus 001 Device 003: ID 248a:8367 Maxxter Wireless Receiver
Bus 001 Device 002: ID 8087:0aa7 Intel Corp.
**Bus 001 Device 005: ID 0711:560b Magic Control Technology Corp. T6 USB Station**
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

I know it's not really the "support" section but I'm out of ideas.

Thank you !

**Comment by displaylink-mlukaszek** [comment]
I'm afraid the device in question is not a device that would be driven using evdi, and therefore also not something that you'd install DisplayLink driver for. The vendor ID of DisplayLink is 17e9, here you see 0711.

**Comment by lerenn** [comment]
I was suspecting this. Thank you for the quick answer !

**Comment by williamnavaraj** [comment]
I got the same device identifier with my mobile pixels Trio  (Newer versions uses DisplayPort not DisplayLink).  If your laptop has  inbuilt displayport over USB-C or ThunderBolt3 then using the right USB-C cable (Such as a thunderbolt 3 USB-C cable) instead of a normal USB-C will sort this problem. I noticed in windows it will work with normal low speed USB-C cables. or USB-A to USB-C adapter with the Trigger driver (not available for Ubuntu). But there also using a displayport compatible high speed USB-C cable will lead to a better performance. All the newer models of MobilePixels devices use DisplayPort, not DisplayLink. I hope this helps someone.

**Comment by rfxDarth** [comment]
Gonna necro this topic to add some useful information to any future strangers coming from google. Got new MobilePixels Trio (2023) with device id `0711:562b`. The mobilepixels support came empty handed so I took a shot and messaged the MCT guys. What they've responded with is [this script](https://github.com/rfxDarth/t6/raw/main/ubuntuT6_24011601.run) which doesn't seem to work as the device id I've asked them about isn't even listed in the sources, and, frankly, the whole thing looks unfinished. But it does indeed use evdi under the hood, so maybe someone with more knowledge in C could make it work.
