### ISSUE TITLE
Changing a DisplayLink monitor to portrait mode results in extreme lag and visual artifacts

### ISSUE THREAD

**Issue by wilsonliam** [DisplayLink/evdi#289]
Nouveau drivers fix this, but for my situation (and I'm sure many others), lack of CUDA support is a deal-breaker. 

I have two portrait monitors that I use a Kensington DisplayLink dock for, connected to a Thinkpad P1 (Xeon E-2176M; Quadro P2000 Max-Q on Nvidia 465 drivers). On Ubuntu 20.04, these monitors are useless due to extreme lag and visual artifacts (when doing anything), but confusingly, only while in portrait mode. Shifting the monitors over to landscape resolves the issue.

**Comment by displaylink-emajewsk** [comment]
Hello, 😇 
If you could, please, raise the issue using the "Contact DisplayLink" form at https://support.displaylink.com/
This will ensure your problem will be investigated in a more timely manner than here.
