### ISSUE TITLE
Can't work on UOS system

### ISSUE THREAD

**Issue by Eddie-064** [DisplayLink/evdi#292]
* Are you using the latest driver? yes
    
  * Are you using the latest EVDI version? 1.9.1 release
    
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website? yes
    
  * Is this issue related to evdi/kernel? yes
    

  * Linux distribution and its version UOS 20
  * Linux kernel version 5.4.50-amd64-desktop (deepin@deepin-PC)
  * Xorg version (if used)  1.20.4
  * Desktop environment in use 
  * eddie@eddie-PC:~/Desktop$ echo $XDG_CURRENT_DESKTOP
Deepin

after plug in displaylink device , the screen show nothing.

when plug in displaylink device the debug message show blow:
eddie@eddie-PC:~/Desktop$ dmesg | grep evdi
[    4.443782] evdi: [I] Initialising logging on level 5
[    4.443784] evdi: [I] Atomic driver: yes
[   70.413212] evdi: [D] evdi_crtc_init:413 drm_crtc_init: 0 p00000000154fb118
[   70.413231] evdi: [D] evdi_detect:95 (dev=0) poll connector state: disconnected
[   70.413256] evdi: [W] evdi_painter_send_update_ready_if_needed:706 Painter does not exist!
[   70.413704] [drm] Initialized evdi 1.9.1 20210126 for evdi.0 on minor 0
[   70.413726] evdi: [I] Evdi platform_device create
[   70.413730] evdi: [I] Attaching to usb:1-4.1.1
[   70.416037] evdi: [D] evdi_driver_postclose:231 (dev=0) Process tries to close us, postclose
[   70.416039] evdi: [I] Task 1412 (Xorg) of process 1412 (Xorg)
[   70.416774] evdi: [D] evdi_driver_postclose:231 (dev=0) Process tries to close us, postclose
[   70.416776] evdi: [I] Task 1412 (Xorg) of process 1412 (Xorg)
[   70.417137] evdi: [D] evdi_detect:95 (dev=0) poll connector state: disconnected
[   70.417255] evdi: [D] evdi_painter_framebuffer_size:594 Scanout buffer not set.
[   70.417257] evdi: [D] evdi_painter_mark_dirty:622 (dev=0) Skip clip rect. Scanout buffer not set.
[   70.417271] evdi: [D] evdi_detect:95 (dev=0) poll connector state: disconnected
[   70.419427] evdi: [D] evdi_painter_dpms_notify:716 (dev=0) Notifying dpms mode: 3
[   70.419430] evdi: [W] evdi_painter_send_event:321 Painter is not connected!
[   70.430927] evdi: [D] evdi_painter_dpms_notify:716 (dev=0) Notifying dpms mode: 3
[   70.430930] evdi: [W] evdi_painter_send_event:321 Painter is not connected!
[   70.437716] evdi: [D] evdi_detect:95 (dev=0) poll connector state: disconnected
[   70.437742] evdi: [D] evdi_detect:95 (dev=0) poll connector state: disconnected
[   70.446502] evdi: [D] evdi_painter_connect:852 (dev=0) Process is trying to connect
[   70.446506] evdi: [I] Task 1463 (DesktopManagerE) of process 1431 (DisplayLinkMana)
[   70.446669] evdi: [D] evdi_add_i2c_adapter:814 (dev=0) Added i2c adapter bus number 0
[   70.446674] evdi: [D] evdi_painter_connect:904 (dev=0) Connected with 00000000e627f9df
[   70.446678] evdi: [D] evdi_detect:91 (dev=0) poll connector state: connected
[   70.452244] evdi: [D] evdi_detect:91 (dev=0) poll connector state: connected
[   70.452248] evdi: [D] evdi_painter_get_edid_copy:242 (dev=0) EDID valid
[   70.452303] evdi: [D] evdi_detect:91 (dev=0) poll connector state: connected
[   70.452304] evdi: [D] evdi_painter_get_edid_copy:242 (dev=0) EDID valid
[   71.439841] evdi: [D] evdi_detect:91 (dev=0) poll connector state: connected
[   71.439847] evdi: [D] evdi_painter_get_edid_copy:242 (dev=0) EDID valid
[   71.439906] evdi: [D] evdi_detect:91 (dev=0) poll connector state: connected
[   71.439908] evdi: [D] evdi_painter_get_edid_copy:242 (dev=0) EDID valid

and after reboot the system will get stuck, and can't get into desktop.
and I think the problem is "/etc/modprobe.d/evdi.conf" file, because after I remove it, I can success get into desktop but still not wok on displaylink device.
I try get into tty to show the following message:  ( just reboot and not plug any displaylink device)
![444202](https://user-images.githubusercontent.com/61262346/124371839-500c2b00-dcb8-11eb-9974-08bb27cd5b7c.jpg)

**Comment by lspintzyk** [comment]
What is your output of command:
glxinfo | grep OpenGL

If you have Mesa >=21 then this might be that issue https://github.com/DisplayLink/evdi/issues/279

**Comment by Eddie-064** [comment]
@lspintzyk  I have checked the Mesa version is 19.2.6

**Comment by synaptics-lspintzyk** [comment]
Closing this issue. Please raise new issue when it still happen. Thank you.
