### ISSUE TITLE
EVDI-Kernel 5.13.2 Issues

### ISSUE THREAD

**Issue by FBobbioC** [DisplayLink/evdi#296]
* Are you using the latest driver? Yes, 5.4
    
  * Are you using the latest EVDI version? Yes, 1.9.1
    
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website? Yes, DisplayLink compiles without any issues
    
  * Is this issue related to evdi/kernel? Yes, the issue is related to evdi-kernel
    

  * Linux distribution and its version -- Slackware64-current
  * Linux kernel version -- 5.13.2
  * Xorg version (if used) -- 1.20.12
  * Desktop environment in use -- Plasma 5.22.3 (KDE)

I tried the fixes listed here:  https://github.com/DisplayLink/evdi/issues/275

I still have the issue when compiling with kernel 5.13.2

make[1]: Entering directory '/usr/src/linux-5.13.2'
  CC [M]  /tmp/SBo/evdi-1.9.1/module/evdi_modeset.o
/tmp/SBo/evdi-1.9.1/module/evdi_modeset.c:331:19: error: initialization of ‘void (*)(struct drm_plane *, struct drm_atomic_state *)’ from incompatible pointer type ‘void (*)(struct drm_plane *, struct drm_plane_state *)’ [-Werror=incompatible-pointer-types]
  331 |  .atomic_update = evdi_plane_atomic_update,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~
/tmp/SBo/evdi-1.9.1/module/evdi_modeset.c:331:19: note: (near initialization for ‘evdi_plane_helper_funcs.atomic_update’)
/tmp/SBo/evdi-1.9.1/module/evdi_modeset.c:332:16: error: ‘drm_gem_fb_prepare_fb’ undeclared here (not in a function); did you mean ‘drm_gem_fb_create’?
  332 |  .prepare_fb = drm_gem_fb_prepare_fb
      |                ^~~~~~~~~~~~~~~~~~~~~
      |                drm_gem_fb_create
/tmp/SBo/evdi-1.9.1/module/evdi_modeset.c:336:19: error: initialization of ‘void (*)(struct drm_plane *, struct drm_atomic_state *)’ from incompatible pointer type ‘void (*)(struct drm_plane *, struct drm_plane_state *)’ [-Werror=incompatible-pointer-types]
  336 |  .atomic_update = evdi_cursor_atomic_update,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/SBo/evdi-1.9.1/module/evdi_modeset.c:336:19: note: (near initialization for ‘evdi_cursor_helper_funcs.atomic_update’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:273: /tmp/SBo/evdi-1.9.1/module/evdi_modeset.o] Error 1
make[1]: *** [Makefile:1847: /tmp/SBo/evdi-1.9.1/module] Error 2
make[1]: Leaving directory '/usr/src/linux-5.13.2'
make: *** [Makefile:77: module] Error 2

**Comment by FBobbioC** [comment]
Same issue with 5.13.4

make[1]: Entering directory '/usr/src/linux-5.13.4'
  CC [M]  /tmp/SBo/evdi-1.9.1/module/evdi_platform_drv.o
  CC [M]  /tmp/SBo/evdi-1.9.1/module/evdi_platform_dev.o
  CC [M]  /tmp/SBo/evdi-1.9.1/module/evdi_sysfs.o
  CC [M]  /tmp/SBo/evdi-1.9.1/module/evdi_modeset.o
/tmp/SBo/evdi-1.9.1/module/evdi_modeset.c:331:19: error: initialization of ‘void (*)(struct drm_plane *, struct drm_atomic_state *)’ from incompatible pointer type ‘void (*)(struct drm_plane *, struct drm_plane_state *)’ [-Werror=incompatible-pointer-types]
  331 |  .atomic_update = evdi_plane_atomic_update,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~
/tmp/SBo/evdi-1.9.1/module/evdi_modeset.c:331:19: note: (near initialization for ‘evdi_plane_helper_funcs.atomic_update’)
/tmp/SBo/evdi-1.9.1/module/evdi_modeset.c:332:16: error: ‘drm_gem_fb_prepare_fb’ undeclared here (not in a function); did you mean ‘drm_gem_fb_create’?
  332 |  .prepare_fb = drm_gem_fb_prepare_fb
      |                ^~~~~~~~~~~~~~~~~~~~~
      |                drm_gem_fb_create
/tmp/SBo/evdi-1.9.1/module/evdi_modeset.c:336:19: error: initialization of ‘void (*)(struct drm_plane *, struct drm_atomic_state *)’ from incompatible pointer type ‘void (*)(struct drm_plane *, struct drm_plane_state *)’ [-Werror=incompatible-pointer-types]
  336 |  .atomic_update = evdi_cursor_atomic_update,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/SBo/evdi-1.9.1/module/evdi_modeset.c:336:19: note: (near initialization for ‘evdi_cursor_helper_funcs.atomic_update’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:273: /tmp/SBo/evdi-1.9.1/module/evdi_modeset.o] Error 1
make[1]: *** [Makefile:1852: /tmp/SBo/evdi-1.9.1/module] Error 2
make[1]: Leaving directory '/usr/src/linux-5.13.4'
make: *** [Makefile:77: module] Error 2

**Comment by GuilhermeBarile** [comment]
@FBobbioC it currently works with the `devel` branch

**Comment by dylanmtaylor** [comment]
I can confirm it works with devel. I'm using evdi-git on Arch with the latest non-LTS kernel and it is working fine. Honestly, would love this module to be part of the upstream kernel :)

**Comment by FBobbioC** [comment]
Thank you,  @GuilhermeBarile and @dylanmtaylor.  I downloaded the zip file from the devel branch and replaced the content of the tar.gz file I had from 1.9.1 with the contents of the zip file and was able to repackage and install evdi-kernel.  After a reboot, my Dell D3100 USB 3.0 docking station was able to display the monitors as usual.  Thank you again for pointing me in the right direction.

**Comment by djallits** [comment]
@FBobbioC 

I am trying to replicate your steps, but for some reason the module is not installing. modprobe fails when looking up evdi, which causes the displaylink-driver service to fail.

Any chance you can send step-by-step instructions on what you did?

**Comment by FBobbioC** [comment]
@djallits 

I am using Slackware64-current and have also an NVIDIA chipset for the video card.

I had to modify the /etc/rc.d/rc.local file and add the following lines:
`# Load evdi after reboot
modprobe evdi
cd /usr/lib64/displaylink
./DisplayLinkManager &
# Create missing nvidia device nodes after reboot
/usr/bin/nvidia-modprobe -c 0 -u`

**Comment by djallits** [comment]
Got it. Thank you for taking the time to write this all out.
