### ISSUE TITLE
linux-image-5.8.0-63-generic don't work

### ISSUE THREAD

**Issue by Le-Syl21** [DisplayLink/evdi#298]
Hi,

I'm on Ubuntu 20.04 with kernel linux-image-5.8.0-63-generic drivers: Release: 5.4 | Apr 6, 2021 I doesn't work.
To make it work I need to reboot on kernel 5.8.0-59-generic

Thx in adv

**Comment by Morta1985** [comment]
It's the same issue like the latest Kernel Bug. Wait new pull of evdi which works with Kernel 5.13

**Comment by synaptics-lspintzyk** [comment]
Support for 5.8 and newer kernels is added every new evdi relese. 

Other issues mentioned by @peddanet  might be related with lack of libssl or some encryption utilities. I suggest to use deb packages from https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu

If this still happening on latest displaylink-drivers.Please raise new issue. 
Meanhwile I am closing this issue.
