### ISSUE TITLE
Fedora 24 - works after updating drm API calls

### ISSUE THREAD

**Issue by RogerOdle** [DisplayLink/evdi#30]
After updating Fedora 24, the kernel is 4.6.3-300.fc24.x86_64
Tried to install displaylink-1.0.335-1.x86_64.rpm but evdi kernel module would not load. Made a few source code mods to get it to build.  Now installed and looks ok.

evdi_fb.c :
dma_buf_begin_cpu_access() and dma_buf_end_cpu_access() have only 2 args (*dma_buf and dir) instead of the 4 parameters used in evdi_fb.c.  The API calls will succeed with only these two args so the 2nd and 3rd parameters in each call can be dropped.

Change parameter list:
static int
evdi_framebuffer_init(struct drm_device *dev,
                      struct evdi_framebuffer *ufb,
                      struct drm_mode_fb_cmd2 *mode_cmd,
                      struct evdi_gem_object *obj)
to

static int
evdi_framebuffer_init(struct drm_device *dev,
                      struct evdi_framebuffer *ufb,
                      const struct drm_mode_fb_cmd2 *mode_cmd,
                      struct evdi_gem_object *obj)

then install the driver using the drmk

(module may already be registered if you tried to install the RPM)
dkms add -m evdi -v 1.0.335
dkms build -m evdi -v 1.0.335
dkms install -m evdi -v 1.0.335

You should now be able to start the displaylink service.  When it is enabled, it should autostart when you plug in the display.  This works with the ASUS MB169 display.

**Comment by DawidKurek** [comment]
Hi @RogerOdle, thanks for you input. 
**1.0.335** is the previous release of DisplayLink for Ubuntu. 
There is new one: **1.1.62** (http://www.displaylink.com/downloads/ubuntu) 
which should already have necessary fixes for kernel 4.6.
