### ISSUE TITLE
Resolution 5120 x 1440 @ 60Hz marked as invalid, mode not being set in DRM

### ISSUE THREAD

**Issue by Devern** [DisplayLink/evdi#304]
Distribution: Fedora 34
Kernel: 5.13.10-200.fc34.x86_64
Windowing system: Wayland (Mutter)

Displaylink Version: 5.4.0-1
EVDI Version: 1.9.1

Been troubleshooting this one a while, and discovered that I could get debug logs for DRM. It's stated plainly what's happening:
```
kernel: [drm:drm_mode_debug_printmodeline [drm]] Modeline "5120x1440": 120 966000 5120 5168 5200 5280 1440 1443 1453 1525 0x48 0x9
kernel: [drm:drm_mode_prune_invalid [drm]] Not using 5120x1440 mode: VIRTUAL_X
kernel: [drm:drm_mode_debug_printmodeline [drm]] Modeline "5120x1440": 100 797250 5120 5168 5200 5280 1440 1443 1453 1510 0x40 0x9
kernel: [drm:drm_mode_prune_invalid [drm]] Not using 5120x1440 mode: VIRTUAL_X
kernel: [drm:drm_mode_debug_printmodeline [drm]] Modeline "5120x1440": 60 469000 5120 5168 5200 5280 1440 1443 1453 1481 0x40 0x9
kernel: [drm:drm_mode_prune_invalid [drm]] Not using 5120x1440 mode: VIRTUAL_X
```
This same hardware configuration works fine in Windows 10 (dual-boot).
I suspect the reason for this is due to the maximum width set in the validation prior to passing modes to DRM:
https://github.com/DisplayLink/evdi/blob/v1.9.1/module/evdi_modeset.c#L455-L456

[drm_debug.txt](https://github.com/DisplayLink/evdi/files/7022596/drm_debug.txt)

**Comment by Devern** [comment]
Just to update: 
- I have patched the line in evdi_modeset.c to set mode_config.max_width to 5280 locally
- make; make install; systemctl reboot
- GNOME settings now has the full display resolution of 5120x1440 available
- Selecting this option results in successfully display at native resolution on my display

**Comment by groovyman** [comment]
Just one question (with regard to my provlems #299  https://github.com/DisplayLink/evdi/issues/299) 
Does your modification also change the access to the display link chip. I would like to see my StarTech Docking station working with 3 4K monitors, but actually it recognize ony 2 of them).

**Comment by Devern** [comment]
> Just one question (with regard to my provlems #299 #299)
> Does your modification also change the access to the display link chip. I would like to see my StarTech Docking station working with 3 4K monitors, but actually it recognize ony 2 of them).

@groovyman I doubt this would do anything for a 3rd display not being detected in the case of issue #299 ; this patch simply allows for higher resolution modes to be set after parsing EDID information provided by the display.

**Comment by displaylink-emajewsk** [comment]
We noticed this recently during testing. It will be fixed in the next release. 😇 Thanks for reporting nonetheless, @Devern 

@groovyman This isn't related to evdi, since the third display is provided by DP alt-mode. I'm sorry.
