### ISSUE TITLE
compile error with kernel 4.4.0-31

### ISSUE THREAD

**Issue by pdefert** [DisplayLink/evdi#31]
Hello 

This morning ubuntu 16.04 upgrade the kernel to 4.4.0.31 . Displaylink does not start
and evdi  doesn't compile

`make

CFLAGS="-Werror -Wextra -Wall" make -C module 
make[1] : on entre dans le répertoire « /home/defert/Dev/evdi/evdi/module »
make -C /lib/modules/4.4.0-31-generic/build M=$PWD
make[2] : on entre dans le répertoire « /usr/src/linux-headers-4.4.0-31-generic »
  LD      /home/defert/Dev/evdi/evdi/module/built-in.o
  CC [M]  /home/defert/Dev/evdi/evdi/module/evdi_drv.o
  CC [M]  /home/defert/Dev/evdi/evdi/module/evdi_modeset.o
/home/defert/Dev/evdi/evdi/module/evdi_modeset.c:345:15: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .fb_create = evdi_fb_user_fb_create,
               ^
/home/defert/Dev/evdi/evdi/module/evdi_modeset.c:345:15: note: (near initialization for ‘evdi_mode_funcs.fb_create’)
cc1: all warnings being treated as errors
scripts/Makefile.build:258 : la recette pour la cible « /home/defert/Dev/evdi/evdi/module/evdi_modeset.o » a échouée
make[3]: *** [/home/defert/Dev/evdi/evdi/module/evdi_modeset.o] Erreur 1
Makefile:1403 : la recette pour la cible « _module_/home/defert/Dev/evdi/evdi/module » a échouée
make[2]: *** [_module_/home/defert/Dev/evdi/evdi/module] Erreur 2
make[2] : on quitte le répertoire « /usr/src/linux-headers-4.4.0-31-generic »
Makefile:55 : la recette pour la cible « module » a échouée
make[1]: *** [module] Erreur 2
make[1] : on quitte le répertoire « /home/defert/Dev/evdi/evdi/module »
Makefile:8 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
`

**Comment by DawidKurek** [comment]
Hi @pdefert,
thanks for reporting this issue. I will take a look at this.

**Comment by displaylink-mlukaszek** [comment]
The module code have been adjusted to kernels up to 4.7 - closing.
