### ISSUE TITLE
EVDI doesn't work on kernel 5.14

### ISSUE THREAD

**Issue by MrZomka** [DisplayLink/evdi#312]
* Are you using the latest driver?
    Yes.
  * Are you using the latest EVDI version?
    Yes
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
    Yes.
  * Is this issue related to evdi/kernel?
    Yes.

  * Linux distribution and its version - Manjaro KDE 21.02
  * Linux kernel version - 5.14
  * Xorg version (if used) - I don't think I use it?
  * Desktop environment in use - KDE Plasma

Hello!
Yesterday I got a ThinkPad Hybrid USB-C with USB-A dock, it works perfectly on Windows but on Linux the monitor output doesn't work, when I tried to install EVDI, it didn't install but when I tried installing it with kernel 5.12, it installed just fine! The problem is, I can't use kernel 5.12 because my laptop is lagging on it because it has a 4th gen AMD Ryzen CPU. So, if you could update it to work on kernel 5.14, that would be great.
Thanks!

**Comment by wvdakker** [comment]
The development tree works op with 5.14

**Comment by MrZomka** [comment]
> The development tree works op with 5.14
> […](#)
> On Fri, 2021-10-01 at 03:55 -0700, MrZomka wrote: * Are you using the latest driver? * Are you using the latest EVDI version? * If you are using a DisplayLink device, have you checked 'troubleshooting' on DisplayLink's website? * Is this issue related to evdi/kernel? * Linux distribution and its version - Manjaro KDE 21.02 * Linux kernel version - 5.14 * Xorg version (if used) - I don't think I use it? * Desktop environment in use - KDE Plasma — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Uh... How do I compile it? 😅

**Comment by wvdakker** [comment]
Usualy with DKMS.

dkms add -m evdi -v 1.9.1
dkms build -m evdi -v 1.9.1
dkms install -m evdi -v 1.9.1

**Comment by shepda** [comment]
As you're using Manjaro you could try evdi-git from the AUR...I've just tried it and it's working fine with Linux 5.14.8

**Comment by MrZomka** [comment]
> As you're using Manjaro you could try evdi-git from the AUR...I've just tried it and it's working fine with Linux 5.14.8

Yeah I did but I found out that I have a whole another issue. https://github.com/DisplayLink/evdi/issues/248
