### ISSUE TITLE
20.04 & 21.04: With Display Port  & HDMI in use for dual monitors, both grub and Windows hang

### ISSUE THREAD

**Issue by theno2soco** [DisplayLink/evdi#317]
1. If both monitors are connected on booting grub (one is Display Post and is primary and the other is HDMI), hangs and never gets to the desktop.
If I try the same using Windows, it boots to the desktop but hangs and is never usable.

2. If I just connect the primary (Display Port) monitor, both grub and Windows boot normally.

3. If the second monitor is turned off grub still hangs. I must not connect the HDMI cable before grub will boot.

4. If I plug in the HDMI cable AFTER booting grub, the second monitor takes over and the desktop completely moves to the second monitor. Setting the Primary monitor in Display settings makes no difference.

/usr/share/doc/xserver-xorg-video-intel/xorg.conf:

`Section "Device"
        Identifier "Intel"
        Driver "intel"
:#       Option "AccelMethod" "uxa"
EndSection`

System Information:

`makem@makems-TUF:~$ lsb_release -a
No LSB modules are available.
Distributor ID:    Ubuntu
Description:    Ubuntu 21.04
Release:    21.04
Codename:    hirsute
makem@makems-TUF:~$ sudo update-pciids
[sudo] password for makem: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  272k  100  272k    0     0   847k      0 --:--:-- --:--:-- --:--:--  845k
Done.
makem@makems-TUF:~$ lspci | grep -i --color 'vga\|3d\|2d'
00:02.0 VGA compatible controller: Intel Corporation RocketLake-S GT1 [UHD Graphics 750] (rev 04)
00:17.0 SATA controller: Intel Corporation Device 43d2 (rev 11)
makem@makems-TUF:~$ lspci -v -s 00:02.0
00:02.0 VGA compatible controller: Intel Corporation RocketLake-S GT1 [UHD Graphics 750] (rev 04) (prog-if 00 [VGA controller])
	DeviceName: Onboard - Video
	Subsystem: ASUSTeK Computer Inc. Device 8694
	Flags: bus master, fast devsel, latency 0, IRQ 159
	Memory at 6000000000 (64-bit, non-prefetchable) [size=16M]
	Memory at 4000000000 (64-bit, prefetchable) [size=256M]
	I/O ports at 4000 [size=64]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915
makem@makems-TUF:~$`

Monitor 1:
MSI Optix G241 Esports Gaming IPS Monitor

2x HDMI (1.4b)
1x Display Port (1.2a)
This monitor is attached to the Display Port

Monitor 2:
ASUS VS248HR

Signal Input : HDMI, D-Sub, DVI-D
AV Audio Input : HDMI
This monitor is attached to the HDMI port

**Comment by theno2soco** [comment]
![20211029_193439](https://user-images.githubusercontent.com/82050970/139485856-0faa421f-759f-4e8e-acb5-11b415969e19.jpg)

**Comment by theno2soco** [comment]
This issue is in the wrong place. Please remove it.

**Comment by displaylink-mlukaszek** [comment]
Closing per previous comment. I don't necessarily see where evdi or DisplayLink docking station is used, and this issue mentions Windows, too.
