### ISSUE TITLE
DisplayLink / EVDI Fails to Load After Kernel Upgrade to 5.15.2

### ISSUE THREAD

**Issue by djallits** [DisplayLink/evdi#319]
* Are you using the latest driver?
    v5.4.1-1 (https://aur.archlinux.org/packages/displaylink/)
  * Are you using the latest EVDI version?
    v1.9.1.r4.gb0b3d13-1 (https://aur.archlinux.org/packages/evdi-git)
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
    Yes
  * Is this issue related to evdi/kernel?
    Yes

  * Linux distribution and its version: Arch Linux
  * Linux kernel version: Linux 5.15.2-arch1-1 x86_64
  * Xorg version: N/A
  * Desktop environment in use: GNOME 41

**Comment by realitix** [comment]
Same problem here, I can't use my screens anymore...

/var/lib/dkms/evdi/1.9.1/build/evdi_drm_drv.h:23:10: erreur fatale: drm/drm_irq.h : Aucun fichier ou dossier de ce type
   23 | #include <drm/drm_irq.h>
      |          ^~~~~~~~~~~~~~~

**Comment by realitix** [comment]
SEE #308

**Comment by djallits** [comment]
This ticket is a duplicate of  #308 . There is a workaround mentioned in that ticket that builds successfully.
