### ISSUE TITLE
Fedora 35 super laggy with spam on dmesg only somehow working on Wayland

### ISSUE THREAD

**Issue by kamdeb6x3** [DisplayLink/evdi#328]
```Fedora 35``` on ```5.15.5-200.fc35.x86_64``` kernel
DisplayLink → ```fedora-34-displaylink-1.9.1-1.x86_64.rpm```
EVDI → https://github.com/nilathedragon/evdi (Only this EVDI version I can compile on this version of kernel.)
Host → Nitro AN515-42 V1.18
DE → Plasma 5.23.3
WM → KWin
CPU → AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx (8) @ 2.000GHz

As I'm trying to connect Toshiba Dynadock PA3927E-1PRP USB3 via HDMI to my second monitor it works super laggy on Wayland.

It runs even worse on X11.

I cannot compile EVDI → https://github.com/DisplayLink/evdi because it gives me an error: drm/drm.h: No such file or directory

When dock station is connected an second monitor is active it spams my dmesg with:

```
[  499.354954] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  499.444852] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  499.541495] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  499.638264] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  499.734476] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  499.826877] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  499.919832] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  500.010354] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  500.102204] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  500.191099] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  500.278920] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  500.368719] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  500.460263] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  500.547712] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
```

And it goes on and on...

**Comment by tberta** [comment]
Have you tried the following options:
```
// Modify /etc/modprobe.d/evdi.conf file to have the following content:
options evdi initial_loglevel=0 initial_device_count=4 disable_texture_import=1
```
And restart.
The kernel messages disappeared on my system after adding those options.

**Comment by displaylink-emajewsk** [comment]
Hi. Instead of doing `disable_texture_import=1`. Could you please try the current `devel` and report the results?

**Comment by kamdeb6x3** [comment]
Okay there is much improvement, I can compile ```devel``` branch and I works better on Wayland but still super laggy on X11. 
I see no spam on ```dmesg``` also so that's nice. Thank you very much!

**Comment by kamdeb6x3** [comment]
But there showed up another spam on dmesg...
```
[  497.925888] evdi: [W] evdi_framebuffer_sanitize_rect:76 Wrong clip rect: x2 > fb.width
[  497.929758] evdi: [W] evdi_framebuffer_sanitize_rect:66 Wrong clip rect: x1 > fb.width
[  497.929764] evdi: [W] evdi_framebuffer_sanitize_rect:76 Wrong clip rect: x2 > fb.width
[  497.929765] evdi: [W] evdi_framebuffer_sanitize_rect:66 Wrong clip rect: x1 > fb.width
[  497.929766] evdi: [W] evdi_framebuffer_sanitize_rect:76 Wrong clip rect: x2 > fb.width
[  497.933788] evdi: [W] evdi_framebuffer_sanitize_rect:66 Wrong clip rect: x1 > fb.width
[  497.933793] evdi: [W] evdi_framebuffer_sanitize_rect:76 Wrong clip rect: x2 > fb.width
[  497.933795] evdi: [W] evdi_framebuffer_sanitize_rect:66 Wrong clip rect: x1 > fb.width
```

**Comment by displaylink-emajewsk** [comment]
Is this on X11 or Wayland?

**Comment by kamdeb6x3** [comment]
On wayland because as I wrote on X11 it's unusable

**Comment by displaylink-emajewsk** [comment]
Sure. I don't think we can do much about X11 on `amugpu` in the near future, unfortunately.

Do you experience any visual glitches? It's just a warning this time, if you wish, those can be turned off with `sudo sh "echo 2 > /sys/devices/evdi/loglevel"`

**Comment by kamdeb6x3** [comment]
Okay it's so close to working but now there is again this dmesg spam:
```
[  420.081910] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  420.166172] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  421.713808] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  421.806414] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  421.891575] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  421.971001] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  422.052956] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  423.087108] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  423.207249] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  423.298123] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
[  425.230711] evdi evdi.0: cannot be used for peer-to-peer DMA as it is not a PCI device
```

**Comment by kamdeb6x3** [comment]
Unfortunately my laptop only has one USB3 port others two are USB2 and it has USB-C but without Thunderbolt support. Correct me if I'm wrong and your talking about other technology that I should take a look at in notebook documentation.

**Comment by groovyman** [comment]
> Unfortunately my laptop only has one USB3 port other two are USB2 and it has USB-C but without Thunderbolt support. Correct me if I'm wrong and your talking about other technology that I should take a look at in notebook documentation.

Salut, umpf .. ok, what  model is your notebook?

As far as i know is: Thunderbold3 is not USB-C DP. Thunderbold 3 maps the PCIe3 Standard intro a cable, that looks like a USB-C. USB-C (Alt) DP maps the DisplayPort signal parallel to the USB3 signals on different line. So we might have:

- USB3 with USB3 Gen2 with 10Mbit  and USB3 Gen2x2 that comes with the double throughput.
-  USB3 (Alt) DP  that uses 4 lines (am i riight), that transports the DisplayPort protocols
-  Thunderbold 3/4 that is completly different and only available for Apple and some mondern Intel-Notebooks.

**Comment by kamdeb6x3** [comment]
Okaaaay you made me intrested!
I found on official Acer website this information:  ```USB Type-C port supporting: USB 3.1 Gen 1 (up to 5 Gbps)``` on https://www.acer.com/datasheets/2018/4876/AN515-42/NH.Q3RAA.002.html

Notebook model: Acer Nitro 5 AN515-42

**Comment by kamdeb6x3** [comment]
Yeeeah Acer <3 Anyway so I have no other options left besides DisplayLink dock?

**Comment by jakub-prussak-synaptics** [comment]
I will close the issue for the time being, let us know if the problems are still appearing.
