### ISSUE TITLE
warnings on snprintf for recent compilers like gcc version 11.2.0 (GCC) (with patch)

### ISSUE THREAD

**Issue by juvanham** [DisplayLink/evdi#335]
evdi_lib.c: In function ‘find_unused_card_for’:
evdi_lib.c:475:44: error: ‘%s’ directive output may be truncated writing up to 4095 bytes into a region of size 4089 [-Werror=format-truncation=]
  475 |         snprintf(link_path, PATH_MAX - 7, "%s/device", dirname);
      |                                            ^~
......
  521 |                 if (!is_correct_parent_device(evdi_path, parent_device))
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
evdi_lib.c:475:9: note: ‘snprintf’ output between 8 and 4103 bytes into a destination of size 4089
  475 |         snprintf(link_path, PATH_MAX - 7, "%s/device", dirname);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
evdi_lib.c:526:74: error: ‘/drm’ directive output may be truncated writing 4 bytes into a region of size between 1 and 4096 [-Werror=format-truncation=]
  526 |                 snprintf(evdi_drm_path, PATH_MAX - strlen(evdi_path), "%s/drm", evdi_path);
      |                                                                          ^~~~
evdi_lib.c:526:17: note: ‘snprintf’ output between 5 and 4100 bytes into a destination of size 4096
  526 |                 snprintf(evdi_drm_path, PATH_MAX - strlen(evdi_path), "%s/drm", evdi_path);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
evdi_lib.c: In function ‘evdi_check_device’:
evdi_lib.c:619:50: error: ‘/drm/card’ directive output may be truncated writing 9 bytes into a region of size between 1 and 4096 [-Werror=format-truncation=]
  619 |                 snprintf(card_path, PATH_MAX, "%s/drm/card%d", path, device);
      |                                                  ^~~~~~~~~
evdi_lib.c:619:17: note: ‘snprintf’ output between 11 and 4116 bytes into a destination of size 4096
  619 |                 snprintf(card_path, PATH_MAX, "%s/drm/card%d", path, device);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [<builtin>: evdi_lib.o] Error 1

  * Slackware-current 15.0
  * Linux 5.15.11

please find my patch below:

From: Jurgen Van Ham <juvanham.tc@gmail.com>
Date: Sat, 25 Dec 2021 08:51:49 +0100
Subject: [PATCH] fix format overflows for snprintf e.g. for gcc 11.2.0

---
 library/evdi_lib.c | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/library/evdi_lib.c b/library/evdi_lib.c
index 83078f2..70e8419 100644
--- a/library/evdi_lib.c
+++ b/library/evdi_lib.c
@@ -514,7 +514,7 @@ static int find_unused_card_for(const char *parent_device)
                if (strncmp(fd_entry->d_name, "evdi", 4) != 0)
                        continue;
 
-               char evdi_path[PATH_MAX];
+               char evdi_path[PATH_MAX-14];
 
                snprintf(evdi_path, PATH_MAX, "%s/%s", evdi_platform_root, fd_entry->d_name);
 
@@ -629,7 +629,7 @@ static enum evdi_device_status evdi_device_to_platform(int device, char *path)
 
 enum evdi_device_status evdi_check_device(int device)
 {
-       char path[PATH_MAX];
+       char path[PATH_MAX-10];
 
        return evdi_device_to_platform(device, path);
 }
-- 
2.34.1

**Comment by chiddekel** [comment]
It's compile with these patch. And My EVDI based device work.
