### ISSUE TITLE
EDID detection error with Qnix 1440p monitor in Linux

### ISSUE THREAD

**Issue by willstare** [DisplayLink/evdi#336]
* Are you using the latest driver? Yes - 5.5 beta
    
  * Are you using the latest EVDI version? Yes, the current devel from Github (1.10)
    
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website? - Yes 
    
  * Is this issue related to evdi/kernel? EVDI I believe
    

  * Linux distribution and its version- Ubuntu Budgie 20.04
  * Linux kernel version - x86_64 Linux 5.11.0-43-generic
  * Xorg version (if used) - 2:1.20.13-1ubuntu1~20.04.2 
  * Desktop environment in use - Budgie

Hi,
I have a Qnix 1440p monitor connected via dual-link DVI (using an active displayport adapter). This setup works well with Displaylink on Windows, but has trouble on Linux. I receive the following  after connecting the monitor in Ubuntu:
>evdi: [E] evdi_painter_connect:864 Wrong edid size. Expected 256 but is 128

I got crafty and modified the evdi_painter.c module to calculate the expected_edid_size by looking at the size of the edid struct only (as that was correctly reported as 128).
>expected_edid_size = sizeof(struct edid);

This allowed the monitor to be detected by the OS but at the wrong resolution. I then assigned a resolution via xrandr (using cvt/gtf to generate the Modeline)
>xrandr --newmode "qnix2560x1440_60.00"  311.83  2560 2744 3024 3488  1440 1441 1444 1490  -HSync +Vsync
>xrandr --output DVI-I-1-1 --mode qnix2560x1440_60.00

Now the monitor is fully working at 1440p 60. 

I see my dmesg is clogged with wrong EDID's and warnings.
>[ 1014.526113] evdi: [I] (card0) Connector state: connected
[ 1014.526131] [drm] EDID checksum is invalid, remainder is 38
[ 1014.526134] Raw EDID:
[ 1014.526137]  	80 43 02 00 80 07 d8 07 04 08 98 08 00 00 38 04
[ 1014.526141]  	3c 04 41 04 65 04 00 00 05 00 00 00 00 00 00 00
[ 1014.526144]  	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[ 1014.526146]  	00 00 00 00 00 00 00 00 00 00 00 00 00 00 40 00
[ 1014.526149]  	14 08 bd 19 4f ac b5 35 22 01 00 00 00 00 ad de
[ 1014.526152]  	31 39 32 30 78 31 30 38 30 00 00 00 00 00 00 00
[ 1014.526154]  	00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[ 1014.526157]  	00 00 00 00 02 00 00 00 00 00 00 00 00 00 00 00
[ 1014.526166] evdi evdi.0: [drm] DVI-I-1: EDID invalid.
[ 1014.526172] evdi: [I] (card0) Edid property set

I am wondering how/why this is happening in Ubuntu but not Windows. I can pull the EDID via the Displaylink adapter in Windows. 
>00 ff ff ff ff ff ff 00 31 d8 00 00 00 00 00 00 
05 16 01 03 6d 42 25 78 ea 5e c0 a4 59 4a 98 25 
20 50 54 00 00 00 21 c0 01 01 01 01 01 01 01 01 
01 01 01 01 01 01 56 5e 00 a0 a0 a0 29 50 30 20 
35 00 9a 77 21 00 00 1e 00 00 00 ff 00 4c 69 6e 
75 78 20 23 30 0a 20 20 20 20 00 00 00 fd 00 3b 
3d 57 59 19 00 0a 20 20 20 20 20 20 00 00 00 fc 
00 32 35 36 30 78 31 34 34 30 0a 20 20 20 00 69 

Thank you!

**Comment by displaylink-emajewsk** [comment]
Hi! Thanks for reporting this issue. This seems to be a problem in the most recent firmware. It should be fixed in 5.5 full release.

**Comment by willstare** [comment]
Wonderful, thank you for the update. Appreciate your help and time.

**Comment by VGerris** [comment]
I have a similar or the same issue. I wonder why this is closed while the 5.5 release is not out. I have it with the current 5.5 beta.
evdi: [E] evdi_painter_connect:875 Wrong edid size. Expected 256 but is 128
also no working second display on both 5.13 and 5.15 kernels with a D6000 dock.

**Comment by displaylink-emajewsk** [comment]
The user closed it, but you're right, I'll reopen it until a fix is released

**Comment by displaylink-emajewsk** [comment]
I'm afraid the firmware fix won't make it into the release. I'll keep pushing, and in the meantime, I'm writing a workaround to alleviate the issue.
FYI, the problem should appear only on DisplayPort connections. HDMI should be fine.

**Comment by displaylink-emajewsk** [comment]
@willstare @VGerris would you mind uploading your failing EDIDs, so that we can verify the fix?

**Comment by VGerris** [comment]
hi @displaylink-emajewsk sure, can you explain exactly what to do? I am running a 5.12 kernel now with the stable driver to have things work. Do I need to run the beta driver and 5.13 or newer kernel or can you post a command that will give you what you need? Thank you

**Comment by displaylink-emajewsk** [comment]
@VGerris sure, the edid files for displays connected to our docks should appear in `/var/log/displaylink/`

**Comment by displaylink-emajewsk** [comment]
Oh, and yes, please use the stable driver, as the one from the beta would be corrupted. Kernel version shouldn't make a difference

**Comment by VGerris** [comment]
[DELL U2414H_DELA0.zip](https://github.com/DisplayLink/evdi/files/8141214/DELL.U2414H_DELA0.zip)
hi, here there are

**Comment by displaylink-emajewsk** [comment]
@VGerris Oh, good news then! We've already checked this one and it works with the new driver. :)

**Comment by VGerris** [comment]
Is that the one that will be releases? I just checked and saw no newer version : https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu . coming soon :)?

**Comment by displaylink-emajewsk** [comment]
Yes :)

**Comment by displaylink-emajewsk** [comment]
@VGerris Hi. Would you please confirm if the newest driver fixed this issue for you? Many thanks

**Comment by VGerris** [comment]
hi @displaylink-emajewsk , yes it works great, also with 5.15 kernel. I am using the nouveau driver. Thank you very much.
This is on Ubuntu 22.04 (dev) using Wayland.

**Comment by willstare** [comment]
Sorry, this did resolve my issue!! Thanks!
