### ISSUE TITLE
Evdi 1.10 does not work with Displaylink 5.4.1

### ISSUE THREAD

**Issue by p91paul** [DisplayLink/evdi#338]
* Linux distribution and its version: Arch Linux
  * Linux kernel version: 5.10.88-2-lts
  * Xorg version (if used): Wayland or Xorg 21.1.2-2
  * Desktop environment in use: Gnome
  * Displaylink version: 5.4.1

Upgrading to evdi 1.10 (I'm using the AUR package), my screens don't get recognized anymore. My external monitors aren't even there in Gnome settings to be selected.
Downgrading to 1.9.1 fixes the issue.
I get no errors related to evdi or DisplayLink in journalctl.
If you point me to where to look, I can upgrade again and do some tests.

**Comment by jcfrosty** [comment]
I'm having a similar issue. evdi is loaded, but there is no additional providers listed when I xrandr --listproviders.

**Comment by F1iX** [comment]
Thanks for the hint! In case of using the AUR package evdi-git, simply change `source[0]+='#branch=devel'` to `source[0]+='#commit=d6b28414a4ceb41a904077318b48fa8a7d8981d1'` in `PKGBUILD` and run `makepkg -si`

**Comment by displaylink-emajewsk** [comment]
Hi @p91paul 
evdi 1.10 is meant to be used with the most recent displaylink 5.5 beta driver, which in turn shouldn't work with evdi 1.9. Are you sure you're using the correct versions?

**Comment by p91paul** [comment]
I'm sure I'm not using dl 5.5 beta. That explains it, so I should hold the evdi package until a corresponding dl update of 5.5 stable comes through. I didn't see anywhere that backwards compatibility wasn't to be expected. My 2 cents: evdi 2.0 would be a more appropriate version naming because of this.

**Comment by displaylink-emajewsk** [comment]
They were really meant to be bundled together (driver + evdi). I hope we can do something to alleviate some of the confusion related to this in the near future. 🤞🏼
I know it's perhaps a little unconventional, but evdi's minor version is not backwards compatible, while the "patch" version is. I'm sorry for the confusion!

**Comment by p91paul** [comment]
I updated issue description so that maybe folks coming from the Internet will find the solution more easily.

A suggestion: your "new issue" template does not feature a "Displaylink version" field (I now modified my first comment to add it)

**Comment by francoism90** [comment]
I case anyone wants to run the beta:
```
# Maintainer: rHermes <teodor_spaeren@riseup.net>
# Maintainer: bnavigator <code@bnavigator.de>
# Contributor: PlusMinus
# Contributor: rhabbachi

pkgname=displaylink
pkgver=5.5.0
_releasedate=2021-09
_pkgfullver=5.5.0-beta-59.118
pkgrel=1
pkgdesc="Linux driver for DL-6xxx, DL-5xxx, DL-41xx and DL-3x00"
arch=('i686' 'x86_64' 'arm' 'armv6h' 'armv7h' 'aarch64')
url=""
license=('custom' 'GPL2' 'LGPL2.1')
depends=('evdi>=1.9.1'
         'libusb>=1.0.0')
makedepends=('grep' 'gawk' 'wget')
install=
source=(displaylink-driver-${pkgver}.zip::https://www.synaptics.com/sites/default/files/exe_files/2021-12/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu%20%28Beta%295.5%20Beta-EXE.zip
        DISPLAYLINK-EULA
        udev.sh
        99-displaylink.rules 
	displaylink.service 
        displaylink-sleep.sh)
sha256sums=('aaa6f2c6d8c4492d18cf670466f4bbf6d1ccdbb3c39ccc4ca20b4e5bc3352d56'
            '2f81fea43332a62b2cf1dd47e56ea01caf1e886bcd16c3f82b18bfe148fb21a9'
            'dc41ae8a2c287fc50fdda65bad8b0ffd76726f7773c25e1b0c5b7de95cecbdb6'
            'c08a4726cf4e2f92c7cab00168ae9cc8d69d36a67c570609396a4a674934245a'
            '342e83abfe2a38d5635ea928345e933d2ad127ebd3f7caca476663d4f583684b'
            '8be4ab7616e38f91746bdd3e7fafe9004322a8be8e6722389746df9868d576e0')

# Update with > updpkgsums

package() {
  echo "Adding udev rule for DisplayLink DL-3xxx/5xxx devices"
  install -D -m644 99-displaylink.rules "$pkgdir/etc/udev/rules.d/99-displaylink.rules"
  install -D -m755 udev.sh "$pkgdir/opt/displaylink/udev.sh"

  echo "Installing DLM systemd service"
  install -D -m644 displaylink.service "$pkgdir/usr/lib/systemd/system/displaylink.service"
  install -D -m755 displaylink-sleep.sh "$pkgdir/usr/lib/systemd/system-sleep/displaylink.sh"
  
  COREDIR="$pkgdir/usr/lib/displaylink"
  install -d -m755 $COREDIR
  install -d -m755 "$pkgdir/var/log/displaylink"

  echo "Extracting DisplayLink Driver Package"
  pushd $srcdir
  chmod +x displaylink-driver-${_pkgfullver}.run
  ./displaylink-driver-${_pkgfullver}.run \
     --noexec \
     --target $pkgname-$pkgver \
     --nox11 \
     --noprogress
  test -d $pkgname-$pkgver || (echo "Extracting the driver with the .run installer failed"; exit 1)
  pushd $pkgname-$pkgver
  
  case $CARCH in
    i686)
      ARCH="x86-ubuntu-1604" ;;
    x86_64)
      ARCH="x64-ubuntu-1604" ;;
    arm|armv6h|armv7h|aarch64)
      ARCH="arm-linux-gnueabihf" ;;
  esac
  
  echo "Installing DisplayLink Manager $ARCH"
  install -D -m755 $ARCH/DisplayLinkManager $COREDIR/DisplayLinkManager

  echo "Installing firmware packages"
  install -D -m644 *.spkg $COREDIR

  echo "Installing license file"
  install -D -m644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
  popd
  popd
  install -D -m644 DISPLAYLINK-EULA "${pkgdir}/usr/share/licenses/${pkgname}/DISPLAYLINK-EULA"
}
```
It's a bit dirty, but it works.

**Comment by francoism90** [comment]
For Arch Linux users, I've created a `displaylink-beta` PKG: https://aur.archlinux.org/packages/displaylink-beta/

**Comment by displaylink-emajewsk** [comment]
Closing as this is an issue with AUR and not evdi.
