### ISSUE TITLE
ChromeOS patch "Implement pin/unpin GEM object functions" was merged incorrectly.

### ISSUE THREAD

**Issue by akmistry** [DisplayLink/evdi#340]
It looks like the ChromeOS patch https://chromium.googlesource.com/chromiumos/third_party/kernel/+/abe08f482733f428f050ae12a59ea1fe8b805810%5E%21/ was merged incorrectly into this repo.

The merged code in this repo looks like:
```
int evdi_gem_vmap(struct evdi_gem_object *obj)
{
	...
	ret = evdi_pin_pages(obj);
	ret = evdi_gem_get_pages(obj, GFP_KERNEL);
	if (ret)
		return ret;
```

But the ChromeOS kernel looks like:
```
int evdi_gem_vmap(struct evdi_gem_object *obj)
{
	...
	ret = evdi_pin_pages(obj);
	if (ret)
		return ret;

```

The call to `evdi_pin_pages` was meant to replace `evdi_gem_get_pages`. With the old call to `evdi_gem_get_pages` kept, there appears to be a memory leak since the backing pages will be allocated twice, with the first allocation overwritten (and lost). I think there's also a nullptr-dereference in the unmap side, but I haven't tested this.

**Comment by displaylink-emajewsk** [comment]
Good catch! I'm not sure where this error could have been introduced since all I did with this one was a cherry-pick. 🤔 Thanks, I'll fix it.

**Comment by displaylink-emajewsk** [comment]
Closing as this will be fixed in the next release. Thanks, again!

**Comment by suprsrsly** [comment]
Hello,

I'm picking this up from akmistry, I just wanted to follow up here to ensure that this fix has been made. Looking in the file DisplayLink/evdi/blob/master/module/evdi_gem.c in the `devel` branch, the fix suggested by this issue has not been applied yet.

What should we look out for to make sure it makes it into the next release?

Thanks!
