### ISSUE TITLE
5.5 Beta fails to make evdi module for kernel line 5.13.0

### ISSUE THREAD

**Issue by astromatt42** [DisplayLink/evdi#341]
DKMS fails to make the evdi module for kernels 5.13.0.21/22/23/25

make.log

DKMS make.log for evdi-5.2.14 for kernel 5.13.0-25-generic (x86_64)
Tue 11 Jan 2022 12:10:23 AEDT
make KBUILD_VERBOSE=1 SUBDIRS=/var/lib/dkms/evdi/5.2.14/build SRCROOT=/var/lib/dkms/evdi/5.2.14/build CONFIG_MODULE_SIG= -C /lib/modules/5.13.0-25-generic/build modules
make[1]: Entering directory '/usr/src/linux-headers-5.13.0-25-generic'
make -f ./scripts/Makefile.build obj=arch/x86/entry/syscalls all
make -f ./scripts/Makefile.build obj=scripts/basic
set -e; mkdir -p include/config/; trap "rm -f include/config/.kernel.release.tmp" EXIT; { echo "5.13.19$(sh ./scripts/setlocalversion .)"; } > include/config/.kernel.release.tmp; if [ ! -r include/config/kernel.release ] || ! cmp -s include/config/kernel.release include/config/.kernel.release.tmp; then : '  UPD     include/config/kernel.release'; mv -f include/config/.kernel.release.tmp include/config/kernel.release; fi
make -f ./scripts/Makefile.asm-generic obj=arch/x86/include/generated/uapi/asm \
generic=include/uapi/asm-generic
set -e; mkdir -p include/generated/uapi/linux/; trap "rm -f include/generated/uapi/linux/.version.h.tmp" EXIT; { 	if [  19 -gt 255 ]; then echo \#define LINUX_VERSION_CODE 331263; else echo \#define LINUX_VERSION_CODE 331027; fi; echo '#define KERNEL_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + ((c) > 255 ? 255 : (c)))'; echo \#define LINUX_VERSION_MAJOR 5; echo \#define LINUX_VERSION_PATCHLEVEL  13; echo \#define LINUX_VERSION_SUBLEVEL  19; } > include/generated/uapi/linux/.version.h.tmp; if [ ! -r include/generated/uapi/linux/version.h ] || ! cmp -s include/generated/uapi/linux/version.h include/generated/uapi/linux/.version.h.tmp; then : '  UPD     include/generated/uapi/linux/version.h'; mv -f include/generated/uapi/linux/.version.h.tmp include/generated/uapi/linux/version.h; fi
./scripts/remove-stale-files
make -f ./scripts/Makefile.asm-generic obj=arch/x86/include/generated/asm \
generic=include/asm-generic
mkdir -p ./tools
mkdir -p ./tools
make LDFLAGS= MAKEFLAGS=" --jobserver-auth=3,4" O=/usr/src/linux-headers-5.13.0-25-generic subdir=tools -C ./tools/ objtool
make LDFLAGS= MAKEFLAGS=" --jobserver-auth=3,4" O=/usr/src/linux-headers-5.13.0-25-generic subdir=tools -C ./tools/ bpf/resolve_btfids
rm -f .tmp_quiet_recordmcount
make[2]: *** No rule to make target 'arch/x86/entry/syscalls/syscall_32.tbl', needed by 'arch/x86/include/generated/uapi/asm/unistd_32.h'.  Stop.
make[1]: *** [arch/x86/Makefile:231: archheaders] Error 2
make[1]: *** Waiting for unfinished jobs....
  DESCEND objtool
  DESCEND bpf/resolve_btfids
/usr/src/linux-headers-5.13.0-25-generic/tools/build/Makefile.build:37: /usr/src/linux-headers-5.13.0-25-generic/tools/build/Build.include: No such file or directory
make[5]: *** No rule to make target '/usr/src/linux-headers-5.13.0-25-generic/tools/build/Build.include'.  Stop.
make[4]: *** [Makefile:47: /usr/src/linux-headers-5.13.0-25-generic/tools/bpf/resolve_btfids/fixdep-in.o] Error 2
make[3]: *** [/usr/src/linux-headers-5.13.0-25-generic/tools/build/Makefile.include:5: fixdep] Error 2
make[2]: *** [Makefile:72: bpf/resolve_btfids] Error 2
make[1]: *** [Makefile:2006: tools/bpf/resolve_btfids] Error 2
make -C /usr/src/linux-headers-5.13.0-25-generic/tools/build CFLAGS= LDFLAGS= /usr/src/linux-headers-5.13.0-25-generic/tools/objtool/fixdep
/usr/src/linux-headers-5.13.0-25-generic/tools/build/Makefile.build:37: /usr/src/linux-headers-5.13.0-25-generic/tools/build/Build.include: No such file or directory
make[5]: *** No rule to make target '/usr/src/linux-headers-5.13.0-25-generic/tools/build/Build.include'.  Stop.
make[4]: *** [Makefile:47: /usr/src/linux-headers-5.13.0-25-generic/tools/objtool/fixdep-in.o] Error 2
make[3]: *** [/usr/src/linux-headers-5.13.0-25-generic/tools/build/Makefile.include:5: fixdep] Error 2
make[2]: *** [Makefile:69: objtool] Error 2
make[1]: *** [Makefile:2006: tools/objtool] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.13.0-25-generic'
make: *** [Makefile:22: all] Error 2

**Comment by displaylink-emajewsk** [comment]
Hi, looks to me like you're missing linux headers for 5.13:
```
/usr/src/linux-headers-5.13.0-25-generic/tools/build/Build.include: No such file or directory
```
Could you try to reinstall them?

**Comment by astromatt42** [comment]
Reinstallation did the trick. Many thanks... Will report back on how it is running once I am back in the office...
Cheers
