### ISSUE TITLE
Occasional monitor double-connect events (monitor goes blank temporarily, then reactivates)

### ISSUE THREAD

**Issue by jayaddison-collabora** [DisplayLink/evdi#342]
OS: Debian Bookworm (testing)
Windowing environment: GNOME Shell 41.2, Xwayland Version 21.1.4 (12101004)
Linux kernel: 5.15.0-2-amd64
DisplayLink driver: 5.5.0-beta-59.118

Roughly once per day, typically a few hours after boot, the monitor will blank out temporarily, and then contents appear again a few seconds later.

Sometimes rendering is partial when content reappears (for example, an individual window or line within a terminal may render) -- typically moving the pointer around the screen will cause a refresh and render of other contents.

The driver seems to be reporting this as a "double connect" event; see `dmesg -T` output below:

```
[Wed Jan 12 12:31:57 2022] evdi: [W] evdi_painter_connect:882 (card1) Double connect - replacing 0000000069bec99c with 0000000069bec99c
[Wed Jan 12 12:31:57 2022] evdi: [I] (card1) Connected with Task 838 (DesktopManagerE) of process 812 (DisplayLinkMana)
[Wed Jan 12 12:31:57 2022] evdi: [I] (card1) Connector state: connected
[Wed Jan 12 12:31:57 2022] evdi: [I] (card1) Notifying mode changed: 1920x1200@60; bpp 32; pixel format XR24 little-endian (0x34325258)
```

**Comment by displaylink-emajewsk** [comment]
I've seen similar behaviour myself. Thanks for the report. I'll push this issue.

**Comment by jayaddison-collabora** [comment]
Thanks - please let me know if there's any supporting information I can provide that would be useful.

**Comment by displaylink-emajewsk** [comment]
This appears to be a problem with the proprietary component. If you could please report this issue at https://support.displaylink.com/ using the "Contact DisplayLink" form. You will be then asked to provide logs and specific system information. Thanks!

**Comment by jayaddison-collabora** [comment]
Will do, thanks @displaylink-emajewsk!
