### ISSUE TITLE
Question: DKMS fails to build evdi module with kernel 5.13.0-28 Ubuntu 20.04

### ISSUE THREAD

**Issue by khink** [DisplayLink/evdi#346]
This may not be the right place to ask, but it seemed a good start. (I answer the default questions about EVDI, platform versions at the bottom.)

Also, it's worth knowing from the start that this question is merely out of curiosity. I was able solve the original problem, all i want to know is how my system ended in the state where i got this error. 

While upgrading (`sudo apt upgrade`), i got this error:

```
Processing triggers for linux-image-5.13.0-28-generic (5.13.0-28.31~20.04.1) ...
/etc/kernel/postinst.d/dkms:
 * dkms: running auto installation service for kernel 5.13.0-28-generic

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j8 KERNELRELEASE=5.13.0-28-generic all INCLUDEDIR=/lib/modules/5.13.0-28-generic/build/include KVERSION=5.13.0-28-generic DKMS_BUILD=1...(bad exit status: 2)
ERROR (dkms apport): binary package for evdi: 1.9.1 not found
Error! Bad return status for module build on kernel: 5.13.0-28-generic (x86_64)
Consult /var/lib/dkms/evdi/1.9.1/build/make.log for more information.
   ...done.
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-5.13.0-28-generic
I: The initramfs will attempt to resume from /dev/dm-2
I: (/dev/mapper/vgubuntu-swap_1)
I: Set the RESUME variable to override this.
/etc/kernel/postinst.d/zz-update-grub:
Sourcing file `/etc/default/grub'
Sourcing file `/etc/default/grub.d/init-select.cfg'
Sourcing file `/etc/default/grub.d/oem-flavour.cfg'
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-5.13.0-28-generic
Found initrd image: /boot/initrd.img-5.13.0-28-generic
Found linux image: /boot/vmlinuz-5.13.0-27-generic
Found initrd image: /boot/initrd.img-5.13.0-27-generic
Found linux image: /boot/vmlinuz-5.11.0-46-generic
Found initrd image: /boot/initrd.img-5.11.0-46-generic
Adding boot menu entry for UEFI Firmware Settings
done
```

`/var/lib/dkms/evdi/1.9.1/build/make.log` starts with:
```
DKMS make.log for evdi-1.9.1 for kernel 5.13.0-28-generic (x86_64)
wo  2 feb 2022  9:51:43 CET
make KBUILD_VERBOSE=1 M=/var/lib/dkms/evdi/1.9.1/build SUBDIRS=/var/lib/dkms/evdi/1.9.1/build SRCROOT=/var/lib/dkms/evdi/1.9.1/build CONFIG_MODULE_SIG= -C /lib/modules/5.13.0-28-generic/build modules
make[1]: Entering directory '/usr/src/linux-headers-5.13.0-28-generic'
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (		\
echo >&2;							\
echo >&2 "  ERROR: Kernel configuration is invalid.";		\
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";	\
echo >&2 ;							\
/bin/false)
```

(This issue looks like #215 respective to when the issue occurs, however the error is different. But i thought i'd copy this issue's title, as it's good.)

Turns out the `evdi-dkms` package wasn't even installed.  `sudo apt install evdi-dkms` fixed it.

So my question is, how can my system have ended up in this state where evdi-dkms wasn't installed, and upgrading a kernel package gave an error about this?

Thanks in advance, and obviously, feel free to close this "issue" as quickly as you please.

Kees

EVDI questions:

  * Are you using the latest driver? Not sure, but the issue is while installing
  * Are you using the latest EVDI version? I think the issue is while installing
  * If you are using a DisplayLink device, have you checked 'troubleshooting' on DisplayLink's website? No, there is no issue, it's just the installation.
  * Is this issue related to evdi/kernel? Not sure

Platform questions:

  * Linux distribution and its version: Ubuntu 20.04.3 LTS
  * Linux kernel version: Currently 5.13.0-27-generic
  * Xorg version (if used): installed is 2:1.20.13-1ubuntu1~20.04.2
  * Desktop environment in use: GNOME 3.36

**Comment by daN4cat** [comment]
Fails on Ubuntu 21.04 with Linux 5.15.0-18-generic kernel too, using the latest DisplayLink beta drivers from Dec 21.
With Linux 5.15.0-17-generic works fine.

**Comment by displaylink-emajewsk** [comment]
> So my question is, how can my system have ended up in this state where evdi-dkms wasn't installed, and upgrading a kernel package gave an error about this?

@khink Unfortunately we cannot help you with this one, as `evdi-dkms` is not managed by us.
