### ISSUE TITLE
Fails to install on Archlinux LTS kernel 5.15.25-1-lts

### ISSUE THREAD

**Issue by prakash2033** [DisplayLink/evdi#349]
* Are you using the latest driver? --> Yes
  * Are you using the latest EVDI version?  --> Yes 1.10.0
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website? 
  * Is this issue related to evdi/kernel? -->  Probably evdi doesn't support kernel 5.15.25-1-lts yet?

  * Linux distribution and its version: Arch Linux
  * Linux kernel version : 5.15.25-1-lts
  * Xorg version (if used): X.Org X Server 1.21.1.3
  * Desktop environment in use: XFCE4
  
    Screenshot:
    `sudo make`
    ![image](https://user-images.githubusercontent.com/9929306/156031796-6d0ed2b1-6bfa-4728-a0dc-f12a788572fe.png)
    
    `sudo make clean install`
    ![image](https://user-images.githubusercontent.com/9929306/156030509-7057b182-dc56-44e0-82d8-6043388094f7.png)

    `sudo make install`
    ![image](https://user-images.githubusercontent.com/9929306/156032257-b8636251-e228-4fce-b547-3b82e3f6f2cc.png)

**Comment by displaylink-emajewsk** [comment]
it's not `make install`
the proper command to install evdi is meant to be: `make && sudo make install_dkms` and `sudo make uninstall_dkms` to uninstall

**Comment by prakash2033** [comment]
![image](https://user-images.githubusercontent.com/9929306/156355922-010958dd-caed-4c27-8ac4-4c5597d38ec2.png)

**Comment by displaylink-emajewsk** [comment]
Sorry, I failed to mention that you should be in the `module` directory

**Comment by prakash2033** [comment]
Thanks it worked!

**Comment by brccabral** [comment]
I have just upgraded Ubuntu from 20.04 to 22.04 which upgrades the kernel to 5.15.0-25-generic and had to execute the same command. My previous kernel was 5.13 and evdi was already installed.
I couldn't find this command in any of the README.md or /docs/*.md.
The Makefile doesn't have a help section neither.

Can someone add it to the README.md or create a new file in /docs?
Appreciated

```
git clone https://github.com/DisplayLink/evdi.git
cd evdi
make
cd module
sudo make install install_dkms
```
