### ISSUE TITLE
Rotation property

### ISSUE THREAD

**Issue by cribalik** [DisplayLink/evdi#35]
Xrandr does not seem to recognize a rotation for displaylinked monitors. Is it possible to add this?

**Comment by displaylink-mlukaszek** [comment]
Rotation was not supported by generic modesetting driver back in the days when evdi was created. However, I think things evolved a bit since, and this might be possible now. Keeping this issue open, a pull request is also welcome. :)

**Comment by dol** [comment]
I'm looking forward for this feature. I use a 90° pivoted monitor for programming.

About PR. Could you provide further details where to start.

**Comment by mlukaszek** [comment]
@dol Have a look at [this thread](http://displaylink.org/forum/showthread.php?t=64525&highlight=rotation) - drm_shadow_* is what's interesting.

**Comment by cribalik** [comment]
Thanks, I'll start poking around and see if I can put up a PR :)

**Comment by sroracle** [comment]
In a similar vein, can proper scaling also be added?

**Comment by displaylink-mlukaszek** [comment]
Interestingly, [this thread ](http://displaylink.org/forum/showthread.php?t=65131)shows that someone actually managed to rotate evdi screen. Note, this was with 1.2 driver, now we've released a 1.3 verson which has further improvements in DLM and also ships the very latest evdi.

**Comment by seidler2547** [comment]
@displaylink-mlukaszek rotation still works with 1.3, not much difference from 1.2. However, performance could be better and it doesn't seem to work well when using `intel` xf86 driver, only when the primary GPU is also on `modesetting`. Maybe the next thing would be to look into why `PageFlip` needs to be off for it to work, maybe this needs more driver support?

**Comment by konserw** [comment]
I'm using rotated screen via Displaylink 1.2 without issues on Arch with xf86 radeon driver. I'll check tommorow with DL 1.3

**Comment by pedrib** [comment]
@seidler2547 @displaylink-mlukaszek rotation also works for me using 1.3, kernel 4.4, Intel HD4000 with PageFlip off.

**Comment by displaylink-mlukaszek** [comment]
OK, I think we could close this issue now that many people report it works.
