### ISSUE TITLE
Kernel 5.13.0 series - evdi taints kernel, fails to load

### ISSUE THREAD

**Issue by astromatt42** [DisplayLink/evdi#350]
* Are you using the latest driver?
5.5
  * Are you using the latest EVDI version?
1.10.1
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
Yes
  * Is this issue related to evdi/kernel?
Pretty sure it is

  * Linux  Mint 20.3
  * 5.13.0.35
  * 2:1.20.13-1ubuntu1~20.04.2
  * Cinnamon 

Latest evdi module fails to load in kernel line 5.13.0 (all works fine in 5.4.0 - so I would guess it's highly likely that this is kernel related and not config) -> no multiple screens

The key lines in dmesg seem to be

[Fri Mar 11 14:11:02 2022] evdi: loading out-of-tree module taints kernel.
[Fri Mar 11 14:11:02 2022] evdi: module verification failed: signature and/or required key missing - tainting kernel
[Fri Mar 11 14:11:02 2022] module: x86/modules: Skipping invalid relocation target, existing value is nonzero for type 1, loc 00000000c3c3bb59, val ffffffffc03faf5f

The last message repeats multiple times with different loc but same val.

Cheers

**Comment by displaylink-emajewsk** [comment]
Thanks for the logs, I'll take a look at it

**Comment by astromatt42** [comment]
Thanks Emilia, would be good to get this working, let me know if there are any troubleshooting steps I can take!

**Comment by displaylink-emajewsk** [comment]
I think it could be related to secure boot. Would you mind trying to disable it and see if it enables evdi to load?
In general it *should* be printing this message, but still load the module, unless your kernel has been compiled with `CONFIG_MODULE_SIG_FORCE`
Are you on plain Linux Mint?

**Comment by astromatt42** [comment]
Hi, so secure boot is already off (double checked) and yes completely plain LM, with the kernel coming from the LM repository.

**Comment by displaylink-emajewsk** [comment]
OK, I'll check Linux Mint myself then

**Comment by displaylink-emajewsk** [comment]
OK, I'll check Linux Mint myself then

**Comment by astromatt42** [comment]
Have you managed to reproduce this in Mint?

**Comment by astromatt42** [comment]
Ok, I seem to have been able to resolve this with a clean install of Mint. It turned out that another module failed to load with the same error message. Some more research suggested that this can happen due to some unidentified misconfiguration that occurs if Mint is updated through a number of versions, which was the case for my system. With a clean install, it is now working on the latest kernel.
