### ISSUE TITLE
Extreme lagging on DisplayLink screens

### ISSUE THREAD

**Issue by mschaefer-es** [DisplayLink/evdi#36]
I managed to get the driver working on my Fedora 23 (KDE/Plasma 5) machine (granted an unsupported configuration). However the attached screens are basically unusable because of a repaint delay between 1 and 2 seconds. Interestingly the results vary depending on the application, i.e. Google Chrome is completely unusable while I can bear using Firefox on the displaylink screens. Additionally I experience a flickering cursor on my laptop screen (display link screen is fine). Any pointers?

**Comment by displaylink-mlukaszek** [comment]
Please raise this on DisplayLink forum. Since you are getting screen updates, EVDI and libevdi (which this project is about) are working fine in your case, consult the DL forum for a support tool that can grab DisplayLink-specific log files.
