### ISSUE TITLE
Kernel oops when unloading evdi v1.11.0

### ISSUE THREAD

**Issue by sredman** [DisplayLink/evdi#365]
* Are you using the latest driver?
    Yes - version 5.6
  * Are you using the latest EVDI version?
    Yes - version 1.11.0
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
      Yes. Not relevant.
  * Is this issue related to evdi/kernel?
    Yes

  * Linux distribution and its version
    Fedora 36
  * Linux kernel version
    5.19.0-0.rc3 and 5.18.6
  * Xorg version (if used)
    N/A - Wayland - kwin 5.24.5
  * Desktop environment in use
    Plasma

dmesg output: https://gist.github.com/sredman/4bd9169090ff9b9de11a924e01d5c30f

My monitor was not displaying anything, so I thought I would see what happened if I did `modprobe -r evdi`. What happened was a kernel oops. This is reliably reproducible.

**Comment by sredman** [comment]
As far as I can tell, there is a dependency on having the DisplayLink Driver running. If the driver is running (even though my monitor is not receiving a signal) and I unload the module, I get this oops. `lsmod | grep evdi` shows 0 users of the module, otherwise the unload would have been prevented. If the DisplayLink Driver is not running, I can correctly unload evdi.

**Comment by synaptics-lspintzyk** [comment]
There was few reworks in the evdi driver and device removal code. It should be working better in latest releases e.g, 1.14.8.
I agree with what you said when there is not processes (DisplayLinkManager or kwin or xserver) using evdi device then evdi removal should succeed. And I believe this is happening under latest Ubuntu with Gnome/wayland.
Closing that issue. Please ask to reopen when it still happening.
