### ISSUE TITLE
SSL error while building and installing evdi module

### ISSUE THREAD

**Issue by askb** [DisplayLink/evdi#369]
* Are you using the latest driver?
       Trying to build from github repo.
  * Are you using the latest EVDI version?
      [v1.11.0](https://github.com/DisplayLink/evdi/releases/tag/v1.11.0)  
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
  * Is this issue related to evdi/kernel?
    Not sure
  * Linux distribution and its version: Fedora 35
  * Linux kernel version: 5.18

The kernel module build, gives out these warning during install.

```
make[2]: Entering directory '/usr/src/kernels/5.18.10-100.fc35.x86_64'
  INSTALL /lib/modules/5.18.10-100.fc35.x86_64//kernel/drivers/gpu/drm/evdi/evdi.ko
  SIGN    /lib/modules/5.18.10-100.fc35.x86_64//kernel/drivers/gpu/drm/evdi/evdi.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: crypto/bio/bss_file.c:69
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: crypto/bio/bss_file.c:76
sign-file: ./certs/signing_key.pem: No such file or directory
  DEPMOD  /lib/modules/5.18.10-100.fc35.x86_64
make[2]: Leaving directory '/usr/src/kernels/5.18.10-100.fc35.x86_64'

```
With this multiple monitors cannot be added using display, only shows a single monitor.

**Comment by commandline-be** [comment]
same issue, Rocky Linux 9.1, worked fine before
suspected this is due to a "best practice" rolled out to decommission old crypto

**Comment by commandline-be** [comment]
consider https://github.com/displaylink-rpm/displaylink-rpm/releases

**Comment by askb** [comment]
The latest evdi modules packed with DisplayLink rpm worked seamlessly.
