### ISSUE TITLE
Evdi 12.0.1 dosen’t work with kernel 5.18.14

### ISSUE THREAD

**Issue by muellerjoel** [DisplayLink/evdi#373]
* ArchLinux 
  * 5.18.14
  * Cinnamon 
  
  Network and USB works but no display signal and can’t choose resulotion with evdi 11.0 works but can’t choose resolution over FullHD. It’s was possible before.

**Comment by fs-evooq** [comment]
Same with me with the version 1.12.0 and kernel 5.18.14-arch1-1
Rollback to 1.11.0 fixes the issue.

**Comment by julian-poidevin** [comment]
@fs-evooq Hello, I have the same issue, how did you roll-back ? Did you compile and install from sources ? Thanks

**Comment by Joel-Muller** [comment]
git clone https://aur.archlinux.git/evdi.git
cd evdi
vim PKGBUILD 

#edit version number 11.0.0 and hash sum ti ‘SKIP’
makepkg -si

**Comment by fs-evooq** [comment]
@julian-poidevin To rollback the *aur* package installed with *paru*:
```sh
cd ~/.cache/paru/clone/evdi
git log
git checkout 4bcc74e6f3dd59fda2abd07fea1d990858fcaa55
makepkg -cirs
sudo rmmod evdi
sudo modprobe evdi
```

**Comment by julian-poidevin** [comment]
Thanks a lot guys !

**Comment by displaylink-emajewsk** [comment]
Hi, recently released Evdi `1.12.0` is incompatible with the Displaylink driver `5.6`, because of an API change. Hm, AUR maintainers should be more careful and wait for the binary driver.

**Comment by olof-nord** [comment]
Same problem here, also Arch Linux. Kernel 5.18.14, GNOME.

- displaylink 5.6-1
- evdi 1.12.0-1

**Comment by lnksz** [comment]
Same problem on Kernel v5.10.131, rollback to v1.11.0 was needed.

**Comment by 1Maxnet1** [comment]
> git clone https://aur.archlinux.git/evdi.git

This address does not exist. The correct command would be: `git clone https://aur.archlinux.org/evdi.git`

**Comment by olof-nord** [comment]
I can confirm a rollback from `evdi 1.12.0-1` to `evdi 1.11.0-1` using the method described by @fs-evooq in their [comment](https://github.com/DisplayLink/evdi/issues/373#issuecomment-1193698810) got my external monitor working again. Really appreciate the advice!

**Comment by direc85** [comment]
As `details.md` says, major version number should be increased when incompatible API changes occur, yet only minor version was increased. This means that v1.12 should have been released as v2.0 instead.

**Comment by palexdev** [comment]
I'm experiencing graphical artifacts at the mouse position on both the screens
evdi 1.11.0-1
displaylink 5.6-1

**Comment by julian-poidevin** [comment]
> I'm experiencing graphical artifacts at the mouse position on both the screens evdi 1.11.0-1 displaylink 5.6-1

@palexdev This is [a known issue](https://support.displaylink.com/forums/287786-displaylink-feature-suggestions/suggestions/36619396-fix-glitching-mouse-pointer-in-ubuntu-arch-debian?page=1&per_page=20). See also https://www.youtube.com/watch?v=3ZGX-3dATW4&ab_channel=FixitKB%21

**The solution for me is to logout then login again and it resolves the issue.**

**Comment by palexdev** [comment]
> > I'm experiencing graphical artifacts at the mouse position on both the screens evdi 1.11.0-1 displaylink 5.6-1
> 
> @palexdev This is [a known issue](https://support.displaylink.com/forums/287786-displaylink-feature-suggestions/suggestions/36619396-fix-glitching-mouse-pointer-in-ubuntu-arch-debian?page=1&per_page=20). See also https://www.youtube.com/watch?v=3ZGX-3dATW4&ab_channel=FixitKB%21
> 
> **The solution for me is to logout then login again and it resolves the issue.**

Thank you very much, that solves the issue for me too
This is a temporary workaround, right? Every time I disconnect/connect the display I will have to do it again?

**Comment by julian-poidevin** [comment]
> > > I'm experiencing graphical artifacts at the mouse position on both the screens evdi 1.11.0-1 displaylink 5.6-1
> > 
> > 
> > @palexdev This is [a known issue](https://support.displaylink.com/forums/287786-displaylink-feature-suggestions/suggestions/36619396-fix-glitching-mouse-pointer-in-ubuntu-arch-debian?page=1&per_page=20). See also https://www.youtube.com/watch?v=3ZGX-3dATW4&ab_channel=FixitKB%21
> > **The solution for me is to logout then login again and it resolves the issue.**
> 
> Thank you very much, that solves the issue for me too This is a temporary workaround, right? Every time I disconnect/connect the display I will have to do it again?

Yes I think. At least, that the case for me.

**Comment by 5472qaywsx** [comment]
> git clone https://aur.archlinux.git/evdi.git cd evdi vim PKGBUILD
> 
> #edit version number 11.0.0 and hash sum to ‘SKIP’ makepkg -si

Worked for me with following changes, HTH:

- `git clone https://aur.archlinux.org/evdi.git` (note the _archlinux.**org**_ part)
- change version number to 1.11.0 (_not 11.0.0_)
- change hash sum line to `sha256sums=('SKIP')` (attention, I don't know if this could be a security issue)

**Comment by direc85** [comment]
[DisplayLink 5.6.1](https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu) has been released, and it's compatible with evdi 1.12.0. Source: [changelog](https://www.synaptics.com/sites/default/files/release_notes/2022-08/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu5.6.1-Release%20Notes.txt).

The [DisplayLink AUR package](https://aur.archlinux.org/packages/displaylink) is still at 5.6 at the time of writing. A self-bumped version works with evdi 1.12.0, for me at least.

**Comment by rbeucher** [comment]
Hi, Just upgraded to 5.19.3-arch1-1 and the displaylink service fails to load...
I am running `evdi 1.12.0` from AUR and `displaylink 5.6.1`

**Comment by Joel-Muller** [comment]
For me evdi 1.11.0 and displaylink 5.6 still works

**Comment by 1up9059** [comment]
Hi am running 5.19.3-arch1-1 and fail when evdi is uploaded from 1.11.0 to 1.12.0, I needed to do a rollback

**Comment by rbeucher** [comment]
rollback to 1.11.0? What version of displaylink are you running?

**Comment by q-wertz** [comment]
Yes, you have to rollback to 1.11.0 (as described by https://github.com/DisplayLink/evdi/issues/373#issuecomment-1193698810) (just replace `cd ~/.cache/paru/clone/evdi` accordingly to your package manager) until the [AUR package of displaylink](https://aur.archlinux.org/packages/displaylink) is updated to the new 5.6.1 version (see https://github.com/DisplayLink/evdi/issues/373#issuecomment-1219468570)

**Comment by 1up9059** [comment]
> rollback to 1.11.0? What version of displaylink are you running?

Yes, if you rollback evdi to 1.11.0 displaylink will works again

**Comment by rbeucher** [comment]
No, I think there is a pb with evdi. I can't add the module:

```
modprobe evdi
modprobe: ERROR: could not insert 'evdi': Invalid argument
```

```
dmesg | grep evdi
[ 6033.780665] failed to validate module [evdi] BTF: -22
[ 6035.177502] failed to validate module [evdi] BTF: -22
[ 6039.029240] failed to validate module [evdi] BTF: -22
[ 6044.290658] failed to validate module [evdi] BTF: -22
[ 6049.530255] failed to validate module [evdi] BTF: -22
[ 6054.789138] failed to validate module [evdi] BTF: -22
[ 6060.041652] failed to validate module [evdi] BTF: -22
```

**Comment by 1up9059** [comment]
> No, I think there is a pb with evdi. I can't add the module:
> 
> ```
> modprobe evdi
> modprobe: ERROR: could not insert 'evdi': Invalid argument
> ```
> 
> ```
> dmesg | grep evdi
> [ 6033.780665] failed to validate module [evdi] BTF: -22
> [ 6035.177502] failed to validate module [evdi] BTF: -22
> [ 6039.029240] failed to validate module [evdi] BTF: -22
> [ 6044.290658] failed to validate module [evdi] BTF: -22
> [ 6049.530255] failed to validate module [evdi] BTF: -22
> [ 6054.789138] failed to validate module [evdi] BTF: -22
> [ 6060.041652] failed to validate module [evdi] BTF: -22
> ```

I only follow this procedure;
I uninstalled evdi
I uninstalled DisplayLink (I think maybe this is not necessary to do, but I did it)
I clone the git repository for evdi from aur page and once I got the PKG file I edited the pkgver to pkgver=1.11.0 and sha256sums to sha256sums=('SKIP'). Once I did that, I did makepkg -si procedure and reinstalled DisplayLink again and my docking worked again. I have a pluggable USB3.0, so that is working fine now 

I based this procedure in the answer of @5472qaywsx and my displaylink version is displaylink 5.6-1

**Comment by rbeucher** [comment]
Yes thanks, I did try that but no luck.

**Comment by Grisu118** [comment]
@rbeucher I have the same issue as you, created a new issue: https://github.com/DisplayLink/evdi/issues/377

**Comment by rbeucher** [comment]
Thanks @Grisu118 . I hope we are gonna sort this out.

**Comment by olof-nord** [comment]
After a recent system upgrade, my external monitor yet again stayed black. I noticed that evdi was again on the incompatible `1.12` version - this despite me using displaylink `5.6-1`.

After reverting back to the old `1.11` evdi version again, I adjusted my pacman config as to avoid evdi from being upgraded.
https://wiki.archlinux.org/title/Pacman#Skip_package_from_being_upgraded

**Comment by direc85** [comment]
@olof-nord Evdi 1.12 doesn't work with displaylink 5.6. The dependencies go like this (using Arch versioning):

* `displaylink 5.6-1` <--> `evdi 1.11.0-1`
* `displaylink 5.6.1-1` <--> `evdi 1.12.0-1`

**Comment by direc85** [comment]
As this ticket was pretty much Arch specific, and displaylink 5.6.1 and evdi 1.12.0 are out, I think this ticket can be closed.

**Comment by rbeucher** [comment]
It now works with 5.19.4.arch

**Comment by Joel-Muller** [comment]
I can install evdi 1.12.0 and displaylink 5.6.1 and is running but doesn’t recognise second screen. Evdi 1.11.0 with 5.6 still works

**Comment by 1up9059** [comment]
Hi, my system upgraded the kernel to the 6.0.2 version, then any of the solutions posted here helped me. I try to downgrade the kernel to the 5.19.3 version, but that produces an issue in my system and the graphical interface doesn't work. Then, I returned to the 6.0.2 kernel but the available version of evdi and displaylink don't work anymore to detect may docking to my second monitor. 
I tried these step:

1. Downgrade the kernel to 5.19.3
2. uninstall evdi and displaylink
3. reboot my system. But the issues with the graphical interface happened, however, I was available to install evdi 1.11.0 and displaylink 5.6-1
4. Then I returned to 6.0.2 kernel, but to recover the graphical interface but evdi and displayllink don't work.

Does anybody know how to solve the issue using the kernel 6.0.2 version?

**Comment by rbeucher** [comment]
I am currently using the main git branch and it works fine for me

**Comment by 1up9059** [comment]
> I am currently using the main git branch and it works fine for me

what kernel version are you using?

**Comment by rbeucher** [comment]
6.0.2
