### ISSUE TITLE
failed to validate module [evdi] BTF: -22

### ISSUE THREAD

**Issue by Grisu118** [DisplayLink/evdi#377]
* Linux distribution and its version
    * Arch
  * Linux kernel version
    * 5.19.3-arch1-1
  * Desktop environment in use
    * KDE Plasma

I am unable to load evdi kernel module
Tested with evdi 1.11.0 and latest 1.12.0 both gave the same error when executing `modprobe evdi`

```
sudo modprobe evdi 
modprobe: ERROR: could not insert 'evdi': Invalid argument
```

Kernel logs
```
Aug 25 07:25:28 brunb500 kernel: evdi: loading out-of-tree module taints kernel.
Aug 25 07:25:28 brunb500 kernel: evdi: module verification failed: signature and/or required key missing - tainting kernel
Aug 25 07:25:28 brunb500 kernel: BPF: [112087] ENUM perf_event_task_context 
Aug 25 07:25:28 brunb500 kernel: BPF: size=4 vlen=4
Aug 25 07:25:28 brunb500 kernel: BPF:  
Aug 25 07:25:28 brunb500 kernel: BPF: Invalid btf_info kind_flag
Aug 25 07:25:28 brunb500 kernel: BPF: 
Aug 25 07:25:28 brunb500 kernel: failed to validate module [evdi] BTF: -22
```

I already tried the following without success
* Uninstall and reinstall evdi
* Rollback kernel to 5.19.2 and 5.19.1, issue persists

It stopped working after I updated my packages yesterday morning. Before that, it worked with kernel 5.19.2 and evdi 1.11.0. Also, my colleague from work, with a similar setup, does not have the issue.

**Comment by DreamTexX** [comment]
Same here, worked with evdi 1.11.0 and kernel 5.19.2 but after upgrading on 5.19.3 everything broke and I cannot get it working anymore.

**Comment by DreamTexX** [comment]
Although doing `modinfo evdi` does give a result, I cannot do `modrm` or `modprobe`, And Displaylink does not work

**Comment by rbeucher** [comment]
Same issue for me. I am on 5.19.3-arch1-1

I have tried to install evdi 1.12.0, 1.11.0 no luck

**Comment by DreamTexX** [comment]
I've got it working again, steps to do:

1. Uninstall evdi (and displaylink)
2. Find all references on evdi, I used `find / -nowarn -iname "*evdi*" 2>/dev/null`
3. Delete evdi references in your modules folders, so try to completely nuke evdi from your system
4. Clone `git clone https://aur.archlinux.org/evdi.git`
5. Basicly do what was suggested [here](https://github.com/DisplayLink/evdi/issues/373#issuecomment-1193698810) but with one commit later `2f74d0020f7fa08528b741b316c7107eade76fb7`

This worked for me, be careful of what you delete from your system

**Comment by rbeucher** [comment]
Thanks, I'll try that and will post the outcome here.

**Comment by Grisu118** [comment]
I tried the steps from @DreamTexX, It still fail with the same error

**Comment by rbeucher** [comment]
Yes I tried too. Same pb.

**Comment by epontan** [comment]
> I tried the steps from @DreamTexX, It still fail with the same error

It didn't work for me either the first time. The second time I rebooted before step 4 and this time evdi module was able to load properly.

**Comment by DreamTexX** [comment]
> > I tried the steps from @DreamTexX, It still fail with the same error
> 
> It didn't work for me either the first time. The second time I rebooted before step 4 and this time evdi module was able to load properly.

Yeah I think I already uninstalled evdi yesterday and just did the cleanup today after reboot, I'm not sure so a reboot after uninstall might be necessary

**Comment by direc85** [comment]
After a brief search, `failed to validate module [evdi] BTF: -22` (or `-EINVAL`) seems to indicate some sort of mismatch between the kernel and the module. Most likely the module isn't properly compiled for the kernel, and this is NOTABUG. This should help:

- Reboot
- `sudo dkms autoinstall`
- Reboot

It may well be that the `dkms` folder is full of old junk. If this is the case, remove `evdi` package and manually remove `/var/lib/dkms/evdi` from the system. Then reboot and install `evdi` again.

And remember:
- `displaylink 5.6` <--> `evdi 1.11.0`
- `displaylink 5.6.1` <--> `evdi 1.12.0`

**Comment by rbeucher** [comment]
I tried again with the above and the issue remains.
I tried 1.11.0 and 1.12.0. I made sure that evdi was uninstalled and I did reboot...

**Comment by rbeucher** [comment]
I am using linux-headers for 5.19.3.arch1-1.
The module should build properly no?

**Comment by Grisu118** [comment]
After the update to kernel `5.19.4-arch1-1` this morning, I was able to install evdi again and it worked

What I did:
1. Remove evdi (and displaylink) completely
2. System upgrade (inlcuding kernel 5.19.4-arch1-1)
3. Reboot
4. Install displaylink with yay
5. Reboot

Now displaylinkg 5.6.1 and evdi 1.12.0 runs without issues.

**Comment by direc85** [comment]
Great! Do you think this issue can be closed then?

**Comment by rbeucher** [comment]
Yes I can confirm. all good.
