### ISSUE TITLE
Fix compilation for 4.8

### ISSUE THREAD

**Issue by SimonPe** [DisplayLink/evdi#38]
some changes were made to the drm subsystem.
mainly drm_connector_(un)register_all are no longer exported as they are called on drm_dev_(un)register automatically

I might or might not cook up a patch during the course of the day (dependant on how busy I am.)

**Comment by philippe-levan** [comment]
I believe this is a duplicate from issue #32 .
It is fixed in the branch dev, but there is no tag.

Best regards,
Philippe

**Comment by SimonPe** [comment]
@philippe-levan it isn't. #32 is for 4.7 this is for 4.8.

While this relates to the same calls they were changed again in 4.8 (which is at rc4 now)

**Comment by displaylink-mlukaszek** [comment]
Fixed with c53b304. Closing.
