### ISSUE TITLE
How to install from source

### ISSUE THREAD

**Issue by BasSmeets** [DisplayLink/evdi#383]
Hi, 

Currently i need the latest develop code in order to work for my kernel 6 machine.
Can someone please detail the steps how to install the displaylink driver from source?

Thanks!

**Comment by timmey09** [comment]
Hey, I can recommend [this post in the DisplayLink forum](https://www.displaylink.org/forum/showpost.php?p=92453&postcount=3). Of course you need to adapt these commands to the latest DisplaylLink driver version.

**Comment by BasSmeets** [comment]
Thanks, i had figured out the same steps yesterday. Its working for me now.
