### ISSUE TITLE
evdi can't be build after Kernel update on Red Hat 8.7 and 9.1

### ISSUE THREAD

**Issue by jodalein** [DisplayLink/evdi#389]
Hi,
after the latest Kernel Upadates to 4.18.0-425 and on Red Hat 9.1 the Module can't be build.

I made some changes and with this it can be build but its very very ugly hacked and im not very good at write code ;).
Can someone take a look over the changes and write them down to good patches?
Feel free to ask.

i added them in this branch
https://github.com/jodalein/evdi/tree/redhat-8.7

**Comment by synaptics-lspintzyk** [comment]
Please check newer evdi 1.14.8 release. Closing this issue.
