### ISSUE TITLE
I Can't installer in clear linux

### ISSUE THREAD

**Issue by JCodeArch** [DisplayLink/evdi#390]
I can't install it on my clear linux. Could someone walk me through it step by step.

WARNING: This is not an officially supported distribution.
Please use DisplayLink Forum for getting help if you find issues.
Cool Message
Installing
[ Installing EVDI ]
[[ Installing EVDI DKMS module ]]
Sign command: /lib/modules/6.0.10-1215.native/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Creating symlink /var/lib/dkms/evdi/1.12.0/source -> /usr/src/evdi-1.12.0
Building module:
Cleaning build area...
make -j12 KERNELRELEASE=6.0.10-1215.native all INCLUDEDIR=/lib/modules/6.0.10-1215.native/build/include KVERSION=6.0.10-1215.native DKMS_BUILD=1...(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.0.10-1215.native (x86_64)
Consult /var/log/displaylink/evdi_install_make.2022-12-04-0103.log for more information.
Deleting module evdi-1.12.0 completely from the DKMS tree. 
ERROR: Failed to install evdi to the kernel tree.

**Comment by synaptics-lspintzyk** [comment]
```Consult /var/log/displaylink/evdi_install_make.2022-12-04-0103.log```
This is probably compilation issue. 

Try download latest evdi driver. As support for newer kernels is added in newer versions.
If this is still happening please raise new issue.
