### ISSUE TITLE
Malfunctioning on Ubuntu 22.04 Linux 5.17

### ISSUE THREAD

**Issue by warent** [DisplayLink/evdi#391]
I booted up my computer today after presumably updating the linux kernel the other day, and the screen went black after the grub splash.

Successfully dropped into a shell and saw various errors from gnome / xorg complaining abiout evdi
![PXL_20221207_180020954_2](https://user-images.githubusercontent.com/13342266/206281941-19e7dfcb-590c-48fd-b9c2-65e39703a0ce.jpg)

When I tried to update the driver it gave me some error complaining about the kernel. I completely uninstalled the driver to then reinstall it, but the re-installation also failed.

Rebooting the machine after uninstalling evdi/displaylink fixed my machine as gdm is no longer trying to load displaylink.
```
$ sudo displaylink-installer uninstall
$ sudo dkms remove evdi/(version) --all -q
```

Not sure why this suddenly happened, all I can think is something with the latest Ubuntu / Linux made evdi angry

**Comment by jerome-diver** [comment]
Because you have to re compil and re install your evdi driver and his kernel module.

**Comment by warent** [comment]
Hey guys, friendly note I just tried to reinstall evdi on my machine after doing a system update, but it's still failing for some reason. This time I was able to capture the error:

```
Preparing to unpack .../evdi-dkms_1.9.1-1ubuntu5_all.deb ...
Unpacking evdi-dkms (1.9.1-1ubuntu5) ...
Selecting previously unselected package libevdi0.
Preparing to unpack .../libevdi0_1.9.1-1ubuntu5_amd64.deb ...
Unpacking libevdi0 (1.9.1-1ubuntu5) ...
Setting up evdi-dkms (1.9.1-1ubuntu5) ...
Loading new evdi-1.9.1 DKMS files...
Building for 5.17.0-051700-generic
Building initial module for 5.17.0-051700-generic
ERROR (dkms apport): kernel package linux-headers-5.17.0-051700-generic is not supported
Error! Bad return status for module build on kernel: 5.17.0-051700-generic (x86_64)
Consult /var/lib/dkms/evdi/1.9.1/build/make.log for more information.
dpkg: error processing package evdi-dkms (--configure):
 installed evdi-dkms package post-installation script subprocess returned error exit status 10
Setting up libevdi0 (1.9.1-1ubuntu5) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
Errors were encountered while processing:
 evdi-dkms
```

**Comment by warent** [comment]
I ended up getting this working by upgrading my kernel version: `sudo apt-get dist-upgrade`
`Linux 5.19.0-32-generic`

And then installing via the run script provided in the displaylink website
https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu
