### ISSUE TITLE
Kernel 4.2 Support

### ISSUE THREAD

**Issue by jravetch** [DisplayLink/evdi#4]
WARNING: Kernel version 4.2.0-17-generic is not supported. Highest supported version is 3.19.

When will 4.2 be supported?

**Comment by tmbgreaves** [comment]
End user report - working absolutely fine for me with VGA output at least (HDMI not tested) on 4.2 (and, I suspect, the kernel you list!), after ignoring the version check warning.

**Comment by jravetch** [comment]
I followed these instructions and now the driver was loaded properly  with Ubuntu 15.10 and kernel 4.2

http://www.displaylink.org/forum/showthread.php?s=9a9900b93b75db842dee3eb1629350ef&t=64181

tl;dr you need to extract the binary and edit the install script to remove the conditional for Ubuntu lsb_release.

**Comment by andreasbehnke** [comment]
Hi,

I have written a script for downloading, patching and installing this driver. Works for me with ubuntu gnome 15.10. There are xorg panics from time to time, but that may be due to gnome-shell.

https://github.com/andreasbehnke/xps13/tree/master/ubuntu-gnome-15.10/displaylink

**Comment by jravetch** [comment]
@andreasbehnke Wow, thanks!  This is very helpful.  +1 on the powersaving tips.  Are you noticing any fan issues with your setup?

**Comment by andreasbehnke** [comment]
@jravetch No, I never had any problems with the fan setup. When playing some old games using wine or compiling some code the fan will be active. But this is a normal behaviour. When surfing the web or watching TV or videos in battery mode, the fan is never active.

**Comment by unfulvio** [comment]
I tried to edit the install script file but I think it doesn't apply to the newer driver version -- has anyone got an older version of the driver or a patched version that can share with me! many thanks!
