### ISSUE TITLE
DisplayLinkMana doesn't start, gets terminated with signal SIGABRT

### ISSUE THREAD

**Issue by nilsdoubleu** [DisplayLink/evdi#40]
Everytime i try to start or restart the DisplayLink-Service a Core-Dump gets created and the service isn't starting. The errors i could extract out of the dump were:

`gdb` with `thread apply all bt full` (I installed the Debug-Files for DisplayLink)
Thread 1 (LWP 6299)
`#0 0x00007f4916ed16f5 in ?? ()`
No symbol table info available.
`#1 0x00007f4916ed32fa in ?? ()`
No symbol table info available.
`#2 0x0000000000000020 in ?? ()`
No symbol table info available.
`#3 0x0000000000000000 in ?? ()`
No symbol table info available.

I am running Fedora 24, with all required depencies installed. 
I am grateful for any help.

**Comment by displaylink-mlukaszek** [comment]
Please raise this on [DisplayLink Linux Forum](http://displaylink.org/forum/forumdisplay.php?f=29). Seeing a stack trace so short makes me suspect there's something wrong with loading libevdi, or the library talking to evdi kernel module. Anyway, the right place is the forum, where you can also attach logs.
Thanks. (closing)
