### ISSUE TITLE
DisplayLink/EVDI breaks on Kernel 6.2

### ISSUE THREAD

**Issue by SimPilotAdamT** [DisplayLink/evdi#402]
* Are you using the latest driver? yes
    
  * Are you using the latest EVDI version? yes, as compiled from the devel branch
    
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website? yes
    
  * Is this issue related to evdi/kernel? yes
    

  * Linux distribution and its version: Arch Linux rolling with all unstable and testing repos enabled
  * Linux kernel version: 6.2.0-arch1-1
  * Xorg version (if used): N/A
  * Desktop environment in use: KDE Plasma

[Here](https://pastebin.com/48gkQvu0) are my logs for building the DKMS module of EVDI as compiled from the devel branch, from [the AUR](https://aur.archlinux.org/packages/evdi-git).

**Comment by verasminsk** [comment]
+1 :)
the build works on 6.1.* kernels, but on 6.2 the same errors...

**Comment by listout** [comment]
#401

**Comment by verasminsk** [comment]
@listout, thank you, it worked! :)

**~$ dkms status
asus-wmi-sensors/202f6c1, 6.2.0-060200-generic, x86_64: installed
evdi/1.12.0, 6.2.0-060200-generic, x86_64: installed
virtualbox/6.1.38, 6.2.0-060200-generic, x86_64: installed**

**Comment by listout** [comment]
@verasminsk thanks a lot for testing. Glad it worked.

**Comment by dylanmtaylor** [comment]
I'm also seeing this on kernel 6.2, 

Error! Bad return status for module build on kernel: 6.2.0-arch1-1 (x86_64)
Consult /var/lib/dkms/evdi/1.12.0/build/make.log for more information.

If this was mainlined (see #25), this wouldn't be an issue.

**Comment by SimPilotAdamT** [comment]
@dylanmtaylor, yeah that's the error message... Have you tried @listout's fix in #401?

**Comment by virtadpt** [comment]
Seeing it here, too.  Linux kernel v6.2.2, evdi 1.12.0.

**Comment by hlovdal** [comment]
The changes in the third comment is present in commit [a47ded875c20](https://github.com/DisplayLink/evdi/commit/a47ded875c208fc38dee3f808f2b0639a86f1730) made 2023-01-03 (but pushed in March?).

And since that commit was included in release v1.13.0 made a month ago I guess this issue could be closed?

**Comment by floeschie** [comment]
I still have this issue and I don't see a evdi release v1.13.0 [on their GitHub page](https://github.com/DisplayLink/evdi/releases). @hlovdal can you point me to the v1.13.0 release?

**Comment by dominikzogg** [comment]
@floeschie use the develop branch it doesn't seemed to be released yet

**Comment by SimPilotAdamT** [comment]
I'm closing this issue now, the fix has been merged into the dev branch, and there is a stable tag with the fix applied.
