### ISSUE TITLE
Build failure 6.1.13-200.fc37.x86_64

### ISSUE THREAD

**Issue by philtreF** [DisplayLink/evdi#403]
* Linux distribution and its version **Fedora 37 Workstation**
  * Linux kernel version **6.1.13-200.fc37.x86_64**
  * Xorg version (if used) **Wayland**
  * Desktop environment in use **Gnome**

Hi, Everything worked fine the first time I installed Displaylink on my fedora 37.
Since kernel upgrade, I got build failure on evdi every time.

```
[root@pc-4 ~]# dkms build -m evdi -v 1.12.0 --force
Sign command: /lib/modules/6.1.13-200.fc37.x86_64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
make -j4 KERNELRELEASE=6.1.13-200.fc37.x86_64 all INCLUDEDIR=/lib/modules/6.1.13-200.fc37.x86_64/build/include KVERSION=6.1.13-200.fc37.x86_64 DKMS_BUILD=1...(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.1.13-200.fc37.x86_64 (x86_64)
Consult /var/lib/dkms/evdi/1.12.0/build/make.log for more information.
```
[Here is /var/lib/dkms/evdi/1.12.0/build/make.log](https://pastebin.com/HansMGeK)

Did someone alreday got that behavior ?

Fred

**Comment by listout** [comment]
Are your kernel version and headers same? I'm guessing you have newer headers than your kernel

**Comment by dylanmtaylor** [comment]
6.1 and 6.2 build is broken right now. There is a patch on #401 but honestly, this should be upstreamed to avoid this issue entirely as suggested in #25.

**Comment by synaptics-lspintzyk** [comment]
Closing. Please raise new issue when this still happens with latest evdi driver.
