### ISSUE TITLE
Monitor not detected and trouble building evdi, Pop!_os, kernel 6.2.6

### ISSUE THREAD

**Issue by absolu-darancourt** [DisplayLink/evdi#411]
Since the last update, I cannot for the life of me make my 3rd monitor work.
I've had trouble in the past with kernel updates and the displaylink usb monitor stopping working but i've always managed using the EVDI repo.
I've tried with the method of cloning the repo with a ``make`` and ``make install`` and patching the installer by forcing it to use the repo evdi, as well as other stuff i dont fully unerstand.

The method that always worked in the past for me was compiling and installing with make. but this time i cant because of first and SSL error which I corrected using this [method](https://github.com/andikleen/simple-pt/issues/8#issuecomment-813438385).

but after ``make install`` i still have no evdi in the list outputed with dkms status.
Here is the make install output:
```
make -C /lib/modules/6.2.0-76060200-generic/build M=$PWD INSTALL_MOD_PATH= INSTALL_MOD_DIR=/kernel/drivers/gpu/drm/evdi modules_install
make[1]: Entering directory '/usr/src/linux-headers-6.2.0-76060200-generic'
  INSTALL /lib/modules/6.2.0-76060200-generic//kernel/drivers/gpu/drm/evdi/evdi.ko
  SIGN    /lib/modules/6.2.0-76060200-generic//kernel/drivers/gpu/drm/evdi/evdi.ko
  DEPMOD  /lib/modules/6.2.0-76060200-generic
Warning: modules_install: missing 'System.map' file. Skipping depmod.
make[1]: Leaving directory '/usr/src/linux-headers-6.2.0-76060200-generic'
true
```
Thanks in advance for your help

System information:

  * Are you using the latest driver?
    Yes (5.6.1-59.184) 
  * Are you using the latest EVDI version?
    Yes (1.13.1)
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
    Yes
  * Is this issue related to evdi/kernel?
  I honestly don't know, I'm a relatively long time linux user, but not well versed on low level stuff like this.
    

  * Linux distribution and its version : Pop!_OS 22.06
  * Linux kernel version 6.2.0-76060200-generic (and 6.2.0)
  * Xorg version: x11 2:21.1.3-2ubuntu2.9
  * Desktop environment in use: Gnome (I think, default of pop!_os)

**Comment by absolu-darancourt** [comment]
I'm stupid,
I renamed the symlink to evdi-1.13.1 thinking I needed to do it since the version changed.
I did not. Reinstalling everything using symlink name evdi-1.12.0 and it works.

Closing.

**Comment by patriciabocho** [comment]
Could you let me know how exactly you build evdi? Or link me to a resource I can use to learn how to do this?

I'm a new-ish linux user and haven't had to do anything like this in the past. I'm trying to do the exact thing you're doing I think: use a displaylink enabled docking station for a multiple monitor setup (2 in my case) but the displaylink driver installation is hanging up on the evdi dependency. 

System information:

    Are you using the latest driver?
    Yes (5.6.1-59.184)

    Are you using the latest EVDI version?
    Yes (1.13.1)

    If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
    Yes

    Is this issue related to evdi/kernel?
    I think so. Here's the error I get.

make -C /lib/modules/6.2.6-76060206-generic/build M=$PWD
make[2]: Entering directory '/usr/src/linux-headers-6.2.6-76060206-generic'

  ERROR: Kernel configuration is invalid.
         include/generated/autoconf.h or include/config/auto.conf are missing.
         Run 'make oldconfig && make prepare' on kernel src to fix it.


    Linux distribution and its version : Pop!_OS 22.04

    Linux kernel version 6.2.6-76060206-generic

    Xorg version: x11 2:21.1.3-2ubuntu2.9

    Desktop environment in use: Gnome (I think, default of pop!_os)

**Comment by absolu-darancourt** [comment]
Try this [method](https://github.com/DisplayLink/evdi/issues/384#issuecomment-1301739514)
You also need to install the official drivers you can download on displaylink's website.
Hope this helps.
