### ISSUE TITLE
How to install evdi from source on Ubuntu? (HOWTO)

### ISSUE THREAD

**Issue by SamSpiri** [DisplayLink/evdi#413]
How do you use this repo with displaylink driver?
It was a pain to figure it out. Hopefully this solution helps:
```
mkdir 123
cd 123
git clone https://github.com/DisplayLink/evdi.git
# please MANUALLY download this file before executing:
./displaylink-driver-x.x.x-xx.xxx.run --target displaylink --noexec
cd displaylink
tar -czf evdi.tar.gz -C ../evdi .
sudo ./displaylink-installer.sh uninstall
sudo rmmod evdi
sudo ./displaylink-installer.sh noreboot
sudo systemctl start displaylink-driver.service
```

**Comment by amatmv** [comment]
Man, you made my day.Thank you!

**Comment by jamesvespa** [comment]
I had this issue with Ubuntu 24.04 - they have released a new version that fixed it:

https://www.synaptics.com/products/displaylink-usb-graphics-software-ubuntu-61?filetype=exe

**Comment by FrankP89** [comment]
> I had this issue with Ubuntu 24.04 - they have released a new version that fixed it:
> 
> https://www.synaptics.com/products/displaylink-usb-graphics-software-ubuntu-61?filetype=exe

This is the real answer
