### ISSUE TITLE
Cant compile on latest OpenSuze version

### ISSUE THREAD

**Issue by maxime-bern** [DisplayLink/evdi#415]
* Are you using the latest driver?
    `yes`
  * Are you using the latest EVDI version?
    `yes`
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
    `yes`
  * Is this issue related to evdi/kernel?
    `yes`

  * Linux distribution and its version
     `openSUSE Tumbleweed x86_64 20230416`

  * Linux kernel version
     `6.2.10-1-default (64-bit)`

  * Xorg version (if used)
```
X.Org X Server 1.21.1.8
X Protocol Version 11, Revision 0  
```

  * Desktop environment in use
     `KDE Plasma`

Hello,
 
I can't compile the module. 
here are the logs: [https://pastebin.com/rKvuDbaT](https://pastebin.com/rKvuDbaT)
As you can see I use gcc 13, do you think that could be the cause of these errors ?

Thanks in advance for your help !

**Comment by maxime-bern** [comment]
It seems that the problem comes from the libdrm package which is not found by the installation script.

`error: include/drm: entry file of the link editor not found: No file or folder of this type`

**Comment by marcelolaia** [comment]
Probable duplicated with [this one](https://github.com/DisplayLink/evdi/issues/412#issue-1666921068)

**Comment by displaylink-emajewsk** [comment]
@maxime-bern @grinco Have you tried using the new standalone 5.7 driver?

https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu

Only Ubuntu is supported in an official manner, but I can assist you with some troubleshooting

**Comment by grinco** [comment]
@displaylink-emajewsk 
[make.log](https://github.com/DisplayLink/evdi/files/11311230/make.log)
I did. evdi fails to build (see log attached).

**Comment by maxime-bern** [comment]
@displaylink-emajewsk 

It's now succesfuly installing with the new driver !
But even after a reboot i can't use my USB dock.

How can i check if the driver is started ?
I can't find it with systemctl.

**Comment by displaylink-emajewsk** [comment]
I have a free moment rn. Let me try installing tumbleweed

`displaylink-driver` service should start after plugging in the dock.

**Comment by maxime-bern** [comment]
It's seems that evdi is not installed even after the installer say it's ok.

```
> modprobe evdi
modprobe: FATAL: Module evdi not found in directory /lib/modules/6.2.12-1-default
```

**Comment by displaylink-emajewsk** [comment]
Yes. It is unable to find libdrm headers even though they're installed. I managed to reproduce (and fix) your issue on Tumbleweed but I'll elaborate on it later. Very short on time today. I believe the same thing happens in #412

**Comment by grinco** [comment]
Can confirm this version work: https://github.com/DisplayLink/evdi/issues/412#issuecomment-1512886563
Using this change: https://github.com/DisplayLink/evdi/issues/412#issuecomment-1523694684

**Comment by displaylink-emajewsk** [comment]
I have pushed the fix to the GitHub repository, but cannot be sure when the updated driver will be released.

**Comment by synaptics-lspintzyk** [comment]
Fix released long time ago. Closing.
