### ISSUE TITLE
Void Linux errors

### ISSUE THREAD

**Issue by johnny-mac** [DisplayLink/evdi#419]
`evdi_lib.c:` In function 'device_exists':
evdi_lib.c:237:18: error: 'PATH_MAX' undeclared (first use in this function)
  237 |         char dev[PATH_MAX] = "";
      |                  ^~~~~~~~
evdi_lib.c:237:18: note: each undeclared identifier is reported only once for each function it appears in
evdi_lib.c:237:14: error: unused variable 'dev' [-Werror=unused-variable]
  237 |         char dev[PATH_MAX] = "";
      |              ^~~
evdi_lib.c: In function 'does_path_links_to':
evdi_lib.c:245:24: error: 'PATH_MAX' undeclared (first use in this function)
  245 |         char real_path[PATH_MAX];
      |                        ^~~~~~~~
evdi_lib.c:245:14: error: unused variable 'real_path' [-Werror=unused-variable]
  245 |         char real_path[PATH_MAX];
      |              ^~~~~~~~~
evdi_lib.c: In function 'process_opened_device':
evdi_lib.c:258:24: error: 'PATH_MAX' undeclared (first use in this function)
  258 |         char maps_path[PATH_MAX];
      |                        ^~~~~~~~
evdi_lib.c:258:14: error: unused variable 'maps_path' [-Werror=unused-variable]
  258 |         char maps_path[PATH_MAX];
      |              ^~~~~~~~~
evdi_lib.c: In function 'process_opened_files':
evdi_lib.c:282:22: error: 'PATH_MAX' undeclared (first use in this function)
  282 |         char fd_path[PATH_MAX];
      |                      ^~~~~~~~
evdi_lib.c:295:22: error: unused variable 'path' [-Werror=unused-variable]
  295 |                 char path[PATH_MAX];
      |                      ^~~~
evdi_lib.c:282:14: error: unused variable 'fd_path' [-Werror=unused-variable]
  282 |         char fd_path[PATH_MAX];
      |              ^~~~~~~
evdi_lib.c: In function 'open_device':
evdi_lib.c:412:18: error: 'PATH_MAX' undeclared (first use in this function)
  412 |         char dev[PATH_MAX] = "";
      |                  ^~~~~~~~
evdi_lib.c:412:14: error: unused variable 'dev' [-Werror=unused-variable]
  412 |         char dev[PATH_MAX] = "";
      |              ^~~
evdi_lib.c: In function 'is_correct_parent_device':
evdi_lib.c:473:24: error: 'PATH_MAX' undeclared (first use in this function)
  473 |         char link_path[PATH_MAX];
      |                        ^~~~~~~~
evdi_lib.c:480:14: error: unused variable 'link_resolution' [-Werror=unused-variable]
  480 |         char link_resolution[PATH_MAX];
      |              ^~~~~~~~~~~~~~~
evdi_lib.c:473:14: error: unused variable 'link_path' [-Werror=unused-variable]
  473 |         char link_path[PATH_MAX];
      |              ^~~~~~~~~
evdi_lib.c: In function 'find_unused_card_for':
evdi_lib.c:517:32: error: 'PATH_MAX' undeclared (first use in this function)
  517 |                 char evdi_path[PATH_MAX];
      |                                ^~~~~~~~
evdi_lib.c:524:22: error: unused variable 'evdi_drm_path' [-Werror=unused-variable]
  524 |                 char evdi_drm_path[PATH_MAX];
      |                      ^~~~~~~~~~~~~
evdi_lib.c:517:22: error: unused variable 'evdi_path' [-Werror=unused-variable]
  517 |                 char evdi_path[PATH_MAX];
      |                      ^~~~~~~~~
evdi_lib.c: In function 'evdi_device_to_platform':
evdi_lib.c:602:24: error: 'PATH_MAX' undeclared (first use in this function)
  602 |         char card_path[PATH_MAX];
      |                        ^~~~~~~~
evdi_lib.c:602:14: error: unused variable 'card_path' [-Werror=unused-variable]
  602 |         char card_path[PATH_MAX];
      |              ^~~~~~~~~
evdi_lib.c: In function 'evdi_check_device':
evdi_lib.c:632:19: error: 'PATH_MAX' undeclared (first use in this function)
  632 |         char path[PATH_MAX];
      |                   ^~~~~~~~
evdi_lib.c:632:14: error: unused variable 'path' [-Werror=unused-variable]
  632 |         char path[PATH_MAX];
      |              ^~~~
evdi_lib.c: In function 'device_exists':
evdi_lib.c:241:1: error: control reaches end of non-void function [-Werror=return-type]
  241 | }
      | ^
evdi_lib.c: In function 'does_path_links_to':
evdi_lib.c:254:1: error: control reaches end of non-void function [-Werror=return-type]
  254 | }
      | ^
evdi_lib.c: In function 'evdi_check_device':
evdi_lib.c:635:1: error: control reaches end of non-void function [-Werror=return-type]
  635 | }
      | ^
cc1: all warnings being treated as errors
make[1]: *** [<builtin>: evdi_lib.o] Error 1
make[1]: Leaving directory '/home/kzn/Compiles/evdi/library'
make: *** [Makefile:11: all] Error 2
`

**Comment by johnny-mac** [comment]
I just copied what I thought was relevant, here's the top of it:
 make -j5
CFLAGS="-isystem./include -isystem./include/uapi -Werror -Wextra -Wall -Wno-error=missing-field-initializers -Werror=sign-compare -Wmissing-prototypes -Wstrict-prototypes -Werror=discarded-qualifiers " make -C module -j5 --jobserver-auth=3,4
make[1]: warning: -j5 forced in submake: resetting jobserver mode.
make[1]: Entering directory '/home/kzn/Compiles/evdi/module'
make -C /lib/modules/6.2.15_1/build M=$PWD
make[2]: Entering directory '/usr/src/kernel-headers-6.2.15_1'
  CC [M]  /home/kzn/Compiles/evdi/module/evdi_platform_drv.o
  CC [M]  /home/kzn/Compiles/evdi/module/evdi_platform_dev.o
  CC [M]  /home/kzn/Compiles/evdi/module/evdi_sysfs.o
  CC [M]  /home/kzn/Compiles/evdi/module/evdi_modeset.o
  CC [M]  /home/kzn/Compiles/evdi/module/evdi_connector.o
gcc: warning: include/drm: linker input file unused because linking not done
  CC [M]  /home/kzn/Compiles/evdi/module/evdi_encoder.o
gcc: warning: include/drm: linker input file unused because linking not done
  CC [M]  /home/kzn/Compiles/evdi/module/evdi_drm_drv.o
gcc: warning: include/drm: linker input file unused because linking not done
gcc: warning: include/drm: linker input file unused because linking not done
  CC [M]  /home/kzn/Compiles/evdi/module/evdi_fb.o
  CC [M]  /home/kzn/Compiles/evdi/module/evdi_gem.o
gcc: warning: include/drm: linker input file unused because linking not done
  CC [M]  /home/kzn/Compiles/evdi/module/evdi_painter.o
gcc: warning: include/drm: linker input file unused because linking not done
  CC [M]  /home/kzn/Compiles/evdi/module/evdi_params.o
gcc: warning: include/drm: linker input file unused because linking not done
  CC [M]  /home/kzn/Compiles/evdi/module/evdi_cursor.o
gcc: warning: include/drm: linker input file unused because linking not done
gcc: warning: include/drm: linker input file unused because linking not done
  CC [M]  /home/kzn/Compiles/evdi/module/evdi_debug.o
  CC [M]  /home/kzn/Compiles/evdi/module/evdi_i2c.o
gcc: warning: include/drm: linker input file unused because linking not done
  CC [M]  /home/kzn/Compiles/evdi/module/evdi_ioc32.o
gcc: warning: include/drm: linker input file unused because linking not done
gcc: warning: include/drm: linker input file unused because linking not done
gcc: warning: include/drm: linker input file unused because linking not done
gcc: warning: include/drm: linker input file unused because linking not done
gcc: warning: include/drm: linker input file unused because linking not done
  LD [M]  /home/kzn/Compiles/evdi/module/evdi.o
  MODPOST /home/kzn/Compiles/evdi/module/Module.symvers
  CC [M]  /home/kzn/Compiles/evdi/module/evdi.mod.o
  LD [M]  /home/kzn/Compiles/evdi/module/evdi.ko
  BTF [M] /home/kzn/Compiles/evdi/module/evdi.ko
Skipping BTF generation for /home/kzn/Compiles/evdi/module/evdi.ko due to unavailability of vmlinux
make[2]: Leaving directory '/usr/src/kernel-headers-6.2.15_1'
make[1]: Leaving directory '/home/kzn/Compiles/evdi/module'
CFLAGS="-I../module -Werror -Wextra -Wall -Wno-error=missing-field-initializers -Werror=sign-compare -Wmissing-prototypes -Wstrict-prototypes -Werror=discarded-qualifiers " make -C library -j5 --jobserver-auth=3,4
make[1]: warning: -j5 forced in submake: resetting jobserver mode.
make[1]: Entering directory '/home/kzn/Compiles/evdi/library'
cc -I../module -std=gnu99 -fPIC -D_FILE_OFFSET_BITS=64 -I../module -Werror -Wextra -Wall -Wno-error=missing-field-initializers -Werror=sign-compare -Wmissing-prototypes -Wstrict-prototypes -Werror=discarded-qualifiers  $(pkg-config --cflags-only-I libdrm)   -c -o evdi_lib.o evdi_lib.c

**Comment by johnny-mac** [comment]
the releases won't build, doesn't find the kernel header so I git cloned the current repo, and that's as far as I can get.

**Comment by synaptics-lspintzyk** [comment]
Please raise it with Void linux maintainers. 
PLease also check latest evdi release. Closing.
