### ISSUE TITLE
Why binary-only driver?

### ISSUE THREAD

**Issue by danielkrajnik** [DisplayLink/evdi#428]
This surely isn't the right place to post this, but I couldn't find any other platform, so if you could please let us know why this hasn't been even addressed that would be really helpful - working with binary only driver is a nightmare for a lot of users. Are there are any reasons why DisplayLink won't open-source the driver and let community develop it?

I imagine that this would take extra effort, but also would increase sales as mentioned multiple times on [the thread](https://support.displaylink.com/forums/287786-displaylink-feature-suggestions/suggestions/17798941-make-the-linux-driver-open-source-and-get-it-into)

**Comment by cpontvieux-systra** [comment]
It seems already Opensource (licence is MIT).
But it’s not included in the main branch Linux kernel.
This means it’s difficult to keep it in sync with any version of the kernel.
Does a merge request have already been done for kernel inclusion ?
