### ISSUE TITLE
Nitpick: Add proper git tags

### ISSUE THREAD

**Issue by torstehu** [DisplayLink/evdi#43]
Hi, minor nitpick here but if i run `git describe --tags` returns:

`v1.2.55`

but `git describe` returns 

`v1.0.68-47-g6fe15f50fb``

I would expect to see `v1.2.55`  or similar to sync up with releases

**Comment by torstehu** [comment]
My mistake I was on the wrong branch.

**Comment by displaylink-mlukaszek** [comment]
$ git checkout master
$ git describe --tags
v1.2.55

But admit it was not very consistent in past :)
