### ISSUE TITLE
building on SuSe Linux 15.x

### ISSUE THREAD

**Issue by commandline-be** [DisplayLink/evdi#430]
* Are you using the latest driver? YES
  * Are you using the latest EVDI version? YES (tested for both 1.7.0 and 1.13.1)
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website? Yes, i know this device works with evdi/displaylink
  * Is this issue related to evdi/kernel? most likely

  * Linux distribution and its version : SUSE Linux Enterprise Desktop 15
  * Linux kernel version 5.14.21-150500.55.7-default
  * Xorg version (if used) using Wayland
  * Desktop environment in use : Gnome 44

### Not building on SLED 15.5, the below are changes which do make it build  without DRM 

> #### building *WITH* drm enabled *fails* as for other reported issues with drm/drm_irq.h #308 

> #### required to add the libkms library to avoid compile errors  

    zypper install libkms-devel   

> modify the Makefile by commenting out  
  
    CONFIG_DRM_EVDI := m   

> so it now reads  
  
    #CONFIG_DRM_EVDI := m  

- Now the module builds and install into dkms but does not install into the kernel tree with either of below warnings depending on the dkms command used (respectively build and install)
    -  WARNING: Symbol version dump "Module.symvers" is missing.
         Modules may not have dependencies or modversions.
         You may get many unresolved symbol warnings.
    - Warning: modules_install: missing 'System.map' file. Skipping depmod.

**Comment by synaptics-lspintzyk** [comment]
Issue #308 is fixed. Please check is this is still happening with latest evdi driver.
Warnings you are mentioning should not cause this issue. Given you are on SUSE linux I would suspect that module was not signed and not loaded.

Therefore I suggest to try again with updated driver or in your case look for updates in SUSE repos.
I am closing this issue. Please raise new one if this still happens.
