### ISSUE TITLE
Build fails on OpenSuse Leap 15.5 Linux version: 5.14.21-150500.53

### ISSUE THREAD

**Issue by houssembenhmida** [DisplayLink/evdi#431]
* Are you using the latest driver?
      yes
    
  * Are you using the latest EVDI version?
      yes,using evdi 1.14.1
    
   * Is this issue related to evdi/kernel? most likely

  * Linux distribution and its version
     opensuse Leap 15.5
  * Linux kernel version
     5.14.21-150500.53-default

Build fails on OpenSuse Leap 15.5 Linux version: 5.14.21-150500.53 with error: 

> [   73s] In file included from /var/tmp/evdi-dkms-check/evdi/1.14.1/build/evdi_drm_drv.c:31:0:
[   73s] /var/tmp/evdi-dkms-check/evdi/1.14.1/build/evdi_drm_drv.h:32:10: fatal error: drm/drm_irq.h: No such file or directory
[   73s]  #include <drm/drm_irq.h>
[   73s]           ^~~~~~~~~~~~~~~
[   73s] compilation terminated.
[   73s] make[3]: *** [/usr/src/linux-5.14.21-150500.53/scripts/Makefile.build:276: /var/tmp/evdi-dkms-check/evdi/1.14.1/build/evdi_drm_drv.o] Error 1
[   73s] make[3]: *** Waiting for unfinished jobs....
[   73s] In file included from /var/tmp/evdi-dkms-check/evdi/1.14.1/build/evdi_platform_dev.c:27:0:
[   73s] /var/tmp/evdi-dkms-check/evdi/1.14.1/build/evdi_drm_drv.h:32:10: fatal error: drm/drm_irq.h: No such file or directory
[   73s]  #include <drm/drm_irq.h>
[   73s]           ^~~~~~~~~~~~~~~
[   73s] compilation terminated.
[   73s] make[3]: *** [/usr/src/linux-5.14.21-150500.53/scripts/Makefile.build:276: /var/tmp/evdi-dkms-check/evdi/1.14.1/build/evdi_platform_dev.o] Error 1
[   73s] In file included from /var/tmp/evdi-dkms-check/evdi/1.14.1/build/evdi_connector.c:19:0:
[   73s] /var/tmp/evdi-dkms-check/evdi/1.14.1/build/evdi_drm_drv.h:32:10: fatal error: drm/drm_irq.h: No such file or directory
[   73s]  #include <drm/drm_irq.h>
[   73s]           ^~~~~~~~~~~~~~~
[   73s] compilation terminated.
[   73s] make[3]: *** [/usr/src/linux-5.14.21-150500.53/scripts/Makefile.build:276: /var/tmp/evdi-dkms-check/evdi/1.14.1/build/evdi_connector.o] Error 1
[   73s] In file included from /var/tmp/evdi-dkms-check/evdi/1.14.1/build/evdi_modeset.c:29:0:
[   73s] /var/tmp/evdi-dkms-check/evdi/1.14.1/build/evdi_drm_drv.h:32:10: fatal error: drm/drm_irq.h: No such file or directory
[   73s]  #include <drm/drm_irq.h>
[   73s]           ^~~~~~~~~~~~~~~
[   73s] compilation terminated.
[   73s] make[3]: *** [/usr/src/linux-5.14.21-150500.53/scripts/Makefile.build:276: /var/tmp/evdi-dkms-check/evdi/1.14.1/build/evdi_modeset.o] Error 1
[   73s] In file included from /var/tmp/evdi-dkms-check/evdi/1.14.1/build/evdi_fb.c:31:0:
[   73s] /var/tmp/evdi-dkms-check/evdi/1.14.1/build/evdi_drm_drv.h:32:10: fatal error: drm/drm_irq.h: No such file or directory
[   73s]  #include <drm/drm_irq.h>
[   73s]           ^~~~~~~~~~~~~~~
[   73s] compilation terminated.
[   73s] In file included from /var/tmp/evdi-dkms-check/evdi/1.14.1/build/evdi_encoder.c:23:0:
[   73s] /var/tmp/evdi-dkms-check/evdi/1.14.1/build/evdi_drm_drv.h:32:10: fatal error: drm/drm_irq.h: No such file or directory
[   73s]  #include <drm/drm_irq.h>
[   73s]           ^~~~~~~~~~~~~~~
[   73s] compilation terminated.
[   73s] make[3]: *** [/usr/src/linux-5.14.21-150500.53/scripts/Makefile.build:276: /var/tmp/evdi-dkms-check/evdi/1.14.1/build/evdi_fb.o] Error 1
[   73s] make[3]: *** [/usr/src/linux-5.14.21-150500.53/scripts/Makefile.build:276: /var/tmp/evdi-dkms-check/evdi/1.14.1/build/evdi_encoder.o] Error 1

And when I applied this patch
>diff --git a/module/evdi_drm_drv.h b/module/evdi_drm_drv.h
index 5eea878..0362036 100644
--- a/module/evdi_drm_drv.h
+++ b/module/evdi_drm_drv.h
@@ -26,7 +26,7 @@
 #else
 #include <drm/drmP.h>
 #endif
-#if KERNEL_VERSION(5, 15, 0) <= LINUX_VERSION_CODE || defined(EL8) || defined(EL9)
+#if KERNEL_VERSION(5, 14, 21) <= LINUX_VERSION_CODE || defined(EL8) || defined(EL9)
 #include <drm/drm_framebuffer.h>
 #else
 #include <drm/drm_irq.h>

I received this error
>[   57s] /var/tmp/evdi-dkms-check/evdi/1.14.1/build/evdi_gem.c:15:10: fatal error: linux/dma-buf-map.h: No such file or directory
[   57s]  #include <linux/dma-buf-map.h>
[   57s]           ^~~~~~~~~~~~~~~~~~~~~
[   57s] compilation terminated.
[   57s]    ./tools/objtool/objtool orc generate  --module  --no-fp   --retpoline  --uaccess   /var/tmp/evdi-dkms-check/evdi/1.14.1/build/evdi_params.o
[   57s] make[3]: *** [/usr/src/linux-5.14.21-150500.53/scripts/Makefile.build:276: /var/tmp/evdi-dkms-check/evdi/1.14.1/build/evdi_gem.o] Error 1
[   57s] make[3]: *** Waiting for unfinished jobs....

**Comment by synaptics-lspintzyk** [comment]
Please update to latest evdi-1.14.8 release.
If this issue still happening please raise new issue. 
Thank you.
