### ISSUE TITLE
Question: sharing the virtual screen over via USB

### ISSUE THREAD

**Issue by Hi-Angel** [DisplayLink/evdi#438]
From the documentation I can't quite get that, so before I'm gonna spend days digging into the code, I'd like to ask if such usecase is covered.

My usecase: I have a turned off phone with a broken display that I want to access for backup purposes. On my Linux desktop I want to create a virtual screen and then connect the phone USB-to-USB and make phone recognize my virtual screen as an external monitor. *(note: I can't enable USB-debugging or anything, so e.g. tools like `scrcpy` won't work, it has to be something that Just Works™ as far as the phone side concerned)*

Is it possible with EVDI? Mentioning basic steps would be appreciated though.

**P.S.**: sorry for asking on a bugtracker, but the project doesn't seem to have a matrix/IRC/mailing list…

**Comment by raldone01** [comment]
I think this project only allows you to create virtual displays on the machine the kernel module is installed.
This module essentially creates a drawing surface the window manager sees as a monitor.
Other programs in user space can then copy the monitor contents and send them off to e.g a vnc connection or some kind of display device.

Does your phone have the evdi module loaded?
Do you have access to your phones shell? (adb not working?)

**Comment by Hi-Angel** [comment]
Regarding adb — it requires to enable USB-debugging, but I can't do that due to broken screen.

I guess I'll have to buy an adapter.
