### ISSUE TITLE
raspberrypi evdi kernel module

### ISSUE THREAD

**Issue by xevilstar** [DisplayLink/evdi#447]
* Are you using the latest driver?
    yes
  * Are you using the latest EVDI version?
    yes
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
   yes
  * Is this issue related to evdi/kernel?
   no it is a compatibility issue

Dead Maintainers,

I use xorg
Reading the forums there are a lot of people like me seeking Displaylink evdi driver support for the raspberry pi.
Is it possible to actually have it ?

Thanks!
-->

**Comment by synaptics-lspintzyk** [comment]
Yes it works, although it is not actively tested or might have some bugs.

You can use standalone installer or debian packages to install it.
https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu

Closing.
