### ISSUE TITLE
6.8.7.arch1 kernel doesn't work - downgrading to 6.8.4.arch1 works

### ISSUE THREAD

**Issue by pjhfggij** [DisplayLink/evdi#465]
* Are you using the latest driver?
yes 
  * Are you using the latest EVDI version?
  yes 1.14.4-0
    
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
yes
  * Is this issue related to evdi/kernel?
yes

  * Linux distribution and its version
  ArchLinux
  * Linux kernel version
  6.8.7.arch1
  * Xorg version (if used)
  Wayland
  * Desktop environment in use
  KDE6

I've just upgraded to 6.8.7.arch1 kernel and displaylink stopped working after reboot. It then worked again after reinstalling the driver and stopped working again after reboot. After downgrading to 6.8.4.arch1 it works again.

**Comment by pjhfggij** [comment]
sorry, I haven't checked errors - it just didn't send any image to an external monitor on reboot.

**Comment by selimblakaj** [comment]
After installing Evdi and I run `modinfo evdi` I get:
`modinfo: ERROR: Module evdi not found.
`
I don't know why is not installing. maybe is the kernel.

**Comment by pjhfggij** [comment]
yep, I've upgraded back to 6.8.7 kernel and `modinfo` and `modprobe` didn't see evdi anymore. Reinstalling evdi AUR package didn't help. I will try to reboot it and see if anything changes.

There seems to be evdi module in `/lib/modules/6.8.7-arch1-1/updates/dkms/evdi.ko.zst`, but I don't know if that's the right location.

**Comment by pjhfggij** [comment]
strange, now it works now after reboot. `modinfo evdi` correctly lists the module (in the above location).
@selimblakaj can you try resintalling evdi and reboot?

**Comment by selimblakaj** [comment]
@pjhfggij It seems I had old kernel 6.8.2 so after upgrading now displaylink is working good.
But still is not recognizing the extrenal monitor (USB to HDMI adapter). Maybe it's adapter fault and it won't work.

**Comment by pjhfggij** [comment]
okay, I don't know what caused this issue on the other day. Cosmic beam must have struck my displaylink. I'll close this then.

Regarding your external monitor - how about you a different HDMI cable (that got me once). Also if you are using KDE have you checked display configuration? On KDE it was off by default and had to be manually toggled on.

**Comment by selimblakaj** [comment]
@pjhfggij I have only this adapter that I was trying to use one extrenal monitor that I am not using, I tried so many things and still nothing, I am giving up it seems adapter it's not for linux.

**Comment by pjhfggij** [comment]
Sorry to hear that, that's annoying. If that's of any help I've been using this model for over a year now with moderate success (if it boots then it's fine). https://kb.cablematters.com/index.php?View=entry&EntryID=4

**Comment by selimblakaj** [comment]
Thank you, I am thinking to order this one: 
https://i-tec.pro/en-us/produkt/c31dual4k60hdmi-9/

**Comment by pjhfggij** [comment]
you'd probably want to know the exact displaylink chipset included in this product and check if there have been success reports for it in linux, but I couldn't find it (neither for the one you send or mine), so if you couldn't find it make sure the supplier has a refund policy.

**Comment by selimblakaj** [comment]
@pjhfggij I didn't have so many choices so I had to pick this one.

I found some comments on Amazon that is working with Ubuntu also it had a Linux logo on their site.
So let's hope for the best.

What is concerning me is the version of my USB-C if it can support two monitors.

**Comment by pjhfggij** [comment]
when I tried another displaylink device with two outputs it only worked for the first, I can't remember what happened when you plugged in the second one, but it either stopped working completely for both or just the second one went blank. Either way if that's the only option right now then fingers crossed.

**Comment by selimblakaj** [comment]
Yeah let's hope for the best, I appreciate your comments.
