### ISSUE TITLE
GDM and GNOME crash and return to login screen in Arch

### ISSUE THREAD

**Issue by RobertoBiundo** [DisplayLink/evdi#470]
* Are you using the latest driver?
  * Yes - aur/displaylink 6.0-0

  * Are you using the latest EVDI version?
  * Yes - ur/evdi 1.14.4-0
  
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
    Yes

  * Is this issue related to evdi/kernel?
    Yes

  * Linux distribution and its version
  *  Arch Linux
  
  * Linux kernel version
  * 6.9.3-arch1-1
  
  * Xorg version (if used)
  * No, Wayland is used extra/wayland 1.23.0-1
  
  * Desktop environment in use
  * GNOME 46

**Issue**
The current EVDI is causing GDM+GNOME to revert back to xorg instead of the default wayland when a displaylink device is connected. 

**Steps to reproduce.**
1. Start the laptop
2. Wait until GDM is presented - At this point GDM shows the GNOME and GNOME + XOrg options
3. Login using normal GNOME (This is the Wayland one)
4. Check currently running Windowing system - Wayland is shown in the about app
5. Connect a displaylink device
6. The screen flashes and im returned to the login screen - At this point only the GNOME options is available (this is the X11 one)
7. Login and open about app
8. About app shows X11 as Windowing System confirming the issue

Checking the dmesg several EVDI warnings are shown, I'm not sure if they are relevant. Here is a file with the log
[dmesg.txt](https://github.com/user-attachments/files/15531173/dmesg.txt)

Please let me know what other information could be useful.

**Here is what i tried so far:**
1. Boot the system with the displaylink device connected - This ends up with a black screen and after stopping and restarting the GDM service GDM pops up with only X11 support
2. Rolling back the kernel and headers to 6.8 (I known things worked there) - This makes no difference at all in the outcome of any of the scenarios explained so far
3. Starting the laptop without the displayLink into wayland. Switching to a different virtual terminal ctrl+alt+F5. Connecting the displaylink device and then returning to the terminal where wayland was running ctrl+alt+F1. Wayland remains running but not video output on the displaylink displays. After a logout GDM reverts to X11.
4. Uninstalling EVDI + DisplayLink and reinstalling them with clean builds (using yay). Nothing. Same outcome on all cases.
5. Trying with a different displayLink device. Nothing. Same outcome on all cases.

**Comment by csehpeti81s** [comment]
This problem affects more than one computer, I have the same issue after updating a computer yesterday. I have exactly the same wayland version (1.23.0-1) but different kernel (6.6.32-1-lts). Linux version is also the same, Arch Linux. 

I have not found the solution yet.

**Comment by displaylink-emajewsk** [comment]
Could you please report this to GNOME as well?

**Comment by RobertoBiundo** [comment]
Where would that be the gnome-shell repo in github has the issues turned off. Do you happen to know where they take issue requests?. Sorry this is my first time reporting issues in both evdi or gnome

**Comment by displaylink-emajewsk** [comment]
@RobertoBiundo GNOME uses Gitlab: https://gitlab.gnome.org/GNOME/gnome-shell

**Comment by RobertoBiundo** [comment]
To keep track the issue in GNOME repo is
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7697

**Comment by Scan-87** [comment]
Can also confirm this issue. Behavior is exactly as described

**Comment by schmunk42** [comment]
JFTR
> I was able to work around the issue by downgrading `mesa` from `1:24.1.0-1` to `1:24.0.8-1`.

**Comment by cedricroijakkers** [comment]
> To keep track the issue in GNOME repo is https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7697

It now seems this might be a mesa issue, opened an issue for them too: https://gitlab.freedesktop.org/mesa/mesa/-/issues/11321

**Comment by delthas** [comment]
Hi,

I had the exact same issue here. Thanks to your comments I just installed `mesa-git` and now everything works (the mentioned MR https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/29546 was merged).

**Comment by cedricroijakkers** [comment]
Issue should be fixed in mesa 24.1.2 to be released on 2024-06-19. This issue can be closed as it is now definitely a mesa issue.
