### ISSUE TITLE
Module evdi not found, 6.6.41-1-lts

### ISSUE THREAD

**Issue by Kofa1** [DisplayLink/evdi#478]
Hello
I've been getting this error on the stable and lts kernels: `modprobe: FATAL: Module evdi not found in directory /lib/modules/6.6.41-1-lts`
Fresh Arch install, latest packages.

Info
  * Arch
  * 6.6.41-1-lts
  * Gnome  46

**Comment by displaylink-emajewsk** [comment]
Could you please provide the `make.log` file?

**Comment by astromatt42** [comment]
I suspect this might be related, building against 6.10.3-200.fc40.x86_64 also fails with the following errors:

`  gcc -Wp,-MMD,/var/lib/dkms/evdi/1.14.4/build/.evdi_ioc32.o.d -nostdinc -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/compiler-version.h -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -fmacro-prefix-map=./= -std=gnu11 -fshort-wchar -funsigned-char -fno-common -fno-PIE -fno-strict-aliasing -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fcf-protection=branch -fno-jump-tables -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -mindirect-branch-cs-prefix -mfunction-return=thunk-extern -fno-jump-tables -mharden-sls=all -fpatchable-function-entry=16,16 -fno-delete-null-pointer-checks -O2 -fno-allow-store-data-races -fstack-protector-strong -ftrivial-auto-var-init=zero -fno-stack-clash-protection -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -fmin-function-alignment=16 -fstrict-flex-arrays=3 -fno-strict-overflow -fno-stack-check -fconserve-stack -Wall -Wundef -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Werror=strict-prototypes -Wno-format-security -Wno-trigraphs -Wno-frame-address -Wno-address-of-packed-member -Wmissing-declarations -Wmissing-prototypes -Wframe-larger-than=2048 -Wno-main -Wno-dangling-pointer -Wvla -Wno-pointer-sign -Wcast-function-type -Wno-stringop-overflow -Wno-array-bounds -Wno-alloc-size-larger-than -Wimplicit-fallthrough=5 -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Wenum-conversion -Wextra -Wunused -Wno-unused-but-set-variable -Wno-unused-const-variable -Wno-packed-not-aligned -Wno-format-overflow -Wno-format-truncation -Wno-stringop-truncation -Wno-override-init -Wno-missing-field-initializers -Wno-type-limits -Wno-shift-negative-value -Wno-maybe-uninitialized -Wno-sign-compare -Wno-unused-parameter -g -Iinclude/uapi/drm -Iinclude/drm  -fsanitize=bounds-strict -fsanitize=shift    -DMODULE  -DKBUILD_BASENAME='"evdi_ioc32"' -DKBUILD_MODNAME='"evdi"' -D__KBUILD_MODNAME=kmod_evdi -c -o /var/lib/dkms/evdi/1.14.4/build/evdi_ioc32.o /var/lib/dkms/evdi/1.14.4/build/evdi_ioc32.c  
/var/lib/dkms/evdi/1.14.4/build/evdi_gem.c: In function ‘evdi_gem_vmap’:
/var/lib/dkms/evdi/1.14.4/build/evdi_gem.c:319:25: error: implicit declaration of function ‘vmap’; did you mean ‘kmap’? [-Wimplicit-function-declaration]
  319 |         obj->vmapping = vmap(obj->pages, page_count, 0, PAGE_KERNEL);
      |                         ^~~~
      |                         kmap
/var/lib/dkms/evdi/1.14.4/build/evdi_gem.c:319:23: error: assignment to ‘void *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  319 |         obj->vmapping = vmap(obj->pages, page_count, 0, PAGE_KERNEL);
      |                       ^
/var/lib/dkms/evdi/1.14.4/build/evdi_gem.c: In function ‘evdi_gem_vunmap’:
/var/lib/dkms/evdi/1.14.4/build/evdi_gem.c:355:17: error: implicit declaration of function ‘vunmap’; did you mean ‘kunmap’? [-Wimplicit-function-declaration]
  355 |                 vunmap(obj->vmapping);
      |                 ^~~~~~
      |                 kunmap
make[3]: *** [scripts/Makefile.build:244: /var/lib/dkms/evdi/1.14.4/build/evdi_gem.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [/usr/src/kernels/6.10.3-200.fc40.x86_64/Makefile:1946: /var/lib/dkms/evdi/1.14.4/build] Error 2
make[1]: *** [Makefile:252: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/kernels/6.10.3-200.fc40.x86_64'
make: *** [Makefile:38: all] Error 2
`

**Comment by synaptics-lspintzyk** [comment]
Please check with latest displaylink drivers from Synaptics apt server: https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu
And raise issue again it still reproducible with evdi 1.14.8
