### ISSUE TITLE
After upgrade Ubuntu Gnome from 16.04 to 16.10 dock station reconnect is required to get evdi working

### ISSUE THREAD

**Issue by RussianNeuroMancer** [DisplayLink/evdi#48]
After upgrade Ubuntu Gnome from 16.04 to 16.10 dock station reconnect is required to get evdi working, both after reboot and after cold boot. 

Lenovo ThinkPad Helix 1gen
Lenovo ThinkPad USB 3.0 Dock (model DU9019D1)
Driver version: 1.2.65
Ubuntu Gnome 16.10 x86_64
Linux 4.8.0-22 (generic build)
intel DDX instead of modesetting DDX

evdi messages in dmesg at boot:

> [   10.389803] evdi: [I] Initialising logging on level 5
> [   11.345813] evdi: [D] add_store:195 Increasing device count to 1
> [   11.350148] evdi: [D] evdi_crtc_init:312 drm_crtc_init: 0
> [   11.353880] evdi: [W] evdi_painter_crtc_state_notify:377 Painter does not exist!
> [   11.353884] evdi: [D] evdi_detect:72 Painter is disconnected
> [   11.353889] evdi evdi.0: No connectors reported connected with modes
> [   11.354764] evdi evdi.0: fb1: evdidrmfb frame buffer device
> [   11.354768] [drm] evdi: evdi_stats_init
> [   11.354773] [drm] Initialized evdi 1.2.64 20161003 on minor 1
> [   17.337795] evdi: [W] evdi_painter_disconnect:478 (dev=0) An unknown connection to ffff91558d6bde00 tries to close us
> [   17.337797] evdi: [W] evdi_painter_disconnect:479  - ignoring

I assume that between 11 and 17 seconds user enter password in gdm and perform login.

After dock station reconnect external screen get enabled.
Booting with Linux 4.4.0-43 left from Ubuntu 16.04 does not workaround this issue - I still get same error message with Linux 4.4.0-43.

**Comment by DawidKurek** [comment]
Hi @RussianNeuroMancer 
Thanks for report. This looks like problem in DisplayLinkManager so please raise this on [DisplayLink Linux Forum](http://displaylink.org/forum/forumdisplay.php?f=29); take a look at our [support page](http://support.displaylink.com/knowledgebase/articles/757047-how-can-i-report-ubuntu-issues-to-displaylink).

**Comment by RussianNeuroMancer** [comment]
Thanks for answer! [Issue is reported on forum](http://displaylink.org/forum/showthread.php?p=82511).
