### ISSUE TITLE
6.10.3: .remove = evdi_platform_device_remove

### ISSUE THREAD

**Issue by dominikzogg** [DisplayLink/evdi#481]
* Are you using the latest driver? **yes**
* Are you using the latest EVDI version? **current main**
* If you are using a DisplayLink device, have you checked 'troubleshooting': **no**
* Is this issue related to evdi/kernel? **yes**
* Linux distribution and its version: **Fedora 40**
* Linux kernel version: **6.10.3-200.fc40.x86_64**
* Xorg version (if used): **-**
* Desktop environment in use: **Gnome 46**

```
make -C /lib/modules/6.10.3-200.fc40.x86_64/build M=$PWD
make[1]: Entering directory '/usr/src/kernels/6.10.3-200.fc40.x86_64'
  CC [M]  /usr/src/evdi-1.14.4/evdi_platform_drv.o
/usr/src/evdi-1.14.4/evdi_platform_drv.c:205:19: error: initialization of ‘int (*)(struct platform_device *)’ from incompatible pointer type ‘void (*)(struct platform_device *)’ [-Wincompatible-pointer-types]
  205 |         .remove = evdi_platform_device_remove,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/evdi-1.14.4/evdi_platform_drv.c:205:19: note: (near initialization for ‘evdi_platform_driver.remove’)
make[3]: *** [scripts/Makefile.build:244: /usr/src/evdi-1.14.4/evdi_platform_drv.o] Error 1
make[2]: *** [/usr/src/kernels/6.10.3-200.fc40.x86_64/Makefile:1946: /usr/src/evdi-1.14.4] Error 2
make[1]: *** [Makefile:252: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/kernels/6.10.3-200.fc40.x86_64'
make: *** [Makefile:87: module] Error 2
```

**Comment by wvdakker** [comment]
In evdi_platform_dev.h (line 35) and evdi_platform_dev.c (line  88) there is a error in the IF statements

Change in both files

`#if KERNEL_VERSION(6, 10, 0) >= LINUX_VERSION_CODE`

to

`#if KERNEL_VERSION(6, 10, 0) <= LINUX_VERSION_CODE`

Then it builds fine.

**Comment by aschleifer** [comment]
I can confirm this works for archlinux

**Comment by dominikzogg** [comment]
@wvdakker when changing the third occurence (see this commit) it works: https://github.com/DisplayLink/evdi/commit/76505e9d1ea8670d101a10896fd67b8203be897c

**Comment by dominikzogg** [comment]
@mkananov FYI

**Comment by wvdakker** [comment]
> @wvdakker when changing the third occurence (see this commit) it works: [76505e9](https://github.com/DisplayLink/evdi/commit/76505e9d1ea8670d101a10896fd67b8203be897c)

Ah it is already merged into main.... great.

**Comment by dominikzogg** [comment]
@wvdakker i mentioned it cause it seems it was one in the wrong direction

**Comment by wvdakker** [comment]
> @wvdakker i mentioned it cause it seems it was one in the wrong direction

Ah, didnt see you referring... on my phone .....

**Comment by synaptics-lspintzyk** [comment]
Should work on evdi-1.14.8. Please raise new issue if this still happen. Closing.
