### ISSUE TITLE
Module evdi not found in directory /lib/modules/6.10.3-arch1-2 

### ISSUE THREAD

**Issue by rbeucher** [DisplayLink/evdi#485]
* Are you using the latest driver? Y
    
  * Are you using the latest EVDI version? Y
    
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website? Y
    
  * Is this issue related to evdi/kernel?
    

  * Linux distribution and its version Arch Linux
  * Linux kernel version 6.10.3-arch1-2
  * Xorg version (if used)
  * Desktop environment in use Gnome

Hi,

I have just hit that issue after upgrading my system this morning (Arch Linux, Kernel 6.10.3)
My diplayport monitors are not detected. The journal shows that the displaylink system is down and cannot find evdi.
I have tried to update evdi using the git repo (AUR evdi-git package) without luck...

```
Aug 12 09:42:27 njord systemd[1]: Starting DisplayLink Manager Service...
Aug 12 09:42:27 njord modprobe[2976]: modprobe: FATAL: Module evdi not found in directory /lib/modules/6.10.3-arch1-2
Aug 12 09:42:27 njord systemd[1]: displaylink.service: Control process exited, code=exited, status=1/FAILURE
Aug 12 09:42:27 njord systemd[1]: displaylink.service: Failed with result 'exit-code'.
Aug 12 09:42:27 njord systemd[1]: Failed to start DisplayLink Manager Service.
lines 4261-4316/4316 (END)
```

Thanks for your help!

**Comment by wvdakker** [comment]
Perhaps the solution in #481 works for you. You have to rebuild the evdi module with dkms.

**Comment by rbeucher** [comment]
Thanks @wvdakker. Yes, that fixed the issue.

**Comment by php4fan** [comment]
I have the same issue. I get:
```
 modprobe: FATAL: Module evdi not found in directory /lib/modules/6.12.25-1-MANJARO
```

What's the actual solution??

I don't know how to apply the workaround linked in @wvdakker 's comment. I have installed `evdi` and `displaylink` with Pamac.

**Comment by cgte** [comment]
Hi sometimes there is a new kernel in between, so installing the latest kernel and header *may* be an option.

 Having this error : 

`#  robe: FATAL: Module evdi not found in directory /lib/modules/6.15.9-2-MANJARO `

i tried to install  linux615 linux615-headers 

`sudo pacman -S linux615 linux615-headers`

the os complained that this way legacy verison and suggested to install 6.16 

there we go 

`sudo pacman -S linux616 linux616-headers`


log shows that the module is added.

(i did a grub-update, but it may not be mandatory)
