### ISSUE TITLE
Cannot compile on Debian 12 kernel 6.1.0-23: errors in Card.h

### ISSUE THREAD

**Issue by AngelBlue01** [DisplayLink/evdi#487]
When I attempt to run `make`  from the latest release version I get the following output:

> FLAGS="-isystem./include -isystem./include/uapi -Werror -Wextra -Wall -Wno-error=missing-field-initializers -Werror=sign-compare -Wmissing-prototypes -Wstrict-prototypes -Werror=discarded-qualifiers " make -C module 
> make[1]: Entering directory '/home/thomas/downloads/evdi-1.14.5/module'
> make -C /lib/modules/6.1.0-23-amd64/build M=$PWD
> make[2]: Entering directory '/usr/src/linux-headers-6.1.0-23-amd64'
>   MODPOST /home/thomas/downloads/evdi-1.14.5/module/Module.symvers
> make[2]: Leaving directory '/usr/src/linux-headers-6.1.0-23-amd64'
> make[1]: Leaving directory '/home/thomas/downloads/evdi-1.14.5/module'
> CFLAGS="-I../module -Werror -Wextra -Wall -Wno-error=missing-field-initializers -Werror=sign-compare -Wmissing-prototypes -Wstrict-prototypes -Werror=discarded-qualifiers " make -C library 
> make[1]: Entering directory '/home/thomas/downloads/evdi-1.14.5/library'
> make[1]: Nothing to be done for 'default'.
> make[1]: Leaving directory '/home/thomas/downloads/evdi-1.14.5/library'
> CXXFLAGS="-I../module -I../library -Werror -Wextra -Wall -Wno-error=missing-field-initializers -Werror=sign-compare " make -C pyevdi 
> make[1]: Entering directory '/home/thomas/downloads/evdi-1.14.5/pyevdi'
> g++ -I../library $(python3 -m pybind11 --includes) -std=c++20 -fPIC -fvisibility=hidden -I../module -I../library -Werror -Wextra -Wall -Wno-error=missing-field-initializers -Werror=sign-compare  -c Card.cpp
> In file included from Card.h:11,
>                  from Card.cpp:6:
> Stats.h:25:26: error: ‘chrono’ is not a member of ‘std’
>    25 |         std::vector<std::chrono::microseconds> grabPixelStats;
>       |                          ^~~~~~
> Stats.h:25:46: error: template argument 1 is invalid
>    25 |         std::vector<std::chrono::microseconds> grabPixelStats;
>       |                                              ^
> Stats.h:25:46: error: template argument 2 is invalid
> Stats.h:25:14: error: ‘<expression error>’ in namespace ‘std’ does not name a type
>    25 |         std::vector<std::chrono::microseconds> grabPixelStats;
>       |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Stats.h:26:26: error: ‘chrono’ is not a member of ‘std’
>    26 |         std::vector<std::chrono::microseconds> bufferStats;
>       |                          ^~~~~~
> Stats.h:26:46: error: template argument 1 is invalid
>    26 |         std::vector<std::chrono::microseconds> bufferStats;
>       |                                              ^
> Stats.h:26:46: error: template argument 2 is invalid
> Stats.h:26:14: error: ‘<expression error>’ in namespace ‘std’ does not name a type
>    26 |         std::vector<std::chrono::microseconds> bufferStats;
>       |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> make[1]: *** [Makefile:33: Card.o] Error 1
> make[1]: Leaving directory '/home/thomas/downloads/evdi-1.14.5/pyevdi'
> make: *** [Makefile:19: pyevdi] Error 2
> 

Debian 12 (Bullseye)
kernel version: 6.1.0-23-amd64 (64-bit)
X11 version number: 11.0
X.Org version: 1.21.1.7
KDE Plasma: 5.27.5
NVIDIA GeForce GT 710 with proprietary drivers

**Comment by HanSyt** [comment]
There seems to bee something wrong with the latest evdi version and debian. However..
add the synaptic repo to your system.  Be aware not to install apt install evdi at this moment, the compiled version here has a problem with Debian (even 12.6 bookworm). Instead do this;
sudo apt install evdi=1.14.6-10 (= forces the version)

Do not forget 
sudo apt-mark hold evdi 
to avoid evdi upgrading to the faulty version.

This will work in debian and you will be able to install displaylink-driver as well from this repo.

**Comment by brandon1024** [comment]
I ran into a similar problem @AngelBlue01 , but forcing version `1.14.6-10` as recommended by @HanSyt wasn't possible because this version isn't available in the repository. The closest available version for me was `1.14.5-93` and it installed correctly.

```shell
# apt install evdi=1.14.5-93
# apt-mark hold evdi
```

**Comment by synaptics-lspintzyk** [comment]
I am not able to reproduce it on evdi-1.14.5 with debian bullseye.
Please with latest main. Or raise an issue again.

**Comment by HanSyt** [comment]
I still have it on Bookworm (Bullseye is old and eol since Aug 14: https://endoflife.date/debian) And yes with Bookworm/Amd64 12.8 it is still an issue, however, old versions are stil working on newer kernels, see image

![Screenshot_20241223_160256](https://github.com/user-attachments/assets/e1b00b48-a36c-4795-a629-4a728210878d)

**Comment by synaptics-lspintzyk** [comment]
> I still have it on Bookworm (Bullseye is old and eol since Aug 14: https://endoflife.date/debian) And yes with Bookworm/Amd64 12.8 it is still an issue, however, old versions are stil working on newer kernels, see image
> 
> ![Screenshot_20241223_160256](https://private-user-images.githubusercontent.com/56794786/398192504-e1b00b48-a36c-4795-a629-4a728210878d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1Mzk2MTIsIm5iZiI6MTczNTUzOTMxMiwicGF0aCI6Ii81Njc5NDc4Ni8zOTgxOTI1MDQtZTFiMDBiNDgtYTM2Yy00Nzk1LWE2MjktNGE3MjgyMTA4NzhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA2MTUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzYjI5OWFmNDNmOTA3MmMzMjc4Y2VjMDZkMWRhZmU5ODU5ZmNlZjY2Mzc0ZDRmODg2OTBhZjJiZTZhZmQwZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hWUHPGb9d_bCcTW7YOTklYIVbBQ0mICkPkNR5zM1LJw)

I don't understand what problem you see. Card.h file is from pyevdi - python bindings that are not available in evdi.deb package.
What errors do you have?

I tried to compile pyevdi on bookworm 12.8 and I don't see any issues.

**Comment by HanSyt** [comment]
I  guess we are writing about 2 different things. I have a problem with packages from the synaptic  package list:

```
han@Latitude5400:/etc/apt/sources.list.d$ cat synaptics.list
deb [signed-by=/usr/share/keyrings/synaptics-repository-keyring.gpg] https://www.synaptics.com/sites/default/files/Ubuntu stable main
deb [signed-by=/usr/share/keyrings/synaptics-repository-keyring.gpg] https://www.synaptics.com/sites/default/files/Ubuntu stable non-free
```
You are trying to solve a probably non existing compile problem (at my place).

I guess there seems to bee a difference between Debian en Ubuntu kernel packages. I am told synaptic compiles the packages for Ubuntu (not sure if this is correct) and might not be compatible with Debian at this moment.

**Comment by synaptics-lspintzyk** [comment]
Ok, Can you share what errors you see?
I was no able to reproduce any issues with compilation on debian bookworm except problems with key enrolment (when secure boot is enabled). If this is yours situation please run 
```
mokutil --import /var/lib/dkms/mok.pub
```
As it is described on https://github.com/dell/dkms?tab=readme-ov-file#secure-boot

If this is installation issue, then please attach logs.
dkms should produce log in /var/lib/dkms/evdi/1.14.8/build/make.log

**Comment by HanSyt** [comment]
I was not able to check on this, sorry. However the good news is that the latest version:
evdi/stable,now 1.14.8-133 amd64 [installed]

is working without any problem, so the issue seems to be solved in Debian 12 with kernel:
Linux LAP70205790 6.1.0-30-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.124-1 (2025-01-12) x86_64 GNU/Linux

Thanks for helping

**Comment by synaptics-lspintzyk** [comment]
Thank you :)
