### ISSUE TITLE
USB3 to HDMI Adapter Not working on Jetson Xavier NX

### ISSUE THREAD

**Issue by cPratik-01** [DisplayLink/evdi#490]
Hello I am facing an issue regarding USB3 to HDMI adapter on Jetson Xavier NX
**L4T Version:- 35.4.1
JetPack Version:- 5.1.2
Kernel-Version:- 5.10.120-tegra
I have compiled the DisplayLink driver (evdi) for kernel version 5.10.120-tegra but it is not showing Display. I have attached driver-related logs and manual driver installation logs.
I connected a USB to HDMI adapter to the Jetson Xavier NX system, and while the status indicates that it is connected, the display does not show any output on the screen.**
[evdi_driver_dmesg_log.txt](https://github.com/user-attachments/files/16747923/evdi_driver_dmesg_log.txt)
[DisplayLink_Driver_Installation_logs.txt](https://github.com/user-attachments/files/16747924/DisplayLink_Driver_Installation_logs.txt)
![usb_to_hdmi](https://github.com/user-attachments/assets/91d1bd0d-5a68-49f7-a4d4-f012e087286b)

**Comment by jakub-prussak-synaptics** [comment]
Hi @cPratik-01 

It seems that your system has secure boot enabled, and a necessary signing step was omitted during the installation.

> evdi: loading out-of-tree module taints kernel.
> evdi: module verification failed: signature and/or required key missing - tainting kernel

Check out [this page](https://support.displaylink.com/knowledgebase/articles/1181617-how-to-use-displaylink-ubuntu-driver-with-uefi-sec) for the instructions.

**Comment by synaptics-lspintzyk** [comment]
Closing. As there is no response from the user. Please raise new issue when this still happen.
