### ISSUE TITLE
new release for kernel 6.12 ?

### ISSUE THREAD

**Issue by hobbes** [DisplayLink/evdi#500]
Hello, 

I'm using Debian sid with evdi from https://www.synaptics.com/sites/default/files/Ubuntu

Debian upgraded the kernel to version 6.12.3-amd64 a few days back. Since then, I have had to revert to the older kernel (6.11) to use displaylink devices, and today I decided to investigate. 

On 6.12, I have this in my dmesg:

[   15.780933] WARNING: CPU: 4 PID: 404 at drivers/gpu/drm/drm_file.c:312 drm_open_helper+0x132/0x150 [drm]
[   15.780986] Modules linked in: typec_ucsi(+) igen6_edac typec roles intel_pmc_core intel_vsec acpi_pad intel_hid pmt_telemetry acpi_tad ac sparse_keymap pmt_class joydev serio_raw evdev msr evdi(OE) parport_pc ppdev lp parport nvme_fabrics loop efi_pstore configfs nfnetlink ip_tables x_tables autofs4 ext4 crc16 mbcache jbd2 btrfs sd_mod dm_crypt dm_mod efivarfs raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c crc32c_generic raid1 raid0 md_mod uas usb_storage cdc_ncm cdc_ether scsi_mod usbnet mii usbhid scsi_common xe drm_gpuvm drm_exec gpu_sched drm_suballoc_helper drm_ttm_helper i915 drm_buddy i2c_algo_bit drm_display_helper hid_multitouch crct10dif_pclmul hid_generic cec crc32_pclmul rc_core crc32c_intel i2c_hid_acpi ghash_clmulni_intel ttm xhci_pci i2c_hid sha512_ssse3 drm_kms_helper hid xhci_hcd intel_lpss_pci video nvme i2c_i801 sha256_ssse3 thunderbolt drm sha1_ssse3 i2c_smbus fan usbcore intel_lpss nvme_core idma64 usb_common battery button wmi aesni_intel
[   15.781069]  gf128mul crypto_simd cryptd
[   15.781074] CPU: 4 UID: 0 PID: 404 Comm: plymouthd Tainted: G           OE      6.12.3-amd64 #1  Debian 6.12.3-1
[   15.781078] Tainted: [O]=OOT_MODULE, [E]=UNSIGNED_MODULE
[   15.781080] Hardware name: TUXEDO TUXEDO InfinityBook Pro 14 Gen6/PHxTxX1, BIOS N.1.12A05 06/11/2021
[   15.781082] RIP: 0010:drm_open_helper+0x132/0x150 [drm]
[   15.781121] Code: f5 22 ef 31 c0 48 83 c4 08 5b 5d 41 5c 41 5d 41 5e 41 5f c3 cc cc cc cc 48 89 df 89 44 24 04 e8 64 fa ff ff 8b 44 24 04 eb db <0f> 0b b8 ea ff ff ff eb d2 b8 ea ff ff ff eb cb b8 f0 ff ff ff eb
[   15.781124] RSP: 0018:ffffb95fc04938c0 EFLAGS: 00010246
[   15.781127] RAX: ffffffffc1599700 RBX: ffff9490468a4508 RCX: 0000000000000000
[   15.781129] RDX: 000044cd20223c40 RSI: ffff9490468a4508 RDI: ffff948f230fd9c0
[   15.781130] RBP: ffff948f230fd9c0 R08: ffff948f134dd480 R09: ffff948f0020c6d0
[   15.781131] R10: 00000000000000e2 R11: 0000000000000002 R12: ffff948f3922a800
[   15.781133] R13: ffffffffc1599700 R14: 00000000ffffffed R15: ffff948f01706ed0
[   15.781134] FS:  00007f350358b000(0000) GS:ffff94929fa00000(0000) knlGS:0000000000000000
[   15.781137] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   15.781138] CR2: 000055c82e45f5d8 CR3: 00000002464ba004 CR4: 0000000000f70ef0
[   15.781140] PKRU: 55555554
[   15.781142] Call Trace:
[   15.781144]  <TASK>
[   15.781146]  ? drm_open_helper+0x132/0x150 [drm]
[   15.781184]  ? __warn.cold+0x93/0xf6
[   15.781189]  ? drm_open_helper+0x132/0x150 [drm]
[   15.781223]  ? report_bug+0xff/0x140
[   15.781228]  ? handle_bug+0x58/0x90
[   15.781231]  ? exc_invalid_op+0x17/0x70
[   15.781233]  ? asm_exc_invalid_op+0x1a/0x20
[   15.781239]  ? drm_open_helper+0x132/0x150 [drm]
[   15.781276]  drm_open+0x73/0x110 [drm]
[   15.781314]  drm_stub_open+0x9b/0xd0 [drm]
[   15.781350]  chrdev_open+0xb2/0x230
[   15.781355]  ? __pfx_chrdev_open+0x10/0x10
[   15.781358]  do_dentry_open+0x14c/0x440
[   15.781361]  vfs_open+0x2e/0xe0
[   15.781364]  path_openat+0x82e/0x12d0
[   15.781368]  ? chacha_block_generic+0x78/0xd0
[   15.781372]  do_filp_open+0xc4/0x170
[   15.781377]  do_sys_openat2+0xae/0xe0
[   15.781382]  __x64_sys_openat+0x55/0xa0
[   15.781385]  do_syscall_64+0x82/0x190
[   15.781389]  ? __skb_try_recv_datagram+0xab/0x190
[   15.781394]  ? __wake_up+0x44/0x60
[   15.781397]  ? netlink_recvmsg+0x374/0x470
[   15.781401]  ? aa_sk_perm+0x46/0x210
[   15.781404]  ? sock_recvmsg+0xbd/0xd0
[   15.781408]  ? __sys_recvfrom+0xda/0x130
[   15.781413]  ? syscall_exit_to_user_mode+0x4d/0x210
[   15.781417]  ? do_syscall_64+0x8e/0x190
[   15.781420]  ? do_syscall_64+0x8e/0x190
[   15.781423]  ? do_syscall_64+0x8e/0x190
[   15.781425]  ? clear_bhb_loop+0x25/0x80
[   15.781429]  ? clear_bhb_loop+0x25/0x80
[   15.781432]  ? clear_bhb_loop+0x25/0x80
[   15.781436]  entry_SYSCALL_64_after_hwframe+0x76/0x7e
[   15.781439] RIP: 0033:0x7f3503830bb8
[   15.781447] Code: 48 89 44 24 20 75 96 44 89 54 24 0c e8 a1 b6 f8 ff 44 8b 54 24 0c 89 da 48 89 ee 41 89 c0 bf 9c ff ff ff b8 01 01 00 00 0f 05 <48> 3d 00 f0 ff ff 77 30 44 89 c7 89 44 24 0c e8 f4 b6 f8 ff 8b 44
[   15.781449] RSP: 002b:00007ffe9a0d3e20 EFLAGS: 00000293 ORIG_RAX: 0000000000000101
[   15.781452] RAX: ffffffffffffffda RBX: 0000000000000002 RCX: 00007f3503830bb8
[   15.781454] RDX: 0000000000000002 RSI: 0000562feca4ec70 RDI: 00000000ffffff9c
[   15.781455] RBP: 0000562feca4ec70 R08: 0000000000000000 R09: 0000000000000000
[   15.781457] R10: 0000000000000000 R11: 0000000000000293 R12: 00007f350358af88
[   15.781459] R13: 00007f350394c840 R14: 000000000000000b R15: 0000562feca4eb50
[   15.781462]  </TASK>

According to internet, this might be related to a2971b023709ea7335964abe5ddab93b6e70b74f

Would you consider publishing a release and push it to the synaptics ubuntu repo so that distribs switching to kernel 6.12 can use displaylink devices ?

Thanks a lot, 
Rémi

**Comment by FloTheSysadmin** [comment]
same issue on arch here

**Comment by synaptics-lspintzyk** [comment]
Please check release v1.14.8

**Comment by FloTheSysadmin** [comment]
@synaptics-lspintzyk  Works for me, thank you.
