### ISSUE TITLE
Please improve Linux drivers

### ISSUE THREAD

**Issue by anaibol** [DisplayLink/evdi#53]

**Comment by autra** [comment]
@anaibol Do you have a specific problem? If so, could you describe it?

Because just saying "please makes things better" is not really constructive. I mean, making the linux driver better is what this repo is about, so...

**Comment by anaibol** [comment]
Hi, sorry about the non descriptive title. In fact I am having big problems trying to setup a Dell D3100 dock.
I've been trying with different kernel versions: 4.4, 4.7, 4.8, with udl module and displaylink driver.
![selection_003](https://cloud.githubusercontent.com/assets/3210177/19892337/aaba35d4-a044-11e6-9c10-0e9a05f7c7d5.png)

**Comment by autra** [comment]
Even though I'm not part of DisplayLink organization,  I would suggest to:

- close this issue
- open another issue for every specific problem you have. Writing a good bug report is an important skill to have if you want your issue to get corrected. I suggest you to read [this link](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines) about it. It's for Firefox, but there are some very good general advice (especially [this section](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines#Other_details_you_should_heed) and [this one](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines#Writing_a_clear_summary) )

**Comment by anaibol** [comment]
Ok, thanks!
