### ISSUE TITLE
Missing information in libevdi docs

### ISSUE THREAD

**Issue by Ferruck** [DisplayLink/evdi#54]
I started playing around with `libevdi` but the docs seem incomplete. When I try to add a new device `evid_add_device` returns `2` whereas the docs state that 

> Return value: 1 when successful, 0 otherwise.

There is no new `cardX` within `/dev/`. Trying to create a new device as non-root leads to the correct zero return value.

As this is the first call `libevdi` I guess it's no programming error. Nevertheless, the return value `2` should be described in the docs.

**Comment by Ferruck** [comment]
I investigated the problem a bit further and it seems that the number of elements to be written by `fwrite` are incorrect. `sizeof(devices_to_add)` is passed as the argument, which is `2`, though only one `char` should be written.

I opened a pull request (#55) that fixes the problem. If it's to hacky, please let me know.

**Comment by displaylink-mlukaszek** [comment]
Thanks for pointing this out. I think it is actually a documentation being wrong there. It should say 0 when there was a problem, and a non-zero value otherwise (without worrying what the exact number is).

**Comment by Ferruck** [comment]
OK, so the pull request is obsolete. But I still wonder, do you really need to write the `\0` into the file as well?

**Comment by displaylink-mlukaszek** [comment]
No, probably not. The value is interpreted by evdi_add_store in the kernel module code, and it should be fine without the terminator.
Btw, if you intend to play with evdi and the library (which I encourage you to do), you might find this useful as an example: https://github.com/mlukaszek/evdipp

**Comment by Ferruck** [comment]
Indeed I want to play with evdi in the next days so your repo is a great ressource, thanks!

**Comment by Ferruck** [comment]
I'm not opening a new issue as I'm probably just holding it wrong.

I tried out your C++ examples and wrote one myself, but neither work. Calling `evdi_check_device` on the different `card`s in `/dev/dri/` lead to different errors:

* `card0` returns a `UNRECOGNIZED` and on the terminal I get the additional error

        [libevdi] ioctl: drop_master error=-1

    I guess this is intended and correct, because this is the default device that is present without the `evdi` driver, as well.
* Every other device I tried (I added devices up to `card10` with `evdi_add_device` which actually works) returns `NOT_PRESENT`. This seems strange to me.

I'm running Arch Linux on a ThinkPad X230, `uname -a` gives the following output:

    Linux TP_Trommler 4.8.6-1-ARCH #1 SMP PREEMPT Mon Oct 31 18:51:30 CET 2016 x86_64 GNU/Linux

Am I just dump and missing some dependencies? Is there just a simple reason why this doesn't work (and probably won't ever)? Or is this a bug in the driver?

I'd really like to work with evdi and hope that I'm just holding it wrong.

Thanks in advance!

**Comment by mlukaszek** [comment]
Could you paste a snippet of code that you're trying?

**Comment by Ferruck** [comment]
I can give you the whole code I tried, [see here](https://gist.github.com/Ferruck/d93f2a5ef6503224c49954bcb66f5720).

But I also tried your C++ examples which give me the same errors.

**Comment by mlukaszek** [comment]
Just to double check - are you running as root? Note the docs says "when the device does not exist **or cannot be opened to check**". This could be a permission problem, you need to use sudo to be able to send IOCTL from the library to the kernel module.

**Comment by Ferruck** [comment]
Of course I tried as root with sudo. Running without superuser permissions lead to different errors.

**Comment by DawidKurek** [comment]
Can you change log level? The easiest way is to write **6** to **/sys/devices/evdi/loglevel**.

**Comment by Ferruck** [comment]
OK, the verbose debug output is as follows:

```
Nov 15 11:36:23 TP_Trommler kernel: evdi: [D] add_store:195 Increasing device count to 1
Nov 15 11:36:23 TP_Trommler kernel: evdi: [V] evdi_platform_probe:119 
Nov 15 11:36:23 TP_Trommler kernel: evdi: [V] evdi_driver_load:25 
Nov 15 11:36:23 TP_Trommler kernel: evdi: [V] evdi_driver_load:37 
Nov 15 11:36:23 TP_Trommler kernel: evdi: [V] evdi_modeset_init:361 
Nov 15 11:36:23 TP_Trommler kernel: evdi: [V] evdi_crtc_init:306 
Nov 15 11:36:23 TP_Trommler kernel: evdi: [D] evdi_crtc_init:312 drm_crtc_init: 0
Nov 15 11:36:23 TP_Trommler kernel: evdi: [V] evdi_flip_workqueue_init:324 
Nov 15 11:36:23 TP_Trommler kernel: evdi: [V] evdi_crtc_disable:112 
Nov 15 11:36:23 TP_Trommler kernel: evdi: [W] evdi_painter_crtc_state_notify:377 Painter does not exist!
Nov 15 11:36:23 TP_Trommler kernel: evdi: [V] evdi_detect:67 
Nov 15 11:36:23 TP_Trommler kernel: evdi: [D] evdi_detect:72 Painter is disconnected
Nov 15 11:36:23 TP_Trommler kernel: evdi evdi.0: No connectors reported connected with modes
Nov 15 11:36:23 TP_Trommler kernel: [drm] Cannot find any crtc or sizes - going 1024x768
Nov 15 11:36:23 TP_Trommler kernel: evdi evdi.0: fb1: evdidrmfb frame buffer device
Nov 15 11:36:23 TP_Trommler kernel: [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
Nov 15 11:36:23 TP_Trommler kernel: [drm] No driver support for vblank timestamp query.
Nov 15 11:36:23 TP_Trommler kernel: evdi: [V] evdi_painter_init:677 
Nov 15 11:36:23 TP_Trommler kernel: [drm] evdi: evdi_stats_init
Nov 15 11:36:23 TP_Trommler kernel: [drm] Initialized evdi 1.2.64 20161003 on minor 1
Nov 15 11:36:23 TP_Trommler gnome-shell[506]: Failed to apply DRM plane transform 0: Keine Berechtigung
Nov 15 11:36:23 TP_Trommler gnome-shell[506]: Failed to apply DRM plane transform 0: Keine Berechtigung
```

**Comment by mlukaszek** [comment]
Have you been modifying the evdi kernel module or library code at all?

What evdi_check_device does is quite simple:
- it checks e.g. /dev/dri/card1 exists at all,
- then tries to open it (which in your case must have succeeded as you see messages about failed drop master IOCTL),
- then checks that the device is EVDI - by using DRM_IOCTL_VERSION ioctl to get the version, and comparing the name of the device with "evdi".

I guess your next logical step is to attach a debugger and step through the calls, to figure out which of the above steps fail.

**Comment by Ferruck** [comment]
No, I have neither modified the kernel module nor the library. I'll debug the program in the next days.

**Comment by Ferruck** [comment]
Sorry for the really late response. I hadn't have access to the laptop I used while encountering this issue any more. On another machine I can't reproduce the problem so I'm closing it now. Thanks for your support.
