### ISSUE TITLE
Displaylink drivers not working for Debian 8.5 (issues with providers)

### ISSUE THREAD

**Issue by dragGH102** [DisplayLink/evdi#60]
As reported [here](https://github.com/AdnanHodzic/displaylink-debian/issues/41#issuecomment-263136986) (drivers compiled for Debian) I apparently have some issues with setting up the 2nd external screen.

For your convenience I quote the part of the issue which I couldn't yet solve (according to the creator of the compiled version for Debian it seems a general driver related issue, rather than the version specifically compiled for Debian):

> xrandr --listproviders

prints

```
Provider 0: id: 0x45 cap: 0xb, Source Output, Sink Output, Sink Offload crtcs: 3 outputs: 3 associated providers: 0 name:Intel
Provider 1: id: 0xfe cap: 0x2, Sink Output crtcs: 1 outputs: 1 associated providers: 0 name:modesetting
```

However when I try to attach the displaylink adapter to my (1st) external screen I can move the mouse to the other screen.. but the screen remains black.

I tried to play a bit with **arandr** by trying different resolutions and positions (this actually seems to work to change position or resolution but doesn't solve the issue)
I also tried **xrandr --output HDMI1 --auto --right-of eDP1**.

Same result.
I didn't try with 2 2nd external screen but the display doesn't show up even for the 1st one, unless I use directly my computer's HDMI port.

Any clue? Am I doing something wrong here?

I also noticed in **arandr** in "Outputs" there is DP1 (besides eDP1) but it's gray and I can't interact with it

**Comment by AdnanHodzic** [comment]
@dragGH102 did you see [displaylink-debian workaround for Jessie](https://github.com/AdnanHodzic/displaylink-debian/issues/42)? Please see my last comment.

**Comment by displaylink-mlukaszek** [comment]
evdi connectors would always present themselves as DVI - the commands you use don't mention DVI. That said, they wouldn't even be added to the system if DisplayLinkManager did not connect to evdi - it only does request new evdi nodes when there is a compatible device connected. In any case, this looks more like a problem which needs more information and would be best progressed on DisplayLink forum, not here.
