### ISSUE TITLE
Tied to Unity?

### ISSUE THREAD

**Issue by jepster** [DisplayLink/evdi#62]
Is EVDI tied to Unity or would it run with Linux Mint also like it is running with Ubuntu? Since Linux Mint is using Cinnamon desktop instead of Unity. Linux Mint is based on Ubuntu. The latest version is based on Ubuntu 16.04.

**Comment by daugustin** [comment]
It runs on all desktops, as long as they use X11, as it uses the modesetting x11 driver.

For wayland support, see #58

**Comment by jepster** [comment]
OK, thanks.
