### ISSUE TITLE
libevdi should specify a SONAME

### ISSUE THREAD

**Issue by daugustin** [DisplayLink/evdi#63]
When compiling libevdi, it is not versioned.

From [Wikipedia](https://en.wikipedia.org/wiki/Soname):
> The soname is often used to provide version backwards-compatibility information. For instance, if versions 1.0 through 1.9 of the shared library libx provide identical interface, they would all have the same soname, e.g. libx.so.1. If the system only includes version 1.3 of that shared object, with filename libx.so.1.3, the soname field of the shared object tells the system that it can be used to fill the dependency for a binary which was originally compiled using version 1.2.
If the application binary interface (ABI) of a library changes in such a way that the dependent programs would be broken, the soname would be incremented, e.g. from libX.so.5 to libX.so.6.

Gentoo also has a nice [QA article](https://dev.gentoo.org/~zmedico/portage/doc/ch07s04.html) about that, as exactly this QA issue is trigger when installing libevdi:

> With simpler libraries, this can be acceptable, but with any sort of ABI sane setup, you need the SONAME tag. This tag is how the system linker tells the loader what libraries a program needs at runtime. With a missing SONAME, the linker needs to guess and with many cases, this guess will not work for long.

Of course the displaylink driver component then should also link against the correct libevdi version.

**Comment by displaylink-mlukaszek** [comment]
Thanks. That's been fixed in f985eb1df7a38d7fab703e5fcbfc5e50be4e89d6
