### ISSUE TITLE
DisplayLink process CPU usage

### ISSUE THREAD

**Issue by AdnanHodzic** [DisplayLink/evdi#65]
Lately I've been noticed that my battery life seems to be a lot shorter. While analyzing what's using it, I noticed that top consumer was DisplayLink process:
![displaylink-top](http://hodzic.org/img/powertop%20displaylink.png)

Furthermore, when I checked how much resources this was process was using, it turns out it's always running in range ~8-10% altough it's not even connected to external screen (idle):
![displaylink-top](http://hodzic.org/img/displaylink%20process%20cpu%20usage.png)

I have this problem on Ubuntu 16.04 on 1.2.65 driver which I installed using my [displaylink-debian](https://github.com/AdnanHodzic/displaylink-debian) tool.

Please note that I didn't have this problem on Debian Stretch.

**Comment by AdnanHodzic** [comment]
With same configuration, this is not an issue on 4.8 kernel. When not connected to external displays (idle), DisplayLink process is steady at 0.0% CPU consumption.

**Comment by carbinefreak** [comment]
If you use the plugdev script, it should only run the displaylink manager when the monitor is physically plugged in, if you are running it as an independent startup task in systemd or init.rc i would migrate so the process only runs when necessary. I agree it should sleep when no monitor is connected but this is a quick fix.

**Comment by simllll** [comment]
I'm experiencing a similar issue on Ubuntu 16.04 and displaylink 1.2.65. It seems like my laptop gets very slow after a while (suspended several time during this period). If I look in my top processes, Xorg and DisplayLinkMana are always on top.
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                     
 1051 root      20   0  995064 125616  64184 R  64,5  0,8   1696:01 Xorg                                                        
19788 root      20   0 2380992  39416    588 S  19,9  0,2  42:28.82 DisplayLinkMana                                             
 2594 simon     20   0 1597956 109644  36716 S   8,3  0,7 899:38.79 compiz                    

Kernel Version: 4.6.0-040600-generic.

Reboot solves this issue temporary.

regards
Simon

**Comment by displaylink-mlukaszek** [comment]
Note that Ubuntu driver ships a set of quite complex set of scripts that use udev to control the lifetime of DLM (that it only runs when a compatible device is connected), it also makes sure that DLM is aware of sleep/resume. We have just released the new 1.3 driver which should improve this even more. It's quite critical that other distros mimic what's done in those scripts precisely.

In any case, this is not a generic evdi problem but something that only concerns DisplayLink client, so I'd prefer to close it here.
