### ISSUE TITLE
evdi module should not disable INTEL_IOMMU

### ISSUE THREAD

**Issue by davidshen84** [DisplayLink/evdi#67]
`INTEL_IOMMU` is required for many ACPI functions and KVM. evdi should be redesigned not to disable `INTEL_IOMMU` module.

**Comment by displaylink-mlukaszek** [comment]
How's evdi disabling IOMMU? Which parts of it look problematic?

**Comment by davidshen84** [comment]
My system is Gentoo 64 bit. When I try to compile it, it says `INTEL_IOMMU` should not be set. Maybe I got the idea wrong?

**Comment by davidshen84** [comment]
Oh~my bad. The message comes from the build script on Gentoo system. I will ask the author why they disable it.

Maybe the latest version can not build successfully with `INTEL_IOMMU` enabled?

**Comment by daugustin** [comment]
@davidshen84

I think you are talking about my ebuild. :)

I'm still not quite sure if INTEL_IOMMU is actually a problem, but there were [users reporting problems](https://jira.hossie.de/browse/GOV-15?focusedCommentId=10603&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-10603) about it.

Thats why I set it is a possible (but not required) problematic kernel option.

Are you a 100% sure that you are running and using IOMMU (e.g. with KVM and VT-d) and have no problems with evdi?

**Comment by davidshen84** [comment]
@daugustin Yes, I was using that ebuild from a overlay. I did not emerge it. I saw the kernel option warning, and stopped. And I wonder if turning off `INTEL_IOMMU` is mandatory, because I need it.

I guess we have to wait DisplayLink to address this problem.
