### ISSUE TITLE
Arm Ubuntu support

### ISSUE THREAD

**Issue by Thunderbolt-sx** [DisplayLink/evdi#7]
Hi, I am wondering if there will be release for ubuntu arm support in near future? I am planning to use Asus MB 169B+ with Nvidia Jetson TX1 development board, which will run Ubuntu 14.04 for arm.

**Comment by displaylink-mlukaszek** [comment]
EVDI can already be compiled for ARM without problems - both the module and library. Having the helper user mode component to drive DisplayLink devices is out of scope for this project, please discuss this on DisplayLink forum.
Other user mode applications consuming screen data can be created and be compatible with ARM - although I admit we are currently owing the community good documentation with examples showing how does one do this. I am hoping this will improve in close future.
