### ISSUE TITLE
Detailed documentation doesn't mention evdi_get_event_ready

### ISSUE THREAD

**Issue by rhofour** [DisplayLink/evdi#71]
While trying to learn how to use EVDI I discovered that evdi_get_event_ready is mentioned in the Quick Start, but not the detailed documentation. As I understand it, the detailed documentation is supposed to document all of libevdi.

**Comment by displaylink-mlukaszek** [comment]
Thanks for pointing this out. Indeed, this looks inconsistent and we'll be fixing it.

**Comment by rhofour** [comment]
It looks like it extends to other events coverage. evdi_handle_events is only ever mentioned there when talking about evdi_selectable.
