### ISSUE TITLE
Install latest(ish) code

### ISSUE THREAD

**Issue by DakotaNelson** [DisplayLink/evdi#73]
Hey all,

Installing on Fedora 25 (4.9.4-201) kicks out an error about `drm_mode_create_dirty_info_property(dev)`, which I believe is fixed in  #50 on Oct. 26. Unfortunately, the driver on http://www.displaylink.com/downloads/ubuntu is from Oct. 7 (gah!) and as such doesn't have the fix.

Is there a way to pull more recent code in, or should I wait for a newer version to be posted on the official download site?

Thanks in advance!

**Comment by daugustin** [comment]
Related question, @displaylink-mlukaszek, is the tag 1.3.43 compatible with the current displaylink driver?

**Comment by ment0s** [comment]
dnf install kernel-headers kernel-devel 
git clone https://github.com/DisplayLink/evdi.git && cd evdi
make all
mkdir /usr/src/evdi-master
cp module/*  /usr/src/evdi-master
dkms install evdi/master

**Comment by displaylink-mlukaszek** [comment]
Devel branch is NOT guaranteed to stay compatible with DisplayLink driver for Ubuntu at all times - combined binary releases for Ubuntu Driver are currently done from master branch. At the moment, there is an API change on devel which makes it not compatible with latest released DisplayLink Manager. DisplayLink will have to refresh the driver for Ubuntu to make it compatible with all the newer changes in the module and library.

**Comment by DakotaNelson** [comment]
Sounds good - I'll wait for the new release to be posted. Thanks!
