### ISSUE TITLE
Document which capabilities libevdi needs

### ISSUE THREAD

**Issue by rhofour** [DisplayLink/evdi#75]
It seems it's now possible to grant linux executables specific [capabilities](https://linux.die.net/man/7/capabilities) rather than running them as root. If libevdi documents which capabilities it needs then people can write programs which don't need to be run as root.

**Comment by displaylink-mlukaszek** [comment]
It is dependent on what a client of libevdi needs to do with pixels though, isn't it. For sure, any evdi client would need access to /dev/dri/cardX nodes, and write privileges to /sys/devices/evdi/..., but if the client wants to talk to USB devices (like DisplayLink's) then there must be enough privileges to do that as well, and so on.

Would it be possible to find the minimal set of capabilities by experimenting, to find out which are actually necessary? This should be true for any given client.
