### ISSUE TITLE
Possible to put build information in README.md?

### ISSUE THREAD

**Issue by zetaomegagon** [DisplayLink/evdi#76]
I only knew how to build from reading through issues/google searches-- and now logs after building and installing. I have seen at least one case on the DisplayLink where someone was pointed to this project and had no idea what to do with it. Contrary to popular belief (my own at least), Linux users range in levels of knowledge/experience greatly.

[How I learned to build](https://github.com/DisplayLink/evdi/issues/69)
[My synthesized instructions](https://github.com/displaylink-rpm/displaylink-rpm/issues/18)

Thanks.

**Comment by displaylink-dkurek** [comment]
Now we have `install|uninstall` targets in `Makefile`. Will this be sufficient?
