### ISSUE TITLE
evdi_mode_valid: Mode rejected

### ISSUE THREAD

**Issue by ment0s** [DisplayLink/evdi#79]
Replacing  libevdi.so built from github with official libevdi.so for Ubuntu from DisplayLink site fixes the issue with modes rejected. ( it might cause other, but I havent noticed any ). Also I had to fully reboot for it to apply.

Mlukaszek, so this is just displaylink being behing you or is there a bug in libevdi?

 I can see Displaylink updated new driver today :) ! nice. Gonna give it a go and see.

**Comment by displaylink-mlukaszek** [comment]
The new 1.3 Ubuntu driver now ships the very latest evdi and a compatible DisplayLinkManager. This was not a bug, just evdi being ahead of DisplayLinkManager and they were API incompatible for a while.
