### ISSUE TITLE
Fedora 25 + Xorg + Intel+Noveau

### ISSUE THREAD

**Issue by ghost** [DisplayLink/evdi#80]
Tried posting to DisplayLink forum but my post just disappeared !

Fedora 25 on Xorg using Ubuntu installer from Displaylink website works nicely on Single graphics. ( Tested on second machine with radeon graphics ) 

However, on Switchable graphics it turns displays on, you can move mouse cursor over the screens and even drag and drop windows however only cursor is visible on displaylink screens. 

I am using Thinkpad P50. 
Thinkpad offers switching to discrete graphics or hybrid. Tried on Nvidia ( noveau) with no success. When Noveau driver is loaded after connecting displaylink device Xorg crashes.

Modprobe -r noveau works in a way that Xorg doesn't crash however the symptoms are like above.

I tried Proptiary driver from RPMFusion and surprisingly it works with EVDI however it has drawing problems as there is a "square" below cursor. 

Logs attached, noveau module removed, ( screens found and attached, one displays my desktop but it looks like just a screenshot as I can only move my cursor over it. Second display is completely black but still the same ( can move my cursor over it ) The display that is completely black is over HDMI from Thinkpad Pro dock, the display that shows something is connected over dvi. 

Below is a Xorg log file when using Intel with noveau module removed.
https://paste.fedoraproject.org/paste/Uytidi3OD8mG7mZS~WxVYl5M1UNdIGYhyRLivL9gydE=

When moving cursor over those displays a journalctl shows this : 

evdi: [D] evdi_crtc_cursor_set:238 evdi_crtc_cursor_set unlock
Feb 26 10:08:38 ceres kernel: evdi: [D] evdi_crtc_cursor_set:238 evdi_crtc_cursor_set unlock
Feb 26 10:08:40 ceres kernel: evdi: [D] evdi_crtc_cursor_set:238 evdi_crtc_cursor_set unlock
Feb 26 10:08:40 ceres kernel: evdi: [D] evdi_crtc_cursor_set:238 evdi_crtc_cursor_set unlock
Feb 26 10:08:40 ceres kernel: evdi: [D] evdi_crtc_cursor_set:238 evdi_crtc_cursor_set unlock
Feb 26 10:08:40 ceres kernel: evdi: [D] evdi_crtc_cursor_set:238 evdi_crtc_cursor_set unlock
Feb 26 10:08:41 ceres kernel: evdi: [D] evdi_crtc_cursor_set:238 evdi_crtc_cursor_set unlock
Feb 26 10:08:41 ceres kernel: evdi: [D] evdi_crtc_cursor_set:238 evdi_crtc_cursor_set unlock
Feb 26 10:08:41 ceres kernel: evdi: [D] evdi_crtc_cursor_set:238 evdi_crtc_cursor_set unlock
Feb 26 10:13:12 ceres kernel: evdi: [D] evdi_crtc_cursor_set:238 evdi_crtc_cursor_set unlock
Feb 26 10:13:12 ceres kernel: evdi: [D] evdi_crtc_cursor_set:238 evdi_crtc_cursor_set unlock
Feb 26 10:13:13 ceres kernel: evdi: [D] evdi_crtc_cursor_set:238 evdi_crtc_cursor_set unlock
Feb 26 10:13:13 ceres kernel: evdi: [D] evdi_crtc_cursor_set:238 evdi_crtc_cursor_set unlock
Feb 26 10:13:16 ceres kernel: evdi: [D] evdi_crtc_cursor_set:238 evdi_crtc_cursor_set unlock
Feb 26 10:13:16 ceres kernel: evdi: [D] evdi_crtc_cursor_set:238 evdi_crtc_cursor_set unlock
Feb 26 10:13:17 ceres kernel: evdi: [D] evdi_crtc_cursor_set:238 evdi_crtc_cursor_set unlock

After removing Thinkpad Pro dock : 

evdi] ioctl: drop_master error=-1
Feb 26 10:14:38 ceres DisplayLinkManager[8162]: [libevdi] ioctl: drop_master error=-1
Feb 26 10:14:38 ceres DisplayLinkManager[8162]: [libevdi] ioctl: drop_master error=-1
Feb 26 10:14:38 ceres DisplayLinkManager[8162]: [libevdi] ioctl: drop_master error=-1
Feb 26 10:14:38 ceres DisplayLinkManager[8162]: [libevdi] ioctl: drop_master error=-1
Feb 26 10:14:38 ceres DisplayLinkManager[8162]: [libevdi] ioctl: drop_master error=-1
Feb 26 10:14:38 ceres DisplayLinkManager[8162]: [libevdi] ioctl: drop_master error=-1
Feb 26 10:14:38 ceres DisplayLinkManager[8162]: [libevdi] ioctl: drop_master error=-1

Below is a Xorg log file after crash - Noveau driver loaded, startx works, plug displaylink into USB - CRASH

https://paste.fedoraproject.org/paste/5czxoBfMCSLuAH7DZq1cDl5M1UNdIGYhyRLivL9gydE=

Interestingly, even after I remove displaylink or noveau module it still fails to startx after this crash ! I have to reboot to get it back to startx. 
This is a log file http://pastebin.com/aNSHTc0Y 

It looks like evdi doesnt remove the virtual displays after unplug ( this doesnt really bother me, I just want to get screens going )

It works nicely on fedora 24 on intel with noveau removed so maybe there is some issue with modesetting on f25 intel ?

**Comment by JameLeung** [comment]
I got the same problem and cannot get the same result as in fedora 23, using the noveau.

the version I used to handle is displaylink-1.0.68-2.x86_64. but it seems unable to compile anymore. Something wrong?

**Comment by dantix** [comment]
Same issue here, 
Intel video card,
Arch, 4.11.9 kernel, evdi 1.4.1

**Comment by displaylink-mlukaszek** [comment]
Have you tried this? http://displaylink.org/forum/showthread.php?t=65364

**Comment by ment0s** [comment]
I can confirm that 

`/etc/X11/xorg.conf.d/20-intel.conf

Section "Device"
Identifier "intel"
Driver "modesetting"
Option "kmsdev" "/dev/dri/card0"
Option "PageFlip" "off"
Option "SWCursor" "on"
Option "ShadowFB" "true"
EndSection

Section "Device"
Identifier "USB3"
BusID "USB"
Driver "modesetting"
Option "kmsdev" "/dev/dri/card1"
Option "PageFlip" "off"
Option "SWCursor" "on"
Option "ShadowFB" "true"
EndSection

Section "Device"
Identifier "USB3"
BusID "USB"
Driver "modesetting"
Option "kmsdev" "/dev/dri/card2"
Option "PageFlip" "off"
Option "SWCursor" "on"
Option "ShadowFB" "true"
EndSection`

Fixes this issue on Fedora 25 and 26. Thinkpad P50, Dual graphics. Intel+Nvidia

**Comment by dantix** [comment]
As soon as I switched from modesetting to Intel driver, everything started to work smoothly.

**Comment by displaylink-mlukaszek** [comment]
Thanks. Closing.
