### ISSUE TITLE
Problem with Display Link and Qt5/KDE Frameworks 5 Applications

### ISSUE THREAD

**Issue by konradrenner** [DisplayLink/evdi#82]
Hi everybody,

I bought a Display Link USB Dock, everything works (USB Hub, Sound, Output on 2 displays) except Applications which are based on kde frameworks 5/qt 5 (Dolphin, Kontact, System Settings and so on). Old KDE Applications are working (e.g. Okular), GTK Apps are also running without any problems, even Java Apps are running. I am running Kubuntu 16.04 with Plasma 5.7 and latest backports on a Dell XPS 13 (Intel graphics card).

As long as the dock is not plugged in, these Apps are working as expected, Apps which I started before plugging in the USB Cable of the dock are running after plugging in the Cable without any problems. But when the cable is plugged into the laptop these Apps are crashing during startup or just show Icons, no text and the app widgets are not displayed correct (some buttons are very big, text fields are not shown and so on).

I have also tried different compositor backends (OpenGL, XRender), but no difference.

Does anybody also have such problems? Does anybody use the KDE Plasma desktop with these apps?

Thanks for your help!

**Comment by nekromoff** [comment]
No such problem, using Plasma 5.8.5

**Comment by displaylink-mlukaszek** [comment]
Given the comment above, I think I'd just close this. If you still encounter such issue, it's probably better to report it on DisplayLink forum.
