### ISSUE TITLE
4.10.1 issue

### ISSUE THREAD

**Issue by carbinefreak** [DisplayLink/evdi#83]
When building a vanilla kernel 4.10.1 i get `depmod: WARNING: /lib/modules/4.10.1/video/evdi.ko needs unknown symbol drm_fb_get_bpp_depth` any ideas?

**Comment by dawikur** [comment]
Are you using latest version of evdi? This issue should be fixed with [this](https://github.com/DisplayLink/evdi/commit/793a65a8f45bc0ca890d8fa8507c0c6c4a5860f8) commit.

**Comment by carbinefreak** [comment]
I just re-pulled the devel and it fixed the issue. I'll open a ticket with my package manager thanks.
