### ISSUE TITLE
Unsatisfied dependencies. Missing component: Linux headers for running kernel, 4.9.13-200.fc25.x86_64

### ISSUE THREAD

**Issue by reypm** [DisplayLink/evdi#84]
I am using Fedora 25 and I need to get EVDI and DisplayLink working since I have two monitors and I would like to use them as well. I did know there is a driver for Ubuntu but I refuse to go to Ubuntu just for this so I am on the "research" and "test" part to see if I can get this working.

I did found [this post](http://mattwilmott.com/2016/11/03/how-to-install-the-displaylink-driver-fedora-2425/comment-page-1/) and I am trying to reproduce the exact same steps but using new drivers version from DisplayLink, below is what I have done and what's failing on my side:

All the commands above has been run as `root`
```
# dnf install kernel-devel kernel-headers dkms
Last metadata expiration check: 1:08:19 ago on Sat Mar 11 08:56:50 2017.
Package kernel-debug-devel-4.9.13-200.fc25.x86_64 is already installed, skipping.
Package kernel-headers-4.9.13-200.fc25.x86_64 is already installed, skipping.
Package dkms-2.3-1.20161202gitde1dca9.fc25.noarch is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
```
The above means packages are already installed and they are in the right version as well.
```
// # Download the latest driver for Ubuntu
# wget http://www.displaylink.com/downloads/file?id=744 -O 'DisplayLink.zip'

// # Unzip the driver
# unzip DisplayLink.zip

// Make the .run script executable
# chmod +x displaylink-driver-1.3.52.run

// Run the script with the noexec flag to prevent it from actually installing the driver 
# ./displaylink-driver-1.3.52.run --noexec --keep

// Enter the directory
# cd displaylink-driver-1.3.52/

// Patch the displaylink-installer.sh with the patch from this gist
// It modifies the script to work with Fedora (Pretty naively...)
# wget https://gist.githubusercontent.com/mattwilmott/d8893a24291f74975b6f2b48fa39fe24/raw/0cec3bbb2f1f21f806588d3cad57fbbdc5127c0a/displaylink-installer.sh.patch -O displaylink-installer.sh.patch
# patch displaylink-installer.sh displaylink-installer.sh.patch

// Confirm the script is executable
chmod +x displaylink-installer.sh

// Install the driver
./displaylink-installer.sh install
```
And here comes the problem:

```
# ./displaylink-installer.sh install
DisplayLink Linux Software 1.3.52 install script called: install
Unsatisfied dependencies. Missing component: Linux headers for running kernel, 4.9.13-200.fc25.x86_64.
This is a fatal error, cannot install DisplayLink Linux Software.
```

The dependencies are installed so far so what else do the script needs in order to install properly? I am missing something here?

I have tried also the RPM from (here)[https://github.com/displaylink-rpm/displaylink-rpm/releases] specifically `fedora-25-displaylink-1.3.43-2.x86_64.rpm` but it didn't work either. See below:

```
# rpm -ivh fedora-25-displaylink-1.3.43-2.x86_64.rpm
Preparing...                      	################################# [100%]
Updating / installing...
   1:displaylink-1.3.43-2         	################################# [100%]
warning: %post(displaylink-1.3.43-2.x86_64) scriptlet failed, exit status 1
```
Can I  get some help? I refuse to move to Ubuntu just because of this

**Comment by JameLeung** [comment]
I hit the problem exactly same using Fedora 25 4.10.11-200.fc25.x86_64
Anyone can help?

**Comment by mpalmer** [comment]
I hit this last night (running Debian Jessie with a backported 4.9 kernel) and by using dkms directly I was able to build without a problem.  I didn't bother digging into the installer script and finding out why, because life's too short, but it seems like the headers detection code in there is very broken -- I've seen other reports on the DisplayLink forums of the script not picking up headers on Ubuntu systems, either.

For the record, I just did this:

    mkdir /usr/src/evdi-1.3.52
    tar xzf evdi-1.3.52.tar.gz -C /usr/src/evdi-1.3.52
    for act in add build install; do dkms $act evdi/1.3.52; done
    modprobe evdi

(As an aside, I also had to do a bunch of other stuff to install `udev.sh` and `DisplayLinkManager` in the right places, and run DLM under a sane process management system, but they're not germane to this discussion)

If you're not using DKMS, then all bets are off, but then you're in a pickle already, because that's what the installer script uses...

**Comment by debgustavocastro** [comment]
i have the same problem!

`
$ sudo ./displaylink-driver-5.2.14.run

Verifying archive integrity...  100%   All good.
Uncompressing DisplayLink Linux Driver 5.2.14  100%  
DisplayLink Linux Software 5.2.14 install script called: install
Distribution discovered: Debian GNU/Linux 10 (buster)
Unsatisfied dependencies. Missing component: Linux headers for running kernel, 4.19.0-6-amd64.
This is a fatal error, cannot install DisplayLink Linux Software.
`

**Comment by caelulum2** [comment]
Same problem, newest version of Debian.

DisplayLink USB Graphics Software for Ubuntu 5.1/displaylink-driver-5.1.26.run' 
Verifying archive integrity...  100%   All good.
Uncompressing DisplayLink Linux Driver 5.1.26  100%  
DisplayLink Linux Software 5.1.26 install script called: install
Distribution discovered: Debian GNU/Linux 10 (buster)
Unsatisfied dependencies. Missing component: Linux headers for running kernel, 4.19.0-14-amd64.
This is a fatal error, cannot install DisplayLink Linux Software.

root@debian:~# apt install linux-headers-amd64
Reading package lists... Done
Building dependency tree       
Reading state information... Done
linux-headers-amd64 is already the newest version (4.19+105+deb10u9).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

root@debian:~# apt list linux-headers-4.19.0-14-amd64
Listing... Done
linux-headers-4.19.0-14-amd64/stable,stable,now 4.19.171-2 amd64 [installed,automatic]

**Comment by gengwg** [comment]
Still has this error

```
# ./displaylink-driver-5.7.0-61.129.run 
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing DisplayLink Linux Driver 5.7.0-61.129  100%  
Distribution discovered: No LSB modules are available.
Debian GNU/Linux 12 (bookworm)
Unsatisfied dependencies. Missing component: Linux headers for running kernel, 5.10.0-20-amd64.
This is a fatal error, cannot install DisplayLink Linux Software.

# uname -a
Linux lnv330s 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux
```
