### ISSUE TITLE
Ubuntu 17.04 works

### ISSUE THREAD

**Issue by ajbogh** [DisplayLink/evdi#85]
I upgraded my machine to 17.04 and installed the latest version of DisplayLink (1.3.43) but the display isn't working using the DVI connection on a Thinkpad Pro docking station.

Networking is also not working.

If there is a way to get the logs, please let me know the commands and I'll paste the responses here.

**Comment by ajbogh** [comment]
Networking was broken because Ubuntu decided to stop managing the network interface, so that wasn't related. I fixed it by creating a blank file for the network manager to see.

```sudo touch /etc/NetworkManager/conf.d/10-globally-managed-devices.conf```

The 3rd monitor that I have connected to the DisplayLink interface showed up in the displays tool, and I enabled it, however it still doesn't receive signal using a DVI to VGA converter.

**Comment by ajbogh** [comment]
It works!

I had 1.3.43 installed when it showed the monitor in displays and didn't turn it on, and that would have worked, but I decided to uninstall it anyway and install 1.3.52 instead to see if that was the problem.

After a reboot with the new kernel module installed I noticed the same issue -- display is enabled but not displaying anything. Then I decided to wiggle the DVI connection and found that it was ever-so-slightly off kilter. Once I fully seated the adapter the monitor turned on! Go figure.

**Comment by ajbogh** [comment]
Sadly, upon further testing, the DisplayLink monitor is only running at 1fps. There is some configuration that  Ubuntu uses that's slowing the refresh rate. It may be related to various other Intel-based mouse flickering issues because my mouse is flickering as well.

Suggestions to disable vsync in ccsm don't help and drivers are all up to date.

**Comment by ajbogh** [comment]
The 1fps lag issue can be fixed by creating or editing the following configuration file (only with Intel-based graphics drivers). Make sure to install the Intel Graphics Update Tool for Linux.

**/usr/share/X11/xorg.conf.d/20-intel.conf**
```
Section "Device"
  Identifier "Intel Graphics"
  Driver "Intel"
  Option "AccelMethod" "sna"
  Option "TearFree" "true"
  Option "TripleBuffer" "true"
  Option "MigrationHeuristic" "greedy"
  Option "Tiling" "true"
  Option "Pageflip" "true"
  Option "ExaNoComposite" "false"
  Option "Tiling" "true"
  Option "Pageflip" "true"
EndSection
```

**Comment by displaylink-mlukaszek** [comment]
This is a very useful comment, thank you! I'll post this workaround to our forum for people using Intel.

**Comment by robmi77** [comment]
@ajbogh the Section in 20-intel.conf plus the empty file for the NetworkManager did the trick. Upgraded to 17.04, running 4.10.0-19-generic and evdi 1.3.52 with intel graphics.
2 external Monitors and a Targus USB docking station. All works as before (16.04).
Many thanks!

**Comment by ironman-hythloday** [comment]
I've actually just had to create the blank /etc/NetworkManager/conf.d/10-globally-managed-devices.conf file as well to get my Ethernet connection working... sadly, it kills my wifi connection.  So, I can have EITHER wifi or wired, but not BOTH, like I used to.

**Comment by cmachler** [comment]
Just creating the `/usr/share/X11/xorg.conf.d/20-intel.conf` file from @ajbogh fixed the issue for me.
Cheers!

**Comment by aremai** [comment]
Is this fix with the `/usr/share/X11/xorg.conf.d/20-intel.conf` only working on Ubuntu 17.04 ?
At the moment I'm running on 16.04.2 LTS

**Comment by majgis** [comment]
I have three attached displays through dell D3100 dock.  Creating the 20-intel.conf file fixed the issue with the displays not showing at all.  I upgraded the bios and displaylink drivers to latest.  Unfortunately, I still have these issues:
1. Displays are very slow to be recognized, on the order of multiple minutes, where on 16.04 the came up almost instantly.
2. There are now trailing cursor artifacts left behind.
Thank you for any additional insights and for the above solution as well!

**Comment by majgis** [comment]
#1 resolved: wait until after login to attach dock
#2 resolved: remove `Option "TearFree" "true"` from `/usr/share/X11/xorg.conf.d/20-intel.conf`

**Comment by JanneM** [comment]
For me (and apparently for others), the 20-intel.conf file doesn't need any "Option" lines at all. Just "Identifier" and "Driver" alone is enough to fix the display. It probably triggers setting some defaults that are otherwise undefined.

**Comment by compuguy** [comment]
@JanneM I can confirm this as well on 17.04. The only caveat is you need to hook the dock in after login (otherwise the screen won't come on).

**Comment by compuguy** [comment]
@ajbogh I noticed that your xorg conf file has several config options duplicated (Two pageflip and Tiling options). Does it need to be declared more than once? Otherwise this in theory should work without the duplicate instances:


`Section "Device"
  Identifier "Intel Graphics"
  Driver "Intel"
  Option "AccelMethod" "sna"
  Option "TearFree" "true"
  Option "TripleBuffer" "true"
  Option "MigrationHeuristic" "greedy"
  Option "Tiling" "true"
  Option "Pageflip" "true"
  Option "ExaNoComposite" "false"
  Option "Tiling" "true"
  Option "Pageflip" "true"
EndSection`

**Comment by ajbogh** [comment]
@compuguy It doesn't have to have duplicates. Those are just copy/paste errors.

**Comment by thecoolestname36** [comment]
Environment:
Razer Blade 14 2014
Intel GPU
Nvidia 870M
1x HDMI port

I originally had no video drivers installed and was using the Intel gpu and this did not work with DisplayLink with 1.4x drivers installed until i added xorg.conf.d/20-intel.conf. After this it worked as a third display but I had disappearing mouse cursor issues constantly and only with the DisplayLink hdmi usb adapter plugged in... there were times when the mouse wouldn't come back for minutes.  Most of the time the behavior would be: on the top half of the screen the mouse would only flicker and on the bottom half it would completely disappear. I experimented with all permutations between 20-nvidia.conf, 20-intel.conf one being active vs both and all of the params in each scenario: TearingFree false/true, TripleBuffering false/true, PageFlip false/true 

Solution for me was to use the GNOME desktop, the 20-intel.conf with only:
Section "Device"
  Identifier "Intel Graphics"
  Driver "Intel"
EndSection

And using the Nvidia driver 340 proprietary in AdditionalDrivers while setting it to be primary usage in Nvidia application with rendering quality set to performance.

No more disappearing mouse, 3 monitors all plugged in at boot and only a 10 second wait for the USB DisplayLink monitor to show up after login.

Cheers

**Comment by wolfen351** [comment]
Just wish to confirm, this worked for me too running Ubuntu 18.04, I didn't have the folder /etc/X11/xorg.conf.d/ - but creating it and making the file inside with the full (deduplicated config) above fixed the issue. Finally I can move my mouse again!

**Comment by ptspawn** [comment]
> Environment:
> Razer Blade 14 2014
> Intel GPU
> Nvidia 870M
> 1x HDMI port
> 
> I originally had no video drivers installed and was using the Intel gpu and this did not work with DisplayLink with 1.4x drivers installed until i added xorg.conf.d/20-intel.conf. After this it worked as a third display but I had disappearing mouse cursor issues constantly and only with the DisplayLink hdmi usb adapter plugged in... there were times when the mouse wouldn't come back for minutes. Most of the time the behavior would be: on the top half of the screen the mouse would only flicker and on the bottom half it would completely disappear. I experimented with all permutations between 20-nvidia.conf, 20-intel.conf one being active vs both and all of the params in each scenario: TearingFree false/true, TripleBuffering false/true, PageFlip false/true
> 
> Solution for me was to use the GNOME desktop, the 20-intel.conf with only:
> Section "Device"
> Identifier "Intel Graphics"
> Driver "Intel"
> EndSection
> 
> And using the Nvidia driver 340 proprietary in AdditionalDrivers while setting it to be primary usage in Nvidia application with rendering quality set to performance.
> 
> No more disappearing mouse, 3 monitors all plugged in at boot and only a 10 second wait for the USB DisplayLink monitor to show up after login.
> 
> Cheers

My current environment is:
Lenovo Yoga 720
Intel GPU
Nvidia GeForce GTX 1050

Not only do I have the mouse flickering problem but despite having the nvidia drivers installed and running, I cant seem to set xorg to run with the GTX1050. Could you show me the config files you created for that purpose?

I would be thankful beyond measure!
