### ISSUE TITLE
Linux DisplayLink Driver

### ISSUE THREAD

**Issue by wordyallen** [DisplayLink/evdi#87]
I have a simple question... I tried contacting displaylink and reaching out to the forums, but no luck. 
http://displaylink.org/forum/showthread.php?t=64014

Is the shell script supposed to be unreadable after line 500? When I download and open it up, I get this:
```sh
if test "$keep" = n; then
    cd $TMPROOT
    /bin/rm -rf $tmpdir
fi
eval $finish; exit $res
����X���nϒ.��m۶m�޻m�w��n۶m۶m��ۿs��=3s�~�����[�kUUV�S�Oe��~�]t���ß�����+���힑����������O;;;#+��������@@�`k��?�������BG�ld�Bkn��

```

**Comment by dawikur** [comment]
Yes, this is normal. The 'script' you download from website already contains compiler driver in the same file and it is at the very end.

**Comment by wordyallen** [comment]
when i run 

`systemctl status dlm`

I get the error:

`Process: 3689 ExecStartPre=/bin/sh -c modprobe evdi || (dkms install evdi/1.3.52 && modprobe evdi) (code=exited, status=1/FAILURE)`
